USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ROS_R3_HGENKA_HOSEIM](
	[KAISHA_CODE] [nvarchar](2) NOT NULL,
	[KOJYO_CODE] [nvarchar](2) NOT NULL,
	[TANTO_CODE] [nvarchar](2) NOT NULL,
	[H_CODE] [nvarchar](18) NOT NULL,
	[NENKI] [nvarchar](5) NOT NULL,
	[APPLY_MONTH] [date] NOT NULL,
	[H_TEXT] [nvarchar](40) NULL,
	[TUKA_CODE] [nvarchar](5) NULL,
	[SU_TANI] [nvarchar](3) NULL,
	[H_GENKA] [decimal](17, 2) NULL,
	[O_H_GENKA] [decimal](17, 2) NULL,
	[HOUKA_GENKA] [decimal](17, 2) NULL,
	[O_HOUKA_GENKA] [decimal](17, 2) NULL,
	[HOSEI_GENKA] [decimal](17, 2) NULL,
	[O_HOSEI_GENKA] [decimal](17, 2) NULL,
	[S_HOSEI_GENKA] [decimal](17, 2) NULL,
	[Y_RATE] [decimal](9, 2) NULL,
	[KANSAN_TUKA] [nvarchar](11) NULL,
	[KOUSIN_KUBUN] [nvarchar](1) NULL,
	[REG_DATETIME] [datetime] NULL,
	[UPD_DATETIME] [datetime] NULL,
 CONSTRAINT [PK_T_ROS_R3_HGENKA_HOSEIM] PRIMARY KEY NONCLUSTERED 
(
	[KAISHA_CODE] ASC,
	[KOJYO_CODE] ASC,
	[TANTO_CODE] ASC,
	[H_CODE] ASC,
	[APPLY_MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([APPLY_MONTH])
) ON [PS_PartitionByMonth_DW]([APPLY_MONTH])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
