USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[R_SFM_BCCV_ACCOUNT_KEY_FINANCE_VIEW](
	[ACCOUNT_KEY_FINANCE_NO] [nvarchar](11) NULL,
	[ACCOUNT_GROUP_CODE] [nvarchar](255) NULL,
	[FISCAL_YEAR_STARTING_POINT] [nvarchar](4) NULL,
	[FISCAL_YEAR] [numeric](4, 0) NULL,
	[BASE] [numeric](38, 0) NULL,
	[SOM_UP] [numeric](38, 0) NULL,
	[SAM_UP] [numeric](38, 0) NULL,
	[CURRENCY_ISO_CODE] [nvarchar](3) NULL,
	[CREATED_DATE] [date] NULL,
	[LAST_MODIFIED_DATE] [date] NULL,
	[IF_LAST_MODIFIED_DATE] [date] NULL
) ON [BI_DW_Staging]

GO
