USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[R_DCP_WBS_DELIBERATION](
	[WBS] [nvarchar](30) NOT NULL,
	[DELIBERATION_CD] [nvarchar](6) NOT NULL,
	[EXPECTED_DATE] [date] NULL,
	[EXECUTION_DATE] [date] NULL,
	[RESULT] [nvarchar](30) NULL,
	[CHAIRMAN] [nvarchar](80) NULL,
	[CURRENCY_CODE] [nvarchar](3) NULL,
	[EXCHANGE_RATE] [numeric](8, 2) NULL,
	[LAST_FLG] [bit] NULL,
	[DCP_UPDATETIME] [smalldatetime] NULL
) ON [BI_DW_Staging]

GO
ALTER TABLE [dbo].[R_DCP_WBS_DELIBERATION] ADD  CONSTRAINT [DF_R_DCP_WBS_DELIBERATION_LAST_FLG]  DEFAULT ((0)) FOR [LAST_FLG]
GO
