USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_SAL_SHIPPING_TO](
	[H_SHIPDOC_NO] [nvarchar](10) NULL,
	[H_BILLDOC_NO] [nvarchar](10) NULL,
	[UPDATE_KIND] [nvarchar](1) NULL,
	[SHIPDOC_TYPE] [nvarchar](4) NULL,
	[DOC_ISSUE_DATE] [date] NULL,
	[BUSINESS_SITE_CD] [nvarchar](2) NULL,
	[R3_COMPANY_CD] [nvarchar](4) NULL,
	[SALES_ORG] [nvarchar](4) NULL,
	[SHIP_CONDITION] [nvarchar](2) NULL,
	[SHIP_POINT] [nvarchar](4) NULL,
	[CARRY_POINT] [nvarchar](2) NULL,
	[TRANSPORT_GROUP] [nvarchar](4) NULL,
	[INCOTERMS] [nvarchar](3) NULL,
	[INCOTERMS2] [nvarchar](28) NULL,
	[FLT_PRIORITY] [nvarchar](2) NULL,
	[DOMESTIC_EXPORT_FLAG] [nvarchar](1) NULL,
	[SCM_PROCESS_FLAG] [nvarchar](2) NULL,
	[SCM_DOC_CATEGORY] [nvarchar](1) NULL,
	[BLANKET_DELI_FLAG] [nvarchar](1) NULL,
	[ORDER_CONV_SHIP_FLG] [nvarchar](1) NULL,
	[SALES_OFFICE] [nvarchar](4) NULL,
	[H_NET_AMOUNT] [decimal](15, 2) NULL,
	[CURRENCY] [nvarchar](5) NULL,
	[H_WH_NO] [nvarchar](3) NULL,
	[INV_NO] [nvarchar](35) NULL,
	[INV_MOVE_PLAN_DATE] [date] NULL,
	[DOC_CURRENCY] [nvarchar](5) NULL,
	[PICKING_DATE] [date] NULL,
	[CARRY_DATE] [date] NULL,
	[REAL_GI_DATE] [date] NULL,
	[GI_CONFIR_DATE] [date] NULL,
	[DELIVER_DATE] [date] NULL,
	[SOLDTO_CD] [nvarchar](10) NULL,
	[SOT_SHORT_NAME] [nvarchar](40) NULL,
	[SOT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SOT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[SOT_CITY_NM_KANA] [nvarchar](40) NULL,
	[SOT_CITY_NM_KANJI] [nvarchar](40) NULL,
	[SOT_BLDG_KANA] [nvarchar](40) NULL,
	[SOT_BLDG_KANJI] [nvarchar](40) NULL,
	[SOT_ADDRESS_KANA] [nvarchar](40) NULL,
	[SOT_ADDRESS_KANJI] [nvarchar](40) NULL,
	[SOT_BLDG_NM_E] [nvarchar](40) NULL,
	[SOT_BLDG_NUMBER_E] [nvarchar](40) NULL,
	[SOT_CITY_NM_E] [nvarchar](40) NULL,
	[SHIPTO_CD] [nvarchar](10) NULL,
	[SIT_SHORT_NAME] [nvarchar](40) NULL,
	[SIT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SIT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[SIT_CITY_NM_KANA] [nvarchar](40) NULL,
	[SIT_CITY_NM_KANJI] [nvarchar](40) NULL,
	[SIT_BLDG_KANA] [nvarchar](40) NULL,
	[SIT_BLDG_KANJI] [nvarchar](40) NULL,
	[SIT_ADDRESS_KANA] [nvarchar](40) NULL,
	[SIT_ADDRESS_KANJI] [nvarchar](40) NULL,
	[SIT_BLDG_NM_E] [nvarchar](40) NULL,
	[SIT_BLDG_NUMBER_E] [nvarchar](40) NULL,
	[SIT_CITY_NM_E] [nvarchar](40) NULL,
	[BILLTO_CD] [nvarchar](10) NULL,
	[BT_SHORT_NAME] [nvarchar](40) NULL,
	[BT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[BT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[BT_CITY_NM_KANA] [nvarchar](40) NULL,
	[BT_CITY_NM_KANJI] [nvarchar](40) NULL,
	[BT_BLDG_KANA] [nvarchar](40) NULL,
	[BT_BLDG_KANJI] [nvarchar](40) NULL,
	[BT_ADDRESS_KANA] [nvarchar](40) NULL,
	[BT_ADDRESS_KANJI] [nvarchar](40) NULL,
	[BT_BLDG_NM_E] [nvarchar](40) NULL,
	[BT_BLDG_NUMBER_E] [nvarchar](40) NULL,
	[BT_CITY_NM_E] [nvarchar](40) NULL,
	[PAYER] [nvarchar](10) NULL,
	[SO_CONTRACT_TO] [nvarchar](10) NULL,
	[SCM_CUSTOMER] [nvarchar](10) NULL,
	[SCM_SHORT_NAME] [nvarchar](40) NULL,
	[SCM_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SCM_SHORT_NAME_EN] [nvarchar](20) NULL,
	[SA_ROUTE_CD] [nvarchar](2) NULL,
	[SP_STOCK_PARTNER] [nvarchar](10) NULL,
	[DELIVERY_METHOD_TO] [nvarchar](10) NULL,
	[DELIVERY_TRADER] [nvarchar](10) NULL,
	[EXP_FWDR] [nvarchar](10) NULL,
	[PD_END_USER] [nvarchar](10) NULL,
	[CUST_CARRY_PLACE_CD] [nvarchar](10) NULL,
	[SO_CONTRACTOR] [nvarchar](10) NULL,
	[CROSS_DOC_SEND_TO] [nvarchar](10) NULL,
	[SHIPTO_CNTRY_CD] [nvarchar](3) NULL,
	[SIT_CNTRY_NAME_JA] [nvarchar](15) NULL,
	[SIT_CNTRY_NAME_EN] [nvarchar](15) NULL,
	[AREA_1_NAME_JA] [nvarchar](20) NULL,
	[AREA_1_NAME_EN] [nvarchar](20) NULL,
	[AREA_2_NAME_JA] [nvarchar](20) NULL,
	[AREA_2_NAME_EN] [nvarchar](20) NULL,
	[AREA_3_NAME_JA] [nvarchar](20) NULL,
	[AREA_3_NAME_EN] [nvarchar](20) NULL,
	[SHIPDOCITEM_NO] [decimal](6, 0) NULL,
	[SO_CNTL_DOC_CATEGORY] [nvarchar](1) NULL,
	[ITEM_CATEGORY] [nvarchar](4) NULL,
	[CO_NO] [nvarchar](12) NULL,
	[PLANT_NO] [nvarchar](4) NULL,
	[PLANT_CNTRY_CD] [nvarchar](3) NULL,
	[PL_CNTRY_NAME_JA] [nvarchar](15) NULL,
	[PL_CNTRY_NAME_EN] [nvarchar](15) NULL,
	[STORAGEPLC] [nvarchar](4) NULL,
	[L_WH_NO] [nvarchar](3) NULL,
	[STORAGEAREA_TYPE] [nvarchar](3) NULL,
	[RACK_NO] [nvarchar](10) NULL,
	[SALES_GROUP] [nvarchar](3) NULL,
	[DIST_CHANNEL] [nvarchar](2) NULL,
	[PD_PART_NO] [nvarchar](40) NULL,
	[PROD_CATEGORY_1_CD] [nvarchar](2) NULL,
	[PROD_NAME_1] [nvarchar](40) NULL,
	[PROD_CATEGORY_2_CD] [nvarchar](2) NULL,
	[PROD_NAME_2] [nvarchar](40) NULL,
	[PROD_CATEGORY_3_CD] [nvarchar](2) NULL,
	[PROD_NAME_3] [nvarchar](40) NULL,
	[PROD_CATEGORY_4_CD] [nvarchar](2) NULL,
	[PROD_NAME_4] [nvarchar](40) NULL,
	[PROD_CATEGORY_5_CD] [nvarchar](2) NULL,
	[PROD_NAME_5] [nvarchar](40) NULL,
	[SAFIX] [nvarchar](10) NULL,
	[PD_PART_NAME] [nvarchar](40) NULL,
	[INPUT_PART_NO] [nvarchar](18) NULL,
	[CUSTOMER_PART_NO] [nvarchar](35) NULL,
	[PART_NO_GROUP] [nvarchar](9) NULL,
	[QTY] [decimal](13, 0) NULL,
	[SUB_QTY] [decimal](15, 3) NULL,
	[BASE_UNIT] [nvarchar](3) NULL,
	[T_WEIGHT] [decimal](15, 3) NULL,
	[LOT] [nvarchar](10) NULL,
	[UNIT_W] [nvarchar](3) NULL,
	[HIGHER_LEVEL_ITEM_NO] [nvarchar](6) NULL,
	[COMPOSITION_ITEM_QTY] [decimal](15, 3) NULL,
	[PICKING_FLAG] [nvarchar](1) NULL,
	[NET_PRICE] [decimal](15, 4) NULL,
	[PRICE_CONDITION_UNIT] [nvarchar](5) NULL,
	[L_NET_AMOUNT] [decimal](15, 2) NULL,
	[NET_PRICE_CONDITION] [decimal](15, 4) NULL,
	[NET_WEIGHT] [decimal](15, 3) NULL,
	[RETURNED_GOODS] [nvarchar](1) NULL,
	[SALES_GRP] [nvarchar](2) NULL,
	[DENOMINATOR] [decimal](5, 0) NULL,
	[NUMERATOR] [decimal](5, 0) NULL,
	[ACCUMULATED_SO_QTY] [decimal](15, 3) NULL,
	[SALES_UNIT] [nvarchar](3) NULL,
	[DIST_FLAG] [nvarchar](3) NULL,
	[LC_NO] [nvarchar](15) NULL,
	[SO_INPUT_DATE] [date] NULL,
	[SO_DATE] [date] NULL,
	[SHIPTO_CUSTPO_DATE] [date] NULL,
	[CUSTPO_NO] [nvarchar](35) NULL,
	[VERIFICATION_KEY] [nvarchar](35) NULL,
	[CONDITION_RATE] [decimal](15, 4) NULL,
	[DESIGN_CHANGE] [nvarchar](17) NULL,
	[REFSO_NO] [nvarchar](10) NULL,
	[REFSOITEM_NO] [nvarchar](6) NULL,
	[ESTIMATE_NO] [nvarchar](10) NULL,
	[ESTIMATEITEM_NO] [nvarchar](6) NULL,
	[RTS_SALES_UNITPRICE] [decimal](15, 4) NULL,
	[RTS_SALES_CURRENCY] [nvarchar](5) NULL,
	[RTS_PRICE_CDTION_UT] [decimal](5, 0) NULL,
	[RDS_SALES_UNITPRICE] [decimal](15, 4) NULL,
	[RDS_SALES_CURRENCY] [nvarchar](5) NULL,
	[RDS_PRICE_CDTON_UT] [decimal](5, 0) NULL,
	[INVENTORY_MOVE_SATUS] [nvarchar](1) NULL,
	[INV_MOVE_SATUS_JA] [nvarchar](10) NULL,
	[SUB_STD_ARTICLE_DELI] [nvarchar](1) NULL,
	[LEAD_FREE] [nvarchar](5) NULL,
	[REMARK1] [nvarchar](66) NULL,
	[REMARK2] [nvarchar](66) NULL,
	[EXPORT_SO_RELAY_KEY] [nvarchar](10) NULL,
	[SITE_SHIPDOC_NO] [nvarchar](10) NULL,
	[DOMESTIC_FACDROP_FLG] [nvarchar](1) NULL,
	[L_REGIST_DATE] [date] NULL,
	[L_REGIST_NAME] [nvarchar](12) NULL,
	[L_REGIST_TIME] [decimal](6, 0) NULL,
	[RENESAS_PART_NO] [nvarchar](30) NULL,
	[WSTS_CD] [nvarchar](2) NULL,
	[MONTHLY_REPORT_CD] [nvarchar](3) NULL,
	[RECEIPT_UNIT_CD] [nvarchar](2) NULL,
	[RECEIPT_DIVISION_CD] [nvarchar](2) NULL,
	[RECEIPT_DEPT_CD] [nvarchar](2) NULL,
	[RECEIPT_SECTION_CD] [nvarchar](2) NULL,
	[RECEIPT_AGENT_CD] [nvarchar](2) NULL,
	[REC_INS_DATE] [nvarchar](8) NULL,
	[REC_INS_TIME] [nvarchar](6) NULL,
	[DOC_ISSUE_MONTH] [nvarchar](8) NULL,
	[UPD_CNT] [decimal](16, 0) NULL,
	[RECEIPT_CD] [nvarchar](2) NULL,
	[DISPLAY_DOCTYPE] [nvarchar](30) NULL,
	[DISPLAY_DOCTYPE_EN] [nvarchar](30) NULL,
	[RDS_UNITPRICE] [decimal](18, 0) NULL,
	[RDS_AMOUNT] [decimal](18, 0) NULL,
	[RTS_UNITPRICE] [decimal](18, 0) NULL,
	[RTS_AMOUNT] [decimal](18, 0) NULL,
	[H_NET_AMOUNT_JPY] [decimal](20, 5) NULL,
	[H_NET_AMOUNT_RATE] [decimal](7, 4) NULL,
	[L_NET_AMOUNT_JPY] [decimal](20, 5) NULL,
	[L_NET_AMOUNT_RATE] [decimal](7, 4) NULL,
	[RDS_AMOUNT_JPY] [decimal](20, 5) NULL,
	[RDS_AMOUNT_RATE] [decimal](7, 4) NULL,
	[RTS_AMOUNT_JPY] [decimal](20, 5) NULL,
	[RTS_AMOUNT_RATE] [decimal](7, 4) NULL,
	[RT_BUSINESS_SITE_CD] [nvarchar](2) NULL,
	[RT_UNIT_CD] [nvarchar](2) NULL,
	[RT_DIVISION_CD] [nvarchar](2) NULL,
	[RT_DEPT_CD] [nvarchar](2) NULL,
	[RT_SECTION_CD] [nvarchar](2) NULL,
	[PLANT_WP_CD] [nvarchar](3) NULL,
	[PLANT_WT_CD] [nvarchar](3) NULL,
	[PLANT_DIC_CD] [nvarchar](3) NULL,
	[PLANT_ASSY_CD] [nvarchar](3) NULL,
	[PLANT_FT_CD] [nvarchar](3) NULL,
	[UPDATE_MONTH] [nvarchar](6) NULL,
	[FIRST_REC_INS_MONTH] [nvarchar](6) NULL,
	[SPEC_MATERIAL_CD] [nvarchar](18) NULL,
	[SPEC_PART_NO] [nvarchar](40) NULL,
	[PD_MATERIAL_CD] [nvarchar](18) NULL,
	[SALES_ORDER_SPEC_1] [nvarchar](3) NULL,
	[SALES_ORDER_SPEC_2] [nvarchar](3) NULL,
	[SALES_ORDER_SPEC_3] [nvarchar](3) NULL,
	[WAREHOUSING_SPEC] [nvarchar](3) NULL,
	[DESIGN_BU_2_CD] [nvarchar](4) NULL,
	[DS_UNIT_NAME_J] [nvarchar](40) NULL,
	[DS_UNIT_NAME_E] [nvarchar](40) NULL,
	[DESIGN_BU_3_CD] [nvarchar](6) NULL,
	[DS_DIVISION_NAME_J] [nvarchar](40) NULL,
	[DS_DIVISION_NAME_E] [nvarchar](40) NULL,
	[SHIPDATA_DIV] [nvarchar](1) NULL,
	[SEG_CD] [nvarchar](28) NULL
) ON [PS_PartitionByMonth_DW]([DOC_ISSUE_DATE])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_T_SAL_SHIPPING_TO_1] ON [dbo].[T_SAL_SHIPPING_TO]
(
	[SCM_CUSTOMER] ASC,
	[SPEC_MATERIAL_CD] ASC,
	[SEG_CD] ASC,
	[DOC_CURRENCY] ASC,
	[UPDATE_MONTH] ASC,
	[DOC_ISSUE_DATE] ASC,
	[SO_DATE] ASC,
	[CARRY_DATE] ASC,
	[SHIPDATA_DIV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([DOC_ISSUE_DATE])
GO
