USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Z_WEB_UPDATE](
	[SSIS_PACKAGE] [nvarchar](256) NOT NULL,
	[DS_TB_NAME] [nvarchar](3) NOT NULL,
	[UPDATE_DATE] [date] NULL,
 CONSTRAINT [PK_Z_WEB_UPDATE] PRIMARY KEY CLUSTERED 
(
	[SSIS_PACKAGE] ASC,
	[DS_TB_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master]
) ON [BI_DW_Master]

GO
