USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_PARTNO_CUST_CD] AS
	SELECT  [SUM].[SO_PART_NO_KEY_A4]
	       ,[SUM].[SCM_CUSTOMER_CD]
	       ,(CASE
			WHEN [SUM].[BILL_COUNT] = 1 AND [SUM].[ORDER_COUNT] = 1 THEN
				0
			WHEN [SUM].[BILL_COUNT] = 1 AND [SUM].[ORDER_COUNT] = 0 THEN
				0
			ELSE
				1
		END
		) AS [BILL_BOOK_FLG]
	from (
			SELECT  [BILLORDER].[SO_PART_NO_KEY_A4]
	               ,[BILLORDER].[SCM_CUSTOMER_CD]
	               ,count([BILLORDER].[BILL_COUNT]) AS [BILL_COUNT]
	               ,count([BILLORDER].[ORDER_COUNT]) AS [ORDER_COUNT]
			FROM (
				SELECT [R].[BOOKING_PN] AS [SO_PART_NO_KEY_A4]
				      ,[BILL].[SCM_CUSTOMER_CD]
				      ,1 AS [BILL_COUNT]
				      ,null AS [ORDER_COUNT]
				  FROM ( 
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_TO_BILL] AS [T]
					 WHERE [T].[REGISTRATION_DATE] >= (SELECT S_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'0')
					   AND [T].[REGISTRATION_DATE] <= (SELECT E_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'0')
					UNION ALL
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_GO_BILL] AS [T]
					 WHERE [T].[REGISTRATION_DATE] >= (SELECT S_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'0')
					   AND [T].[REGISTRATION_DATE] <= (SELECT E_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'0')
					UNION ALL
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_SO_BILL] AS [T]
					 WHERE [T].[REGISTRATION_DATE] >= (SELECT S_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'0')
					   AND [T].[REGISTRATION_DATE] <= (SELECT E_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'0')
				       )  AS [BILL]
				  LEFT OUTER JOIN [DM_MST].[dbo].[V_MST_BOOK_PN] AS [R]
				   ON ([BILL].[SO_PART_NO] = [R].[BOOKING_PN_CD])
				GROUP BY [R].[BOOKING_PN]
				        ,[BILL].[SCM_CUSTOMER_CD]
				UNION ALL
				SELECT [R].[BOOKING_PN] AS [SO_PART_NO_KEY_A4]
				      ,[ORDER].[SCM_CUSTOMER_CD]
				      ,null AS [BILL_COUNT]
				      ,1 AS [ORDER_COUNT]
				  FROM ( 
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_TO_BOOK] AS [T]
					 WHERE [T].[REQUEST_DATE] >= (SELECT DATEADD(month, -1, S_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					   AND [T].[REQUEST_DATE] <= (SELECT E_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					UNION ALL
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_GO_BOOK] AS [T]
					 WHERE [T].[REQUEST_DATE] >= (SELECT DATEADD(month, -1, S_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					   AND [T].[REQUEST_DATE] <= (SELECT E_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					UNION ALL
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_SO_BOOK] AS [T]
					 WHERE [T].[REQUEST_DATE] >= (SELECT DATEADD(month, -1, S_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					   AND [T].[REQUEST_DATE] <= (SELECT E_DATE FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					UNION ALL
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_TO_BOOK] AS [T]
					 WHERE [T].[REGISTRATION_DATE] >= (SELECT DATEADD(month, -2, S_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					   AND [T].[REGISTRATION_DATE] <= (SELECT DATEADD(month, -2, E_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					UNION ALL
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_GO_BOOK] AS [T]
					 WHERE [T].[REGISTRATION_DATE] >= (SELECT DATEADD(month, -2, S_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					   AND [T].[REGISTRATION_DATE] <= (SELECT DATEADD(month, -2, E_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					UNION ALL
					SELECT  [T].[BOOKING_PN_CD] AS [SO_PART_NO]
					   ,[T].[SCM_CUSTOMER] AS [SCM_CUSTOMER_CD]
					  FROM [DM_SALES].[dbo].[TUSR_T_SO_BOOK] AS [T]
					 WHERE [T].[REGISTRATION_DATE] >= (SELECT DATEADD(month, -2, S_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
					   AND [T].[REGISTRATION_DATE] <= (SELECT DATEADD(month, -2, E_DATE) FROM [BI_DW].[dbo].[Z_SEL_DATE] WHERE BILL_BOOK_FLG = N'1')
				        ) AS [ORDER]
				  LEFT OUTER JOIN [DM_MST].[dbo].[V_MST_BOOK_PN] AS [R]
				   ON ([ORDER].[SO_PART_NO] = [R].[BOOKING_PN_CD])
				GROUP BY [R].[BOOKING_PN]
	                    ,[ORDER].[SCM_CUSTOMER_CD]
			) AS [BILLORDER]
			GROUP BY [BILLORDER].[SO_PART_NO_KEY_A4]
	                ,[BILLORDER].[SCM_CUSTOMER_CD]
		) AS [SUM]
GO
