USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_SAL_BACKLOG_TO](
	[H_SALESDOC_NO] [nvarchar](10) NULL,
	[UPDATE_KIND] [nvarchar](1) NULL,
	[SODOC_TYPE] [nvarchar](4) NULL,
	[BUSINESS_SITE_CD] [nvarchar](2) NULL,
	[R3_COMPANY_CD] [nvarchar](4) NULL,
	[SALES_ORG] [nvarchar](4) NULL,
	[DIST_CHANNEL] [nvarchar](2) NULL,
	[SALES_GRP] [nvarchar](2) NULL,
	[APPLICATION_CD] [nvarchar](3) NULL,
	[DOC_ISSUE_DATE] [date] NULL,
	[CNTL_AREA] [nvarchar](4) NULL,
	[NET_AMOUNT] [decimal](15, 2) NULL,
	[SO_CNTL_DOC_CATEGORY] [nvarchar](1) NULL,
	[H_REFSO_NO] [nvarchar](10) NULL,
	[SHIP_CONDITION] [nvarchar](2) NULL,
	[DOC_CURRENCY] [nvarchar](5) NULL,
	[SO_DC_SHIPDOC_NO] [nvarchar](10) NULL,
	[H_PAYTERM] [nvarchar](4) NULL,
	[SCM_DOC_CATEGORY] [nvarchar](1) NULL,
	[SCM_PROCESS_FLAG] [nvarchar](2) NULL,
	[L_SALESDOCITEM_NO] [decimal](6, 0) NULL,
	[DELI_SCHD_LINE_NO] [decimal](4, 0) NULL,
	[ITEM_CATEGORY] [nvarchar](4) NULL,
	[PLANT_NO] [nvarchar](4) NULL,
	[PLANT_CNTRY_CD] [nvarchar](3) NULL,
	[PL_CNTRY_NAME_JA] [nvarchar](15) NULL,
	[PL_CNTRY_NAME_EN] [nvarchar](15) NULL,
	[STORAGEPLC] [nvarchar](4) NULL,
	[SHIP_POINT] [nvarchar](4) NULL,
	[PD_PART_NO] [nvarchar](40) NULL,
	[PROD_CATEGORY_1_CD] [nvarchar](2) NULL,
	[PROD_NAME_1] [nvarchar](40) NULL,
	[PROD_CATEGORY_2_CD] [nvarchar](2) NULL,
	[PROD_NAME_2] [nvarchar](40) NULL,
	[PROD_CATEGORY_3_CD] [nvarchar](2) NULL,
	[PROD_NAME_3] [nvarchar](40) NULL,
	[PROD_CATEGORY_4_CD] [nvarchar](2) NULL,
	[PROD_NAME_4] [nvarchar](40) NULL,
	[PROD_CATEGORY_5_CD] [nvarchar](2) NULL,
	[PROD_NAME_5] [nvarchar](40) NULL,
	[PART_NO_GROUP] [nvarchar](9) NULL,
	[CUSTOMER_PART_NO] [nvarchar](35) NULL,
	[INPUT_PART_NO] [nvarchar](18) NULL,
	[ACCUMULATED_SO_QTY] [decimal](15, 3) NULL,
	[BASE_UNIT] [nvarchar](3) NULL,
	[UNIT] [nvarchar](3) NULL,
	[REFUSAL_REASON] [nvarchar](2) NULL,
	[INCOTERMS] [nvarchar](3) NULL,
	[INCOTERMS2] [nvarchar](28) NULL,
	[SUBSTITUTION_ITEM_NO] [decimal](6, 0) NULL,
	[NET_PRICE] [decimal](15, 4) NULL,
	[NET_PRICE_CONDITION] [decimal](15, 4) NULL,
	[PRICE_CONDITION_UNIT] [decimal](5, 0) NULL,
	[NET_A] [decimal](15, 2) NULL,
	[NET_WEIGHT] [decimal](15, 3) NULL,
	[TAX_AMOUNT] [decimal](15, 2) NULL,
	[WBS_ELEMENT] [nvarchar](24) NULL,
	[CARRYING_ROUTE] [nvarchar](6) NULL,
	[SALES_UNIT] [nvarchar](3) NULL,
	[COST_PRICE] [decimal](15, 4) NULL,
	[RDLV_DATE] [date] NULL,
	[L_PAYTERM] [nvarchar](4) NULL,
	[PRICE_UPDN_RELAY_FLG] [nvarchar](1) NULL,
	[DIST_FLAG] [nvarchar](3) NULL,
	[INV_NO] [nvarchar](35) NULL,
	[CARRY_FLAG] [nvarchar](2) NULL,
	[PRSSD_GOODS_FLG] [nvarchar](1) NULL,
	[SCM_PRDCT_JDG_FLG] [nvarchar](1) NULL,
	[OSC_TIEUP_KEY] [nvarchar](10) NULL,
	[ORIGIN_DATA_FLAG] [nvarchar](1) NULL,
	[CO_ANNOUNCE_DATE] [date] NULL,
	[LC_NO] [nvarchar](15) NULL,
	[CONDITION_RATE] [decimal](15, 4) NULL,
	[ITEM_CDTION_CURRENCY] [nvarchar](5) NULL,
	[SO_COMPANY] [nvarchar](10) NULL,
	[OSC_SOLDTO] [nvarchar](10) NULL,
	[OSC_SO_UNITPRICE] [decimal](15, 4) NULL,
	[OSC_SO_CURRENCY] [nvarchar](5) NULL,
	[SECONDARY_CURRENCY] [nvarchar](5) NULL,
	[SECONDARY_SO_NO] [nvarchar](35) NULL,
	[SECONDARY_UNITPRICE] [decimal](15, 4) NULL,
	[SO_NO] [nvarchar](10) NULL,
	[SOITEM_NO] [nvarchar](6) NULL,
	[CUSTPO_NO] [nvarchar](35) NULL,
	[CUSTPOITEM_NO] [nvarchar](6) NULL,
	[SHIPTO_CUSTPO_NO] [nvarchar](35) NULL,
	[SHIPTO_CUSTPO_DATE] [date] NULL,
	[REF_FLAG] [nvarchar](12) NULL,
	[ESTIMATE_NO] [nvarchar](10) NULL,
	[ESTIMATEITEM_NO] [nvarchar](6) NULL,
	[L_REFSO_NO] [nvarchar](10) NULL,
	[REFSOITEM_NO] [decimal](6, 0) NULL,
	[SO_NO_22] [nvarchar](22) NULL,
	[RETURNED_GOODSITEM] [nvarchar](1) NULL,
	[REMARK1] [nvarchar](66) NULL,
	[REMARK2] [nvarchar](66) NULL,
	[DELI_STATEMENT_SO] [nvarchar](10) NULL,
	[SOLDTO_CD] [nvarchar](10) NULL,
	[SOT_SHORT_NAME] [nvarchar](40) NULL,
	[SOT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SOT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[SHIPTO_CD] [nvarchar](10) NULL,
	[SIT_SHORT_NAME] [nvarchar](40) NULL,
	[SIT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SIT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[BILLTO_CD] [nvarchar](10) NULL,
	[BT_SHORT_NAME] [nvarchar](40) NULL,
	[BT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[BT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[PAYER] [nvarchar](10) NULL,
	[SO_CONTRACT_TO] [nvarchar](10) NULL,
	[SCM_CUSTOMER] [nvarchar](10) NULL,
	[SCM_SHORT_NAME] [nvarchar](40) NULL,
	[SCM_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SCM_SHORT_NAME_EN] [nvarchar](20) NULL,
	[SA_ROUTE_CD] [nvarchar](2) NULL,
	[SP_STOCK_PARTNER] [nvarchar](10) NULL,
	[DELIVERY_METHOD_TO] [nvarchar](10) NULL,
	[DELIVERY_TRADER] [nvarchar](10) NULL,
	[EXP_FWDR] [nvarchar](10) NULL,
	[PD_END_USER] [nvarchar](10) NULL,
	[CUST_CARRY_PLACE_CD] [nvarchar](10) NULL,
	[SO_CONTRACTOR] [nvarchar](10) NULL,
	[CROSS_DOC_SEND_TO] [nvarchar](10) NULL,
	[SALES_ROUTE_FLAG] [nvarchar](2) NULL,
	[RDS_PRICE_CDTON_UT] [decimal](5, 0) NULL,
	[RDS_SALES_UNITPRICE] [decimal](15, 4) NULL,
	[RDS_SALES_CURRENCY] [nvarchar](5) NULL,
	[RTS_PRICE_CDTION_UT] [decimal](5, 0) NULL,
	[RTS_SALES_UNITPRICE] [decimal](15, 4) NULL,
	[RTS_SALES_CURRENCY] [nvarchar](5) NULL,
	[INORDER_INVERT_FLAG] [nvarchar](1) NULL,
	[SOTO_COTO_FLAG] [nvarchar](1) NULL,
	[ORDER_FLAG] [nvarchar](1) NULL,
	[CONSIGNMENT_FLAG] [nvarchar](1) NULL,
	[EXPORT_SO_RELAY_KEY] [nvarchar](10) NULL,
	[SHIPTO_CNTRY_CD] [nvarchar](3) NULL,
	[SIT_CNTRY_NAME_JA] [nvarchar](15) NULL,
	[SIT_CNTRY_NAME_EN] [nvarchar](15) NULL,
	[AREA_1_NAME_JA] [nvarchar](20) NULL,
	[AREA_1_NAME_EN] [nvarchar](20) NULL,
	[AREA_2_NAME_JA] [nvarchar](20) NULL,
	[AREA_2_NAME_EN] [nvarchar](20) NULL,
	[AREA_3_NAME_JA] [nvarchar](20) NULL,
	[AREA_3_NAME_EN] [nvarchar](20) NULL,
	[MAX_SPRIT_DELI_FRQ] [decimal](1, 0) NULL,
	[SPRIT_DELI_FLG] [nvarchar](1) NULL,
	[LATEST_RDLV_DATE] [date] NULL,
	[GI_DATE] [date] NULL,
	[BKLG_QTY] [decimal](15, 3) NULL,
	[CONFIR_QTY] [decimal](15, 3) NULL,
	[CONFIR_BKLG_QTY] [decimal](15, 3) NULL,
	[FLT_FIXED_QTY] [decimal](15, 3) NULL,
	[RENESAS_PART_NO] [nvarchar](30) NULL,
	[RECEIPT_GROUP_CD] [nvarchar](2) NULL,
	[RECEIPT_UNIT_CD] [nvarchar](2) NULL,
	[RECEIPT_DIVISION_CD] [nvarchar](2) NULL,
	[RECEIPT_DEPT_CD] [nvarchar](2) NULL,
	[RECEIPT_SECTION_CD] [nvarchar](2) NULL,
	[RECEIPT_AGENT_CD] [nvarchar](2) NULL,
	[REC_INS_DATE] [nvarchar](8) NULL,
	[REC_INS_TIME] [nvarchar](6) NULL,
	[TKY_MONTH] [nvarchar](6) NULL,
	[RECEIPT_CD] [nvarchar](2) NULL,
	[RDS_UNITPRICE] [decimal](10, 9) NULL,
	[RDS_AMOUNT] [decimal](10, 9) NULL,
	[RTS_UNITPRICE] [decimal](10, 9) NULL,
	[RTS_AMOUNT] [decimal](10, 9) NULL,
	[DISPLAY_DOCTYPE] [nvarchar](30) NULL,
	[DISPLAY_DOCTYPE_EN] [nvarchar](30) NULL,
	[FORJUDGE_PARTNO] [nvarchar](30) NULL,
	[NET_AMOUNT_JPY] [decimal](20, 5) NULL,
	[NET_AMOUNT_RATE] [decimal](7, 4) NULL,
	[NET_A_JPY] [decimal](20, 5) NULL,
	[NET_A_RATE] [decimal](7, 4) NULL,
	[RDS_AMOUNT_JPY] [decimal](20, 5) NULL,
	[RDS_AMOUNT_RATE] [decimal](7, 4) NULL,
	[RTS_AMOUNT_JPY] [decimal](20, 5) NULL,
	[RTS_AMOUNT_RATE] [decimal](7, 4) NULL,
	[BKLG_QTY_AMOUNT] [decimal](20, 5) NULL,
	[BKLG_QTY_AMOUNT_JPY] [decimal](20, 5) NULL,
	[FLT_FIXED_QTY_A] [decimal](20, 5) NULL,
	[FLT_FIXED_QTY_A_JPY] [decimal](20, 5) NULL,
	[RT_BUSINESS_SITE_CD] [nvarchar](2) NULL,
	[RT_UNIT_CD] [nvarchar](2) NULL,
	[RT_DIVISION_CD] [nvarchar](2) NULL,
	[RT_DEPT_CD] [nvarchar](2) NULL,
	[RT_SECTION_CD] [nvarchar](2) NULL,
	[SPEC_MATERIAL_CD] [nvarchar](18) NULL,
	[SPEC_PART_NO] [nvarchar](40) NULL,
	[PD_MATERIAL_CD] [nvarchar](18) NULL,
	[SALES_ORDER_SPEC_1] [nvarchar](3) NULL,
	[SALES_ORDER_SPEC_2] [nvarchar](3) NULL,
	[SALES_ORDER_SPEC_3] [nvarchar](3) NULL,
	[SEG_CD] [nvarchar](28) NULL,
	[RECORD_DATE] [date] NULL
) ON [PS_PartitionByMonth_DW]([RECORD_DATE])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_T_SAL_BACKLOG_TO_1] ON [dbo].[T_SAL_BACKLOG_TO]
(
	[SCM_CUSTOMER] ASC,
	[SPEC_MATERIAL_CD] ASC,
	[SEG_CD] ASC,
	[DOC_CURRENCY] ASC,
	[TKY_MONTH] ASC,
	[RECORD_DATE] ASC,
	[DOC_ISSUE_DATE] ASC,
	[SHIPTO_CUSTPO_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([RECORD_DATE])
GO
