USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[R_ANP_BUDGET_FIXED](
	[CUSTOMERCD] [nvarchar](10) NULL,
	[PARTNO] [nvarchar](40) NULL,
	[PNCUSTOMERCD] [nvarchar](50) NULL,
	[SALESAGENTCD] [nvarchar](2) NULL,
	[SALESROUTE] [nvarchar](3) NULL,
	[VERSIONOPEN] [nvarchar](1) NULL,
	[VERSIONRESULT] [nvarchar](1) NULL,
	[QUARTERYM] [nvarchar](6) NULL,
	[CURRENCYCD] [nvarchar](3) NULL,
	[COMMITQTY] [decimal](14, 1) NULL,
	[COMMITAMT] [money] NULL,
	[COMMITAMTJPY] [decimal](15, 0) NULL,
	[UPDATE_DATE] [date] NULL,
	[REG_DATETIME] [smalldatetime] NULL,
	[UPD_DATETIME] [smalldatetime] NULL
) ON [BI_DW_Staging]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
ALTER TABLE [dbo].[R_ANP_BUDGET_FIXED] ADD  CONSTRAINT [DF_R_ANP_BUDGET_FIXED_REG_DATETIME]  DEFAULT (getdate()) FOR [REG_DATETIME]
GO
ALTER TABLE [dbo].[R_ANP_BUDGET_FIXED] ADD  CONSTRAINT [DF_R_ANP_BUDGET_FIXED_UPD_DATETIME]  DEFAULT (getdate()) FOR [UPD_DATETIME]
GO
