USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Z_SSIS_CTRL](
	[SSIS_PACKAGE] [nvarchar](128) NOT NULL,
	[JOB_TYPE] [nvarchar](1) NOT NULL,
	[DS_TB_NAME] [nvarchar](3) NOT NULL,
	[DEEMED_DATE] [date] NULL,
	[PROC_S_DATE] [date] NULL,
	[PROC_E_DATE] [date] NULL,
	[LAST_DATA_ACCUM_PROC_DATETIME] [datetime] NULL,
	[UPDT_S_YM] [nvarchar](6) NULL,
	[UPDT_E_YM] [nvarchar](6) NULL,
	[UPDT_S_DATE] [date] NULL,
	[UPDT_E_DATE] [date] NULL,
	[DATA_DATE] [datetime] NULL,
	[AUTO_PROSESS_DIV] [nvarchar](1) NULL,
	[ADJUST_UPDT_BASE_DATE] [nvarchar](1) NULL,
	[ADJUST_UPDT_FLG] [nvarchar](2) NULL,
	[ADJUST_UPDT_S] [numeric](10, 0) NULL,
	[ADJUST_UPDT_E] [numeric](10, 0) NULL,
 CONSTRAINT [PK_Z_SSIS_CTRL] PRIMARY KEY CLUSTERED 
(
	[SSIS_PACKAGE] ASC,
	[JOB_TYPE] ASC,
	[DS_TB_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master]
) ON [BI_DW_Master]

GO
