USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_SAL_V1JSF](
	[SCM_CUSTOMER_CD] [nvarchar](10) NULL,
	[ORDER_PART_NO_CD] [nvarchar](18) NULL,
	[SEG_CD] [nvarchar](28) NULL,
	[BUSINESS_SITE] [nvarchar](2) NULL,
	[CALENDAR_YM] [date] NULL,
	[UPDATE_DATE] [date] NULL,
	[RESULTDIV] [nvarchar](1) NULL,
	[CURRENCY] [nvarchar](5) NULL,
	[V0V1DIV] [nvarchar](2) NULL,
	[SHAREUPFLG] [decimal](1, 0) NULL,
	[AUTOJSFMONTHFLG] [decimal](1, 0) NULL,
	[GODemand_Amt_JPY] [money] NULL,
	[GODemand_Std] [money] NULL,
	[GODemand_Qty] [decimal](20, 4) NULL,
	[JSF_Amt_JPY] [money] NULL,
	[JSF_Qty] [decimal](20, 4) NULL
) ON [PS_PartitionByMonth_DW]([UPDATE_DATE])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_T_SAL_V1JSF_1] ON [dbo].[T_SAL_V1JSF]
(
	[SCM_CUSTOMER_CD] ASC,
	[ORDER_PART_NO_CD] ASC,
	[CALENDAR_YM] ASC,
	[UPDATE_DATE] ASC,
	[RESULTDIV] ASC,
	[V0V1DIV] ASC,
	[SHAREUPFLG] ASC,
	[AUTOJSFMONTHFLG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([UPDATE_DATE])
GO

