USE [BI_DW]
GO
/****** Object:  Table [dbo].[Z_TABULAR_CTRL]    Script Date: 2017/05/29 10:25:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Z_TABULAR_CTRL](
	[DATABASE_NAME] [nvarchar](64) NOT NULL,
	[TABLE_NAME] [nvarchar](64) NOT NULL,
	[SOURCE_TABLE] [nvarchar](64) NOT NULL,
	[SOURCE_COLUMNS] [nvarchar](max) NULL,
	[DATASOURCE] [nvarchar](64) NULL,
	[MIN_PARTITION_NAME] [nvarchar](64) NULL,
	[START_DATE] [date] NULL,
	[END_DATE] [date] NULL,
	[INTERVAL_DATE_PART] [nvarchar](10) NULL,
	[INTERVAL_VALUE] [int] NULL,
	[CONDITION] [nvarchar](128) NULL,
	[TABLE_DIV] [nvarchar](10) NOT NULL,
	[SSIS_PACKAGE] [nchar](256) NULL,
	[PROCESS_COMPLETION_DATETIME] [smalldatetime] NULL,
 CONSTRAINT [PK_Z_TABULAR_CTRL] PRIMARY KEY CLUSTERED 
(
	[DATABASE_NAME] ASC,
	[TABLE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [BI_DW_Master]
) ON [BI_DW_Master] TEXTIMAGE_ON [BI_DW_Transaction_NonPartition]

GO
ALTER TABLE [dbo].[Z_TABULAR_CTRL] ADD  CONSTRAINT [DF_Z_TABULAR_CTRL_SOURCE_TABLE]  DEFAULT ('') FOR [SOURCE_TABLE]
GO
ALTER TABLE [dbo].[Z_TABULAR_CTRL] ADD  CONSTRAINT [DF_Z_TABULAR_CTRL_SOURCE_COLUMNS]  DEFAULT ('*') FOR [SOURCE_COLUMNS]
GO
ALTER TABLE [dbo].[Z_TABULAR_CTRL] ADD  CONSTRAINT [DF_Z_TABULAR_CTRL_TABLE_DIV]  DEFAULT (N'FACT') FOR [TABLE_DIV]
GO
