USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_SAL_BILL_TO](
	[H_BILLDOC_NO] [nvarchar](10) NULL,
	[CO_NO] [nvarchar](12) NULL,
	[BILLDOC_TYPE] [nvarchar](4) NULL,
	[BILL_CATEGORY] [nvarchar](1) NULL,
	[BILL_DATE] [date] NULL,
	[BUSINESS_SITE_CD] [nvarchar](2) NULL,
	[R3_COMPANY_CD] [nvarchar](4) NULL,
	[H_SALES_ORG] [nvarchar](4) NULL,
	[H_DIST_CHANNEL] [nvarchar](2) NULL,
	[H_SALES_GRP] [nvarchar](2) NULL,
	[SHIP_CONDITION] [nvarchar](2) NULL,
	[INCOTERMS] [nvarchar](3) NULL,
	[INCOTERMS2] [nvarchar](28) NULL,
	[DOC_CURRENCY] [nvarchar](5) NULL,
	[PAYTERM] [nvarchar](4) NULL,
	[H_REFSO_NO] [nvarchar](16) NULL,
	[ALLOCATION_NO] [nvarchar](18) NULL,
	[SO_CNTL_DOC_CAT] [nvarchar](1) NULL,
	[ULPORT_CNTRY] [nvarchar](3) NULL,
	[UL_CNTRY_NAME_JA] [nvarchar](15) NULL,
	[UL_CNTRY_NAME_EN] [nvarchar](15) NULL,
	[AREA] [nvarchar](3) NULL,
	[AREA_1_NAME_JA] [nvarchar](20) NULL,
	[AREA_1_NAME_EN] [nvarchar](20) NULL,
	[AREA_2_NAME_JA] [nvarchar](20) NULL,
	[AREA_2_NAME_EN] [nvarchar](20) NULL,
	[AREA_3_NAME_JA] [nvarchar](20) NULL,
	[AREA_3_NAME_EN] [nvarchar](20) NULL,
	[TAX_SHIPTO_CNTRY] [nvarchar](3) NULL,
	[TAX_CNTRY_NAME_JA] [nvarchar](15) NULL,
	[TAX_CNTRY_NAME_EN] [nvarchar](15) NULL,
	[H_TAX_AMOUNT] [decimal](15, 2) NULL,
	[SOLDTO_CD] [nvarchar](10) NULL,
	[SOT_SHORT_NAME] [nvarchar](40) NULL,
	[SOT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SOT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[SHIPTO_CD] [nvarchar](10) NULL,
	[SIT_SHORT_NAME] [nvarchar](40) NULL,
	[SIT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SIT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[BILLTO_CD] [nvarchar](10) NULL,
	[BT_SHORT_NAME] [nvarchar](40) NULL,
	[BT_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[BT_SHORT_NAME_EN] [nvarchar](20) NULL,
	[PAYER] [nvarchar](10) NULL,
	[SO_CONTRACT_TO] [nvarchar](10) NULL,
	[SCM_CUSTOMER] [nvarchar](10) NULL,
	[SCM_SHORT_NAME] [nvarchar](40) NULL,
	[SCM_SHORT_NAME_KANA] [nvarchar](20) NULL,
	[SCM_SHORT_NAME_EN] [nvarchar](20) NULL,
	[SA_ROUTE_CD] [nvarchar](2) NULL,
	[SP_STOCK_PRTNR] [nvarchar](10) NULL,
	[DELIVERY_METHOD_TO] [nvarchar](10) NULL,
	[DELIVERY_TRADER] [nvarchar](10) NULL,
	[EXP_FWDR] [nvarchar](10) NULL,
	[PD_END_USER] [nvarchar](10) NULL,
	[CUST_CARRY_PLACE_CD] [nvarchar](10) NULL,
	[SO_CONTRACTOR] [nvarchar](10) NULL,
	[CROSS_DOC_SEND_TO] [nvarchar](10) NULL,
	[EXTERNAL_DELIVERY_ID] [nvarchar](18) NULL,
	[BILLTO_DATE] [nvarchar](8) NULL,
	[BILLTO_CUSTNAME_KANA] [nvarchar](35) NULL,
	[CUSTTAX_FLAG] [nvarchar](1) NULL,
	[COMPANY_NAME] [nvarchar](40) NULL,
	[BILLORG_ZIP_CD] [nvarchar](7) NULL,
	[BILLORG_ADD1] [nvarchar](50) NULL,
	[BILLORG_ADD2] [nvarchar](50) NULL,
	[BILLORG_TEL_NO] [nvarchar](30) NULL,
	[BILLDOCITEM_NO] [decimal](6, 0) NULL,
	[PLANT_NO] [nvarchar](4) NULL,
	[SALESDOC_NO] [nvarchar](10) NULL,
	[SALESDOCITEM_NO] [decimal](6, 0) NULL,
	[SODOC_TYPE] [nvarchar](4) NULL,
	[L_REFSO_NO] [nvarchar](10) NULL,
	[REFSOITEM_NO] [decimal](6, 0) NULL,
	[CUSTPO_NO] [nvarchar](35) NULL,
	[VERIFICATION_KEY] [nvarchar](35) NULL,
	[SO_BOOKING_DATE] [date] NULL,
	[PD_PART_NO] [nvarchar](40) NULL,
	[PROD_CATEGORY_1_CD] [nvarchar](2) NULL,
	[PROD_NAME_1] [nvarchar](40) NULL,
	[PROD_CATEGORY_2_CD] [nvarchar](2) NULL,
	[PROD_NAME_2] [nvarchar](40) NULL,
	[PROD_CATEGORY_3_CD] [nvarchar](2) NULL,
	[PROD_NAME_3] [nvarchar](40) NULL,
	[PROD_CATEGORY_4_CD] [nvarchar](2) NULL,
	[PROD_NAME_4] [nvarchar](40) NULL,
	[PROD_CATEGORY_5_CD] [nvarchar](2) NULL,
	[PROD_NAME_5] [nvarchar](40) NULL,
	[INPUT_PART_NO] [nvarchar](18) NULL,
	[BASE_UNIT] [nvarchar](3) NULL,
	[SALES_UNIT] [nvarchar](3) NULL,
	[BILL_QTY] [decimal](15, 3) NULL,
	[NET_WEIGHT] [decimal](15, 3) NULL,
	[T_WEIGHT] [decimal](15, 3) NULL,
	[UNIT_W] [nvarchar](3) NULL,
	[NET_PRICE] [decimal](15, 4) NULL,
	[PRICE_CONDITION_UNIT] [nvarchar](5) NULL,
	[NET_AMOUNT] [decimal](15, 2) NULL,
	[TAX_CD] [nvarchar](2) NULL,
	[L_TAX_AMOUNT] [decimal](15, 2) NULL,
	[WBS_ELEMENT] [nvarchar](24) NULL,
	[PRICING_DATE] [date] NULL,
	[RDLV_DATE] [date] NULL,
	[LOT] [nvarchar](10) NULL,
	[HIGHER_LEVEL_ITEM_NO] [decimal](6, 0) NULL,
	[PRE_DOC_CATEGORY] [nvarchar](1) NULL,
	[SPRIT_DELIVERY_NO] [decimal](3, 0) NULL,
	[EXCHANGE_RATE] [decimal](12, 5) NULL,
	[NET_PRICE_CDTION] [decimal](15, 4) NULL,
	[RDS_PRICE_CDTION_UT] [decimal](5, 0) NULL,
	[RDS_SALES_UNITPRICE] [decimal](15, 4) NULL,
	[RDS_SALES_CURRENCY] [nvarchar](5) NULL,
	[RTS_PRICE_CDTION_UT] [decimal](5, 0) NULL,
	[RTS_SALES_UNITPRICE] [decimal](15, 4) NULL,
	[RTS_SALES_CURRENCY] [nvarchar](5) NULL,
	[L_REGIST_DATE] [date] NULL,
	[L_REGIST_NAME] [nvarchar](12) NULL,
	[L_REGIST_TIME] [nvarchar](6) NULL,
	[RENESAS_PART_NO] [nvarchar](30) NULL,
	[RECEIPT_UNIT_CD] [nvarchar](2) NULL,
	[RECEIPT_DIVISION_CD] [nvarchar](2) NULL,
	[RECEIPT_DEPT_CD] [nvarchar](2) NULL,
	[RECEIPT_SECTION_CD] [nvarchar](2) NULL,
	[RECEIPT_AGENT_CD] [nvarchar](2) NULL,
	[REC_INS_DATE] [nvarchar](8) NULL,
	[REC_INS_TIME] [nvarchar](6) NULL,
	[BILLTO_MONTH] [nvarchar](6) NULL,
	[RECEIPT_CD] [nvarchar](2) NULL,
	[DISPLAY_DOCTYPE] [nvarchar](30) NULL,
	[DISPLAY_DOCTYPE_EN] [nvarchar](30) NULL,
	[RDS_UNITPRICE] [decimal](18, 0) NULL,
	[RDS_AMOUNT] [decimal](18, 0) NULL,
	[RTS_UNITPRICE] [decimal](18, 0) NULL,
	[RTS_AMOUNT] [decimal](18, 0) NULL,
	[NET_AMOUNT_JPY] [decimal](20, 5) NULL,
	[NET_AMOUNT_RATE] [decimal](7, 4) NULL,
	[RDS_AMOUNT_JPY] [decimal](20, 5) NULL,
	[RDS_AMOUNT_RATE] [decimal](7, 4) NULL,
	[RTS_AMOUNT_JPY] [decimal](20, 5) NULL,
	[RTS_AMOUNT_RATE] [decimal](7, 4) NULL,
	[RT_BUSINESS_SITE_CD] [nvarchar](2) NULL,
	[RT_UNIT_CD] [nvarchar](2) NULL,
	[RT_DIVISION_CD] [nvarchar](2) NULL,
	[RT_DEPT_CD] [nvarchar](2) NULL,
	[RT_SECTION_CD] [nvarchar](2) NULL,
	[SHIPTO_DATE] [date] NULL,
	[UPDATE_MONTH] [nvarchar](6) NULL,
	[FIRST_REC_INS_MONTH] [nvarchar](6) NULL,
	[SPEC_MATERIAL_CD] [nvarchar](18) NULL,
	[SPEC_PART_NO] [nvarchar](40) NULL,
	[PD_MATERIAL_CD] [nvarchar](18) NULL,
	[SALES_ORDER_SPEC_1] [nvarchar](3) NULL,
	[SALES_ORDER_SPEC_2] [nvarchar](3) NULL,
	[SALES_ORDER_SPEC_3] [nvarchar](3) NULL,
	[SEG_CD] [nvarchar](28) NULL,
	[TP1_AMT] [money] NULL,
	[TP2_AMT] [money] NULL,
	[STD_AMT_USER] [money] NULL,
	[SRP_AMT] [money] NULL,
	[ACTUAL_UNMANAGED_FLG] [nvarchar](1) NULL
) ON [PS_PartitionByMonth_DW]([BILL_DATE])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_T_SAL_BILL_TO_1] ON [dbo].[T_SAL_BILL_TO]
(
	[SCM_CUSTOMER] ASC,
	[SPEC_MATERIAL_CD] ASC,
	[SEG_CD] ASC,
	[DOC_CURRENCY] ASC,
	[BILL_DATE] ASC,
	[SO_BOOKING_DATE] ASC,
	[RDLV_DATE] ASC,
	[SHIPTO_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([BILL_DATE])
GO
