USE [BI_DW]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_SFM_BCCV_D_IN_TARGET_PRD_VIEW_H](
    [OPPORTUNITY_SEQ] [NVARCHAR](80) NOT NULL,
    [SCM_CUSTOMER_CODE] [NVARCHAR](20) NOT NULL,
    [D_IN_TARGET_YEAR] [NVARCHAR](7) NOT NULL,
    [TARGET_FISCAL_YEAR] [NUMERIC](4,0) NULL,
    [TARGET_HALF_YEAR] [NVARCHAR](2) NULL,
    [D_IN_TARGET_PROBABILITY] [NVARCHAR](10) NULL,
    [APPLICATION1_CODE] [NVARCHAR](1) NULL,
    [APPLICATION2_CODE] [NVARCHAR](2) NULL,
    [APPLICATION3_CODE] [NVARCHAR](3) NULL,
    [PART_NO] [NVARCHAR](40) NULL,
    [D_IN_INPUT_YEAR] [NVARCHAR](7) NOT NULL,
    [INPUT_FISCAL_YEAR] [NUMERIC](4,0) NULL,
    [INPUT_HALF_YEAR] [NVARCHAR](2) NULL,
    [D_IN_TARGET_ORIGINAL] [NUMERIC](15,0) NULL,
    [D_IN_TARGET_STRETCH] [NUMERIC](15,0) NULL,
    [D_IN_TARGET] [NUMERIC](18,0) NULL,
    [CURRENCY_ISO_CODE] [NVARCHAR](3) NULL,
    [DELETE_FLAG] [NVARCHAR](1) NULL,
    [CREATED_BY_FEDERATION_ID] [NVARCHAR](4000) NULL,
    [CREATED_BY_EMAIL] [NVARCHAR](128) NULL,
    [CREATED_DATE] [DATE] NULL,
    [LAST_MODIFIED_BY_FEDERATION_ID] [NVARCHAR](4000) NULL,
    [LAST_MODIFIED_BY_EMAIL] [NVARCHAR](128) NULL,
    [LAST_MODIFIED_DATE] [DATE] NULL,
    [SYSTEM_MODSTAMP] [DATE] NULL,
    [UPDATE_DATE] [DATE] NULL
) ON [PS_PartitionByMonth_DW]([UPDATE_DATE])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO

CREATE CLUSTERED INDEX [I_T_SFM_BCCV_D_IN_TARGET_PRD_VIEW_H_1] ON [dbo].[T_SFM_BCCV_D_IN_TARGET_PRD_VIEW_H]
(
	[OPPORTUNITY_SEQ] ASC,
	[UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([UPDATE_DATE])
GO

