USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Z_SSAS_SYNC_LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DB_NAME] [nvarchar](20) NOT NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NULL,
 CONSTRAINT [PK_Z_SSAS_SYNC_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master]
) ON [BI_DW_Master]

GO
