USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[R_DCP_DELIBERATION](
	[DELIBERATION_CD] [nvarchar](6) NOT NULL,
	[DELIBERATION_NAME] [nvarchar](20) NULL,
	[DCP_FLAG] [int] NULL,
	[DCP_UPDATETIME] [smalldatetime] NULL
) ON [BI_DW_Staging]

GO
