USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[T_KPI_DAT](
	[SUMMARY_CODE] [varchar](10) NOT NULL,
	[SUMMARY_KEY_ORG] [varchar](100) NOT NULL,
	[SUMMARY_KEY_YM] [char](7) NOT NULL,
	[SUMMARY_KEY_NUM] [int] NOT NULL,
	[KPI_NAME] [nvarchar](100) NULL,
	[KPI_TYPE] [int] NOT NULL,
	[INPUT_YM] [date] NOT NULL,
	[KEY_RESERVE_01] [nvarchar](300) NULL,
	[KEY_RESERVE_02] [nvarchar](300) NULL,
	[KEY_RESERVE_03] [nvarchar](300) NULL,
	[FISCAL_MNTH_01] [numeric](22, 6) NULL,
	[FISCAL_MNTH_02] [numeric](22, 6) NULL,
	[FISCAL_MNTH_03] [numeric](22, 6) NULL,
	[FISCAL_MNTH_04] [numeric](22, 6) NULL,
	[FISCAL_MNTH_05] [numeric](22, 6) NULL,
	[FISCAL_MNTH_06] [numeric](22, 6) NULL,
	[FISCAL_MNTH_07] [numeric](22, 6) NULL,
	[FISCAL_MNTH_08] [numeric](22, 6) NULL,
	[FISCAL_MNTH_09] [numeric](22, 6) NULL,
	[FISCAL_MNTH_10] [numeric](22, 6) NULL,
	[FISCAL_MNTH_11] [numeric](22, 6) NULL,
	[FISCAL_MNTH_12] [numeric](22, 6) NULL,
	[INS_DATETIME] [datetime] NULL,
	[UPD_DATETIME] [datetime] NULL,
	[CANCEL_FLG] [bit] NULL,
 CONSTRAINT [PK_T_KPI_DAT] PRIMARY KEY CLUSTERED 
(
	[SUMMARY_CODE] ASC,
	[SUMMARY_KEY_ORG] ASC,
	[SUMMARY_KEY_YM] ASC,
	[SUMMARY_KEY_NUM] ASC,
	[KPI_TYPE] ASC,
	[INPUT_YM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([INPUT_YM])
) ON [PS_PartitionByMonth_DW]([INPUT_YM])

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[T_KPI_DAT] ADD  CONSTRAINT [DF_T_KPI_DAT_INS_DATETIME]  DEFAULT (getdate()) FOR [INS_DATETIME]
GO
ALTER TABLE [dbo].[T_KPI_DAT] ADD  CONSTRAINT [DF_T_KPI_DAT_UPD_DATETIME]  DEFAULT (getdate()) FOR [UPD_DATETIME]
GO
