USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Z_CUBE_CTRL](
	[DATABASE_ID] [nvarchar](64) NOT NULL,
	[CUBE_ID] [nvarchar](64) NOT NULL,
	[MEASURE_GROUP_ID] [nvarchar](64) NOT NULL,
	[DATABASE_NAME] [nvarchar](64) NULL,
	[CUBE_NAME] [nvarchar](64) NULL,
	[MEASURE_GROUP_NAME] [nvarchar](64) NULL,
	[SSIS_PACKAGE] [nvarchar](256) NULL,
	[DEEMED_DATE] [date] NULL,
	[PARTITION_RANGE_TYPE] [char](1) NULL,
	[UPDT_S_YM] [nvarchar](6) NULL,
	[UPDT_E_YM] [nvarchar](6) NULL,
	[UPDT_S_DATE] [date] NULL,
	[UPDT_E_DATE] [date] NULL,
	[DATA_DATE] [date] NULL,
	[PROCESS_COMPLETION_DATETIME] [smalldatetime] NULL,
 CONSTRAINT [PK_Z_CUBE_CTRL] PRIMARY KEY CLUSTERED 
(
	[DATABASE_ID] ASC,
	[CUBE_ID] ASC,
	[MEASURE_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master]
) ON [BI_DW_Master]

GO
SET ANSI_PADDING OFF
GO
