USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[R_KPI_DAT](
	[SUMMARY_CODE] [varchar](10) NULL,
	[SUMMARY_KEY_ORG] [varchar](100) NULL,
	[SUMMARY_KEY_YM] [char](7) NULL,
	[SUMMARY_KEY_NUM] [int] NULL,
	[KPI_NAME] [nvarchar](100) NULL,
	[KPI_TYPE] [int] NULL,
	[INPUT_YM] [date] NULL,
	[KEY_RESERVE_01] [nvarchar](300) NULL,
	[KEY_RESERVE_02] [nvarchar](300) NULL,
	[KEY_RESERVE_03] [nvarchar](300) NULL,
	[FISCAL_MNTH_01] [numeric](23, 7) NULL,
	[FISCAL_MNTH_02] [numeric](23, 7) NULL,
	[FISCAL_MNTH_03] [numeric](23, 7) NULL,
	[FISCAL_MNTH_04] [numeric](23, 7) NULL,
	[FISCAL_MNTH_05] [numeric](23, 7) NULL,
	[FISCAL_MNTH_06] [numeric](23, 7) NULL,
	[FISCAL_MNTH_07] [numeric](23, 7) NULL,
	[FISCAL_MNTH_08] [numeric](23, 7) NULL,
	[FISCAL_MNTH_09] [numeric](23, 7) NULL,
	[FISCAL_MNTH_10] [numeric](23, 7) NULL,
	[FISCAL_MNTH_11] [numeric](23, 7) NULL,
	[FISCAL_MNTH_12] [numeric](23, 7) NULL,
	[INS_DATETIME] [datetime] NULL,
	[UPD_DATETIME] [datetime] NULL,
	[CANCEL_FLG] [bit] NULL
) ON [BI_DW_Staging]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[R_KPI_DAT] ADD  CONSTRAINT [DF_R_KPI_DAT_INS_DATETIME]  DEFAULT (getdate()) FOR [INS_DATETIME]
GO
ALTER TABLE [dbo].[R_KPI_DAT] ADD  CONSTRAINT [DF_R_KPI_DAT_UPD_DATETIME]  DEFAULT (getdate()) FOR [UPD_DATETIME]
GO
