USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PSL_SYS_DBPROFILE](
	[DBPROFILE] [varchar](50) NOT NULL,
	[DBSERVER] [varchar](50) NOT NULL,
	[DBNAME] [varchar](50) NOT NULL,
	[DBUSER] [varchar](50) NULL,
	[DBPASSWORD] [varchar](50) NULL,
	[FLAGNTLMAUTH] [bit] NULL,
	[NOTE] [varchar](255) NULL,
 CONSTRAINT [PK_PSL_SYS_DBPROFILE] PRIMARY KEY CLUSTERED 
(
	[DBPROFILE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master]
) ON [BI_DW_Master]

GO
ALTER TABLE [dbo].[PSL_SYS_DBPROFILE] ADD  CONSTRAINT [DF_PSL_SYS_DBPROFILE_DBFLAGNTLMAuth]  DEFAULT ((1)) FOR [FLAGNTLMAUTH]
GO
