USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PSL_SYS_COLMAPPING](
	[QUERY_PROFILE] [varchar](50) NOT NULL,
	[ORG_FNAMEINT] [varchar](30) NOT NULL,
	[NEW_COLUMN_NAME] [varchar](30) NOT NULL,
 CONSTRAINT [PK_PSL_SYS_COLMAPPING] PRIMARY KEY CLUSTERED 
(
	[QUERY_PROFILE] ASC,
	[ORG_FNAMEINT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master],
 CONSTRAINT [IX_PSL_SYS_COLMAPPING] UNIQUE NONCLUSTERED 
(
	[QUERY_PROFILE] ASC,
	[NEW_COLUMN_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_NonClusteredIndex]
) ON [BI_DW_Master]

GO
SET ANSI_PADDING OFF
GO
