USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_RBW_LTVGRAPHDIN_BI_V_H](
	[OPPSEQ] [nvarchar](13) NULL,
	[KCOMPANYG2CD] [nvarchar](300) NULL,
	[KSALESAGENTCD] [nvarchar](12) NULL,
	[KCUSTOMERCD] [nvarchar](12) NULL,
	[BASEPN] [nvarchar](30) NULL,
	[CUSTOMERCD] [nvarchar](10) NULL,
	[PARTNO] [nvarchar](40) NULL,
	[APPLCAT3CD] [nvarchar](3) NULL,
	[S1DATE] [date] NULL,
	[LATESTLTVCURRENCYCD] [nvarchar](3) NULL,
	[NBDIV] [nvarchar](1) NULL,
	[MONTH12] [date] NULL,
	[NENKI] [nvarchar](6) NULL,
	[LTVAMT] [numeric](18, 4) NULL,
	[BILLAMT] [numeric](18, 4) NULL,
	[ALLOCBILLAMT] [numeric](18, 4) NULL,
	[SFAMT] [numeric](18, 4) NULL,
	[ALLOCSFAMT] [numeric](18, 4) NULL,
	[BILLAMTBEYONDLTV] [numeric](18, 4) NULL,
	[SFAMTBEYONDLTV] [numeric](18, 4) NULL,
	[DATADATE] [date] NULL,
	[UPDATE_DATE] [date] NULL
) ON [PS_PartitionByMonth_DW]([MONTH12])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_T_RBW_LTVGRAPHDIN_BI_V_H_1] ON [dbo].[T_RBW_LTVGRAPHDIN_BI_V_H]
(
	[OPPSEQ] ASC,
	[CUSTOMERCD] ASC,
	[PARTNO] ASC,
	[MONTH12] ASC,
	[NENKI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([MONTH12])
GO
