USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PSL_ENUM_PARAMTYPE](
	[PARAMTYPE] [varchar](2) NOT NULL,
	[PARAMTYPENAME] [varchar](50) NULL,
 CONSTRAINT [PK_PSL_ENUM_PARAMTYPE] PRIMARY KEY CLUSTERED 
(
	[PARAMTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master]
) ON [BI_DW_Master]

GO
SET ANSI_PADDING OFF
GO
