USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_SFM_BCCV_OPPORTUNITY_VIEW_H](
	[OPPORTUNITY_NO] [nvarchar](7) NULL,
	[STAGE_TYPE] [nvarchar](2) NULL,
	[OPPORTUNITY_OWNER] [nvarchar](4000) NULL,
	[OPPORTUNITY_OWNER_EMAIL] [nvarchar](128) NULL,
	[OPPORTUNITY_NAME] [nvarchar](120) NULL,
	[ACCOUNT_GROUP_CODE] [nvarchar](255) NULL,
	[ACCOUNT_NAME] [nvarchar](255) NULL,
	[D_IN_SALES_COMPANY] [nvarchar](2) NULL,
	[D_IN_SCM_CUST_CODE_FOR_MTF] [nvarchar](10) NULL,
	[D_IN_SCM_CUST_CODE_FOR_SCM_OPE] [nvarchar](10) NULL,
	[D_IN_SCM_CUST_CODE_DUMMY_FLAG] [nvarchar](1) NULL,
	[APPLICATION1_CODE] [nvarchar](1) NULL,
	[APPLICATION2_CODE] [nvarchar](2) NULL,
	[APPLICATION3_CODE] [nvarchar](3) NULL,
	[CHANNEL_PARTNER_CODE] [nvarchar](40) NULL,
	[CHANNEL_PARTNER_NAME] [nvarchar](255) NULL,
	[OPPORTUNITY_COMMENT] [nvarchar](255) NULL,
	[MP_START_MONTH] [nvarchar](7) NULL,
	[MP_START_DATE] [date] NULL,
	[DURATION_MONTH] [numeric](3, 0) NULL,
	[ESTIMATED_ANNUAL_USAGE] [numeric](18, 0) NULL,
	[ACCUMULATED_USAGE] [numeric](18, 0) NULL,
	[SALES_LEADER_FEDERATION_ID] [nvarchar](4000) NULL,
	[SALES_LEADER_EMAIL] [nvarchar](128) NULL,
	[OPPORTUNITY_CURRENCY] [nvarchar](3) NULL,
	[NDA_FLAG] [nvarchar](1) NULL,
	[OPPORTUNITY_INDUSTRY] [nvarchar](2) NULL,
	[TRACKING_TYPE_STATUS] [nvarchar](2) NULL,
	[DELETE_FLAG] [nvarchar](1) NULL,
	[CREATED_BY_FEDERATION_ID] [nvarchar](4000) NULL,
	[CREATED_BY_EMAIL] [nvarchar](128) NULL,
	[CREATED_DATE] [date] NULL,
	[LAST_MODIFIED_BY_FEDERATION_ID] [nvarchar](4000) NULL,
	[LAST_MODIFIED_BY_EMAIL] [nvarchar](128) NULL,
	[LAST_MODIFIED_DATE] [date] NULL,
	[IF_LAST_MODIFIED_DATE] [date] NULL,
	[UPDATE_DATE] [date] NULL,
	[OPPORTUNITY_DISCERNMENT] [nvarchar](2) NULL,
	[CAMPAIGN_NAME] [nvarchar](255) NULL,
	[LEAD_ID] [nvarchar](18) NULL,
	[LEAD_NAME] [nvarchar](400) NULL,
	[PREOPPORTUNITY_ID] [nvarchar](18) NULL,
	[PRE_OPP_NO] [nvarchar](10) NULL,
	[END_CUSTOMER_FREE_TEXT] [nvarchar](255) NULL,
	[AUTOMOTIVE_OEM_NAME] [nvarchar](80) NULL,
	[GROUPING_NAME] [nvarchar](255) NULL,
	[SALES_TEAM_NAME_1] [nvarchar](120) NULL,
	[SALES_TEAM_NAME_2] [nvarchar](120) NULL,
	[SALES_TEAM_NAME_3] [nvarchar](120) NULL,
	[SALES_TEAM_NAME_4] [nvarchar](120) NULL,
	[END_CUSTOMER_NAME] [nvarchar](80) NULL,
	[END_CUSTOMER_COUNTRY] [nvarchar](2) NULL
) ON [PS_PartitionByMonth_DW]([UPDATE_DATE])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_T_SFM_BCCV_OPPORTUNITY_VIEW_H_1] ON [dbo].[T_SFM_BCCV_OPPORTUNITY_VIEW_H]
(
	[OPPORTUNITY_NO] ASC,
	[UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([UPDATE_DATE])
GO
