USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Z_SEL_DATE](
	[BILL_BOOK_FLG] [nvarchar](1) NOT NULL,
	[DEEMED_DATE] [date] NULL,
	[S_DATE] [date] NULL,
	[E_DATE] [date] NULL,
 CONSTRAINT [PK_Z_SEL_DATE] PRIMARY KEY CLUSTERED 
(
	[BILL_BOOK_FLG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DW_Master]
) ON [BI_DW_Master]

GO
