USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[R_ROS_R3_HGENKA_HOUKA_HOSEIM](
	[KAISHA_CODE] [nvarchar](2) NOT NULL,
	[KOJYO_CODE] [nvarchar](2) NOT NULL,
	[TANTO_CODE] [nvarchar](2) NOT NULL,
	[H_CODE] [nvarchar](18) NOT NULL,
	[HOUKA_GENKA] [money] NULL,
	[O_HOUKA_GENKA] [money] NULL,
	[NENKI] [nvarchar](5) NULL,
	[KOUSIN_KUBUN] [nvarchar](1) NULL,
	[REG_DATETIME] [smalldatetime] NULL,
	[UPD_DATETIME] [smalldatetime] NULL
) ON [BI_DW_Staging]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
ALTER TABLE [dbo].[R_ROS_R3_HGENKA_HOUKA_HOSEIM] ADD  CONSTRAINT [DF_R_ROS_R3_HGENKA_HOUKA_HOSEIM_REG_DATETIME]  DEFAULT (getdate()) FOR [REG_DATETIME]
GO
ALTER TABLE [dbo].[R_ROS_R3_HGENKA_HOUKA_HOSEIM] ADD  CONSTRAINT [DF_R_ROS_R3_HGENKA_HOUKA_HOSEIM_UPD_DATETIME]  DEFAULT (getdate()) FOR [UPD_DATETIME]
GO
