USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ROS_R3_HGENKA_HOUKA_HOSEIM](
	[KAISHA_CODE] [nvarchar](2) NOT NULL,
	[KOJYO_CODE] [nvarchar](2) NOT NULL,
	[TANTO_CODE] [nvarchar](2) NOT NULL,
	[H_CODE] [nvarchar](18) NOT NULL,
	[HOUKA_GENKA] [money] NULL,
	[O_HOUKA_GENKA] [money] NULL,
	[NENKI] [nvarchar](5) NULL,
	[KOUSIN_KUBUN] [nvarchar](1) NULL,
	[APPLY_MONTH] [date] NOT NULL,
	[REG_DATETIME] [smalldatetime] NULL,
	[UPD_DATETIME] [smalldatetime] NULL,
 CONSTRAINT [PK_T_ROS_R3_HGENKA_HOUKA_HOSEIM] PRIMARY KEY CLUSTERED 
(
	[KAISHA_CODE] ASC,
	[KOJYO_CODE] ASC,
	[TANTO_CODE] ASC,
	[H_CODE] ASC,
	[APPLY_MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DW]([APPLY_MONTH])
) ON [PS_PartitionByMonth_DW]([APPLY_MONTH])

GO
