USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[R_SFM_BCCV_ACCOUNT_D_IN_TARGET_VIEW](
	[ACCOUNT_D_IN_TARGET_NO] [nvarchar](7) NULL,
	[ACCOUNT_GROUP_CODE] [nvarchar](255) NULL,
	[SCM_CUSTOMER_CODE] [nvarchar](10) NULL,
	[FISCAL_YEAR] [numeric](4, 0) NULL,
	[HALFYEAR] [nvarchar](2) NULL,
	[D_IN_TARGET] [numeric](15, 0) NULL,
	[CURRENCY_ISO_CODE] [nvarchar](3) NULL,
	[CREATED_DATE] [date] NULL,
	[LAST_MODIFIED_DATE] [date] NULL,
	[IF_LAST_MODIFIED_DATE] [date] NULL
) ON [BI_DW_Master]

GO
