USE [BI_DW]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Z_SSIS_LOG](
	[LOGTIME] [datetime] NOT NULL,
	[SSIS_PACKAGE] [nvarchar](128) NOT NULL,
	[ERROR_CODE] [int] NULL,
	[ERROR_MESSAGE] [nvarchar](200) NULL,
	[ERROR_COLUMN] [int] NULL,
	[LOG_MESSAGE] [nvarchar](4000) NULL
) ON [BI_DW_Staging]

GO
