USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_EBZ_BAMBOO_BRG_MST](
	[EBZ_REGION] [nvarchar](255) NULL,
	[BAMBOO_REGION] [nvarchar](255) NULL
) ON [BI_DM_Fact_NonPartition]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
