USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VD_RBW_MTF_L] AS
SELECT
 [OPPSEQ]
,[CUSTOMERCD] AS [SCM_CUSTOMER_CD]
,BOOK.BOOKING_PN_CD AS [ORDER_PART_NO_CD]
,[STAGEDIV]
,[MTFRATE]
,[PROBABILITY]
,[LTVACCURACY]
FROM [BI_DM].[dbo].[F_RBW_MTF_L] MTF
LEFT JOIN [BI_DM].[dbo].[M_PNO_BOOK_PN] BOOK
ON MTF.[PARTNO] = BOOK.[BOOKING_PN]
UNION ALL
SELECT
 '0000000-00' AS OPPSEQ
,[SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
, 'B0' AS STAGEDIV
, 0 AS MTFRATE
, '0.non' AS PROBABILITY
, 0 AS LTVACCURACY
FROM [BI_DM].[dbo].[F_SAL_BILL_GO]
UNION ALL
SELECT
 '0000000-00' AS OPPSEQ
,[SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
, 'B0' AS STAGEDIV
, 0 AS MTFRATE
, '0.non' AS PROBABILITY
, 0 AS LTVACCURACY
FROM [BI_DM].[dbo].[F_SAL_BILL_SO]


GO
