USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_CMN_ACTUAL_UNMANAGED_FLG](
	[ACTUAL_UNMANAGED_FLG] [nvarchar](1) NULL,
	[ACTUAL_UNMANAGED_TXT] [nvarchar](12) NULL
) ON [BI_DM_Dimension]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
