USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VD_SFM_OPP_HIST] AS
SELECT
   OPP.OPPORTUNITY_NO
  ,OPP.D_IN_SCM_CUST_CODE_FOR_MTF
  ,OPP.D_IN_SCM_CUST_CODE_FOR_SCM_OPE
  ,OPP.OPP_APPLICATION3_CODE
  ,OPP.CHANNEL_PARTNER_CODE
  ,OPP.CHANNEL_PARTNER_NAME
  ,OPP.ACCOUNT_GROUP_CODE
  ,OPP.ACCOUNT_NAME
  ,OPP.UPDATE_DATE
  ,OPP.END_CUSTOMER_FREE_TEXT
  ,OPP.AUTOMOTIVE_OEM_NAME
  ,OPP.GROUPING_NAME
  ,OPP.SALES_TEAM_NAME_1
  ,OPP.SALES_TEAM_NAME_2
  ,OPP.SALES_TEAM_NAME_3
  ,OPP.SALES_TEAM_NAME_4
  ,OPP.D_IN_SCM_CUST_CODE_DUMMY_FLAG
  ,OPP.NDA_FLAG
  ,OPP.STAGE_TYPE
  ,T.CODE_NAME                     AS STAGE_TYPE_TXT
  ,OPP.D_IN_SALES_COMPANY
  ,T3.CODE_NAME                    AS D_IN_SALES_COMPANY_TXT
  ,OPP.ESTIMATED_ANNUAL_USAGE
  ,OPP.MP_START_MONTH
  ,OPP.MP_START_DATE
  ,OPP.OPPORTUNITY_NAME
  ,OPP.OPPORTUNITY_INDUSTRY
  ,T2.CODE_NAME                    AS OPPORTUNITY_INDUSTRY_TXT
  ,OPP.TRACKING_TYPE_STATUS
  ,T1.CODE_NAME                    AS TRACKING_TYPE_STATUS_TXT
  ,OPP.OPP_CREATED_BY_FEDERATION_ID
  ,OPP.OPP_CREATED_BY_EMAIL
  ,OPP.OPP_CREATED_DATE
  ,OPP.END_CUSTOMER_NAME
  ,OPP.END_CUSTOMER_COUNTRY
  ,OPP.OPP_OPPORTUNITY_DISCERNMENT
  ,OPP.CAMPAIGN_NAME
  ,OPP.LEAD_ID
FROM
  [BI_DM].[dbo].[F_SFM_OPP_PRD_DEMAND_H] OPP
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C030'
  ) T
ON
  OPP.STAGE_TYPE = T.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C500'
  ) T1
ON
  OPP.TRACKING_TYPE_STATUS = T1.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C300'
  ) T2
ON
  OPP.OPPORTUNITY_INDUSTRY = T2.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C130'
  ) T3
ON
  OPP.D_IN_SALES_COMPANY = T3.CODE_VALUE
WHERE
  OPP.LATEST_FLG = '0'
AND OPP.CURRENCY_TYPE = 'Input Currency'

GO
