USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VD_CMN_SO_PART_NO]
AS
SELECT [BOOK_PN].[BOOKING_PN_CD]               AS [ORDER_PART_NO_CD]
      ,[BOOK_PN].[PRODUCT_PLAN_PN]             AS [PRODPLAN_PART_NO]
      ,[BOOK_PN].[RENESAS_PN]                  AS [RENESAS_PART_NO]
      ,[BOOK_PN].[PRICE_PN]                    AS [PRICE_PART_NO]
      ,[BOOK_PN].[ORDER_PRODUCT_STATUS]        AS [PRODUCT_STATUS]
      ,[BOOK_PN].[MOQ]                         AS [MOQ]
      ,[BOOK_PN].[SPQ]                         AS [SPQ]
      ,[BOOK_PN].[RENESAS_PRODUCT_FLAG]        AS [RENESAS_PROD_FLG]
      ,[BOOK_PN].[TS_FLAG]                     AS [TS_FLG]
      ,[BOOK_PN].[PB_FREE_DIV]                 AS [PB_FREE_DIV]
      ,[BOOK_PN].[WAREHOUSE_TYPE]              AS [WAREHOUSE_DIV]
      ,[BOOK_PN].[ROM_TYPE]                    AS [ROM_DIV]
      ,[BOOK_PN].[PACKAGE_CODE]                AS [PACKAGE_CD]
      ,[BOOK_PN].[SOFTWARE_IP_USE]             AS [SOFTWARE_IP_USE]
      ,[BOOK_PN].[CATALOG_PN_RENESAS_PN]       AS [CATALOG_PART_NO]
      ,[BOOK_PN].[FRAME_2_4_DIV]               AS [FRAME_2_4_DIV]
      ,[BOOK_PN].[CAT1]                        AS [PROD_CAT1_CD]
      ,[BOOK_PN].[CAT2]                        AS [PROD_CAT2_CD]
      ,[BOOK_PN].[CAT3]                        AS [PROD_CAT3_CD]
      ,[BOOK_PN].[CAT4]                        AS [PROD_CAT4_CD]
      ,[BOOK_PN].[CAT5]                        AS [PROD_CAT5_CD] 
      ,[BOOK_PN].[EISUI_DS_NO]                 AS [EISUI_PRSN_CD]
      ,[BOOK_PN].[EISUI_FAMILY_NAME]           AS [FMLY_NAME_KANJI]
      ,[BOOK_PN].[EISUI_FIRST_NAME]            AS [FIRST_NAME_KANJI]
      ,[BOOK_PN].[POSITION_E_TXT]              AS [POSITION_EN]
      ,[BOOK_PN].[POSITION_TXT]                AS [POSITION_JA]
      ,[BOOK_PN].[E_MAIL]                      AS [E_MAIL]
      ,[BOOK_PN].[PHONE_NO]                    AS [PHONE_NO_1]
      ,[BOOK_PN].[EISUI_UNIT]                  AS [SALES_UNIT_CD]
      ,[BOOK_PN].[EISUI_DIVITION]              AS [SALES_DIVISION_CD]
      ,[BOOK_PN].[EISUI_DEPARTMENT]            AS [SALES_DEPARTMENT_CD]
      ,[BOOK_PN].[EISUI_SECTION]               AS [SALES_SECTION_CD]
      ,[BOOK_PN].[DESIGN_GROUP_UNIT]           AS [DESIGN_UNIT_CD]
      ,[BOOK_PN].[DESIGN_GROUP_DIVISION]       AS [DESIGN_DIVISION_CD]
      ,[BOOK_PN].[DESIGN_GROUP_DEPARTMENT]     AS [DESIGN_DEPARTMENT_CD]
      ,[BOOK_PN].[DESIGN_GROUP_SECTION]        AS [DESIGN_SECTION_CD]
      ,[BOOK_PN].[MP_DATE]                     AS [MPDATEFROMBASE]
      ,[BOOK_PN].[1ST_SHIP_DATE]               AS [INITMPDTFROMBASE]
      ,[BOOK_PN].[SCM_FLAG]                    AS [ORDER_AUTO_GEN_DIV]
      ,[BOOK_PN].[BOOKING_PN]                  AS [SO_PART_NO_KEY_A4]
      ,[BOOK_PN].[CLASS_FLAG]                  AS [EL_SPEC_FLG]
      ,[BOOK_PN].[BOOKING_CLASS1]              AS [SALES_ORDER_SPEC_1]
      ,[BOOK_PN].[BOOKING_CLASS2]              AS [SALES_ORDER_SPEC_2]
      ,[BOOK_PN].[BOOKING_CLASS3]              AS [SALES_ORDER_SPEC_3]
      ,[BOOK_PN].[PART_NO_FROM_DIV]            AS [PART_NO_FROM_DIV]
      ,[BOOK_PN].[SO_PT_NO_K_A4_W]             AS [SO_PART_NO_KEY_A4_W]
      ,[BOOK_PN].[ORIGINAL_PN]                 AS [ORIGINAL_PART_NO_CD]
      ,[BOOK_PN].[ORDER_PRODUCT_STATUS_TXT]    AS [PRODUCT_STATUS_NAME_E]
      ,[BOOK_PN].[RENESAS_PRODUCT_FLAG_TXT]    AS [RENESAS_PROD_FLG_LNAME]
      ,[BOOK_PN].[TS_FLAG_TXT]                 AS [TS_FLG_LNAME]
      ,[BOOK_PN].[WAREHOUSE_TYPE_TXT]          AS [WAREHOUSE_DIV_LNAME]
      ,[BOOK_PN].[ROM_TYPE_TXT]                AS [ROM_DIV_LNAME]
      ,[BOOK_PN].[CAT1_TXT]                    AS [PROD_CAT1_LONG_NAME]
      ,[BOOK_PN].[CAT2_TXT]                    AS [PROD_CAT2_LONG_NAME]
      ,[BOOK_PN].[CAT3_TXT]                    AS [PROD_CAT3_LONG_NAME]
      ,[BOOK_PN].[CAT4_TXT]                    AS [PROD_CAT4_LONG_NAME]
      ,[BOOK_PN].[CAT5_TXT]                    AS [PROD_CAT5_LONG_NAME]
      ,[BOOK_PN].[EISUI_UNIT_TXT]              AS [SALES_UNIT_SNAME]
      ,[BOOK_PN].[EISUI_DIVITION_TXT]          AS [SALES_DIVISION_SNAME]
      ,[BOOK_PN].[EISUI_DEPARTMENT_TXT]        AS [SALES_DEPARTMENT_SNAME]
      ,[BOOK_PN].[EISUI_SECTION_TXT]           AS [SALES_SECTION_SNAME]
      ,[BOOK_PN].[DESIGN_GROUP_UNIT_TXT]       AS [DESIGN_UNIT_SNAME]
      ,[BOOK_PN].[DESIGN_GROUP_DIVISION_TXT]   AS [DESIGN_DIVISION_SNAME]
      ,[BOOK_PN].[DESIGN_GROUP_DEPARTMENT_TXT] AS [DESIGN_DEPARTMENT_SNAME]
      ,[BOOK_PN].[DESIGN_GROUP_SECTION_TXT]    AS [DESIGN_SECTION_SNAME]
      ,[BOOK_PN].[SCM_FLAG_TXT]                AS [ORDER_AUTO_GEN_DIV_LNAME]
      ,[BOOK_PN].[EOL_AFFECT_POLICY]           AS [SO_PART_NO_KEY_A4_TAB_002]
      ,[BOOK_PN].[EOL_CURRENT_WP_WT]           AS [SO_PART_NO_KEY_A4_TAB_003]
      ,[BOOK_PN].[EOL_POLICY]                  AS [SO_PART_NO_KEY_A4_TAB_004]
      ,[BOOK_PN].[EOL_POLICY_TYPE]             AS [SO_PART_NO_KEY_A4_TAB_005]
      ,[BOOK_PN].[EOL_SITECHANGE_ASSY]         AS [SO_PART_NO_KEY_A4_TAB_006]
      ,[BOOK_PN].[EOL_WPWT_DETAIL]             AS [SO_PART_NO_KEY_A4_TAB_007]
      ,[BOOK_PN].[EOL_WPWT_FUTURE]             AS [SO_PART_NO_KEY_A4_TAB_008]
      ,[BOOK_PN].[EOL_X1FREE_ITEM]             AS [SO_PART_NO_KEY_A4_TAB_009]
      ,[BOOK_PN].[EOL_X2FREE_ITEM]             AS [SO_PART_NO_KEY_A4_TAB_010]
      ,[BOOK_PN].[EOL_X3FREE_ITEM]             AS [SO_PART_NO_KEY_A4_TAB_011]
      ,[BOOK_PN].[PART_NO_FROM_DIV_TXT]        AS [PART_NO_FROM_DIV_LNAME] 
      ,[M_PNO_STANDARD_PRICE].[STANDARD_PRICE]
      ,[M_PNO_STANDARD_PRICE].[StdCst_Flg]
      ,[BOOK_PN].[MCU_SOC_AP_KBN]              AS [MCU_SOC_AP_KBN]
      ,[BOOK_PN].[COST_CENTER_CD]              AS [Cost_Center_CD]
      ,[BOOK_PN].[COST_CENTER_TXT]             AS [Cost_Center_txt]
      ,[BOOK_PN].[DEVELOPMENT_YEAR_HARF]       AS [Development_Year_Harf]
	  ,[BOOK_PN].[MCU_TYPE]                    AS [MCU_TYPE]
  FROM [dbo].[V_MST_BOOK_PN] [BOOK_PN]
 LEFT OUTER JOIN [dbo].[M_PNO_STANDARD_PRICE]
    ON ([BOOK_PN].[ANCESTRAL_PART_NO_CD] = [M_PNO_STANDARD_PRICE].[ORDER_PART_NO_CD]);




GO
