USE [BI_DM]
GO

/****** Object:  View [dbo].[VPRC_FT_BUDGET_FIXED_DIN_TBLR]    Script Date: 2018/01/15 21:17:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VPRC_FT_BUDGET_FIXED_DIN_TBLR] AS
WITH   CUR_RATE
AS     (SELECT * FROM [DM_MST].[dbo].[VPRC_FSDM_OSC_CUR_RATE]),

BUDGET_FIXED_DIN_BM AS (
SELECT [SCM_CUSTOMER_CD]
,[B_WIN_SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[CURRENCY]
,[VERSION_RESULT]
,CUR_RATE.[CURR_CD_TO] AS [CURRENCY_EXCH]
,CONVERT(money,[TO_AMT] * CUR_RATE.B_RATE) AS [TO_AMT_B]
,CONVERT(money,[TO_AMT] * CUR_RATE.M_RATE) AS [TO_AMT_M]
,CONVERT(money,[TO_STD] * CUR_RATE_STD.B_RATE) AS [TO_STD_B]
,CONVERT(money,[TO_STD] * CUR_RATE_STD.M_RATE) AS [TO_STD_M]
,CONVERT(money,[GO_AMT] * CUR_RATE.B_RATE) AS [GO_AMT_B]
,CONVERT(money,[GO_AMT] * CUR_RATE.M_RATE) AS [GO_AMT_M]
,CONVERT(money,[GO_STD] * CUR_RATE_STD.B_RATE) AS [GO_STD_B]
,CONVERT(money,[GO_STD] * CUR_RATE_STD.M_RATE) AS [GO_STD_M]
,CONVERT(money,[SO_AMT] * CUR_RATE.B_RATE) AS [SO_AMT_B]
,CONVERT(money,[SO_AMT] * CUR_RATE.M_RATE) AS [SO_AMT_M]
,CONVERT(money,[SO_STD] * CUR_RATE_STD.B_RATE) AS [SO_STD_B]
,CONVERT(money,[SO_STD] * CUR_RATE_STD.M_RATE) AS [SO_STD_M]
,CONVERT(money,[GO_AMT_NB_Bwin] * CUR_RATE.B_RATE) AS [GO_AMT_NB_Bwin_B]
,CONVERT(money,[GO_AMT_NB_Bwin] * CUR_RATE.M_RATE) AS [GO_AMT_NB_Bwin_M]
,CONVERT(money,[GO_AMT_NB_Din] * CUR_RATE.B_RATE) AS [GO_AMT_NB_Din_B]
,CONVERT(money,[GO_AMT_NB_Din] * CUR_RATE.M_RATE) AS [GO_AMT_NB_Din_M]
FROM [BI_DM].[dbo].[F_SAL_BUDGET_FIXED_DIN]
LEFT OUTER JOIN CUR_RATE
          ON [F_SAL_BUDGET_FIXED_DIN].[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
         AND [F_SAL_BUDGET_FIXED_DIN].[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
LEFT OUTER JOIN CUR_RATE CUR_RATE_STD
  ON CUR_RATE_STD.[CURR_CD_FROM] = 'JPY'
 AND CUR_RATE.[CURR_CD_TO]= CUR_RATE_STD.[CURR_CD_TO]
 AND [F_SAL_BUDGET_FIXED_DIN].[CALENDAR_YM] = CUR_RATE_STD.[VALID_FROM_YMD]
WHERE [CURRENCY_EXCH] = 'Input Currency'
),
BUDGET_FIXED_DIN_BM_INXS AS (
SELECT [SCM_CUSTOMER_CD]
,[B_WIN_SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[CURRENCY]
,[VERSION_RESULT]
,CUR_RATE.[CURR_CD_TO] AS [CURRENCY_EXCH]
,CONVERT(money,[TO_AMT] * CUR_RATE.B_RATE) AS [TO_AMT_B]
,CONVERT(money,[TO_AMT] * CUR_RATE.M_RATE) AS [TO_AMT_M]
,CONVERT(money,[TO_STD] * CUR_RATE_STD.B_RATE) AS [TO_STD_B]
,CONVERT(money,[TO_STD] * CUR_RATE_STD.M_RATE) AS [TO_STD_M]
,CONVERT(money,[GO_AMT] * CUR_RATE.B_RATE) AS [GO_AMT_B]
,CONVERT(money,[GO_AMT] * CUR_RATE.M_RATE) AS [GO_AMT_M]
,CONVERT(money,[GO_STD] * CUR_RATE_STD.B_RATE) AS [GO_STD_B]
,CONVERT(money,[GO_STD] * CUR_RATE_STD.M_RATE) AS [GO_STD_M]
,CONVERT(money,[SO_AMT] * CUR_RATE.B_RATE) AS [SO_AMT_B]
,CONVERT(money,[SO_AMT] * CUR_RATE.M_RATE) AS [SO_AMT_M]
,CONVERT(money,[SO_STD] * CUR_RATE_STD.B_RATE) AS [SO_STD_B]
,CONVERT(money,[SO_STD] * CUR_RATE_STD.M_RATE) AS [SO_STD_M]
,CONVERT(money,[GO_AMT_NB_Bwin] * CUR_RATE.B_RATE) AS [GO_AMT_NB_Bwin_B]
,CONVERT(money,[GO_AMT_NB_Bwin] * CUR_RATE.M_RATE) AS [GO_AMT_NB_Bwin_M]
,CONVERT(money,[GO_AMT_NB_Din] * CUR_RATE.B_RATE) AS [GO_AMT_NB_Din_B]
,CONVERT(money,[GO_AMT_NB_Din] * CUR_RATE.M_RATE) AS [GO_AMT_NB_Din_M]
FROM [DM_SALES].[dbo].[TPRC_T_NREL_BUDGET_DIN]
LEFT OUTER JOIN CUR_RATE
          ON [TPRC_T_NREL_BUDGET_DIN].[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
         AND [TPRC_T_NREL_BUDGET_DIN].[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
LEFT OUTER JOIN CUR_RATE CUR_RATE_STD
  ON CUR_RATE_STD.[CURR_CD_FROM] = 'USD'
 AND CUR_RATE.[CURR_CD_TO]= CUR_RATE_STD.[CURR_CD_TO]
 AND [TPRC_T_NREL_BUDGET_DIN].[CALENDAR_YM] = CUR_RATE_STD.[VALID_FROM_YMD]
WHERE [CURRENCY_EXCH] = 'Input Currency'
)

SELECT [F_SAL_BUDGET_FIXED_DIN].[SCM_CUSTOMER_CD]
,[F_SAL_BUDGET_FIXED_DIN].[B_WIN_SCM_CUSTOMER_CD]
,[F_SAL_BUDGET_FIXED_DIN].[ORDER_PART_NO_CD]
,[F_SAL_BUDGET_FIXED_DIN].[SEG_CD]
,[F_SAL_BUDGET_FIXED_DIN].[BUSINESS_SITE]
,[F_SAL_BUDGET_FIXED_DIN].[CALENDAR_YM]
,[F_SAL_BUDGET_FIXED_DIN].[CURRENCY]
,[F_SAL_BUDGET_FIXED_DIN].[VERSION_RESULT]
,[F_SAL_BUDGET_FIXED_DIN].[CURRENCY_EXCH]
,[TO_AMT] AS [TO_AMT_Q]
,[TO_AMT_B]
,[TO_AMT_M]
,[TO_AMT_JPY]
,[TO_STD] AS [TO_STD_Q]
,[TO_STD_B]
,[TO_STD_M]
,[TO_QTY]
,[GO_AMT] AS [GO_AMT_Q]
,[GO_AMT_B]
,[GO_AMT_M]
,[GO_AMT_JPY]
,[GO_STD] AS [GO_STD_Q]
,[GO_STD_B]
,[GO_STD_M]
,[GO_QTY]
,[SO_AMT] AS [SO_AMT_Q]
,[SO_AMT_B]
,[SO_AMT_M]
,[SO_AMT_JPY]
,[SO_STD] AS [SO_STD_Q]
,[SO_STD_B]
,[SO_STD_M]
,[SO_QTY]
,[GO_AMT_NB_Bwin] AS [GO_AMT_NB_Bwin_Q]
,[GO_AMT_NB_Bwin_B]
,[GO_AMT_NB_Bwin_M]
,[GO_AMT_NB_Din] AS [GO_AMT_NB_Din_Q]
,[GO_AMT_NB_Din_B]
,[GO_AMT_NB_Din_M]
FROM     [BI_DM].[dbo].[F_SAL_BUDGET_FIXED_DIN]
LEFT JOIN BUDGET_FIXED_DIN_BM
ON  ISNULL([F_SAL_BUDGET_FIXED_DIN].[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[ORDER_PART_NO_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[SEG_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[SEG_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[BUSINESS_SITE],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[BUSINESS_SITE],'$$NULL$$')
AND ISNULL(CONVERT(nvarchar,[F_SAL_BUDGET_FIXED_DIN].[CALENDAR_YM],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,BUDGET_FIXED_DIN_BM.[CALENDAR_YM],112),'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[CURRENCY],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[CURRENCY],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[VERSION_RESULT],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[VERSION_RESULT],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[CURRENCY_EXCH],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[CURRENCY_EXCH],'$$NULL$$')
WHERE ([F_SAL_BUDGET_FIXED_DIN].[VERSION_RESULT] IN (N'0', N'H'))

UNION ALL

SELECT [F_SAL_BUDGET_FIXED_DIN].[SCM_CUSTOMER_CD]
,[F_SAL_BUDGET_FIXED_DIN].[B_WIN_SCM_CUSTOMER_CD]
,[F_SAL_BUDGET_FIXED_DIN].[ORDER_PART_NO_CD]
,[F_SAL_BUDGET_FIXED_DIN].[SEG_CD]
,[F_SAL_BUDGET_FIXED_DIN].[BUSINESS_SITE]
,[F_SAL_BUDGET_FIXED_DIN].[CALENDAR_YM]
,[F_SAL_BUDGET_FIXED_DIN].[CURRENCY]
,[F_SAL_BUDGET_FIXED_DIN].[VERSION_RESULT]
,[F_SAL_BUDGET_FIXED_DIN].[CURRENCY_EXCH]
,[TO_AMT] AS [TO_AMT_Q]
,[TO_AMT_B]
,[TO_AMT_M]
,[TO_AMT_JPY]
,[TO_STD] AS [TO_STD_Q]
,[TO_STD_B]
,[TO_STD_M]
,[TO_QTY]
,[GO_AMT] AS [GO_AMT_Q]
,[GO_AMT_B]
,[GO_AMT_M]
,[GO_AMT_JPY]
,[GO_STD] AS [GO_STD_Q]
,[GO_STD_B]
,[GO_STD_M]
,[GO_QTY]
,[SO_AMT] AS [SO_AMT_Q]
,[SO_AMT_B]
,[SO_AMT_M]
,[SO_AMT_JPY]
,[SO_STD] AS [SO_STD_Q]
,[SO_STD_B]
,[SO_STD_M]
,[SO_QTY]
,[GO_AMT_NB_Bwin] AS [GO_AMT_NB_Bwin_Q]
,[GO_AMT_NB_Bwin_B]
,[GO_AMT_NB_Bwin_M]
,[GO_AMT_NB_Din] AS [GO_AMT_NB_Din_Q]
,[GO_AMT_NB_Din_B]
,[GO_AMT_NB_Din_M]
FROM     [BI_DM].[dbo].[F_SAL_BUDGET_FIXED_DIN]
LEFT JOIN BUDGET_FIXED_DIN_BM
ON  ISNULL([F_SAL_BUDGET_FIXED_DIN].[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[ORDER_PART_NO_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[SEG_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[SEG_CD],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[BUSINESS_SITE],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[BUSINESS_SITE],'$$NULL$$')
AND ISNULL(CONVERT(nvarchar,[F_SAL_BUDGET_FIXED_DIN].[CALENDAR_YM],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,BUDGET_FIXED_DIN_BM.[CALENDAR_YM],112),'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[CURRENCY],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[CURRENCY],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[VERSION_RESULT],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[VERSION_RESULT],'$$NULL$$')
AND ISNULL([F_SAL_BUDGET_FIXED_DIN].[CURRENCY_EXCH],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM.[CURRENCY_EXCH],'$$NULL$$')
WHERE ([F_SAL_BUDGET_FIXED_DIN].[VERSION_RESULT] IN
                            (SELECT            MAX([VERSION_RESULT])
                               FROM              [BI_DM].[dbo].[F_SAL_BUDGET_FIXED_DIN]
                               WHERE             ([VERSION_RESULT] NOT IN (N'0', N'H', N'O'))/*-N'1', N'2', N'3'*/ ))

--INXS‘Î‰ž
UNION ALL

SELECT [TPRC_T_NREL_BUDGET_DIN].[SCM_CUSTOMER_CD]
,[TPRC_T_NREL_BUDGET_DIN].[B_WIN_SCM_CUSTOMER_CD]
,[TPRC_T_NREL_BUDGET_DIN].[ORDER_PART_NO_CD]
,[TPRC_T_NREL_BUDGET_DIN].[SEG_CD]
,[TPRC_T_NREL_BUDGET_DIN].[BUSINESS_SITE]
,[TPRC_T_NREL_BUDGET_DIN].[CALENDAR_YM]
,[TPRC_T_NREL_BUDGET_DIN].[CURRENCY]
,[TPRC_T_NREL_BUDGET_DIN].[VERSION_RESULT]
,[TPRC_T_NREL_BUDGET_DIN].[CURRENCY_EXCH]
,[TO_AMT] AS [TO_AMT_Q]
,[TO_AMT_B]
,[TO_AMT_M]
,[TO_AMT_JPY]
,[TO_STD] AS [TO_STD_Q]
,[TO_STD_B]
,[TO_STD_M]
,[TO_QTY]
,[GO_AMT] AS [GO_AMT_Q]
,[GO_AMT_B]
,[GO_AMT_M]
,[GO_AMT_JPY]
,[GO_STD] AS [GO_STD_Q]
,[GO_STD_B]
,[GO_STD_M]
,[GO_QTY]
,[SO_AMT] AS [SO_AMT_Q]
,[SO_AMT_B]
,[SO_AMT_M]
,[SO_AMT_JPY]
,[SO_STD] AS [SO_STD_Q]
,[SO_STD_B]
,[SO_STD_M]
,[SO_QTY]
,[GO_AMT_NB_Bwin] AS [GO_AMT_NB_Bwin_Q]
,[GO_AMT_NB_Bwin_B]
,[GO_AMT_NB_Bwin_M]
,[GO_AMT_NB_Din] AS [GO_AMT_NB_Din_Q]
,[GO_AMT_NB_Din_B]
,[GO_AMT_NB_Din_M]
FROM     [DM_SALES].[dbo].[TPRC_T_NREL_BUDGET_DIN]
LEFT JOIN BUDGET_FIXED_DIN_BM_INXS
ON  ISNULL([TPRC_T_NREL_BUDGET_DIN].[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL([TPRC_T_NREL_BUDGET_DIN].[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL([TPRC_T_NREL_BUDGET_DIN].[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[ORDER_PART_NO_CD],'$$NULL$$')
AND ISNULL([TPRC_T_NREL_BUDGET_DIN].[SEG_CD],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[SEG_CD],'$$NULL$$')
AND ISNULL([TPRC_T_NREL_BUDGET_DIN].[BUSINESS_SITE],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[BUSINESS_SITE],'$$NULL$$')
AND ISNULL(CONVERT(nvarchar,[TPRC_T_NREL_BUDGET_DIN].[CALENDAR_YM],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,BUDGET_FIXED_DIN_BM_INXS.[CALENDAR_YM],112),'$$NULL$$')
AND ISNULL([TPRC_T_NREL_BUDGET_DIN].[CURRENCY],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[CURRENCY],'$$NULL$$')
AND ISNULL([TPRC_T_NREL_BUDGET_DIN].[VERSION_RESULT],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[VERSION_RESULT],'$$NULL$$')
AND ISNULL([TPRC_T_NREL_BUDGET_DIN].[CURRENCY_EXCH],'$$NULL$$') = ISNULL(BUDGET_FIXED_DIN_BM_INXS.[CURRENCY_EXCH],'$$NULL$$')


GO


