USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[VF_SAL_RAINBOWDATA_PAST] AS
SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,0 AS [TODemand_Amt_JPY]
,0 AS [TODemand_Qty]
,0 AS [TOReply_Amt_JPY]
,0 AS [TOReply_Qty]
,0 AS [GODemand_Amt_JPY]
,0 AS [GODemand_V0_Amt_JPY]
,0 AS [GODemand_V1_Amt_JPY]
,0 AS [GODemand_Other_Amt_JPY]
,0 AS [GODemand_Std]
,0 AS [GODemand_V0_Std]
,0 AS [GODemand_V1_Std]
,0 AS [GODemand_Other_Std]
,0 AS [GODemand_Qty]
,0 AS [GODemand_V0_Qty]
,0 AS [GODemand_V1_Qty]
,0 AS [GODemand_Other_Qty]
,0 AS [GOReply_Amt_JPY]
,0 AS [GOReply_Std]
,0 AS [GOReply_Qty]
,SUM([ShippableAATP_Amt_JPY]) AS [ShippableAATP_Amt_JPY]
,SUM([ShippableAATP_Qty]) AS [ShippableAATP_Qty]
,SUM([AdjustedSFOut_Amt_JPY]) AS [AdjustedSFOut_Amt_JPY]
,SUM([AdjustedSFOut_Qty]) AS [AdjustedSFOut_Qty]
,0 AS [JSF_Amt_JPY]
,0 AS [JSF_V0_Amt_JPY]
,0 AS [JSF_V1_Amt_JPY]
,0 AS [JSF_Other_Amt_JPY]
,0 AS [JSF_Qty]
,0 AS [JSF_V0_Qty]
,0 AS [JSF_V1_Qty]
,0 AS [JSF_Other_Qty]
,0 AS [ProductionPlanning_Amt]
,0 AS [ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_FHPNO_CST_ALLSUM_PAST]
WHERE [RESULTDIV] <> N'1'
GROUP BY 
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,SUM([TODemand_Amt_JPY]) AS [TODemand_Amt_JPY]
,SUM([TODemand_Qty]) AS [TODemand_Qty]
,SUM([TOReply_Amt_JPY]) AS [TOReply_Amt_JPY]
,SUM([TOReply_Qty]) AS [TOReply_Qty]
,(isnull(SUM([GODemand_V0_Amt_JPY]),(0)) + isnull(SUM([GODemand_V1_Amt_JPY]),(0))) AS [GODemand_Amt_JPY]
,SUM([GODemand_V0_Amt_JPY]) AS [GODemand_V0_Amt_JPY]
,SUM([GODemand_V1_Amt_JPY]) AS [GODemand_V1_Amt_JPY]
,SUM([GODemand_Other_Amt_JPY]) AS [GODemand_Other_Amt_JPY]
,(isnull(SUM([GODemand_V0_Std]),(0)) + isnull(SUM([GODemand_V1_Std]),(0))) AS [GODemand_Std]
,SUM([GODemand_V0_Std]) AS [GODemand_V0_Std]
,SUM([GODemand_V1_Std]) AS [GODemand_V1_Std]
,SUM([GODemand_Other_Std]) AS [GODemand_Other_Std]
,(isnull(SUM([GODemand_V0_Qty]),(0)) + isnull(SUM([GODemand_V1_Qty]),(0))) AS [GODemand_Qty]
,SUM([GODemand_V0_Qty]) AS [GODemand_V0_Qty]
,SUM([GODemand_V1_Qty]) AS [GODemand_V1_Qty]
,SUM([GODemand_Other_Qty]) AS [GODemand_Other_Qty]
,SUM([GOReply_Amt_JPY]) AS [GOReply_Amt_JPY]
,SUM([GOReply_Std]) AS [GOReply_Std]
,SUM([GOReply_Qty]) AS [GOReply_Qty]
,SUM([ShippableAATP_Amt_JPY]) AS [ShippableAATP_Amt_JPY]
,SUM([ShippableAATP_Qty]) AS [ShippableAATP_Qty]
,SUM([AdjustedSFOut_Amt_JPY]) AS [AdjustedSFOut_Amt_JPY]
,SUM([AdjustedSFOut_Qty]) AS [AdjustedSFOut_Qty]
,(isnull(SUM([JSF_V0_Amt_JPY]),(0)) + isnull(SUM([JSF_V1_Amt_JPY]),(0))) AS [JSF_Amt_JPY]
,SUM([JSF_V0_Amt_JPY]) AS [JSF_V0_Amt_JPY]
,SUM([JSF_V1_Amt_JPY]) AS [JSF_V1_Amt_JPY]
,SUM([JSF_Other_Amt_JPY]) AS [JSF_Other_Amt_JPY]
,(isnull(SUM([JSF_V0_Qty]),(0)) + isnull(SUM([JSF_V1_Qty]),(0))) AS [JSF_Qty]
,SUM([JSF_V0_Qty]) AS [JSF_V0_Qty]
,SUM([JSF_V1_Qty]) AS [JSF_V1_Qty]
,SUM([JSF_Other_Qty]) AS [JSF_Other_Qty]
,SUM([ProductionPlanning_Amt]) AS [ProductionPlanning_Amt]
,SUM([ProductionPlanning_Qty]) AS [ProductionPlanning_Qty]
,SUM(OSC_MoveAve_Cst)    AS [OSC_MoveAve_Cst]
,SUM(OSC_MoveAve_GP_Amt) AS [OSC_MoveAve_GP_Amt]
FROM (
SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[RESULTDIV]
,[CURRENCY]
,0 AS [TODemand_Amt_JPY]
,0 AS [TODemand_Qty]
,0 AS [TOReply_Amt_JPY]
,0 AS [TOReply_Qty]
--,CASE WHEN [V0V1DIV] = N'V0'                       THEN [GODemand_Amt_JPY] ELSE 0 END AS [GODemand_V0_Amt_JPY]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Amt_JPY] ELSE 0 END AS [GODemand_V0_Amt_JPY]
--,CASE WHEN [V0V1DIV] = N'V1'
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
        THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
                  THEN 0 
                  ELSE [GODemand_Amt_JPY]
             END 
        ELSE 0 END AS [GODemand_V1_Amt_JPY]
--,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1')        THEN [GODemand_Amt_JPY] ELSE 0 END AS [GODemand_Other_Amt_JPY]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [GODemand_Amt_JPY] ELSE 0 END AS [GODemand_Other_Amt_JPY]
--,CASE WHEN [V0V1DIV] = N'V0'                       THEN [GODemand_Std] ELSE 0 END AS [GODemand_V0_Std]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Std] ELSE 0 END AS [GODemand_V0_Std]
--,CASE WHEN [V0V1DIV] = N'V1'
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
        THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
                  THEN 0 
                  ELSE [GODemand_Std]
             END 
        ELSE 0 END AS [GODemand_V1_Std]
--,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1')        THEN [GODemand_Std] ELSE 0 END AS [GODemand_Other_Std]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')       THEN [GODemand_Std] ELSE 0 END AS [GODemand_Other_Std]
--,CASE WHEN [V0V1DIV] = N'V0'                       THEN [GODemand_Qty] ELSE 0 END AS [GODemand_V0_Qty]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Qty] ELSE 0 END AS [GODemand_V0_Qty]
--,CASE WHEN [V0V1DIV] = N'V1'                       
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')                       
        THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE)) 
                  THEN 0 
                  ELSE [GODemand_Qty]
             END 
        ELSE 0 END AS [GODemand_V1_Qty]
--,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1')        THEN [GODemand_Qty] ELSE 0 END AS [GODemand_Other_Qty]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [GODemand_Qty] ELSE 0 END AS [GODemand_Other_Qty]
,0 AS [GOReply_Amt_JPY]
,0 AS [GOReply_Std]
,0 AS [GOReply_Qty]
,0 AS [ShippableAATP_Amt_JPY]
,0 AS [ShippableAATP_Qty]
,0 AS [AdjustedSFOut_Amt_JPY]
,0 AS [AdjustedSFOut_Qty]
--,CASE WHEN [V0V1DIV] = N'V0'                       THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_V0_Amt_JPY]
,CASE WHEN [V0V1DIV] IN (N'V0',N'S0')              THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_V0_Amt_JPY]
--,CASE WHEN [V0V1DIV] = N'V1'                       THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_V1_Amt_JPY]
,CASE WHEN [V0V1DIV] IN (N'V1',N'S1')                       THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_V1_Amt_JPY]
--,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1')        THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_Other_Amt_JPY]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_Other_Amt_JPY]
--,CASE WHEN [V0V1DIV] = N'V0'                       THEN [JSF_Qty] ELSE 0 END AS [JSF_V0_Qty]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [JSF_Qty] ELSE 0 END AS [JSF_V0_Qty]
--,CASE WHEN [V0V1DIV] = N'V1'                       THEN [JSF_Qty] ELSE 0 END AS [JSF_V1_Qty]
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')                       THEN [JSF_Qty] ELSE 0 END AS [JSF_V1_Qty]
--,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1')        THEN [JSF_Qty] ELSE 0 END AS [JSF_Other_Qty]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [JSF_Qty] ELSE 0 END AS [JSF_Other_Qty]
,0 AS [ProductionPlanning_Amt]
,0 AS [ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_V1JSF_PAST]
) AS T
GROUP BY 
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,SUM([TODemand_Amt_JPY]) AS [TODemand_Amt_JPY]
,SUM([TODemand_Qty]) AS [TODemand_Qty]
,SUM([TOReply_Amt_JPY]) AS [TOReply_Amt_JPY]
,SUM([TOReply_Qty]) AS [TOReply_Qty]
,0 AS [GODemand_Amt_JPY]
,0 AS [GODemand_V0_Amt_JPY]
,0 AS [GODemand_V1_Amt_JPY]
,0 AS [GODemand_Other_Amt_JPY]
,0 AS [GODemand_Std]
,0 AS [GODemand_V0_Std]
,0 AS [GODemand_V1_Std]
,0 AS [GODemand_Other_Std]
,0 AS [GODemand_Qty]
,0 AS [GODemand_V0_Qty]
,0 AS [GODemand_V1_Qty]
,0 AS [GODemand_Other_Qty]
,SUM([GOReply_Amt_JPY]) AS [GOReply_Amt_JPY]
,SUM([GOReply_Std]) AS [GOReply_Std]
,SUM([GOReply_Qty]) AS [GOReply_Qty]
,0 AS [ShippableAATP_Amt_JPY]
,0 AS [ShippableAATP_Qty]
,0 AS [AdjustedSFOut_Amt_JPY]
,0 AS [AdjustedSFOut_Qty]
,0 AS [JSF_Amt_JPY]
,0 AS [JSF_V0_Amt_JPY]
,0 AS [JSF_V1_Amt_JPY]
,0 AS [JSF_Other_Amt_JPY]
,0 AS [JSF_Qty]
,0 AS [JSF_V0_Qty]
,0 AS [JSF_V1_Qty]
,0 AS [JSF_Other_Qty]
,0 AS [ProductionPlanning_Amt]
,0 AS [ProductionPlanning_Qty]
,SUM(ISNULL([OSC_MoveAve_Cst], 0))    AS [OSC_MoveAve_Cst]
,SUM(ISNULL([OSC_MoveAve_GP_Amt], 0)) AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_TOGOTRADE_INV_PAST]
GROUP BY 
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,0 AS [TODemand_Amt_JPY]
,0 AS [TODemand_Qty]
,0 AS [TOReply_Amt_JPY]
,0 AS [TOReply_Qty]
,0 AS [GODemand_Amt_JPY]
,0 AS [GODemand_V0_Amt_JPY]
,0 AS [GODemand_V1_Amt_JPY]
,0 AS [GODemand_Other_Amt_JPY]
,0 AS [GODemand_Std]
,0 AS [GODemand_V0_Std]
,0 AS [GODemand_V1_Std]
,0 AS [GODemand_Other_Std]
,0 AS [GODemand_Qty]
,0 AS [GODemand_V0_Qty]
,0 AS [GODemand_V1_Qty]
,0 AS [GODemand_Other_Qty]
,0 AS [GOReply_Amt_JPY]
,0 AS [GOReply_Std]
,0 AS [GOReply_Qty]
,0 AS [ShippableAATP_Amt_JPY]
,0 AS [ShippableAATP_Qty]
,0 AS [AdjustedSFOut_Amt_JPY]
,0 AS [AdjustedSFOut_Qty]
,0 AS [JSF_Amt_JPY]
,0 AS [JSF_V0_Amt_JPY]
,0 AS [JSF_V1_Amt_JPY]
,0 AS [JSF_Other_Amt_JPY]
,0 AS [JSF_Qty]
,0 AS [JSF_V0_Qty]
,0 AS [JSF_V1_Qty]
,0 AS [JSF_Other_Qty]
,[ProductionPlanning_Amt]
,[ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_FIXED_PPPRODPLAN_PAST]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,SUM([TODemand_Amt]) AS [TODemand_Amt_JPY]
,SUM([TODemand_Qty]) AS [TODemand_Qty]
,SUM([TOReply_Amt]) AS [TOReply_Amt_JPY]
,SUM([TOReply_Qty]) AS [TOReply_Qty]
,SUM([GODemand_Amt]) AS [GODemand_Amt_JPY]
,SUM([GODemand_V0_Amt]) AS [GODemand_V0_Amt_JPY]
,SUM([GODemand_V1_Amt]) AS [GODemand_V1_Amt_JPY]
,SUM([GODemand_Other_Amt]) AS [GODemand_Other_Amt_JPY]
,SUM([GODemand_Std]) AS [GODemand_Std]
,SUM([GODemand_V0_Std]) AS [GODemand_V0_Std]
,SUM([GODemand_V1_Std]) AS [GODemand_V1_Std]
,SUM([GODemand_Other_Std]) AS [GODemand_Other_Std]
,SUM([GODemand_Qty]) AS [GODemand_Qty]
,SUM([GODemand_V0_Qty]) AS [GODemand_V0_Qty]
,SUM([GODemand_V1_Qty]) AS [GODemand_V1_Qty]
,SUM([GODemand_Other_Qty]) AS [GODemand_Other_Qty]
,SUM([GOReply_Amt]) AS [GOReply_Amt_JPY]
,SUM([GOReply_Std]) AS [GOReply_Std]
,SUM([GOReply_Qty]) AS [GOReply_Qty]
,SUM([ShippableAATP_Amt]) AS [ShippableAATP_Amt_JPY]
,SUM([ShippableAATP_Qty]) AS [ShippableAATP_Qty]
,SUM([AdjustedSFOut_Amt]) AS [AdjustedSFOut_Amt_JPY]
,SUM([AdjustedSFOut_Qty]) AS [AdjustedSFOut_Qty]
,SUM([JSF_Amt]) AS [JSF_Amt_JPY]
,SUM([JSF_V0_Amt]) AS [JSF_V0_Amt_JPY]
,SUM([JSF_V1_Amt]) AS [JSF_V1_Amt_JPY]
,SUM([JSF_Other_Amt]) AS [JSF_Other_Amt_JPY]
,SUM([JSF_Qty]) AS [JSF_Qty]
,SUM([JSF_V0_Qty]) AS [JSF_V0_Qty]
,SUM([JSF_V1_Qty]) AS [JSF_V1_Qty]
,SUM([JSF_Other_Qty]) AS [JSF_Other_Qty]
,SUM([ProductionPlanning_Amt]) AS [ProductionPlanning_Amt]
,SUM([ProductionPlanning_Qty]) AS [ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[T_PRO_RAINBOWDATA]
GROUP BY 
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]






GO
