USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_V_MST_BOOKPN_CUST_APL_CRM](
	[RR_BU_DIVISION_TXT] [nvarchar](300) NULL,
	[RR_BU_UNIT_TXT] [nvarchar](300) NULL,
	[RR_BU_DEPARTMENT_TXT] [nvarchar](300) NULL,
	[RR_BU_SECTION_TXT] [nvarchar](300) NULL,
	[FIXED_APL_SEGMENT] [nvarchar](300) NULL,
	[FIXED_APL_SUB_SEGMENT] [nvarchar](300) NULL,
	[FIXED_APL_INVEST_LABEL] [nvarchar](300) NULL,
	[FREE_ITEM_01] [nvarchar](300) NULL,
	[FREE_ITEM_02] [nvarchar](300) NULL,
	[BOOKING_PN_CD] [nvarchar](18) NULL,
	[SCM_CUSTOMER] [nvarchar](10) NOT NULL
) ON [BI_DM_Dimension]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_M_V_MST_BOOKPN_CUST_APL_CRM_1] ON [dbo].[M_V_MST_BOOKPN_CUST_APL_CRM]
(
	[BOOKING_PN_CD] ASC,
	[SCM_CUSTOMER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
GO
