USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW [dbo].[VF_GP_REPO_2_MID_SCAT_PLOT] AS
 SELECT
       FORMAT(GO.RECORD_DATE,'yyyy/MM') as RECORD_DATE
      ,ISNULL(CUST.[CUSTOMER_GRP2],'UnKnown') as CUSTOMER_GRP2
      ,ISNULL(APL.[RR_BU_DIVISION_TXT],'UnKnown') as RR_BU_DIVISION_TXT
      ,sum(GO.GO_AMT_JPY) AS GO_Bill_Amt
      ,(sum(GO.GO_AMT_JPY)-sum(GO.GO_AMT_STD)) as GO_Bill_GP_Amt
      ,(sum(GO.GO_AMT_JPY)-sum(GO.GO_AMT_STD))/ NULLIF(sum(GO.GO_AMT_JPY),0) as GO_Bill_GP_Rate
FROM [BI_DM].[dbo].[F_SAL_BILL_GO] as GO
--LEFT OUTER JOIN (select * from [BI_DM].[dbo].[M_SCM_CUST] where [INTERNALFLG] = 'DD001') as CUST
LEFT OUTER JOIN [BI_DM].[dbo].[M_SCM_CUST] as CUST
    ON GO.[SCM_CUSTOMER_CD] = CUST.[SCM_CUSTOMER]
--LEFT OUTER JOIN (select * from [BI_DM].[dbo].[M_PNO_BOOK_PN] where [RENESAS_PRODUCT_FLAG] = '1') as BKPN
LEFT OUTER JOIN [BI_DM].[dbo].[M_PNO_BOOK_PN] as BKPN
    ON GO.[ORDER_PART_NO_CD] = BKPN.[BOOKING_PN_CD]
  LEFT OUTER JOIN [BI_DM].[dbo].[M_APL_CUST_BOOK_PN] as APL
    ON GO.[SCM_CUSTOMER_CD]  = APL.[SCM_CUSTOMER]
   AND GO.[ORDER_PART_NO_CD] = APL.[BOOKING_PN_CD]
WHERE (GO.GO_AMT_JPY <> 0 or GO.GO_AMT_STD <> 0)
  AND CUST.[INTERNALFLG] = 'DD001'
  AND BKPN.[RENESAS_PRODUCT_FLAG] = '1'
GROUP BY
         FORMAT(GO.RECORD_DATE,'yyyy/MM')
        ,CUST.[CUSTOMER_GRP2]
        ,APL.[RR_BU_DIVISION_TXT]
		
;









GO
