USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VF_SAL_ORDER_DIN] AS
SELECT
   [SCM_CUSTOMER_CD]
  ,[B_WIN_SCM_CUSTOMER_CD]
  ,[ORDER_PART_NO_CD]
  ,[SEG_CD]
  ,[CURRENCY]
  ,[RECORD_DATE]
  ,[ORDER_DATE]
  ,[RDLV_DATE]
  ,[CURRENCY_EXCH]
  ,SUM([TO_AMT]) AS [TO_AMT]
  ,SUM([TO_ANP_AMT]) AS [TO_ANP_AMT]
  ,SUM([TO_AMT_STD]) AS [TO_AMT_STD]
  ,SUM([GO_AMT]) AS [GO_AMT]
  ,SUM([GO_ANP_AMT]) AS [GO_ANP_AMT]
  ,SUM([GO_AMT_STD]) AS [GO_AMT_STD]
  ,SUM([SO_AMT]) AS [SO_AMT]
  ,SUM([SO_AMT_STD]) AS [SO_AMT_STD]
--20180410  D-in CUBEÇ…QtyçÄñ⁄ÇÃí«â¡ëŒâû CDC  Start
  ,SUM([GO_QTY]) AS [GO_QTY]
  ,SUM([TO_QTY]) AS [TO_QTY]
  ,SUM([SO_QTY]) AS [SO_QTY]
--20180410  D-in CUBEÇ…QtyçÄñ⁄ÇÃí«â¡ëŒâû CDC  End
  FROM [BI_DM].[dbo].[T_SAL_ORDER_DIN]
GROUP BY
   [SCM_CUSTOMER_CD]
  ,[B_WIN_SCM_CUSTOMER_CD]
  ,[ORDER_PART_NO_CD]
  ,[SEG_CD]
  ,[CURRENCY]
  ,[RECORD_DATE]
  ,[ORDER_DATE]
  ,[RDLV_DATE]
  ,[CURRENCY_EXCH]



GO
