USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VD_SFM_PROD_HIST] AS
SELECT
   S.OPPORTUNITY_SEQ
  ,SUBSTRING(S.OPPORTUNITY_SEQ, 1, 10) AS OPPORTUNITY_SEQ_PRD
  ,S.STAGE
  ,T1.CODE_NAME AS STAGE_H_TXT
  ,S.B_WIN_SCM_CUSTOMER_CODE
  ,S.SALES_ORDER_PN_FOR_MTF
  ,S.SALES_ORDER_PN_FOR_SCM_OPE
  ,S.PRD_APPLICATION3_CODE
  ,S.STATUS
  ,T.CODE_NAME AS STATUS_TXT
  ,S.TARGET_NOMINATION_DATE
  ,S.TARGET_AWARD_DATE
  ,S.D_IN_CONFIDENCE_LEVEL_PERCENT
  ,T22.CODE_NAME AS D_IN_CONFIDENCE_LEVEL_PERCENT_TXT
  ,S.QTY_UNIT
  ,S.SHARE_PERCENT
  ,S.START_MONTH_OF_FISCAL_YEAR
  ,T2.CODE_NAME AS START_MONTH_OF_FISCAL_YEAR_TXT
  ,S.MP_START_MONTH
  ,S.CURRENCY
  ,S.UPDATE_DATE
  ,S.URL_OPP_PRODUCT_FOR_REL
  ,S.URL_OPP_PRODUCT_FOR_CHANNEL
  ,S.COMPETITOR_CURRENCY1
  ,S.COMPETITOR_PRICE_JPY1
  ,S.COMPETITOR_CURRENCY2
  ,S.COMPETITOR_PRICE_JPY2
  ,S.COMPETITOR_CURRENCY3
  ,S.COMPETITOR_PRICE_JPY3
  ,S.USER_LAST_MODIFIED_DATE
  ,S.USER_LAST_MOD_FEDERATION_ID
  ,S.USER_LAST_MODIFIED_EMAIL
  ,S.PCN_STATUS
  ,S.D_IN_DEMAND_QUANTITY
  ,S.D_IN_DEMAND_AMOUNT
  ,S.D_IN_TOTAL_COST
  ,S.D_IN_TOTAL_GP
  ,S.D_IN_TOTAL_GP_PERCENT
  ,S.CURRENT_TOTAL_COST
  ,S.CURRENT_TOTAL_GP
  ,S.CURRENT_TOTAL_GP_PERCENT
  ,S.CROSS_SELL
  ,S.APPROVAL_STATUS
  ,S.STAGE_SUB_TYPE
  ,S.CUSTOMER_PART_NO
  ,S.AVERAGE_PRICE
  ,S.B_WIN_OSC
  ,T15.CODE_NAME AS B_WIN_OSC_TXT
  ,S.MP_END_MONTH
  ,S.MP_END_DATE
  ,S.NICKNAME
  ,S.PROD_OPPORTUNITY_DISCERNMENT
  ,S.PPAP_BY
  ,S.PRODUCT_FAMILY_CODE
  ,S.PRODUCT_CATEGORY1_CODE
  ,S.PRODUCT_CATEGORY2_CODE
  ,S.PRODUCT_CATEGORY3_CODE
  ,S.PRODUCT_CATEGORY4_CODE
  ,S.PRODUCT_CATEGORY5_CODE
  ,S.SALES_ORDER_PN_DUMMY_FLAG
  ,S.PROGRESS
  ,S.PROMOTION_SAMPLE
  ,T5.CODE_NAME AS PROMOTION_SAMPLE_TXT
  ,S.RENESAS_NEW_PRODUCT
  ,S.SCHEDULE
  ,T14.CODE_NAME AS SCHEDULE_TXT
  ,S.TARGET_PRICE
  ,T4.CODE_NAME AS TARGET_PRICE_TXT
  ,S.TECHNICAL
  ,T3.CODE_NAME AS TECHNICAL_TXT
  ,S.RENESAS_MEET_SCHEDULE_FLG
  ,T7.CODE_NAME AS RENESAS_MEET_SCHEDULE_FLG_TXT
  ,S.RENESAS_PRD_REQ_FLG
  ,T6.CODE_NAME AS RENESAS_PRD_REQ_FLG_TXT
  ,S.PRICE_SUBMIT_FLG
  ,T8.CODE_NAME AS PRICE_SUBMIT_FLG_TXT
  ,S.SAMPLE_DELIVERY_FLG
  ,T9.CODE_NAME AS SAMPLE_DELIVERY_FLG_TXT
  ,S.ACCOUNT_GROUP_CODE
  ,S.APPROVER_FEDERATION_ID
  ,S.APPROVER_EMAIL
  ,S.AWARD_CONFIDENCE_LEVEL_PERCENT
  ,T23.CODE_NAME AS AWARD_CONFIDENCE_LEVEL_PERCENT_TXT
  ,S.STATUS_UPDATE_DATE
  ,S.OPEN_DEAD_STATUS
  ,T21.CODE_NAME AS OPEN_DEAD_STATUS_TXT
  ,S.AUTOMOTIVE_OEM
  ,S.ESTIMATED_GP_PERCENT
  ,S.STAGE_DETAIL
  ,S.DAUGHTER_PROJECT_NAME
  ,S.DEMAND_TYPE
  ,S.DELETE_FLAG
  ,S.PROD_CREATED_BY_FEDERATION_ID
  ,S.PROD_CREATED_BY_EMAIL
  ,S.PROD_CREATED_DATE
  ,S.LAST_MODIFIED_BY_FEDERATION_ID
  ,S.LAST_MODIFIED_BY_EMAIL
  ,S.LAST_MODIFIED_DATE
  ,S.COMPETITOR1
  ,T17.CODE_NAME AS COMPETITOR1_TXT
  ,S.COMPETITOR_PART_NO1
  ,S.COMPETITOR_PRICE1
  ,S.COMPETITOR2
  ,T18.CODE_NAME AS COMPETITOR2_TXT
  ,S.COMPETITOR_PART_NO2
  ,S.COMPETITOR_PRICE2
  ,S.COMPETITOR3
  ,T19.CODE_NAME AS COMPETITOR3_TXT
  ,S.COMPETITOR_PART_NO3
  ,S.COMPETITOR_PRICE3
  ,S.APPROVAL_REQUEST_DATE
  ,S.DR_STATUS
  ,S.APPROVAL_NOTES
  ,S.DR_EXPIRATION_DATE
  ,S.DR_REQ_DISTI_PART_STATUS
  ,S.DR_REQUESTOR_FEDERATION_ID
  ,S.DR_APRVR_FR_APRV_FEDERATION_ID
  ,S.CURRENT_LTV
  ,S.CURRENT_LTQ
  ,S.TYPE_STAGE
  ,S.PRODUCT_SHARE
  ,T16.CODE_NAME AS PRODUCT_SHARE_TXT
  ,S.S0_ACTUAL_DATE
  ,S.QUANTITY_GAP
  ,S.PROMOTION_DATE
  ,S.DISCOVERY_DATE
  ,S.PARTIAL_AWARD_SEQ
  ,S.ANNUAL_DEMAND_LTV_TOTAL
  ,S.ANNUAL_DEMAND_QUANTITIY_TOTAL
FROM
  [BI_DM].[dbo].[F_SFM_OPP_PRD_DEMAND_H] S
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C050'
  ) T
ON
  S.STATUS = T.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C040'
  ) T1
ON
  S.STAGE = T1.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C250'
  ) T2
ON
  S.START_MONTH_OF_FISCAL_YEAR = T2.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T3
ON
  S.TECHNICAL = T3.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T4
ON
  S.TARGET_PRICE = T4.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T5
ON
  S.PROMOTION_SAMPLE = T5.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T6
ON
  S.RENESAS_PRD_REQ_FLG = T6.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T7
ON
  S.RENESAS_MEET_SCHEDULE_FLG = T7.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T8
ON
  S.PRICE_SUBMIT_FLG = T8.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T9
ON
  S.SAMPLE_DELIVERY_FLG = T9.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C070'
  ) T14
ON
  S.SCHEDULE = T14.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C130'
  ) T15
ON
  S.B_WIN_OSC = T15.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C560'
  ) T16
ON
  S.PRODUCT_SHARE = T16.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C420'
  ) T17
ON
  S.COMPETITOR1 = T17.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C420'
  ) T18
ON
  S.COMPETITOR2 = T18.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C420'
  ) T19
ON
  S.COMPETITOR3 = T19.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C510'
  ) T21
ON
  S.OPEN_DEAD_STATUS = T21.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C080'
  ) T22
ON
  S.D_IN_CONFIDENCE_LEVEL_PERCENT = T22.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C080'
  ) T23
ON
  S.AWARD_CONFIDENCE_LEVEL_PERCENT = T23.CODE_VALUE
WHERE
  LATEST_FLG = '0'
  AND S.CURRENCY_TYPE = 'Input Currency'

GO
