USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


				
				
CREATE VIEW [dbo].[VU_MT_BOOK_PN]				
AS				
SELECT [BOOKING_PN]	AS	[Booking_PN]
      ,[BOOKING_PN_CD]	AS	[Booking_PN_CD]
      ,[PRODUCT_PLAN_PN]	AS	[Product_Plan_PN]
      ,[RENESAS_PN]	AS	[Renesas_PN]
      ,[CAT1]	AS	[CAT1]
      ,[CAT1_TXT]	AS	[CAT1_txt]
      ,[CAT2]	AS	[CAT2]
      ,[CAT2_TXT]	AS	[CAT2_txt]
      ,[CAT3]	AS	[CAT3]
      ,[CAT3_TXT]	AS	[CAT3_txt]
      ,[CAT4]	AS	[CAT4]
      ,[CAT4_TXT]	AS	[CAT4_txt]
      ,[CAT5]	AS	[CAT5]
      ,[CAT5_TXT]	AS	[CAT5_txt]
      ,[DESIGN_GROUP_BUSINESS]	AS	[Design_Group_Business]
      ,[DESIGN_GROUP_BUSINESS_TXT]	AS	[Design_Group_Business_txt]
      ,[DESIGN_GROUP_UNIT]	AS	[Design_Group_Unit]
      ,[DESIGN_GROUP_UNIT_TXT]	AS	[Design_Group_Unit_txt]
      ,[DESIGN_GROUP_DIVISION]	AS	[Design_Group_Division]
      ,[DESIGN_GROUP_DIVISION_TXT]	AS	[Design_Group_Division_txt]
      ,[DESIGN_GROUP_DEPARTMENT]	AS	[Design_Group_Department]
      ,[DESIGN_GROUP_DEPARTMENT_TXT]	AS	[Design_Group_Department_txt]
      ,[DESIGN_GROUP_SECTION]	AS	[Design_Group_Section]
      ,[DESIGN_GROUP_SECTION_TXT]	AS	[Design_Group_Section_txt]
      ,[EISUI_BUSINESS]	AS	[Eisui_Business]
      ,[EISUI_BUSINESS_TXT]	AS	[Eisui_Business_txt]
      ,[EISUI_UNIT]	AS	[Eisui_Unit]
      ,[EISUI_UNIT_TXT]	AS	[Eisui_Unit_txt]
    --20190904_明細ViewのSCM顧客マスタViewと受注型名マスタViewの項目追加対応 Start
--      ,[EISUI_DIVITION] AS [Eisui_Divition]
--      ,[EISUI_DIVITION_TXT] AS [Eisui_Divition_txt]
      ,[EISUI_DIVITION] AS [Eisui_Division]
      ,[EISUI_DIVITION_TXT] AS [Eisui_Division_txt]
    --20190904_明細ViewのSCM顧客マスタViewと受注型名マスタViewの項目追加対応 End
      ,[EISUI_DEPARTMENT]	AS	[Eisui_Department]
      ,[EISUI_DEPARTMENT_TXT]	AS	[Eisui_Department_txt]
      ,[EISUI_SECTION]	AS	[Eisui_Section]
      ,[EISUI_SECTION_TXT]	AS	[Eisui_Section_txt]
      ,[EISUI_DS_NO]	AS	[Eisui_DS_NO]
      ,[EISUI_FAMILY_NAME]	AS	[Eisui_Family_Name]
      ,[EISUI_FIRST_NAME]	AS	[Eisui_First_Name]
      ,[POSITION_TXT]	AS	[Position_txt]
      ,[POSITION_E_TXT]	AS	[Position_E_txt]
      ,[E_MAIL]	AS	[E_Mail]
      ,[PHONE_NO]	AS	[Phone_NO]
      ,[SEIKAN_GROUP_BUSINESS]	AS	[Seikan_Group_Business]
      ,[SEIKAN_GROUP_BUSINESS_TXT]	AS	[Seikan_Group_Business_txt]
      ,[SEIKAN_GROUP_UNIT]	AS	[Seikan_Group_Unit]
      ,[SEIKAN_GROUP_UNIT_TXT]	AS	[Seikan_Group_Unit_txt]
      ,[SEIKAN_GROUP_DIVISION]	AS	[Seikan_Group_Division]
      ,[SEIKAN_GROUP_DIVISION_TXT]	AS	[Seikan_Group_Division_txt]
      ,[SEIKAN_GROUP_DEPT]	AS	[Seikan_Group_Dept]
      ,[SEIKAN_GROUP_DEPT_TXT]	AS	[Seikan_Group_Dept_txt]
      ,[SEIKAN_GROUP_SECTION]	AS	[Seikan_Group_Section]
      ,[SEIKAN_GROUP_SECTION_TXT]	AS	[Seikan_Group_Section_txt]
      ,[PN_TYPE]	AS	[PN_Type]
      ,[PN_TYPE2]	AS	[PN_Type2]
      ,[SCM_CUSTOM_TYPE]	AS	[SCM_Custom_Type]
      ,[ORDER_PRODUCT_STATUS]	AS	[Order_Product_Status]
      ,[ORDER_PRODUCT_STATUS_TXT]	AS	[Order_Product_Status_txt]
      ,[RENESAS_PRODUCT_FLAG]	AS	[Renesas_Product_Flag]
      ,[RENESAS_PRODUCT_FLAG_TXT]	AS	[Renesas_Product_Flag_txt]
      ,[OMC_FLAG]	AS	[OMC_Flag]
      ,[AUTOMATIC_ORDERING_FLAG]	AS	[Automatic_Ordering_Flag]
      ,[BASE_PN_FLAG]	AS	[Base_PN_Flag]
      ,[ROM_TYPE]	AS	[ROM_Type]
      ,[ROM_TYPE_TXT]	AS	[ROM_Type_txt]
      ,[BOOKING_STATUS]	AS	[Booking_Status]
      ,[SCM_FLAG]	AS	[SCM_Flag]
      ,[SCM_FLAG_TXT]	AS	[SCM_Flag_txt]
      ,[ORDER_LINK_TYPE]	AS	[Order_Link_Type]
      ,[INNER_BOX_QUANTITY]	AS	[Inner_Box_Quantity]
      ,[OUTER_BOX_QUANTITY]	AS	[Outer_Box_Quantity]
      ,[TUBE_OR_TRAY_QUANTITY]	AS	[Tube_Or_Tray_Quantity]
      ,[TAPING_SPEC]	AS	[Taping_Spec]
      ,[FULL_CARTON_SPEC]	AS	[Full_Carton_Spec]
      ,[MOQ]	AS	[MOQ]
      ,[SPQ]	AS	[SPQ]
      ,[TS_FLAG]	AS	[TS_Flag]
      ,[TS_FLAG_TXT]	AS	[TS_Flag_txt]
      ,[PB_FREE_DIV]	AS	[PB_Free_Div]
      ,[PROCESS_CD]	AS	[Process_CD]
      ,[PACKAGE_CODE]	AS	[Package_Code]
      ,[STORAGE_PERIOD_BOOKING_PN]	AS	[Storage_Period_Booking_PN]
      ,[TOTAL_WEIGHT]	AS	[Total_Weight]
      ,[SALES_ORDER_20_PART_NO]	AS	[Sales_Order_20_Part_NO]
      ,[ORIGINAL_PN]	AS	[Original_PN]
      ,[PART_NO_FROM_DIV]	AS	[Part_NO_From_Div]
      ,[PART_NO_FROM_DIV_TXT]	AS	[Part_NO_From_Div_txt]
      ,[ORDER_PART_NO_CD]	AS	[Order_PN_CD]
      ,[SPEC_JUDGE_FLG]	AS	[Spec_Judge_Flg]
      ,[SO_PT_NO_K_A4_W]	AS	[Booking_PN_White40]
      ,[ANCESTRAL_PART_NO]	AS	[Ancestral_Part_NO]
      ,[ANCESTRAL_PART_NO_CD]	AS	[Ancestral_Part_NO_CD]
      ,[PN_MEMO]	AS	[PN_Memo]
      ,[CLASS_FLAG]	AS	[Class_Flag]
      ,[BOOKING_CLASS1]	AS	[Booking_Class1]
      ,[BOOKING_CLASS2]	AS	[Booking_Class2]
      ,[BOOKING_CLASS3]	AS	[Booking_Class3]
      ,[WAREHOUSE_TYPE]	AS	[Warehouse_Type]
      ,[WAREHOUSE_TYPE_TXT]	AS	[Warehouse_Type_txt]
      ,[WBS_NO_BOOKING_PN]	AS	[WBS_NO_Booking_PN]
      ,[EXPORT_JUDGE_PN_BOOKING_PN]	AS	[Export_Judge_PN_Booking_PN]
      ,[CATALOG_PN]	AS	[Catalog_PN]
      ,[CATALOG_FLAG_BOOKING_PN]	AS	[Catalog_Flag_Booking_PN]
      ,[PRICE_PN]	AS	[Price_PN]
      ,[BASE_PRICE_PART_NO]	AS	[Base_Price_Part_NO]
      ,[PRODUCT_STATUS_RENESAS_PN]	AS	[Product_Status_Renesas_PN]
      ,[DEVELOP_NO]	AS	[Develop_NO]
      ,[EXPORT_JUDGE_PN_RENESAS_PN]	AS	[Export_Judge_PN_Renesas_PN]
      ,[CATALOG_PN_RENESAS_PN]	AS	[Catalog_PN_Renesas_PN]
      ,[CATALOG_FLAG_RENESAS_PN]	AS	[Catalog_Flag_Renesas_PN]
      ,[SPEED]	AS	[Speed]
      ,[VOLTAGE]	AS	[Voltage]
      ,[TEMPERATURE_RANGE]	AS	[Temperature_Range]
      ,[MAX_TEMPERATURE]	AS	[Max_Temperature]
      ,[MIN_TEMPERATURE]	AS	[Min_Temperature]
      ,[GENERATION]	AS	[Generation]
      ,[BIT_COMPOSITION]	AS	[Bit_Composition]
      ,[WORD]	AS	[Word]
      ,[PRODUCT_CAPACITY]	AS	[Product_Capacity]
      ,[HARDWARE_IP_USE]	AS	[Hardware_IP_Use]
      ,[SOFTWARE_IP_USE]	AS	[Software_IP_Use]
      ,[FRAME_2_4_DIV]	AS	[Frame_2_4_Div]
      ,[MP_DATE]	AS	[MP_Date]
      ,[1ST_SHIP_DATE]	AS	[1st_Ship_Date]
      ,[EOL_AFFECT_POLICY]	AS	[EOL_AFFECT_POLICY]
      ,[EOL_POLICY]	AS	[EOL_POLICY]
      ,[EOL_CURRENT_WP_WT]	AS	[EOL_CURRENT_WP_WT]
      ,[EOL_POLICY_TYPE]	AS	[EOL_POLICY_TYPE]
      ,[EOL_SITECHANGE_ASSY]	AS	[EOL_SITECHANGE_ASSY]
      ,[EOL_WPWT_DETAIL]	AS	[EOL_WPWT_DETAIL]
      ,[EOL_WPWT_FUTURE]	AS	[EOL_WPWT_FUTURE]
      ,[EOL_X1FREE_ITEM]	AS	[EOL_x1FREE_ITEM]
      ,[EOL_X2FREE_ITEM]	AS	[EOL_x2FREE_ITEM]
      ,[EOL_X3FREE_ITEM]	AS	[EOL_x3FREE_ITEM]
      ,[MCU_SOC_AP_KBN]	AS	[MCU_SOC_AP_KBN]
      ,[COST_CENTER_CD]	AS	[Cost_Center_CD]
      ,[COST_CENTER_TXT]	AS	[Cost_Center_txt]
      ,[DEVELOPMENT_YEAR_HARF]	AS	[Development_Year_Harf]
      ,[PRODUCT_FAMILY_CD]	AS	[Product_Family_CD]
      ,[PRODUCT_FAMILY]	AS	[Product_Family]
      ,[PRODUCT_GROUP_CD]	AS	[Product_Group_CD]
      ,[PRODUCT_GROUP]	AS	[Product_Group]
      ,[CANCEL_FLG]	AS	[Cancel_FLG]
    --20190703_KIS折衷案 Start
      ,[TAB_PROCESS_NAME]	AS	[Process]
    --20190703_KIS折衷案 End
      ,[INS_DATE_RENESAS_PN]	AS	[INS_Date_Renesas_PN]
      ,[INS_TIME_RENESAS_PN]	AS	[INS_Time_Renesas_PN]
      ,[INS_DATE_BOOKING_PN]	AS	[INS_Date_Booking_PN]
      ,[INS_TIME_BOOKING_PN]	AS	[INS_Time_Booking_PN]
      ,[UPD_DATE]	AS	[UPD_Date]
      ,[UPD_TIME]	AS	[UPD_Time]
    --20190904_明細ViewのSCM顧客マスタViewと受注型名マスタViewの項目追加対応 Start
      ,[PROCESS_NICK_NAME]	AS	[PROCESS_NICK_NAME]
      ,[REPRESENT_PART_NO_OYA]	AS	[REPRESENT_PART_NO_OYA]
      ,[SCM_FLAG2_TXT]	AS	[SCM_FLAG2_TXT]
      ,[MCU_TYPE]	AS	[MCU_TYPE]
      ,[ROCHESTER_FLG]	AS	[ROCHESTER_FLG]
      ,[SHIPPING_SITE_TXT]	AS	[Shipping Site]
      ,[HI_REL_FLG_TXT]	AS	[Hi-Rel Flag]
    --20190904_明細ViewのSCM顧客マスタViewと受注型名マスタViewの項目追加対応 End
FROM [BI_DM].[dbo].[M_PNO_BOOK_PN]				
				
				
				

GO
