USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VD_SFM_BCCV_PRODUCT_HISTORY] AS
SELECT
   PRODUCT_HISTORY_NO
  ,OPPORTUNITY_SEQ
  ,ACTUAL_TYPE
  ,EVENT_TYPE
  ,STAGE_TYPE
FROM
  [BI_DM].[dbo].[F_SFM_PRODUCT_HISTORY_L]
--CDC CRM明細ビューAggregate対応 2018/06/20 START 
WHERE CURRENCY_TYPE = 'Input Currency'
--CDC CRM明細ビューAggregate対応 2018/06/20 END
GO


