USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VF_GP_REPO_1_TOP_PROD_PLOT] AS
 SELECT
       FORMAT(GO.RECORD_DATE,'yyyy/MM') as RECORD_DATE
      ,ISNULL(CUST.[CUSTOMER_GRP1],'UnKnown') as CUSTOMER_GRP1
	  ,ISNULL(BKPN.[DESIGN_GROUP_UNIT_TXT],'UnKnown') as DESIGN_GROUP_UNIT_TXT
	  ,ISNULL(BKPN.[DESIGN_GROUP_DIVISION_TXT],'UnKnown') as DESIGN_GROUP_DIVISION_TXT
	  ,ISNULL(BKPN.[DESIGN_GROUP_DEPARTMENT_TXT],'UnKnown') as DESIGN_GROUP_DEPARTMENT_TXT
      ,sum(GO.GO_AMT_JPY) AS GO_Bill_Amt
      ,(sum(GO.GO_AMT_JPY)-sum(GO.GO_AMT_STD)) as GO_Bill_GP_Amt
      ,(sum(GO.GO_AMT_JPY)-sum(GO.GO_AMT_STD))/ NULLIF(sum(GO.GO_AMT_JPY),0) as GO_Bill_GP_Rate
FROM [BI_DM].[dbo].[F_SAL_BILL_GO] as GO
LEFT OUTER JOIN [BI_DM].[dbo].[M_SCM_CUST] as CUST
    ON GO.[SCM_CUSTOMER_CD] = CUST.[SCM_CUSTOMER]
LEFT OUTER JOIN [BI_DM].[dbo].[M_PNO_BOOK_PN] as BKPN
    ON GO.[ORDER_PART_NO_CD] = BKPN.[BOOKING_PN_CD]
WHERE (GO.GO_AMT_JPY <> 0 or GO.GO_AMT_STD <> 0)
  AND CUST.[INTERNALFLG] = 'DD001'
  AND BKPN.[RENESAS_PRODUCT_FLAG] = '1'
GROUP BY
         FORMAT(GO.RECORD_DATE,'yyyy/MM')
        ,CUST.[CUSTOMER_GRP1]
		,BKPN.[DESIGN_GROUP_UNIT_TXT]
		,BKPN.[DESIGN_GROUP_DIVISION_TXT]
		,BKPN.[DESIGN_GROUP_DEPARTMENT_TXT]	
;












GO
