USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_DCP_DELIBERATION](
	[DELIBERATION_CD] [nvarchar](6) NOT NULL,
	[DELIBERATION_NAME] [nvarchar](20) NULL,
	[DCP_FLAG] [int] NULL,
	[DCP_UPDATETIME] [smalldatetime] NULL,
	[REG_DATETIME] [smalldatetime] NULL,
	[UPD_DATETIME] [smalldatetime] NULL,
 CONSTRAINT [PK_M_DCP_DELIBERATION] PRIMARY KEY CLUSTERED 
(
	[DELIBERATION_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
) ON [BI_DM_Dimension]

GO
ALTER TABLE [dbo].[M_DCP_DELIBERATION] ADD  DEFAULT (getdate()) FOR [REG_DATETIME]
GO
ALTER TABLE [dbo].[M_DCP_DELIBERATION] ADD  DEFAULT (getdate()) FOR [UPD_DATETIME]
GO
