USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_PNO_BOOK_PN](
	[BOOKING_PN] [nvarchar](40) NULL,
	[BOOKING_PN_CD] [nvarchar](18) NOT NULL,
	[PRODUCT_PLAN_PN] [nvarchar](40) NULL,
	[RENESAS_PN] [nvarchar](30) NULL,
	[CAT1] [nvarchar](2) NULL,
	[CAT1_TXT] [nvarchar](40) NULL,
	[CAT2] [nvarchar](4) NULL,
	[CAT2_TXT] [nvarchar](40) NULL,
	[CAT3] [nvarchar](6) NULL,
	[CAT3_TXT] [nvarchar](40) NULL,
	[CAT4] [nvarchar](8) NULL,
	[CAT4_TXT] [nvarchar](40) NULL,
	[CAT5] [nvarchar](10) NULL,
	[CAT5_TXT] [nvarchar](40) NULL,
	[DESIGN_GROUP_BUSINESS] [nvarchar](2) NULL,
	[DESIGN_GROUP_BUSINESS_TXT] [nvarchar](40) NULL,
	[DESIGN_GROUP_UNIT] [nvarchar](4) NULL,
	[DESIGN_GROUP_UNIT_TXT] [nvarchar](60) NULL,
	[DESIGN_GROUP_DIVISION] [nvarchar](6) NULL,
	[DESIGN_GROUP_DIVISION_TXT] [nvarchar](60) NULL,
	[DESIGN_GROUP_DEPARTMENT] [nvarchar](8) NULL,
	[DESIGN_GROUP_DEPARTMENT_TXT] [nvarchar](60) NULL,
	[DESIGN_GROUP_SECTION] [nvarchar](10) NULL,
	[DESIGN_GROUP_SECTION_TXT] [nvarchar](60) NULL,
	[EISUI_BUSINESS] [nvarchar](2) NULL,
	[EISUI_BUSINESS_TXT] [nvarchar](40) NULL,
	[EISUI_UNIT] [nvarchar](4) NULL,
	[EISUI_UNIT_TXT] [nvarchar](60) NULL,
	[EISUI_DIVITION] [nvarchar](6) NULL,
	[EISUI_DIVITION_TXT] [nvarchar](60) NULL,
	[EISUI_DEPARTMENT] [nvarchar](8) NULL,
	[EISUI_DEPARTMENT_TXT] [nvarchar](60) NULL,
	[EISUI_SECTION] [nvarchar](10) NULL,
	[EISUI_SECTION_TXT] [nvarchar](60) NULL,
	[EISUI_DS_NO] [nvarchar](10) NULL,
	[EISUI_FIRST_NAME] [nvarchar](40) NULL,
	[EISUI_FAMILY_NAME] [nvarchar](40) NULL,
	[POSITION_TXT] [nvarchar](120) NULL,
	[POSITION_E_TXT] [nvarchar](120) NULL,
	[E_MAIL] [nvarchar](80) NULL,
	[PHONE_NO] [nvarchar](30) NULL,
	[SEIKAN_GROUP_BUSINESS] [nvarchar](2) NULL,
	[SEIKAN_GROUP_BUSINESS_TXT] [nvarchar](40) NULL,
	[SEIKAN_GROUP_UNIT] [nvarchar](4) NULL,
	[SEIKAN_GROUP_UNIT_TXT] [nvarchar](60) NULL,
	[SEIKAN_GROUP_DIVISION] [nvarchar](6) NULL,
	[SEIKAN_GROUP_DIVISION_TXT] [nvarchar](60) NULL,
	[SEIKAN_GROUP_DEPT] [nvarchar](8) NULL,
	[SEIKAN_GROUP_DEPT_TXT] [nvarchar](60) NULL,
	[SEIKAN_GROUP_SECTION] [nvarchar](10) NULL,
	[SEIKAN_GROUP_SECTION_TXT] [nvarchar](60) NULL,
	[PN_TYPE] [nvarchar](2) NULL,
	[PN_TYPE2] [nvarchar](4) NULL,
	[SCM_CUSTOM_TYPE] [nvarchar](1) NULL,
	[ORDER_PRODUCT_STATUS] [nvarchar](2) NULL,
	[ORDER_PRODUCT_STATUS_TXT] [nvarchar](100) NULL,
	[RENESAS_PRODUCT_FLAG] [nvarchar](1) NULL,
	[RENESAS_PRODUCT_FLAG_TXT] [nvarchar](100) NULL,
	[OMC_FLAG] [nvarchar](1) NULL,
	[AUTOMATIC_ORDERING_FLAG] [nvarchar](1) NULL,
	[BASE_PN_FLAG] [nvarchar](1) NULL,
	[ROM_TYPE] [nvarchar](1) NULL,
	[ROM_TYPE_TXT] [nvarchar](100) NULL,
	[BOOKING_STATUS] [nvarchar](1) NULL,
	[SCM_FLAG] [nvarchar](1) NULL,
	[SCM_FLAG_TXT] [nvarchar](100) NULL,
	[ORDER_LINK_TYPE] [nvarchar](1) NULL,
	[INNER_BOX_QUANTITY] [numeric](13, 0) NULL,
	[OUTER_BOX_QUANTITY] [numeric](13, 0) NULL,
	[TUBE_OR_TRAY_QUANTITY] [numeric](13, 0) NULL,
	[TAPING_SPEC] [nvarchar](10) NULL,
	[FULL_CARTON_SPEC] [nvarchar](10) NULL,
	[MOQ] [numeric](10, 0) NULL,
	[SPQ] [numeric](10, 0) NULL,
	[TS_FLAG] [nvarchar](2) NULL,
	[TS_FLAG_TXT] [nvarchar](100) NULL,
	[PB_FREE_DIV] [nvarchar](2) NULL,
	[PROCESS_CD] [nvarchar](32) NULL,
	[PACKAGE_CODE] [nvarchar](18) NULL,
	[STORAGE_PERIOD_BOOKING_PN] [numeric](4, 0) NULL,
	[TOTAL_WEIGHT] [numeric](13, 3) NULL,
	[SALES_ORDER_20_PART_NO] [nvarchar](40) NULL,
	[ORIGINAL_PN] [nvarchar](18) NULL,
	[PART_NO_FROM_DIV] [nvarchar](1) NULL,
	[PART_NO_FROM_DIV_TXT] [nvarchar](100) NULL,
	[ORDER_PART_NO_CD] [nvarchar](18) NULL,
	[SPEC_JUDGE_FLG] [numeric](18, 0) NULL,
	[SO_PT_NO_K_A4_W] [nvarchar](40) NULL,
	[ANCESTRAL_PART_NO] [nvarchar](40) NULL,
	[ANCESTRAL_PART_NO_CD] [nvarchar](18) NULL,
	[PN_MEMO] [nvarchar](300) NULL,
	[CLASS_FLAG] [nvarchar](1) NULL,
	[BOOKING_CLASS1] [nvarchar](3) NULL,
	[BOOKING_CLASS2] [nvarchar](3) NULL,
	[BOOKING_CLASS3] [nvarchar](3) NULL,
	[WAREHOUSE_TYPE] [nvarchar](4) NULL,
	[WAREHOUSE_TYPE_TXT] [nvarchar](100) NULL,
	[WBS_NO_BOOKING_PN] [nvarchar](10) NULL,
	[EXPORT_JUDGE_PN_BOOKING_PN] [nvarchar](30) NULL,
	[CATALOG_PN] [nvarchar](30) NULL,
	[CATALOG_FLAG_BOOKING_PN] [nvarchar](1) NULL,
	[PRICE_PN] [nvarchar](32) NULL,
	[BASE_PRICE_PART_NO] [nvarchar](30) NULL,
	[PRODUCT_STATUS_RENESAS_PN] [nvarchar](1) NULL,
	[DEVELOP_NO] [nvarchar](7) NULL,
	[EXPORT_JUDGE_PN_RENESAS_PN] [nvarchar](30) NULL,
	[CATALOG_PN_RENESAS_PN] [nvarchar](30) NULL,
	[CATALOG_FLAG_RENESAS_PN] [nvarchar](1) NULL,
	[SPEED] [numeric](5, 0) NULL,
	[VOLTAGE] [numeric](7, 2) NULL,
	[TEMPERATURE_RANGE] [nvarchar](1) NULL,
	[MAX_TEMPERATURE] [numeric](7, 0) NULL,
	[MIN_TEMPERATURE] [numeric](7, 0) NULL,
	[GENERATION] [nvarchar](1) NULL,
	[BIT_COMPOSITION] [nvarchar](5) NULL,
	[WORD] [nvarchar](12) NULL,
	[PRODUCT_CAPACITY] [nvarchar](12) NULL,
	[HARDWARE_IP_USE] [nvarchar](1) NULL,
	[SOFTWARE_IP_USE] [nvarchar](1) NULL,
	[FRAME_2_4_DIV] [nvarchar](1) NULL,
	[MP_DATE] [nvarchar](8) NULL,
	[1ST_SHIP_DATE] [nvarchar](8) NULL,
	[EOL_AFFECT_POLICY] [nvarchar](300) NULL,
	[EOL_POLICY] [nvarchar](300) NULL,
	[EOL_CURRENT_WP_WT] [nvarchar](300) NULL,
	[EOL_POLICY_TYPE] [nvarchar](300) NULL,
	[EOL_SITECHANGE_ASSY] [nvarchar](300) NULL,
	[EOL_WPWT_DETAIL] [nvarchar](300) NULL,
	[EOL_WPWT_FUTURE] [nvarchar](300) NULL,
	[EOL_X1FREE_ITEM] [nvarchar](300) NULL,
	[EOL_X2FREE_ITEM] [nvarchar](300) NULL,
	[EOL_X3FREE_ITEM] [nvarchar](300) NULL,
	[MCU_SOC_AP_KBN] [nvarchar](300) NULL,
	[COST_CENTER_CD] [nvarchar](300) NULL,
	[COST_CENTER_TXT] [nvarchar](300) NULL,
	[DEVELOPMENT_YEAR_HARF] [nvarchar](300) NULL,
	[PRODUCT_FAMILY_CD] [nvarchar](300) NULL,
	[PRODUCT_FAMILY] [nvarchar](300) NULL,
	[PRODUCT_GROUP_CD] [nvarchar](300) NULL,
	[PRODUCT_GROUP] [nvarchar](300) NULL,
	[CANCEL_FLG] [nvarchar](1) NULL,
	[INS_DATE_RENESAS_PN] [nvarchar](8) NULL,
	[INS_TIME_RENESAS_PN] [nvarchar](6) NULL,
	[INS_DATE_BOOKING_PN] [nvarchar](8) NULL,
	[INS_TIME_BOOKING_PN] [nvarchar](6) NULL,
	[UPD_DATE] [nvarchar](8) NULL,
	[UPD_TIME] [nvarchar](6) NULL,
	[PROCESS_NICK_NAME] [nvarchar](300) NULL,
	[TAB_PROCESS_NAME] [nvarchar](300) NULL,
	[TAB_PROCESS_FOCUS_FLG] [nvarchar](300) NULL,
	[REPRESENT_PART_NO_OYA] [nvarchar](30) NULL,
	[MCU_TYPE] [nvarchar](300) NULL,
	[COST] [numeric](15, 2) NULL,
	[COST_2015] [numeric](15, 2) NULL,
	[COST_2016] [numeric](15, 2) NULL,
	[COST_2017] [numeric](15, 2) NULL,
	[COST_2018] [numeric](15, 2) NULL,
	[COST_2019] [numeric](15, 2) NULL,
	[COST_2020] [numeric](15, 2) NULL,
	[COST_2021] [numeric](15, 2) NULL,
	[COST_2022] [numeric](15, 2) NULL,
	[COST_2023] [numeric](15, 2) NULL,
	[COST_2024] [numeric](15, 2) NULL,
	[COST_2025] [numeric](15, 2) NULL,
	[COST_2026] [numeric](15, 2) NULL,
	[COST_2027] [numeric](15, 2) NULL,
	[COST_2028] [numeric](15, 2) NULL,
	[COST_2029] [numeric](15, 2) NULL,
	[COST_2030] [numeric](15, 2) NULL,
	[COST_2031] [numeric](15, 2) NULL,
	[COST_2032] [numeric](15, 2) NULL,
	[COST_2033] [numeric](15, 2) NULL,
	[COST_2034] [numeric](15, 2) NULL,
	[COST_2035] [numeric](15, 2) NULL,
	[COST_2036] [numeric](15, 2) NULL,
	[COST_2037] [numeric](15, 2) NULL,
	[COST_2038] [numeric](15, 2) NULL,
	[COST_2039] [numeric](15, 2) NULL,
	[COST_2040] [numeric](15, 2) NULL,
	[COST_2041] [numeric](15, 2) NULL,
	[COST_2042] [numeric](15, 2) NULL,
	[COST_2043] [numeric](15, 2) NULL,
	[COST_2044] [numeric](15, 2) NULL,
	[COST_2045] [numeric](15, 2) NULL,
	[SCM_FLAG2_TXT] [nvarchar](300) NULL,
	[ROCHESTER_FLG] [nvarchar](300) NULL,
	[SHIPPING_SITE_TXT] [nvarchar](100) NULL,
	[HI_REL_FLG_TXT] [nvarchar](100) NULL,
 CONSTRAINT [PK_M_PNO_BOOK_PN_1] PRIMARY KEY CLUSTERED 
(
	[BOOKING_PN_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
) ON [BI_DM_Dimension]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [I_M_PNO_BOOK_PN_1] ON [dbo].[M_PNO_BOOK_PN]
(
	[CANCEL_FLG] ASC,
	[BOOKING_PN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
GO
