USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VD_SFM_OPP] AS
SELECT
   OPP.OPPORTUNITY_NO
  ,OPP.STAGE_TYPE
  ,T.CODE_NAME                      AS STAGE_TYPE_TXT
  ,OPP.OPPORTUNITY_OWNER
  ,OPP.OPPORTUNITY_OWNER_EMAIL
  ,OPP.OPPORTUNITY_NAME
  ,OPP.ACCOUNT_GROUP_CODE
  ,ACCOUNT.ACCOUNT_NAME
  ,OPP.CHANNEL_PARTNER_CODE
  ,OPP.CHANNEL_PARTNER_NAME
  ,OPP.DURATION_MONTH
  ,OPP.SALES_LEADER_FEDERATION_ID
  ,OPP.SALES_LEADER_EMAIL
  ,OPP.NDA_FLAG
  ,OPP.TRACKING_TYPE_STATUS
  ,T1.CODE_NAME                     AS TRACKING_TYPE_STATUS_TXT
  ,OPP.DELETE_FLAG
  ,OPP.CREATED_BY_FEDERATION_ID
  ,OPP.CREATED_BY_EMAIL
  ,OPP.CREATED_DATE
  ,OPP.LAST_MODIFIED_BY_FEDERATION_ID
  ,OPP.LAST_MODIFIED_BY_EMAIL
  ,OPP.LAST_MODIFIED_DATE
  ,OPP.OPPORTUNITY_INDUSTRY
  ,T2.CODE_NAME                    AS OPPORTUNITY_INDUSTRY_TXT
  ,OPP.D_IN_SALES_COMPANY
  ,T3.CODE_NAME                    AS D_IN_SALES_COMPANY_TXT
  ,OPP.END_CUSTOMER_NAME
  ,OPP.END_CUSTOMER_COUNTRY
  ,OPP.SEGMENT
  ,T4.CODE_NAME                    AS SEGMENT_TXT
  ,OPP.OWNER_COMPANYNAME
  ,OPP.APPLICATION_NOTE
  ,OPP.MP_START_MONTH
  ,OPP.ESTIMATED_ANNUAL_USAGE
  ,OPP.CAMPAIGN_NAME
  ,OPP.LEAD_ID
  ,OPP.LEAD_NAME
  ,OPP.END_CUSTOMER_FREE_TEXT
  ,OPP.AUTOMOTIVE_OEM_NAME
  ,OPP.GROUPING_NAME
  ,OPP.SALES_TEAM_NAME_1
  ,OPP.SALES_TEAM_NAME_2
  ,OPP.SALES_TEAM_NAME_3
  ,OPP.SALES_TEAM_NAME_4
  ,OPP.D_IN_SCM_CUST_CODE_FOR_SCM_OPE
  ,OPP.D_IN_SCM_CUST_CODE_DUMMY_FLAG
  ,OPP.MP_START_DATE
  ,OPP.OPPORTUNITY_DISCERNMENT
--LatestキューブへのAggregate対応 遅 20180927 START
  ,T5.CODE_NAME                    AS OPPORTUNITY_DISCERNMENT_TXT
--LatestキューブへのAggregate対応 遅 20180927 END
  ,OPP.PREOPPORTUNITY_ID
  ,OPP.PRE_OPP_NO
FROM
  [BI_DW].[dbo].[T_SFM_BCCV_OPPORTUNITY_VIEW] OPP
LEFT OUTER JOIN
  [BI_DW].[dbo].[R_SFM_BCCV_ACCOUNT_VIEW] ACCOUNT
ON
  OPP.ACCOUNT_GROUP_CODE = ACCOUNT.ACCOUNT_GROUP_CODE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C030'
  ) T
ON
  OPP.STAGE_TYPE = T.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C500'
  ) T1
ON
  OPP.TRACKING_TYPE_STATUS = T1.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C300'
  ) T2
ON
  OPP.OPPORTUNITY_INDUSTRY = T2.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C130'
  ) T3
ON
  OPP.D_IN_SALES_COMPANY = T3.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C550'
  ) T4
ON
  OPP.SEGMENT = T4.CODE_VALUE
LEFT OUTER JOIN
  (
	SELECT
	  CODE_ID,
	  CODE_VALUE,
	  CODE_NAME
	FROM
	  [BI_DW].[dbo].[R_SFM_BCCT_BAMBOO_CODE_MST]
	WHERE
	  CODE_ID = 'C100'
  ) T5
ON
  OPP.OPPORTUNITY_DISCERNMENT = T5.CODE_VALUE
GO
