USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_SFM_OPPORTUNITY_DETAIL_L](
	[Conversion_Currency] [nvarchar](14) NULL,
	[Design_Region] [nvarchar](255) NULL,
	[Tracking_Type_Status] [nvarchar](255) NULL,
	[Tracking_Type_Status_Code] [nvarchar](2) NULL,
	[Open_Dead_Status] [nvarchar](255) NULL,
	[Stage_Type] [nvarchar](255) NULL,
	[Stage_Sub_Type] [nvarchar](2) NULL,
	[Mother_Daughter] [varchar](10) NULL,
	[Stage_Code] [nchar](2) NULL,
	[Type_Stage] [nvarchar](255) NULL,
	[Stage_Detail] [varchar](255) NULL,
	[Opportunity_Discernment] [nvarchar](255) NULL,
	[Campaign_Name] [nvarchar](255) NULL,
	[Lead_Name] [nvarchar](400) NULL,
	[Share_Up] [nvarchar](255) NULL,
	[Daughter_Design_Region] [nchar](2) NULL,
	[Offshore_Customer_Conversion] [nchar](1) NULL,
	[Opportunity] [nvarchar](7) NULL,
	[Opportunity_Seq] [varchar](10) NULL,
	[Unique_Opportunity_Seq] [varchar](13) NULL,
	[Opportunity_Name] [nvarchar](120) NULL,
	[Project_Name_Award] [nvarchar](60) NULL,
	[Customer_Grp2] [nvarchar](300) NULL,
	[End_Customer_Name] [nvarchar](335) NULL,
	[End_Customer_Opp] [nvarchar](80) NULL,
	[End_Customer_Country] [nvarchar](2) NULL,
	[Channel_Partner_Name] [nvarchar](255) NULL,
	[URL_Opp_Product_For_REL] [nvarchar](255) NULL,
	[APL1_Opp_Code] [nvarchar](1) NULL,
	[APL1_Opp] [nvarchar](40) NULL,
	[APL2_Opp_Code] [nvarchar](2) NULL,
	[APL2_Opp] [nvarchar](40) NULL,
	[APL3_Opp_Code] [nvarchar](3) NULL,
	[APL3_Opp] [nvarchar](40) NULL,
	[Application_Note] [nvarchar](255) NULL,
	[GST_1_AFFECT_Opp] [nvarchar](300) NULL,
	[GST_2_Opp] [nvarchar](300) NULL,
	[GST_3_Opp] [nvarchar](300) NULL,
	[Segment] [nvarchar](300) NULL,
	[SubSegment] [nvarchar](300) NULL,
	[Invest_Label] [nvarchar](300) NULL,
	[Din_Target_Half] [nvarchar](7) NULL,
	[Din_Target_Month] [nvarchar](7) NULL,
	[Din_Target_Date] [date] NULL,
	[Din_Confidence_Level] [varchar](8) NULL,
	[Din_Request_Date] [datetime] NULL,
	[Din_Actual_Date] [date] NULL,
	[Target_Nomination_Date] [date] NULL,
	[Nomination_Confidence_Level] [nvarchar](255) NULL,
	[Nomination_Request_Date] [datetime] NULL,
	[Target_Award_Date] [date] NULL,
	[Award_Confidence_Level] [nvarchar](255) NULL,
	[Award_Request_Date] [datetime] NULL,
	[Progress] [varchar](7) NULL,
	[MP_Start_Half] [nvarchar](7) NULL,
	[MP_Start_Month] [nvarchar](7) NULL,
	[MP_Start_Date] [date] NULL,
	[MP_End_Date] [date] NULL,
	[Duration_Month] [numeric](3, 0) NULL,
	[Estimated_Annual_Usage_Per_Year] [numeric](18, 0) NULL,
	[Pieces_Per_Customer_Set] [decimal](18, 0) NULL,
	[Share_Rate] [decimal](3, 0) NULL,
	[Forecast_Type] [nvarchar](255) NULL,
	[Currency_ISO_Code] [nchar](3) NULL,
	[Under_FY(N-1)_Demand_Qty] [numeric](18, 0) NULL,
	[1Q_FY(N)_1-3_Demand_Qty] [numeric](18, 0) NULL,
	[2Q_FY(N)_4-6_Demand_Qty] [numeric](18, 0) NULL,
	[3Q_FY(N)_7-9_Demand_Qty] [numeric](18, 0) NULL,
	[4Q_FY(N)_10-12_Demand_Qty] [numeric](18, 0) NULL,
	[1H_FY(N+1)_Demand_Qty] [numeric](18, 0) NULL,
	[2H_FY(N+1)_Demand_Qty] [numeric](18, 0) NULL,
	[1H_FY(N+2)_Demand_Qty] [numeric](18, 0) NULL,
	[2H_FY(N+2)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+3)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+4)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+5)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+6)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+7)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+8)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+9)_Demand_Qty] [numeric](18, 0) NULL,
	[Over_FY(N+10)_Demand_Qty] [numeric](18, 0) NULL,
	[Asof_Current_RFY_Total_Quantity] [decimal](18, 0) NULL,
	[Under_FY(N-1)_Demand_Price] [numeric](37, 4) NULL,
	[1Q_FY(N)_1-3_Demand_Price] [numeric](37, 4) NULL,
	[2Q_FY(N)_4-6_Demand_Price] [numeric](37, 4) NULL,
	[3Q_FY(N)_7-9_Demand_Price] [numeric](37, 4) NULL,
	[4Q_FY(N)_10-12_Demand_Price] [numeric](37, 4) NULL,
	[1H_FY(N+1)_Demand_Price] [numeric](37, 4) NULL,
	[2H_FY(N+1)_Demand_Price] [numeric](37, 4) NULL,
	[1H_FY(N+2)_Demand_Price] [numeric](37, 4) NULL,
	[2H_FY(N+2)_Demand_Price] [numeric](37, 4) NULL,
	[FY(N+3)_Demand_Price] [numeric](37, 4) NULL,
	[FY(N+4)_Demand_Price] [numeric](37, 4) NULL,
	[FY(N+5)_Demand_Price] [numeric](37, 4) NULL,
	[FY(N+6)_Demand_Price] [numeric](37, 4) NULL,
	[FY(N+7)_Demand_Price] [numeric](37, 4) NULL,
	[FY(N+8)_Demand_Price] [numeric](37, 4) NULL,
	[FY(N+9)_Demand_Price] [numeric](37, 4) NULL,
	[Over_FY(N+10)_Demand_Price] [numeric](37, 4) NULL,
	[Under_FY(N-1)_Demand_Amt] [numeric](38, 4) NULL,
	[1Q_FY(N)_1-3_Demand_Amt] [numeric](38, 4) NULL,
	[2Q_FY(N)_4-6_Demand_Amt] [numeric](38, 4) NULL,
	[3Q_FY(N)_7-9_Demand_Amt] [numeric](38, 4) NULL,
	[4Q_FY(N)_10-12_Demand_Amt] [numeric](38, 4) NULL,
	[1H_FY(N+1)_Demand_Amt] [numeric](38, 4) NULL,
	[2H_FY(N+1)_Demand_Amt] [numeric](38, 4) NULL,
	[1H_FY(N+2)_Demand_Amt] [numeric](38, 4) NULL,
	[2H_FY(N+2)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+3)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+4)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+5)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+6)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+7)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+8)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+9)_Demand_Amt] [numeric](38, 4) NULL,
	[Over_FY(N+10)_Demand_Amt] [numeric](38, 4) NULL,
	[Asof_Current_RFY_Total_Amount] [decimal](18, 0) NULL,
	[Asof_Current_RFY_Total_GO_Amount] [decimal](18, 0) NULL,
	[Asof_Award_Approved_RFY_Total_Amount] [decimal](18, 0) NULL,
	[Delta_Amount_Current_and_Din] [decimal](18, 0) NULL,
	[LTQ_Remaining] [decimal](18, 0) NULL,
	[LTV_Remaining] [decimal](18, 0) NULL,
	[S0_Actual_Date] [datetime] NULL,
	[S1_Actual_Date] [datetime] NULL,
	[S2_Actual_Date] [datetime] NULL,
	[S3_Actual_Date] [datetime] NULL,
	[S4_Actual_Date] [datetime] NULL,
	[Created_Date] [datetime] NULL,
	[Dead_Date_Product] [datetime] NULL,
	[Dead_Reason] [nvarchar](255) NULL,
	[Dead_Reason_Code] [nchar](2) NULL,
	[Competitor1] [nvarchar](255) NULL,
	[Competitor2] [nvarchar](255) NULL,
	[Competitor3] [nvarchar](255) NULL,
	[Part_No] [varchar](40) NULL,
	[MCU_SOC_AP_KBN] [nvarchar](300) NULL,
	[Product_Family] [nvarchar](300) NULL,
	[CAT1] [nvarchar](40) NULL,
	[CAT1_Code] [nvarchar](2) NULL,
	[CAT2] [nvarchar](40) NULL,
	[CAT2_Code] [nvarchar](4) NULL,
	[CAT3] [nvarchar](40) NULL,
	[CAT3_Code] [nvarchar](6) NULL,
	[Booking_PN] [nvarchar](40) NULL,
	[Booking_PN_White40] [nvarchar](40) NULL,
	[Sales_Order_PN_Dummy_Flag] [nvarchar](1) NULL,
	[Order_Product_Status] [nvarchar](100) NULL,
	[PN_Type] [nvarchar](2) NULL,
	[EOL_POLICY_TYPE] [nvarchar](300) NULL,
	[PCN_Status] [nvarchar](3) NULL,
	[Pricing_PN] [nvarchar](32) NULL,
	[Renesas_PN] [nvarchar](30) NULL,
	[Process_Name_for_Summary] [nvarchar](300) NULL,
	[In_MP_Clarified_POR_from_BU] [nchar](1) NULL,
	[PPAP_Due_Date] [date] NULL,
	[Automotive_OEM] [nvarchar](255) NULL,
	[Start_Month_of_Customer_FY_Code] [nchar](2) NULL,
	[NDA] [nvarchar](1) NULL,
	[BF_Channel] [nvarchar](300) NULL,
	[Customer_Grp1] [nvarchar](300) NULL,
	[End_Customer] [nvarchar](10) NULL,
	[NIKKEI_WW_FLG] [nvarchar](300) NULL,
	[Receipt_Agent] [nvarchar](60) NULL,
	[Receipt_Unit] [nvarchar](60) NULL,
	[Receipt_Division] [nvarchar](60) NULL,
	[Receipt_Dept] [nvarchar](60) NULL,
	[Receipt_Section] [nvarchar](60) NULL,
	[Region] [nvarchar](300) NULL,
	[REL_Sales_Department] [nvarchar](60) NULL,
	[Sales_Planning_Grp] [nvarchar](300) NULL,
	[SCM_Customer_Code] [nvarchar](10) NULL,
	[SCM_Customer] [nvarchar](20) NULL,
	[Design_SCM_Customer_Dummy_Flag] [nvarchar](1) NULL,
	[Fulfillment_Region] [nvarchar](255) NULL,
	[Fulfillment_SCM_Customer] [varchar](20) NULL,
	[User_Last_Modified_Date_Product] [datetime] NULL,
	[Opportunity_Owner] [nvarchar](4000) NULL,
	[Opportunity_Owner_Company] [nvarchar](80) NULL,
	[Opportunity_Owner_Email] [nvarchar](128) NULL,
	[Design_Group_Unit] [nvarchar](60) NULL,
	[Design_Group_Division] [nvarchar](60) NULL,
	[Design_Group_Department] [nvarchar](60) NULL,
	[Revenue_Recognition_BU_Unit] [nvarchar](300) NULL,
	[Revenue_Recognition_BU_Division] [nvarchar](300) NULL,
	[Revenue_Recognition_BU_Department] [nvarchar](300) NULL,
	[Revenue_Recognition_BU_Section] [nvarchar](300) NULL,
	[CALENDAR_YEAR_MONTH_DATE] [date] NULL
) ON [BI_DM_Fact_NonPartition]
WITH
(
DATA_COMPRESSION = PAGE
)
GO
SET ANSI_PADDING ON
GO
CREATE CLUSTERED INDEX [I_F_SFM_OPPORTUNITY_DETAIL_L] ON [dbo].[F_SFM_OPPORTUNITY_DETAIL_L]
(
	[Opportunity] DESC,
	[Unique_Opportunity_Seq] ASC,
	[Conversion_Currency] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Fact_NonPartition]
GO
