USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VF_SAL_BACKLOG_nonEXCH] AS
SELECT
  [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, [RDLV_DIFF]
, SUM([TO_AMT_JPY]) AS [TO_AMT_JPY]
, SUM([TO_AMT_NET]) AS [TO_AMT_NET]
, SUM([TO_ANP_AMT_NET]) AS [TO_ANP_AMT_NET]
, SUM([TO_AMT_STD]) AS [TO_AMT_STD]
, SUM([TO_QTY]) AS [TO_QTY]
, SUM([GO_AMT_JPY]) AS [GO_AMT_JPY]
, SUM([GO_AMT_NET]) AS [GO_AMT_NET]
, SUM([GO_ANP_AMT_NET]) AS [GO_ANP_AMT_NET]
, SUM([GO_AMT_STD]) AS [GO_AMT_STD]
, SUM([GO_QTY]) AS [GO_QTY]
, SUM([SO_AMT_JPY]) AS [SO_AMT_JPY]
, SUM([SO_AMT_NET]) AS [SO_AMT_NET]
, SUM([SO_AMT_STD]) AS [SO_AMT_STD]
, SUM([SO_QTY]) AS [SO_QTY]
, SUM([TO_REALISTIC_AMT_JPY]) AS [TO_REALISTIC_AMT_JPY]
, SUM([TO_REALISTIC_AMT_NET]) AS [TO_REALISTIC_AMT_NET]
, SUM([TO_REALISTIC_ANP_AMT_NET]) AS [TO_REALISTIC_ANP_AMT_NET]
, SUM([TO_REALISTIC_AMT_STD]) AS [TO_REALISTIC_AMT_STD]
, SUM([TO_REALISTIC_QTY]) AS [TO_REALISTIC_QTY]
, SUM([GO_REALISTIC_AMT_JPY]) AS [GO_REALISTIC_AMT_JPY]
, SUM([GO_REALISTIC_AMT_NET]) AS [GO_REALISTIC_AMT_NET]
, SUM([GO_REALISTIC_ANP_AMT_NET]) AS [GO_REALISTIC_ANP_AMT_NET]
, SUM([GO_REALISTIC_AMT_STD]) AS [GO_REALISTIC_AMT_STD]
, SUM([GO_REALISTIC_QTY]) AS [GO_REALISTIC_QTY]
, SUM([SO_REALISTIC_AMT_JPY]) AS [SO_REALISTIC_AMT_JPY]
, SUM([SO_REALISTIC_AMT_NET]) AS [SO_REALISTIC_AMT_NET]
, SUM([SO_REALISTIC_AMT_STD]) AS [SO_REALISTIC_AMT_STD]
, SUM([SO_REALISTIC_QTY]) AS [SO_REALISTIC_QTY]
, SUM([TO_PLANNED_AMT_JPY]) AS [TO_PLANNED_AMT_JPY]
, SUM([TO_PLANNED_AMT_NET]) AS [TO_PLANNED_AMT_NET]
, SUM([TO_PLANNED_ANP_AMT_NET]) AS [TO_PLANNED_ANP_AMT_NET]
, SUM([TO_PLANNED_AMT_STD]) AS [TO_PLANNED_AMT_STD]
, SUM([TO_PLANNED_QTY]) AS [TO_PLANNED_QTY]
, SUM([GO_PLANNED_AMT_JPY]) AS [GO_PLANNED_AMT_JPY]
, SUM([GO_PLANNED_AMT_NET]) AS [GO_PLANNED_AMT_NET]
, SUM([GO_PLANNED_ANP_AMT_NET]) AS [GO_PLANNED_ANP_AMT_NET]
, SUM([GO_PLANNED_AMT_STD]) AS [GO_PLANNED_AMT_STD]
, SUM([GO_PLANNED_QTY]) AS [GO_PLANNED_QTY]
, SUM([SO_PLANNED_AMT_JPY]) AS [SO_PLANNED_AMT_JPY]
, SUM([SO_PLANNED_AMT_NET]) AS [SO_PLANNED_AMT_NET]
, SUM([SO_PLANNED_AMT_STD]) AS [SO_PLANNED_AMT_STD]
, SUM([SO_PLANNED_QTY]) AS [SO_PLANNED_QTY]
, SUM([TO_INITIAL_AMT_JPY]) AS [TO_INITIAL_AMT_JPY]
, SUM([TO_INITIAL_AMT_NET]) AS [TO_INITIAL_AMT_NET]
, SUM([TO_INITIAL_ANP_AMT_NET]) AS [TO_INITIAL_ANP_AMT_NET]
, SUM([TO_INITIAL_AMT_STD]) AS [TO_INITIAL_AMT_STD]
, SUM([TO_INITIAL_QTY]) AS [TO_INITIAL_QTY]
, SUM([GO_INITIAL_AMT_JPY]) AS [GO_INITIAL_AMT_JPY]
, SUM([GO_INITIAL_AMT_NET]) AS [GO_INITIAL_AMT_NET]
, SUM([GO_INITIAL_ANP_AMT_NET]) AS [GO_INITIAL_ANP_AMT_NET]
, SUM([GO_INITIAL_AMT_STD]) AS [GO_INITIAL_AMT_STD]
, SUM([GO_INITIAL_QTY]) AS [GO_INITIAL_QTY]
, SUM([SO_INITIAL_AMT_JPY]) AS [SO_INITIAL_AMT_JPY]
, SUM([SO_INITIAL_AMT_NET]) AS [SO_INITIAL_AMT_NET]
, SUM([SO_INITIAL_AMT_STD]) AS [SO_INITIAL_AMT_STD]
, SUM([SO_INITIAL_QTY]) AS [SO_INITIAL_QTY]
FROM (
   SELECT [TUSR_T_TO_BKLG].[SCM_CUSTOMER]           AS [SCM_CUSTOMER_CD]
        , [TUSR_T_TO_BKLG].[BOOKING_PN_CD]          AS[ORDER_PART_NO_CD]
        , [TUSR_T_TO_BKLG].[SEG_CD]
        , [TUSR_T_TO_BKLG].[CURRENCY]
        , [TUSR_T_TO_BKLG].[RECORD_REGISTRATION_DATE]          AS [RECORD_DATE]
        , [TUSR_T_TO_BKLG].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_TO_BKLG].[REQUEST_DATE]              AS [RDLV_DATE]
        , [TUSR_T_TO_BKLG].[REQUEST_DIFF_TYPE]      AS [RDLV_DIFF]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_ANP_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST([TUSR_T_TO_BKLG].[TO_BKLG_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(20,4))
          END                                       AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_TO_BKLG]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_TO_BKLG].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]
   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')

UNION ALL

   SELECT [TUSR_T_GO_BKLG].[SCM_CUSTOMER]           AS [SCM_CUSTOMER_CD]
        , [TUSR_T_GO_BKLG].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_GO_BKLG].[SEG_CD]
        , [TUSR_T_GO_BKLG].[CURRENCY]
        , [TUSR_T_GO_BKLG].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_GO_BKLG].[BOOKING_DATE]           AS [ORDER_DATE]
        , [TUSR_T_GO_BKLG].[REQUEST_DATE]           AS [RDLV_DATE]
        , [TUSR_T_GO_BKLG].[REQUEST_DIFF_TYPE]      AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [GO_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [GO_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_ANP_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [GO_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [GO_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST([TUSR_T_GO_BKLG].[GO_BKLG_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(20,4))
          END                                       AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_GO_BKLG]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_GO_BKLG].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]
   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')

UNION ALL

   SELECT [TUSR_T_SO_BKLG].[SCM_CUSTOMER]           AS [SCM_CUSTOMER_CD]
        , [TUSR_T_SO_BKLG].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_SO_BKLG].[SEG_CD]
        , [TUSR_T_SO_BKLG].[CURRENCY]
        , [TUSR_T_SO_BKLG].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_SO_BKLG].[BOOKING_DATE]           AS [ORDER_DATE]
        , [TUSR_T_SO_BKLG].[REQUEST_DATE]           AS [RDLV_DATE]
        , [TUSR_T_SO_BKLG].[REQUEST_DIFF_TYPE]      AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [SO_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [SO_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [SO_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST([TUSR_T_SO_BKLG].[SO_BKLG_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(20,4))
          END                                       AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_SO_BKLG]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_SO_BKLG].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]
   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
UNION ALL

 SELECT [TUSR_T_TO_BKLG_C].[SCM_CUSTOMER]             AS [SCM_CUSTOMER_CD]
        , [TUSR_T_TO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_TO_BKLG_C].[SEG_CD]
        , [TUSR_T_TO_BKLG_C].[CURRENCY]
        , [TUSR_T_TO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_TO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_TO_BKLG_C].[ZZKAIRE]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_REALISTIC_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_REALISTIC_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_ANP_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_REALISTIC_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_REALISTIC_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(20,4))
          END                                       AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_TO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_TO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]

   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_TO_BKLG_C].[ZZKAIRE] IS NOT NULL
UNION ALL

 SELECT [TUSR_T_GO_BKLG_C].[SCM_CUSTOMER]             AS [SCM_CUSTOMER_CD]
        , [TUSR_T_GO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_GO_BKLG_C].[SEG_CD]
        , [TUSR_T_GO_BKLG_C].[CURRENCY]
        , [TUSR_T_GO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_GO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_GO_BKLG_C].[ZZKAIRE]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_REALISTIC_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_REALISTIC_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_ANP_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_REALISTIC_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_REALISTIC_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(22,3))
           END AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_GO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_GO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]
   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_GO_BKLG_C].[ZZKAIRE] IS NOT NULL
UNION ALL

   SELECT [TUSR_T_SO_BKLG_C].[SCM_CUSTOMER]           AS [SCM_CUSTOMER_CD]
        , [TUSR_T_SO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_SO_BKLG_C].[SEG_CD]
        , [TUSR_T_SO_BKLG_C].[CURRENCY]
        , [TUSR_T_SO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_SO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_SO_BKLG_C].[ZZKAIRE]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END  AS [SO_REALISTIC_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [SO_REALISTIC_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [SO_REALISTIC_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(22,3))
           END AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_SO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_SO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]

   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_SO_BKLG_C].[ZZKAIRE] IS NOT NULL

UNION ALL

 SELECT [TUSR_T_TO_BKLG_C].[SCM_CUSTOMER]             AS [SCM_CUSTOMER_CD]
        , [TUSR_T_TO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_TO_BKLG_C].[SEG_CD]
        , [TUSR_T_TO_BKLG_C].[CURRENCY]
        , [TUSR_T_TO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_TO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_TO_BKLG_C].[ZZKAIPR]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_PLANNED_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_PLANNED_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_ANP_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_PLANNED_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_PLANNED_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(20,4))
          END                                       AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_TO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_TO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]

   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_TO_BKLG_C].[ZZKAIPR] IS NOT NULL
UNION ALL

 SELECT [TUSR_T_GO_BKLG_C].[SCM_CUSTOMER]             AS [SCM_CUSTOMER_CD]
        , [TUSR_T_GO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_GO_BKLG_C].[SEG_CD]
        , [TUSR_T_GO_BKLG_C].[CURRENCY]
        , [TUSR_T_GO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_GO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_GO_BKLG_C].[ZZKAIPR]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_PLANNED_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_PLANNED_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_ANP_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_PLANNED_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_PLANNED_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(22,3))
           END AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_GO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_GO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]
   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_GO_BKLG_C].[ZZKAIPR] IS NOT NULL
UNION ALL

   SELECT [TUSR_T_SO_BKLG_C].[SCM_CUSTOMER]           AS [SCM_CUSTOMER_CD]
        , [TUSR_T_SO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_SO_BKLG_C].[SEG_CD]
        , [TUSR_T_SO_BKLG_C].[CURRENCY]
        , [TUSR_T_SO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_SO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_SO_BKLG_C].[ZZKAIPR]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END  AS [SO_PLANNED_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [SO_PLANNED_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [SO_PLANNED_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(22,3))
           END AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_SO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_SO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]

   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_SO_BKLG_C].[ZZKAIPR] IS NOT NULL
   
UNION ALL

 SELECT [TUSR_T_TO_BKLG_C].[SCM_CUSTOMER]             AS [SCM_CUSTOMER_CD]
        , [TUSR_T_TO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_TO_BKLG_C].[SEG_CD]
        , [TUSR_T_TO_BKLG_C].[CURRENCY]
        , [TUSR_T_TO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_TO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_TO_BKLG_C].[ZZKAIIN]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_INITIAL_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_INITIAL_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_ANP_AMT] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_INITIAL_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
          END                                       AS [TO_INITIAL_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST([TUSR_T_TO_BKLG_C].[TO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(20,4))
          END                                       AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_TO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_TO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]

   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_TO_BKLG_C].[ZZKAIIN] IS NOT NULL
UNION ALL

 SELECT [TUSR_T_GO_BKLG_C].[SCM_CUSTOMER]             AS [SCM_CUSTOMER_CD]
        , [TUSR_T_GO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_GO_BKLG_C].[SEG_CD]
        , [TUSR_T_GO_BKLG_C].[CURRENCY]
        , [TUSR_T_GO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_GO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_GO_BKLG_C].[ZZKAIIN]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_INITIAL_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_INITIAL_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_ANP_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_ANP_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_INITIAL_ANP_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [GO_INITIAL_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST ([TUSR_T_GO_BKLG_C].[GO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(22,3))
           END AS [GO_INITIAL_QTY]
        , 0 AS [SO_INITIAL_AMT_JPY]
        , 0 AS [SO_INITIAL_AMT_NET]
        , 0 AS [SO_INITIAL_AMT_STD]
        , 0 AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_GO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_GO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]
   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_GO_BKLG_C].[ZZKAIIN] IS NOT NULL
UNION ALL

   SELECT [TUSR_T_SO_BKLG_C].[SCM_CUSTOMER]           AS [SCM_CUSTOMER_CD]
        , [TUSR_T_SO_BKLG_C].[BOOKING_PN_CD]          AS [ORDER_PART_NO_CD]
        , [TUSR_T_SO_BKLG_C].[SEG_CD]
        , [TUSR_T_SO_BKLG_C].[CURRENCY]
        , [TUSR_T_SO_BKLG_C].[REGISTRATION_DATE]      AS [RECORD_DATE]
        , [TUSR_T_SO_BKLG_C].[BOOK_DATE]              AS [ORDER_DATE]
        , [TUSR_T_SO_BKLG_C].[ZZKAIIN]                AS [RDLV_DATE]
        , 0 AS [RDLV_DIFF]
        , 0 AS [TO_AMT_JPY]
        , 0 AS [TO_AMT_NET]
        , 0 AS [TO_ANP_AMT_NET]
        , 0 AS [TO_AMT_STD]
        , 0 AS [TO_QTY]
        , 0 AS [GO_AMT_JPY]
        , 0 AS [GO_AMT_NET]
        , 0 AS [GO_ANP_AMT_NET]
        , 0 AS [GO_AMT_STD]
        , 0 AS [GO_QTY]
        , 0 AS [SO_AMT_JPY]
        , 0 AS [SO_AMT_NET]
        , 0 AS [SO_AMT_STD]
        , 0 AS [SO_QTY]
        , 0 AS [TO_REALISTIC_AMT_JPY]
        , 0 AS [TO_REALISTIC_AMT_NET]
        , 0 AS [TO_REALISTIC_ANP_AMT_NET]
        , 0 AS [TO_REALISTIC_AMT_STD]
        , 0 AS [TO_REALISTIC_QTY]
        , 0 AS [GO_REALISTIC_AMT_JPY]
        , 0 AS [GO_REALISTIC_AMT_NET]
        , 0 AS [GO_REALISTIC_ANP_AMT_NET]
        , 0 AS [GO_REALISTIC_AMT_STD]
        , 0 AS [GO_REALISTIC_QTY]
        , 0 AS [SO_REALISTIC_AMT_JPY]
        , 0 AS [SO_REALISTIC_AMT_NET]
        , 0 AS [SO_REALISTIC_AMT_STD]
        , 0 AS [SO_REALISTIC_QTY]
        , 0 AS [TO_PLANNED_AMT_JPY]
        , 0 AS [TO_PLANNED_AMT_NET]
        , 0 AS [TO_PLANNED_ANP_AMT_NET]
        , 0 AS [TO_PLANNED_AMT_STD]
        , 0 AS [TO_PLANNED_QTY]
        , 0 AS [GO_PLANNED_AMT_JPY]
        , 0 AS [GO_PLANNED_AMT_NET]
        , 0 AS [GO_PLANNED_ANP_AMT_NET]
        , 0 AS [GO_PLANNED_AMT_STD]
        , 0 AS [GO_PLANNED_QTY]
        , 0 AS [SO_PLANNED_AMT_JPY]
        , 0 AS [SO_PLANNED_AMT_NET]
        , 0 AS [SO_PLANNED_AMT_STD]
        , 0 AS [SO_PLANNED_QTY]
        , 0 AS [TO_INITIAL_AMT_JPY]
        , 0 AS [TO_INITIAL_AMT_NET]
        , 0 AS [TO_INITIAL_ANP_AMT_NET]
        , 0 AS [TO_INITIAL_AMT_STD]
        , 0 AS [TO_INITIAL_QTY]
        , 0 AS [GO_INITIAL_AMT_JPY]
        , 0 AS [GO_INITIAL_AMT_NET]
        , 0 AS [GO_INITIAL_ANP_AMT_NET]
        , 0 AS [GO_INITIAL_AMT_STD]
        , 0 AS [GO_INITIAL_QTY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END  AS [SO_INITIAL_AMT_JPY]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_AMT] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [SO_INITIAL_AMT_NET]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_STDCST_AMT_JPY] AS MONEY)
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_STDCST_AMT_JPY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[AMT_PM_DIV] AS MONEY)
           END AS [SO_INITIAL_AMT_STD]
        , CASE
              WHEN [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE] IS NULL THEN
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_QTY] AS DECIMAL(20,4))
          ELSE
                   CAST ([TUSR_T_SO_BKLG_C].[SO_COMMIT_QTY] * [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[QTY_PM_DIV] AS DECIMAL(22,3))
           END AS [SO_INITIAL_QTY]
   FROM [DM_SALES].[dbo].[TUSR_T_SO_BKLG_C]
   LEFT JOIN [DM_MST].[dbo].[TPRC_SDM_EX_DOC_TYPE_CATEGORY]
          ON [TUSR_T_SO_BKLG_C].[SOURCE_SYSTEM_DOC_TYPE] = [TPRC_SDM_EX_DOC_TYPE_CATEGORY].[SOURCE_SYSTEM_DOC_TYPE]

   WHERE (TPRC_SDM_EX_DOC_TYPE_CATEGORY.CUBE_LINK_FLG = '1')
   AND   [TUSR_T_SO_BKLG_C].[ZZKAIIN] IS NOT NULL

) BASE

GROUP BY [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, [RDLV_DIFF]

GO
