USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO









CREATE VIEW [dbo].[VF_RBW_MTF_H] AS
SELECT MTF_H.[OPPSEQ]
      ,MTF_H.[CUSTOMERCD]
      ,MTF_H.[CUSTOMERNAME]
      ,MTF_H.[PARTNO]
      ,MTF_H.[NBDIV]
      ,MTF_H.[FTCUSTOMERCD]
      ,MTF_H.[DINPLANDATE]
      ,MTF_H.[STAGEDIV]
      ,MTF_H.[OFFSHOREFLG]
      ,MTF_H.[STAGEDETAIL]
      ,MTF_H.[OPPNAME]
      ,MTF_H.[DAUGHTERPROJECTNAME]
      ,MTF_H.[DUPLILTVDIV]
      ,MST01.[VALUE_NAME] AS Rainbow_Duplication_txt
      ,MTF_H.[MTFRATE]
      ,MTF_H.[MTFDATADIV]
      ,MST02.[VALUE_NAME] AS MTF_Attribute_txt
      ,MTF_H.[GORESULTQTYPRE2H1]
      ,MTF_H.[GORESULTQTYPRE2H2]
      ,MTF_H.[GORESULTQTYPRE1H1]
      ,MTF_H.[GORESULTQTYPRE1H2]
      ,MTF_H.[GORESULTQTYCURH1]
      ,MTF_H.[GORESULTQTYCURH2]
      ,MTF_H.[GORESULTAMTPRE2H1]
      ,MTF_H.[GORESULTAMTPRE2H2]
      ,MTF_H.[GORESULTAMTPRE1H1]
      ,MTF_H.[GORESULTAMTPRE1H2]
      ,MTF_H.[GORESULTAMTCURH1]
      ,MTF_H.[GORESULTAMTCURH2]
      ,MTF_H.[QTYCURH1]
      ,MTF_H.[QTYCURH2]
      ,MTF_H.[QTYNEX1H1]
      ,MTF_H.[QTYNEX1H2]
      ,MTF_H.[QTYNEX2H1]
      ,MTF_H.[QTYNEX2H2]
      ,MTF_H.[QTYNEX3H1]
      ,MTF_H.[QTYNEX3H2]
      ,MTF_H.[QTYNEX4H1]
      ,MTF_H.[QTYNEX4H2]
      ,MTF_H.[QTYNEX5H1]
      ,MTF_H.[QTYNEX5H2]
      ,MTF_H.[QTYNEX6H1]
      ,MTF_H.[QTYNEX6H2]
      ,MTF_H.[QTYNEX7LATER]
      ,MTF_H.[AMTCURH1]
      ,MTF_H.[AMTCURH2]
      ,MTF_H.[AMTNEX1H1]
      ,MTF_H.[AMTNEX1H2]
      ,MTF_H.[AMTNEX2H1]
      ,MTF_H.[AMTNEX2H2]
      ,MTF_H.[AMTNEX3H1]
      ,MTF_H.[AMTNEX3H2]
      ,MTF_H.[AMTNEX4H1]
      ,MTF_H.[AMTNEX4H2]
      ,MTF_H.[AMTNEX5H1]
      ,MTF_H.[AMTNEX5H2]
      ,MTF_H.[AMTNEX6H1]
      ,MTF_H.[AMTNEX6H2]
      ,MTF_H.[AMTNEX7LATER]
      ,MTF_H.[DATADATE]
      ,MTF_H.[COMPANYG2CD]
      ,MTF_H.[COMPANYG2NAME]
      ,MTF_H.[COMPANYG2SORTKEY]
      ,MTF_H.[COMPANYG1CD]
      ,MTF_H.[COMPANYG1NAME]
      ,MTF_H.[COMPANYG1SORTKEY]
      ,MTF_H.[COUNTRYCD]
      ,MTF_H.[COUNTRYNAME]
      ,MTF_H.[COUNTRYSORTKEY]
      ,MTF_H.[AREACD]
      ,MTF_H.[AREANAME]
      ,MTF_H.[AREASORTKEY]
      ,MTF_H.[OVERSEASFLG]
      ,MTF_H.[PRODFAMILYCD]
      ,MTF_H.[PRODFAMILYNAME]
      ,MTF_H.[PRODGROUPCD]
      ,MTF_H.[PRODGROUPNAME]
      ,MTF_H.[AUTOGPDIV]
      ,MTF_H.[UPDATE_DATE]
	  ,'0' AS [LATEST_FLG]
FROM [BI_DM].[dbo].[F_RBW_MTF_H] AS MTF_H
INNER JOIN 
(SELECT [CODE_NAME],[CODE_VALUE],[VALUE_NAME]
 FROM [BI_DM].[dbo].[M_CRM_MST]
 WHERE [CODE_ID] = 'C001') MST01
ON MTF_H.[DUPLILTVDIV] = MST01.[CODE_VALUE]
INNER JOIN
(SELECT [CODE_NAME],[CODE_VALUE],[VALUE_NAME]
 FROM [BI_DM].[dbo].[M_CRM_MST]
 WHERE [CODE_ID] = 'C002') MST02
ON MTF_H.[MTFDATADIV] = MST02.[CODE_VALUE]
WHERE MTF_H.[OPPSEQ] is not null
AND MTF_H.DUPLILTVDIV in (1,4)
UNION ALL
SELECT MTF_L.[OPPSEQ]
      ,MTF_L.[CUSTOMERCD]
      ,MTF_L.[CUSTOMERNAME]
      ,MTF_L.[PARTNO]
      ,MTF_L.[NBDIV]
      ,MTF_L.[FTCUSTOMERCD]
      ,MTF_L.[DINPLANDATE]
      ,MTF_L.[STAGEDIV]
      ,MTF_L.[OFFSHOREFLG]
      ,MTF_L.[STAGEDETAIL]
      ,MTF_L.[OPPNAME]
      ,MTF_L.[DAUGHTERPROJECTNAME]
      ,MTF_L.[DUPLILTVDIV]
      ,MST01.[VALUE_NAME]
      ,MTF_L.[MTFRATE]
      ,MTF_L.[MTFDATADIV]
      ,MST02.[VALUE_NAME]
      ,MTF_L.[GORESULTQTYPRE2H1]
      ,MTF_L.[GORESULTQTYPRE2H2]
      ,MTF_L.[GORESULTQTYPRE1H1]
      ,MTF_L.[GORESULTQTYPRE1H2]
      ,MTF_L.[GORESULTQTYCURH1]
      ,MTF_L.[GORESULTQTYCURH2]
      ,MTF_L.[GORESULTAMTPRE2H1]
      ,MTF_L.[GORESULTAMTPRE2H2]
      ,MTF_L.[GORESULTAMTPRE1H1]
      ,MTF_L.[GORESULTAMTPRE1H2]
      ,MTF_L.[GORESULTAMTCURH1]
      ,MTF_L.[GORESULTAMTCURH2]
      ,MTF_L.[QTYCURH1]
      ,MTF_L.[QTYCURH2]
      ,MTF_L.[QTYNEX1H1]
      ,MTF_L.[QTYNEX1H2]
      ,MTF_L.[QTYNEX2H1]
      ,MTF_L.[QTYNEX2H2]
      ,MTF_L.[QTYNEX3H1]
      ,MTF_L.[QTYNEX3H2]
      ,MTF_L.[QTYNEX4H1]
      ,MTF_L.[QTYNEX4H2]
      ,MTF_L.[QTYNEX5H1]
      ,MTF_L.[QTYNEX5H2]
      ,MTF_L.[QTYNEX6H1]
      ,MTF_L.[QTYNEX6H2]
      ,MTF_L.[QTYNEX7LATER]
      ,MTF_L.[AMTCURH1]
      ,MTF_L.[AMTCURH2]
      ,MTF_L.[AMTNEX1H1]
      ,MTF_L.[AMTNEX1H2]
      ,MTF_L.[AMTNEX2H1]
      ,MTF_L.[AMTNEX2H2]
      ,MTF_L.[AMTNEX3H1]
      ,MTF_L.[AMTNEX3H2]
      ,MTF_L.[AMTNEX4H1]
      ,MTF_L.[AMTNEX4H2]
      ,MTF_L.[AMTNEX5H1]
      ,MTF_L.[AMTNEX5H2]
      ,MTF_L.[AMTNEX6H1]
      ,MTF_L.[AMTNEX6H2]
      ,MTF_L.[AMTNEX7LATER]
      ,MTF_L.[DATADATE]
      ,MTF_L.[COMPANYG2CD]
      ,MTF_L.[COMPANYG2NAME]
      ,MTF_L.[COMPANYG2SORTKEY]
      ,MTF_L.[COMPANYG1CD]
      ,MTF_L.[COMPANYG1NAME]
      ,MTF_L.[COMPANYG1SORTKEY]
      ,MTF_L.[COUNTRYCD]
      ,MTF_L.[COUNTRYNAME]
      ,MTF_L.[COUNTRYSORTKEY]
      ,MTF_L.[AREACD]
      ,MTF_L.[AREANAME]
      ,MTF_L.[AREASORTKEY]
      ,MTF_L.[OVERSEASFLG]
      ,MTF_L.[PRODFAMILYCD]
      ,MTF_L.[PRODFAMILYNAME]
      ,MTF_L.[PRODGROUPCD]
      ,MTF_L.[PRODGROUPNAME]
      ,MTF_L.[AUTOGPDIV]
      ,MTF_L.[UPDATE_DATE]
      ,'1'
FROM [BI_DM].[dbo].[F_RBW_MTF_L] AS MTF_L
INNER JOIN 
(SELECT [CODE_NAME],[CODE_VALUE],[VALUE_NAME]
 FROM [BI_DM].[dbo].[M_CRM_MST]
 WHERE [CODE_ID] = 'C001') MST01
ON MTF_L.[DUPLILTVDIV] = MST01.[CODE_VALUE]
INNER JOIN
(SELECT [CODE_NAME],[CODE_VALUE],[VALUE_NAME]
 FROM [BI_DM].[dbo].[M_CRM_MST]
 WHERE [CODE_ID] = 'C002') MST02
ON MTF_L.[MTFDATADIV] = MST02.[CODE_VALUE]
WHERE MTF_L.[OPPSEQ] is not null
AND MTF_L.DUPLILTVDIV in (1,4)









GO
