USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_VD_SFM_BCCV_D_IN_TARGET_PRD_H_CRM](
	[OPPORTUNITY_SEQ] [nvarchar](80) NOT NULL,
	[SCM_CUSTOMER_CODE] [nvarchar](20) NOT NULL,
	[D_IN_TARGET_YEAR] [nvarchar](7) NOT NULL,
	[D_IN_INPUT_YEAR] [nvarchar](7) NOT NULL,
	[D_IN_TARGET_PROBABILITY] [nvarchar](10) NULL,
	[APPLICATION1_CODE] [nvarchar](1) NULL,
	[APPLICATION2_CODE] [nvarchar](2) NULL,
	[APPLICATION3_CODE] [nvarchar](3) NULL,
	[PART_NO] [nvarchar](40) NULL,
	[CURRENCY_ISO_CODE] [nvarchar](3) NULL,
	[UPDATE_DATE] [date] NULL
) ON [BI_DM_Dimension]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_M_VD_SFM_BCCV_D_IN_TARGET_PRD_H_CRM_1] ON [dbo].[M_VD_SFM_BCCV_D_IN_TARGET_PRD_H_CRM]
(
	[OPPORTUNITY_SEQ] ASC,
	[SCM_CUSTOMER_CODE] ASC,
	[D_IN_TARGET_YEAR] ASC,
	[D_IN_INPUT_YEAR] ASC,
	[UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
GO
