USE [BI_DM]
GO
/****** Object:  View [dbo].[VT_SFM_OPP_PRD_DEMAND_H]    Script Date: 2017/02/27 11:19:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VT_SFM_OPP_PRD_DEMAND_H] AS
SELECT
   OPPORTUNITY_SEQ
  ,OPPORTUNITY_NO
  ,OPPORTUNITY_SEQ_PRD
  ,STAGE
  ,D_IN_SCM_CUST_CODE_FOR_MTF
  ,D_IN_SCM_CUST_CODE_FOR_SCM_OPE
  ,B_WIN_SCM_CUSTOMER_CODE
  ,SALES_ORDER_PN_FOR_MTF
  ,SALES_ORDER_PN_FOR_SCM_OPE
  ,OPP_APPLICATION3_CODE
  ,PRD_APPLICATION3_CODE
  ,CHANNEL_PARTNER_CODE
  ,CHANNEL_PARTNER_NAME
  ,STATUS
  ,CASE WHEN TARGET_NOMINATION_DATE IS NULL THEN TARGET_NOMINATION_DATE
   ELSE CAST((TARGET_NOMINATION_DATE + '/01') AS DATE)
   END AS TARGET_NOMINATION_DATE
  ,CASE WHEN TARGET_AWARD_DATE IS NULL THEN TARGET_AWARD_DATE
   ELSE CAST((TARGET_AWARD_DATE + '/01') AS DATE)
   END AS TARGET_AWARD_DATE
--LatestキューブへのAggregate対応 遅 20181001 START
  ,CONVERT(DATE,APPROVED_DATE) AS APPROVED_DATE
  ,APPROVED_DATE AS APPROVED_DATE_SALES
--LatestキューブへのAggregate対応 遅 20181001 END
  ,D_IN_CONFIDENCE_LEVEL_PERCENT
  ,QTY_UNIT
  ,SHARE_PERCENT
  ,START_MONTH_OF_FISCAL_YEAR
  ,MP_START_MONTH
  ,ACCOUNT_GROUP_CODE
  ,ACCOUNT_NAME
  ,CURRENCY
  ,CURRENCY_TYPE 
  ,CALENDAR_YM
  ,QUANTITY_1PIECE
  ,PRICE
  ,AMOUNT
  ,AMOUNT_STD
  ,AMOUNT_GP
  ,ORIGINAL_QUANTITY_1PIECE
  ,ORIGINAL_AMOUNT
  ,UPDATE_DATE
  ,DISP_UPDATE_DATE
  ,LATEST_FLG
  ,TARGET_NOMINATION_DATE_D
  ,TARGET_AWARD_DATE_D
  ,OPP_APPLICATION1_CODE
  ,OPP_APPLICATION2_CODE
  ,MP_START_DATE
  ,CAMPAIGN_NAME
  ,LEAD_ID
  ,LEAD_NAME
  ,ANNUAL_DEMAND_LTV_TOTAL
  ,S0_ACTUAL_DATE
  ,DISCOVERY_DATE
  ,PROMOTION_DATE
  ,GP_AMOUNT
FROM
  [BI_DM].[dbo].[F_SFM_OPP_PRD_DEMAND_H]
UNION ALL
SELECT
   OPPORTUNITY_SEQ
  ,OPPORTUNITY_NO
  ,OPPORTUNITY_SEQ_PRD
  ,STAGE
  ,D_IN_SCM_CUST_CODE_FOR_MTF
  ,D_IN_SCM_CUST_CODE_FOR_SCM_OPE
  ,B_WIN_SCM_CUSTOMER_CODE
  ,SALES_ORDER_PN_FOR_MTF
  ,SALES_ORDER_PN_FOR_SCM_OPE
  ,OPP_APPLICATION3_CODE
  ,PRD_APPLICATION3_CODE
  ,CHANNEL_PARTNER_CODE
  ,CHANNEL_PARTNER_NAME
  ,STATUS
  ,CASE WHEN TARGET_NOMINATION_DATE IS NULL THEN TARGET_NOMINATION_DATE
   ELSE CAST((TARGET_NOMINATION_DATE + '/01') AS DATE)
   END AS TARGET_NOMINATION_DATE
  ,CASE WHEN TARGET_AWARD_DATE IS NULL THEN TARGET_AWARD_DATE
   ELSE CAST((TARGET_AWARD_DATE + '/01') AS DATE)
   END AS TARGET_AWARD_DATE
--LatestキューブへのAggregate対応 遅 20181001 START
  ,CONVERT(DATE,APPROVED_DATE) AS APPROVED_DATE
  ,APPROVED_DATE AS APPROVED_DATE_SALES
--LatestキューブへのAggregate対応 遅 20181001 END
  ,D_IN_CONFIDENCE_LEVEL_PERCENT
  ,QTY_UNIT
  ,SHARE_PERCENT
  ,START_MONTH_OF_FISCAL_YEAR
  ,MP_START_MONTH
  ,ACCOUNT_GROUP_CODE
  ,ACCOUNT_NAME
  ,CURRENCY
  ,CURRENCY_TYPE 
  ,CASE WHEN MONTH(CALENDAR_YM) IN ('1','4','7','10')
      THEN CAST(CAST(YEAR(CALENDAR_YM) AS VARCHAR) +'0101' AS DATE)
   ELSE CALENDAR_YM END AS CALENDAR_YM
  ,SUM(QUANTITY_1PIECE) AS QUANTITY_1PIECE
  ,MAX(PRICE) AS PRICE
  ,SUM(AMOUNT) AS AMOUNT
  ,SUM(AMOUNT_STD) AS AMOUNT_STD
  ,SUM(AMOUNT_GP) AS AMOUNT_GP
  ,SUM(ORIGINAL_QUANTITY_1PIECE) AS ORIGINAL_QUANTITY_1PIECE
  ,SUM(ORIGINAL_AMOUNT) AS ORIGINAL_AMOUNT
  ,UPDATE_DATE
  ,DISP_UPDATE_DATE
  ,LATEST_FLG
  ,TARGET_NOMINATION_DATE_D
  ,TARGET_AWARD_DATE_D
  ,OPP_APPLICATION1_CODE
  ,OPP_APPLICATION2_CODE
  ,MP_START_DATE
  ,CAMPAIGN_NAME
  ,LEAD_ID
  ,LEAD_NAME
  ,MAX(ANNUAL_DEMAND_LTV_TOTAL) AS ANNUAL_DEMAND_LTV_TOTAL
  ,S0_ACTUAL_DATE
  ,DISCOVERY_DATE
  ,PROMOTION_DATE
  ,SUM(GP_AMOUNT) AS GP_AMOUNT
FROM
  [BI_DM].[dbo].[F_SFM_OPP_PRD_DEMAND_L]
GROUP BY 
   OPPORTUNITY_SEQ
  ,OPPORTUNITY_NO
  ,OPPORTUNITY_SEQ_PRD
  ,STAGE
  ,D_IN_SCM_CUST_CODE_FOR_MTF
  ,D_IN_SCM_CUST_CODE_FOR_SCM_OPE
  ,B_WIN_SCM_CUSTOMER_CODE
  ,SALES_ORDER_PN_FOR_MTF
  ,SALES_ORDER_PN_FOR_SCM_OPE
  ,OPP_APPLICATION3_CODE
  ,PRD_APPLICATION3_CODE
  ,CHANNEL_PARTNER_CODE
  ,CHANNEL_PARTNER_NAME
  ,STATUS
  ,TARGET_NOMINATION_DATE
  ,TARGET_AWARD_DATE
--LatestキューブへのAggregate対応 遅 20181001 START
  ,CONVERT(DATE,APPROVED_DATE)
  ,APPROVED_DATE
--LatestキューブへのAggregate対応 遅 20181001 END
  ,D_IN_CONFIDENCE_LEVEL_PERCENT
  ,QTY_UNIT
  ,SHARE_PERCENT
  ,START_MONTH_OF_FISCAL_YEAR
  ,MP_START_MONTH
  ,ACCOUNT_GROUP_CODE
  ,ACCOUNT_NAME
  ,CURRENCY
  ,CURRENCY_TYPE 
  ,CASE WHEN MONTH(CALENDAR_YM) IN ('1','4','7','10')
      THEN CAST(CAST(YEAR(CALENDAR_YM) AS VARCHAR) +'0101' AS DATE)
   ELSE CALENDAR_YM END
  ,UPDATE_DATE
  ,DISP_UPDATE_DATE
  ,LATEST_FLG
  ,TARGET_NOMINATION_DATE_D
  ,TARGET_AWARD_DATE_D
  ,OPP_APPLICATION1_CODE
  ,OPP_APPLICATION2_CODE
  ,MP_START_DATE
  ,CAMPAIGN_NAME
  ,LEAD_ID
  ,LEAD_NAME
  ,S0_ACTUAL_DATE
  ,DISCOVERY_DATE
  ,PROMOTION_DATE



GO
