USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_SFM_OPP_PRD_DEMAND_GST](
	[OPPORTUNITY_SEQ] [nvarchar](13) NULL,
	[ANNUAL_DEMAND_LTV_TOTAL] [numeric](38, 4) NULL,
	[CURRENCY_TYPE] [nvarchar](14) NULL,
	[STAGE] [nvarchar](2) NULL,
	[APL1] [nvarchar](1) NULL,
	[OPEN_DEAD] [nvarchar](255) NULL,
	[CURRENT_LTV] [numeric](18, 0) NULL,
	[STATUS_UPDATE_DATE] [date] NULL,
	[S0_ACTUAL_DATE] [date] NULL,
	[TYPE_STAGE] [nvarchar](255) NULL,
	[TRACKING_TYPE] [nvarchar](255) NULL,
	[REGION] [nvarchar](255) NULL,
	[STAGE_TYPE_TXT] [nvarchar](255) NULL,
	[SECTION] [nvarchar](60) NULL,
	[CUSTGRP2] [nvarchar](300) NULL,
	[AFFECT_GST] [nvarchar](300) NULL
) ON [BI_DM_Fact_NonPartition]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_F_SFM_OPP_PRD_DEMAND_GST_1] ON [dbo].[F_SFM_OPP_PRD_DEMAND_GST]
(
	[OPPORTUNITY_SEQ] ASC,
	[STATUS_UPDATE_DATE] ASC,
	[S0_ACTUAL_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Fact_NonPartition]
GO
