USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VD_CMN_SCM_CUSTOMER]
AS
SELECT [SCM_CUSTOMER]                 AS [SCM_CUSTOMER_CD]
      ,[SCM_CUSTOMER_TXT_S]           AS [SCM_CUSTOMER_SNAME]
      ,[SCM_CUSTOMER_TXT_L]           AS [SCM_CUSTOMER_LNAME]
      ,[RECEIPT_RENESASGROUP]         AS [RCP_RENESAS_GR_CD]
      ,[RECEIPT_UNIT]                 AS [RCP_UNIT_CD]
      ,[RECEIPT_DIVISION]             AS [RCP_DIVISION_CD]
      ,[RECEIPT_DEPT]                 AS [RCP_DEPARTMENT_CD]
      ,[RECEIPT_SECTION]              AS [RCP_SECTION_CD]
      ,[RECEIPT_AGENT]                AS [RCP_AGENT_CD]
      ,[SCM_CUSTOMER_RANK]            AS [CSTMR_RANK_DIV]
      ,[SALES_RT1]                    AS [SA_AG_ROUTE_CD1]
      ,[SALES_RT2]                    AS [SA_AG_ROUTE_CD2]
    --20190409_KISê‹íèàƒ Start
      ,[BUSINESS_SITE_CD]             AS [BUSINESS_SITE_CD]
    --20190409_KISê‹íèàƒ End
      ,[SCM_CUSTOMER_PREFECTURE]      AS [SCM_PREF_CD]
      ,[SCM_CUSTOMER_COUNTRY]         AS [SCM_COUNTRY_CD]
      ,[SCM_CUSTOMER_AREA_1]          AS [SCM_AREA_1_CD]
      ,[SCM_CUSTOMER_AREA_2]          AS [SCM_AREA_2_CD]
      ,[SCM_CUSTOMER_AREA_3]          AS [SCM_AREA_3_CD]
      ,[SCM_PARENT_CORP_CD_SFM]       AS [SFM_HIGH_CSTM_CD]
      ,[SCM_PARENT_CORP_COUNTRY_SFM]  AS [SFM_COUNTRY_CD]
      ,[SCM_PARENT_CORP_AREA_1_SFM]   AS [SFM_AREA_1_CD]
      ,[SCM_PARENT_CORP_AREA_2_SFM]   AS [SFM_AREA_2_CD]
      ,[SCM_PARENT_CORP_AREA_3_SFM]   AS [SFM_AREA_3_CD]
      ,[SCM_PARENT_CORP_CD_CORP]      AS [HJN_HIGH_CORP_CD]
      ,[SCM_PARENT_CORP_COUNTRY_CORP] AS [HJN_COUNTRY_CD]
      ,[SCM_PARENT_CORP_AREA_1_CORP]  AS [HJN_AREA_1_CD]
      ,[SCM_PARENT_CORP_AREA_2_CORP]  AS [HJN_AREA_2_CD]
      ,[SCM_PARENT_CORP_AREA_3_CORP]  AS [HJN_AREA_3_CD]
      ,[SCM_PARENT_CORP_CD_GRP]       AS [CGR_HIGH_CORP_CD]
      ,[PRICE_CODE]                   AS [PRICE_DIV]
      ,[AGENT_LOCATION]               AS [AGENT_LOC_DIV]
      ,[END_CUST_CD_CORP]             AS [HI_CORP_CD]
      ,[INTERNALFLG]                  AS [TOTAL_AX_CD2]
      ,[REL_SALES_SITE]               AS [SALES_BUSINESS_SITE_CD]
      ,[REL_SALES_UNIT]               AS [SALES_UNIT_CD]
      ,[REL_SALES_DIVISION]           AS [SALES_DIVISION_CD]
      ,[REL_SALES_DEPARTMENT]         AS [SALES_DEPARTMENT_CD]
      ,[REL_SALES_SECTION]            AS [SALES_SECTION_CD]
      ,[CUSTOMER_GRP1]                AS [Customer_Grp1Name]
      ,[CUSTOMER_GRP2]                AS [Customer_Grp2Name]
      ,[CUSTOMER_GRPCOUNTRY]          AS [Customer_GrpCountry]
      ,[NIKKEI_WW_FLG]                AS [NIKKEI_WW_FLG]
      ,[SALES_PLANNING_GRP]           AS [Sales_Planning_Grp]
      ,[BF_CHANNEL]                   AS [BF_Channel]
      ,[RECEIPT_RENESASGROUP_TXT]     AS [RCP_RENESAS_GR_SNAME]
      ,[RECEIPT_UNIT_TXT]             AS [RCP_UNIT_SNAME]
      ,[RECEIPT_DIVISION_TXT]         AS [RCP_DIVISION_SNAME]
      ,[RECEIPT_DEPT_TXT]             AS [RCP_DEPARTMENT_SNAME]
      ,[RECEIPT_SECTION_TXT]          AS [RCP_SECTION_SNAME]
      ,[RECEIPT_AGENT_TXT]            AS [RCP_AGENT_SNAME]
      ,[SALES_RT1_TXT]                AS [SA_AG_ROUTE_1_NAME]
      ,[SALES_RT2_TXT]                AS [SA_AG_ROUTE_2_NAME]
      ,[INTERNALFLG_TXT]              AS [INTERNAL_FLG_NAME]
      ,[REL_SALES_SITE_TXT]           AS [SALES_BUSINESS_SITE_SNAME]
      ,[REL_SALES_UNIT_TXT]           AS [SALES_UNIT_SNAME]
      ,[REL_SALES_DIVISION_TXT]       AS [SALES_DIVISION_SNAME]
      ,[REL_SALES_DEPARTMENT_TXT]     AS [SALES_DEPARTMENT_SNAME]
      ,[REL_SALES_SECTION_TXT]        AS [SALES_SECTION_SNAME]
      ,[SALEMAN]                      AS [SALEMAN]
      ,[REGION]                       AS [REGION]
      ,[EMS]                          AS [EMS]
  FROM [dbo].[V_MST_SCM_CUST]


GO
