USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_VD_SFM_OPP_HIST_CRM](
	[ACCOUNT_GROUP_CODE] [nvarchar](255) NULL,
	[ACCOUNT_NAME] [nvarchar](255) NULL,
	[CAMPAIGN_NAME] [nvarchar](255) NULL,
	[CHANNEL_PARTNER_NAME] [nvarchar](255) NULL,
	[CHANNEL_PARTNER_CODE] [nvarchar](40) NULL,
	[OPP_CREATED_DATE] [date] NULL,
	[OPP_CREATED_BY_EMAIL] [nvarchar](128) NULL,
	[OPP_CREATED_BY_FEDERATION_ID] [nvarchar](4000) NULL,
	[D_IN_SALES_COMPANY] [nvarchar](2) NULL,
	[D_IN_SALES_COMPANY_TXT] [nvarchar](255) NULL,
	[D_IN_SCM_CUST_CODE_DUMMY_FLAG] [nvarchar](1) NULL,
	[D_IN_SCM_CUST_CODE_FOR_SCM_OPE] [nvarchar](10) NULL,
	[END_CUSTOMER_COUNTRY] [nvarchar](2) NULL,
	[END_CUSTOMER_FREE_TEXT] [nvarchar](255) NULL,
	[END_CUSTOMER_NAME] [nvarchar](80) NULL,
	[ESTIMATED_ANNUAL_USAGE] [numeric](18, 0) NULL,
	[LEAD_ID] [nvarchar](18) NULL,
	[NDA_FLAG] [nvarchar](1) NULL,
	[OPP_OPPORTUNITY_DISCERNMENT] [nvarchar](2) NULL,
	[OPPORTUNITY_NO] [nvarchar](7) NULL,
	[OPPORTUNITY_INDUSTRY] [nvarchar](2) NULL,
	[OPPORTUNITY_INDUSTRY_TXT] [nvarchar](255) NULL,
	[OPPORTUNITY_NAME] [nvarchar](120) NULL,
	[SALES_TEAM_NAME_1] [nvarchar](120) NULL,
	[SALES_TEAM_NAME_2] [nvarchar](120) NULL,
	[SALES_TEAM_NAME_3] [nvarchar](120) NULL,
	[SALES_TEAM_NAME_4] [nvarchar](120) NULL,
	[STAGE_TYPE] [nvarchar](2) NULL,
	[STAGE_TYPE_TXT] [nvarchar](255) NULL,
	[TRACKING_TYPE_STATUS] [nvarchar](2) NULL,
	[TRACKING_TYPE_STATUS_TXT] [nvarchar](255) NULL,
	[UPDATE_DATE] [date] NULL
) ON [BI_DM_Dimension]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_M_VD_SFM_OPP_HIST_CRM_1] ON [dbo].[M_VD_SFM_OPP_HIST_CRM]
(
	[OPPORTUNITY_NO] ASC,
	[UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
GO
