USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_SS_ORD_FLG](
	[SS_ORD_FLG] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_M_SS_ORD_FLG] PRIMARY KEY CLUSTERED 
(
	[SS_ORD_FLG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
) ON [BI_DM_Dimension]

GO
