USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_DCP_WBS_DELIBERATION](
	[WBS] [nvarchar](30) NOT NULL,
	[DELIBERATION_CD] [nvarchar](6) NOT NULL,
	[EXPECTED_DATE] [date] NULL,
	[EXECUTION_DATE] [date] NULL,
	[RESULT] [nvarchar](30) NULL,
	[CHAIRMAN] [nvarchar](80) NULL,
	[CURRENCY_CODE] [nvarchar](3) NULL,
	[EXCHANGE_RATE] [numeric](8, 2) NULL,
	[LAST_FLG] [bit] NULL,
	[DCP_UPDATETIME] [smalldatetime] NULL,
	[REG_DATETIME] [smalldatetime] NULL,
	[UPD_DATETIME] [smalldatetime] NULL,
 CONSTRAINT [PK_M_DCP_WBS_DELIBERATION] PRIMARY KEY CLUSTERED 
(
	[WBS] ASC,
	[DELIBERATION_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
) ON [BI_DM_Dimension]

GO
ALTER TABLE [dbo].[M_DCP_WBS_DELIBERATION] ADD  CONSTRAINT [DF_M_DCP_WBS_DELIBERATION_LAST_FLG]  DEFAULT ((0)) FOR [LAST_FLG]
GO
ALTER TABLE [dbo].[M_DCP_WBS_DELIBERATION] ADD  CONSTRAINT [DF__M_DCP_WBS__REG_D__7CC477D0]  DEFAULT (getdate()) FOR [REG_DATETIME]
GO
ALTER TABLE [dbo].[M_DCP_WBS_DELIBERATION] ADD  CONSTRAINT [DF__M_DCP_WBS__UPD_D__7DB89C09]  DEFAULT (getdate()) FOR [UPD_DATETIME]
GO
