USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VF_SAL_BILL_GO] AS

SELECT
 BASE.WBS
, BASE.DELIBERATION_CD
, BASE.CALENDAR_YM
, BASE.ORDER_PART_NO_CD
, BASE.SCM_CUSTOMER_CD
, BASE.HORIZON_ID
, SUM(REVENUE) AS REVENUE
, SUM(SC_AMT) AS SC_AMT
, SUM(GP_AMT) AS GP_AMT
, SUM(VOLUME) AS VOLUME
FROM (
	SELECT
	 CAST(ISNULL(P.DEVELOP_NO, '$ACT$') AS NVARCHAR(30)) AS WBS
	, CAST('$ACT$' AS NVARCHAR(6)) AS DELIBERATION_CD
	, C.MONTH AS CALENDAR_YM
	, CAST(ISNULL(B.ORDER_PART_NO_CD, '$ACT$') AS NVARCHAR(18)) AS ORDER_PART_NO_CD
	, CAST(ISNULL(B.SCM_CUSTOMER_CD, '$ACT$') AS NVARCHAR(10)) AS SCM_CUSTOMER_CD
	, '2' AS HORIZON_ID

	, B.GO_AMT_JPY AS REVENUE
	, B.GO_AMT_STD AS SC_AMT
	, B.GO_AMT_JPY - B.GO_AMT_STD AS GP_AMT
	, B.GO_QTY AS VOLUME

	FROM F_SAL_BILL_GO B

	LEFT JOIN V_MST_BOOK_PN P
	ON B.ORDER_PART_NO_CD = P.BOOKING_PN_CD

	LEFT JOIN M_CAL_CALENDAR C
	ON B.RECORD_DATE = C.DAY ) BASE

GROUP BY BASE.WBS
, BASE.DELIBERATION_CD
, BASE.CALENDAR_YM
, BASE.ORDER_PART_NO_CD
, BASE.SCM_CUSTOMER_CD
, BASE.HORIZON_ID





GO
