USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_VT_SFM_BCCV_D_IN_TARGET_PRD_H_CRM](
	[OPPORTUNITY_SEQ] [nvarchar](80) NOT NULL,
	[OPPORTUNITY_NO] [nvarchar](7) NULL,
	[D_IN_TARGET_YEAR] [nvarchar](7) NOT NULL,
	[D_IN_INPUT_YEAR] [nvarchar](7) NOT NULL,
	[CURRENCY_ISO_CODE] [nvarchar](3) NULL,
	[CURRENCY_TYPE] [nvarchar](14) NULL,
	[SCM_CUSTOMER_CODE] [nvarchar](20) NOT NULL,
	[SALES_ORDER_PN_FOR_MTF] [nvarchar](18) NULL,
	[APPLICATION1_CODE] [nvarchar](1) NULL,
	[APPLICATION2_CODE] [nvarchar](2) NULL,
	[APPLICATION3_CODE] [nvarchar](3) NULL,
	[UPDATE_DATE] [date] NULL,
	[DISP_UPDATE_DATE] [varchar](8) NULL,
	[D_IN_TARGET_ORIGINAL] [numeric](38, 4) NULL,
	[D_IN_TARGET_STRETCH] [numeric](38, 4) NULL,
	[D_IN_TARGET] [numeric](38, 4) NULL
) ON [BI_DM_Fact_NonPartition]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [I_F_VT_SFM_BCCV_D_IN_TARGET_PRD_H_CRM_1] ON [dbo].[F_VT_SFM_BCCV_D_IN_TARGET_PRD_H_CRM]
(
	[OPPORTUNITY_SEQ] ASC,
	[D_IN_TARGET_YEAR] ASC,
	[D_IN_INPUT_YEAR] ASC,
	[SCM_CUSTOMER_CODE] ASC,
	[UPDATE_DATE] ASC,
	[DISP_UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Fact_NonPartition]
GO
