USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VF_SAL_RAINBOWDATA] AS
SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,[CURRENCY_EXCH]
,0 AS [TODemand_Amt]
,0 AS [TODemand_Qty]
,0 AS [TOReply_Amt]
,0 AS [TOReply_Qty]
,0 AS [GODemand_Amt]
,0 AS [GODemand_V0_Amt]
,0 AS [GODemand_V1_Amt]
,0 AS [GODemand_Other_Amt]
,0 AS [GODemand_Std]
,0 AS [GODemand_V0_Std]
,0 AS [GODemand_V1_Std]
,0 AS [GODemand_Other_Std]
,0 AS [GODemand_Qty]
,0 AS [GODemand_V0_Qty]
,0 AS [GODemand_V1_Qty]
,0 AS [GODemand_Other_Qty]
,0 AS [GOReply_Amt]
,0 AS [GOReply_Std]
,0 AS [GOReply_Qty]
,[ShippableAATP_Amt_EXCH] AS [ShippableAATP_Amt]
,[ShippableAATP_Qty]
,[AdjustedSFOut_Amt_EXCH] AS [AdjustedSFOut_Amt]
,[AdjustedSFOut_Qty]
,0 AS [JSF_Amt]
,0 AS [JSF_V0_Amt]
,0 AS [JSF_V1_Amt]
,0 AS [JSF_Other_Amt]
,0 AS [JSF_Qty]
,0 AS [JSF_V0_Qty]
,0 AS [JSF_V1_Qty]
,0 AS [JSF_Other_Qty]
,0 AS [ProductionPlanning_Amt]
,0 AS [ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_FHPNO_CST_ALLSUM_EXCH]
WHERE [RESULTDIV] <> N'1'


UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,[CURRENCY_EXCH]
,[TODemand_Amt_JPY] AS [TODemand_Amt]
,[TODemand_Qty] AS [TODemand_Qty]
,[TOReply_Amt_JPY] AS [TOReply_Amt]
,[TOReply_Qty] AS [TOReply_Qty]
,(isnull([GODemand_V0_Amt_JPY],(0)) + isnull([GODemand_V1_Amt_JPY],(0))) AS [GODemand_Amt]
,[GODemand_V0_Amt_JPY] AS [GODemand_V0_Amt]
,[GODemand_V1_Amt_JPY] AS [GODemand_V1_Amt]
,[GODemand_Other_Amt_JPY] AS [GODemand_Other_Amt]
,(isnull([GODemand_V0_Std],(0)) + isnull([GODemand_V1_Std],(0))) AS [GODemand_Std]
,[GODemand_V0_Std] AS [GODemand_V0_Std]
,[GODemand_V1_Std] AS [GODemand_V1_Std]
,[GODemand_Other_Std] AS [GODemand_Other_Std]
,(isnull([GODemand_V0_Qty],(0)) + isnull([GODemand_V1_Qty],(0))) AS [GODemand_Qty]
,[GODemand_V0_Qty] AS [GODemand_V0_Qty]
,[GODemand_V1_Qty] AS [GODemand_V1_Qty]
,[GODemand_Other_Qty] AS [GODemand_Other_Qty]
,[GOReply_Amt_JPY] AS [GOReply_Amt]
,[GOReply_Std] AS [GOReply_Std]
,[GOReply_Qty] AS [GOReply_Qty]
,[ShippableAATP_Amt_JPY] AS [ShippableAATP_Amt]
,[ShippableAATP_Qty] AS [ShippableAATP_Qty]
,[AdjustedSFOut_Amt_JPY] AS [AdjustedSFOut_Amt]
,[AdjustedSFOut_Qty] AS [AdjustedSFOut_Qty]
,(isnull([JSF_V0_Amt_JPY],(0)) + isnull([JSF_V1_Amt_JPY],(0))) AS [JSF_Amt]
,[JSF_V0_Amt_JPY] AS [JSF_V0_Amt]
,[JSF_V1_Amt_JPY] AS [JSF_V1_Amt]
,[JSF_Other_Amt_JPY] AS [JSF_Other_Amt]
,(isnull([JSF_V0_Qty],(0)) + isnull([JSF_V1_Qty],(0))) AS [JSF_Qty]
,[JSF_V0_Qty] AS [JSF_V0_Qty]
,[JSF_V1_Qty] AS [JSF_V1_Qty]
,[JSF_Other_Qty] AS [JSF_Other_Qty]
,[ProductionPlanning_Amt] AS [ProductionPlanning_Amt]
,[ProductionPlanning_Qty] AS [ProductionPlanning_Qty]
,OSC_MoveAve_Cst    AS [OSC_MoveAve_Cst]
,OSC_MoveAve_GP_Amt AS [OSC_MoveAve_GP_Amt]
FROM (
SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[RESULTDIV]
,[CURRENCY]
,[CURRENCY_EXCH]
,0 AS [TODemand_Amt_JPY]
,0 AS [TODemand_Qty]
,0 AS [TOReply_Amt_JPY]
,0 AS [TOReply_Qty]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Amt_EXCH] ELSE 0 END AS [GODemand_V0_Amt_JPY]
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
        THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
                  THEN 0 
                  ELSE [GODemand_Amt_EXCH]
             END 
        ELSE 0 END AS [GODemand_V1_Amt_JPY]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [GODemand_Amt_EXCH] ELSE 0 END AS [GODemand_Other_Amt_JPY]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Std_EXCH] ELSE 0 END AS [GODemand_V0_Std]
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
        THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
                  THEN 0 
                  ELSE [GODemand_Std_EXCH]
             END 
        ELSE 0 END AS [GODemand_V1_Std]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')       THEN [GODemand_Std_EXCH] ELSE 0 END AS [GODemand_Other_Std]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Qty] ELSE 0 END AS [GODemand_V0_Qty]
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')                       
        THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE)) 
                  THEN 0 
                  ELSE [GODemand_Qty]
             END 
        ELSE 0 END AS [GODemand_V1_Qty]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [GODemand_Qty] ELSE 0 END AS [GODemand_Other_Qty]
,0 AS [GOReply_Amt_JPY]
,0 AS [GOReply_Std]
,0 AS [GOReply_Qty]
,0 AS [ShippableAATP_Amt_JPY]
,0 AS [ShippableAATP_Qty]
,0 AS [AdjustedSFOut_Amt_JPY]
,0 AS [AdjustedSFOut_Qty]
,CASE WHEN [V0V1DIV] IN (N'V0',N'S0')              THEN [JSF_Amt_EXCH] ELSE 0 END AS [JSF_V0_Amt_JPY]
,CASE WHEN [V0V1DIV] IN (N'V1',N'S1')                       THEN [JSF_Amt_EXCH] ELSE 0 END AS [JSF_V1_Amt_JPY]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [JSF_Amt_EXCH] ELSE 0 END AS [JSF_Other_Amt_JPY]
,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [JSF_Qty] ELSE 0 END AS [JSF_V0_Qty]
,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')                       THEN [JSF_Qty] ELSE 0 END AS [JSF_V1_Qty]
,CASE WHEN [V0V1DIV] NOT IN  (N'V0', N'V1', N'S0', N'S1')        THEN [JSF_Qty] ELSE 0 END AS [JSF_Other_Qty]
,0 AS [ProductionPlanning_Amt]
,0 AS [ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_V1JSF_EXCH]
) AS T

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,[CURRENCY_EXCH]
,[TODemand_Amt_EXCH] AS [TODemand_Amt]
,[TODemand_Qty]
,[TOReply_Amt_EXCH] AS [TOReply_Amt]
,[TOReply_Qty]
,0 AS [GODemand_Amt]
,0 AS [GODemand_V0_Amt]
,0 AS [GODemand_V1_Amt]
,0 AS [GODemand_Other_Amt]
,0 AS [GODemand_Std]
,0 AS [GODemand_V0_Std]
,0 AS [GODemand_V1_Std]
,0 AS [GODemand_Other_Std]
,0 AS [GODemand_Qty]
,0 AS [GODemand_V0_Qty]
,0 AS [GODemand_V1_Qty]
,0 AS [GODemand_Other_Qty]
,[GOReply_Amt_EXCH] AS [GOReply_Amt]
,[GOReply_Std_EXCH] AS [GOReply_Std]
,[GOReply_Qty]
,0 AS [ShippableAATP_Amt]
,0 AS [ShippableAATP_Qty]
,0 AS [AdjustedSFOut_Amt]
,0 AS [AdjustedSFOut_Qty]
,0 AS [JSF_Amt]
,0 AS [JSF_V0_Amt]
,0 AS [JSF_V1_Amt]
,0 AS [JSF_Other_Amt]
,0 AS [JSF_Qty]
,0 AS [JSF_V0_Qty]
,0 AS [JSF_V1_Qty]
,0 AS [JSF_Other_Qty]
,0 AS [ProductionPlanning_Amt]
,0 AS [ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_TOGOTRADE_INV_EXCH]

UNION ALL
SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,'JPY' AS [CURRENCY_EXCH]
,0 AS [TODemand_Amt]
,0 AS [TODemand_Qty]
,0 AS [TOReply_Amt]
,0 AS [TOReply_Qty]
,0 AS [GODemand_Amt]
,0 AS [GODemand_V0_Amt]
,0 AS [GODemand_V1_Amt]
,0 AS [GODemand_Other_Amt]
,0 AS [GODemand_Std]
,0 AS [GODemand_V0_Std]
,0 AS [GODemand_V1_Std]
,0 AS [GODemand_Other_Std]
,0 AS [GODemand_Qty]
,0 AS [GODemand_V0_Qty]
,0 AS [GODemand_V1_Qty]
,0 AS [GODemand_Other_Qty]
,0 AS [GOReply_Amt]
,0 AS [GOReply_Std]
,0 AS [GOReply_Qty]
,0 AS [ShippableAATP_Amt]
,0 AS [ShippableAATP_Qty]
,0 AS [AdjustedSFOut_Amt]
,0 AS [AdjustedSFOut_Qty]
,0 AS [JSF_Amt]
,0 AS [JSF_V0_Amt]
,0 AS [JSF_V1_Amt]
,0 AS [JSF_Other_Amt]
,0 AS [JSF_Qty]
,0 AS [JSF_V0_Qty]
,0 AS [JSF_V1_Qty]
,0 AS [JSF_Other_Qty]
,0 AS [ProductionPlanning_Amt]
,0 AS [ProductionPlanning_Qty]
,ISNULL([OSC_MoveAve_Cst], 0)    AS [OSC_MoveAve_Cst]
,ISNULL([OSC_MoveAve_GP_Amt], 0) AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_TOGOTRADE_INV]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
,[ORDER_PART_NO_CD]
,[SEG_CD]
,[BUSINESS_SITE]
,[CALENDAR_YM]
,[UPDATE_DATE]
,[CURRENCY]
,[CURRENCY_EXCH]
,0 AS [TODemand_Amt]
,0 AS [TODemand_Qty]
,0 AS [TOReply_Amt]
,0 AS [TOReply_Qty]
,0 AS [GODemand_Amt]
,0 AS [GODemand_V0_Amt]
,0 AS [GODemand_V1_Amt]
,0 AS [GODemand_Other_Amt]
,0 AS [GODemand_Std]
,0 AS [GODemand_V0_Std]
,0 AS [GODemand_V1_Std]
,0 AS [GODemand_Other_Std]
,0 AS [GODemand_Qty]
,0 AS [GODemand_V0_Qty]
,0 AS [GODemand_V1_Qty]
,0 AS [GODemand_Other_Qty]
,0 AS [GOReply_Amt]
,0 AS [GOReply_Std]
,0 AS [GOReply_Qty]
,0 AS [ShippableAATP_Amt]
,0 AS [ShippableAATP_Qty]
,0 AS [AdjustedSFOut_Amt]
,0 AS [AdjustedSFOut_Qty]
,0 AS [JSF_Amt]
,0 AS [JSF_V0_Amt]
,0 AS [JSF_V1_Amt]
,0 AS [JSF_Other_Amt]
,0 AS [JSF_Qty]
,0 AS [JSF_V0_Qty]
,0 AS [JSF_V1_Qty]
,0 AS [JSF_Other_Qty]
,[ProductionPlanning_Amt_EXCH] AS [ProductionPlanning_Amt]
,[ProductionPlanning_Qty]
,0 AS [OSC_MoveAve_Cst]
,0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_FIXED_PPPRODPLAN_EXCH]



GO
