USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VT_SFM_BCCV_PRODUCT_HISTORY_L] AS
SELECT
   PRO_HIS_L.PRODUCT_HISTORY_NO
  ,PRO_HIS_L.OPPORTUNITY_SEQ
  ,PRO_HIS_L.OPPORTUNITY_NO
  ,PRO_HIS_L.D_IN_DATE
  ,PRO_HIS_L.CURRENCY_ISO_CODE
  ,PRO_HIS_L.CURRENCY_TYPE
  ,PRO_HIS_L.D_IN_SCM_CUST_CODE_FOR_MTF
  ,PRO_HIS_L.SALES_ORDER_PN_FOR_MTF
  ,PRO_HIS_L.APPLICATION1_CODE
  ,PRO_HIS_L.APPLICATION2_CODE
  ,PRO_HIS_L.APPLICATION3_CODE
--CDC 20180522 LatestキューブへのAggregateのBI_ExecutionLog対応 Start
--  ,CONVERT(DATE,NULL) AS UPDATE_DATE
  ,T_CTRL.DEEMED_DATE   AS UPDATE_DATE
--CDC 20180522 LatestキューブへのAggregateのBI_ExecutionLog対応 End
  ,'Latest' AS DISP_UPDATE_DATE
  ,PRO_HIS_L.AMOUNT_DIFFERENCE
  ,PRO_HIS_L.AMOUNT
  ,PRO_HIS_L.QUANTITY_DIFFERENCE
  ,PRO_HIS_L.QUANTITY
FROM
  [BI_DM].[dbo].[F_SFM_PRODUCT_HISTORY_L] PRO_HIS_L
--CDC 20180522 LatestキューブへのAggregateのBI_ExecutionLog対応 Start
LEFT JOIN
  [BI_DW].[dbo].[Z_SSIS_CTRL] T_CTRL
ON  T_CTRL.[SSIS_PACKAGE] = N'Bamboo_PRODUCT_HISTORY'
AND T_CTRL.[JOB_TYPE]   = '1'
AND T_CTRL.[DS_TB_NAME] = '0'
--CDC 20180522 LatestキューブへのAggregateのBI_ExecutionLog対応 End

GO
