USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_PNO_STANDARD_PRICE](
	[ORDER_PART_NO_CD] [nvarchar](18) NOT NULL,
	[ZZWAERS] [nvarchar](5) NULL,
	[STANDARD_PRICE] [money] NULL,
	[STANDARD_PRICE_UNIT] [money] NULL,
	[SP_UNIT] [money] NULL,
	[StdCst_Flg] [nvarchar](10) NULL,
 CONSTRAINT [PK_M_PNO_STANDARD_PRICE] PRIMARY KEY CLUSTERED 
(
	[ORDER_PART_NO_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
) ON [BI_DM_Dimension]

GO
