USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_SFM_OPP_PRD_DEMAND_L_V_YOKO](
	[OPPORTUNITY_SEQ] [nvarchar](13) NULL,
	[OPPORTUNITY_NO] [nvarchar](7) NULL,
	[CURRENCY_TYPE] [nvarchar](14) NULL,
	[D_IN_SCM_CUST_CODE_FOR_MTF] [nvarchar](10) NULL,
	[SALES_ORDER_PN_FOR_MTF] [nvarchar](18) NULL,
	[OPP_APPLICATION1_CODE] [nvarchar](1) NULL,
	[OPP_APPLICATION2_CODE] [nvarchar](2) NULL,
	[OPP_APPLICATION3_CODE] [nvarchar](3) NULL,
	[MP_START_DATE] [date] NULL,
	[Under_FY(N-1)_Demand_Qty] [numeric](18, 0) NULL,
	[1Q_FY(N)_1-3_Demand_Qty] [numeric](18, 0) NULL,
	[2Q_FY(N)_4-6_Demand_Qty] [numeric](18, 0) NULL,
	[3Q_FY(N)_7-9_Demand_Qty] [numeric](18, 0) NULL,
	[4Q_FY(N)_10-12_Demand_Qty] [numeric](18, 0) NULL,
	[1H_FY(N+1)_Demand_Qty] [numeric](18, 0) NULL,
	[2H_FY(N+1)_Demand_Qty] [numeric](18, 0) NULL,
	[1H_FY(N+2)_Demand_Qty] [numeric](18, 0) NULL,
	[2H_FY(N+2)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+3)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+4)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+5)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+6)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+7)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+8)_Demand_Qty] [numeric](18, 0) NULL,
	[FY(N+9)_Demand_Qty] [numeric](18, 0) NULL,
	[Over_FY(N+10)_Demand_Qty] [numeric](18, 0) NULL,
	[Under_FY(N-1)_Demand_Amt] [numeric](38, 4) NULL,
	[1Q_FY(N)_1-3_Demand_Amt] [numeric](38, 4) NULL,
	[2Q_FY(N)_4-6_Demand_Amt] [numeric](38, 4) NULL,
	[3Q_FY(N)_7-9_Demand_Amt] [numeric](38, 4) NULL,
	[4Q_FY(N)_10-12_Demand_Amt] [numeric](38, 4) NULL,
	[1H_FY(N+1)_Demand_Amt] [numeric](38, 4) NULL,
	[2H_FY(N+1)_Demand_Amt] [numeric](38, 4) NULL,
	[1H_FY(N+2)_Demand_Amt] [numeric](38, 4) NULL,
	[2H_FY(N+2)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+3)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+4)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+5)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+6)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+7)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+8)_Demand_Amt] [numeric](38, 4) NULL,
	[FY(N+9)_Demand_Amt] [numeric](38, 4) NULL,
	[Over_FY(N+10)_Demand_Amt] [numeric](38, 4) NULL,
	[Under_FY(N-1)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[1Q_FY(N)_1-3_Demand_GO_Amt] [numeric](38, 4) NULL,
	[2Q_FY(N)_4-6_Demand_GO_Amt] [numeric](38, 4) NULL,
	[3Q_FY(N)_7-9_Demand_GO_Amt] [numeric](38, 4) NULL,
	[4Q_FY(N)_10-12_Demand_GO_Amt] [numeric](38, 4) NULL,
	[1H_FY(N+1)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[2H_FY(N+1)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[1H_FY(N+2)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[2H_FY(N+2)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[FY(N+3)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[FY(N+4)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[FY(N+5)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[FY(N+6)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[FY(N+7)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[FY(N+8)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[FY(N+9)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[Over_FY(N+10)_Demand_GO_Amt] [numeric](38, 4) NULL,
	[Under_FY(N-1)_Demand_GO_Price] [numeric](38, 4) NULL,
	[1Q_FY(N)_1-3_Demand_GO_Price] [numeric](38, 4) NULL,
	[2Q_FY(N)_4-6_Demand_GO_Price] [numeric](38, 4) NULL,
	[3Q_FY(N)_7-9_Demand_GO_Price] [numeric](38, 4) NULL,
	[4Q_FY(N)_10-12_Demand_GO_Price] [numeric](38, 4) NULL,
	[1H_FY(N+1)_Demand_GO_Price] [numeric](38, 4) NULL,
	[2H_FY(N+1)_Demand_GO_Price] [numeric](38, 4) NULL,
	[1H_FY(N+2)_Demand_GO_Price] [numeric](38, 4) NULL,
	[2H_FY(N+2)_Demand_GO_Price] [numeric](38, 4) NULL,
	[FY(N+3)_Demand_GO_Price] [numeric](38, 4) NULL,
	[FY(N+4)_Demand_GO_Price] [numeric](38, 4) NULL,
	[FY(N+5)_Demand_GO_Price] [numeric](38, 4) NULL,
	[FY(N+6)_Demand_GO_Price] [numeric](38, 4) NULL,
	[FY(N+7)_Demand_GO_Price] [numeric](38, 4) NULL,
	[FY(N+8)_Demand_GO_Price] [numeric](38, 4) NULL,
	[FY(N+9)_Demand_GO_Price] [numeric](38, 4) NULL,
	[Over_FY(N+10)_Demand_GO_Price] [numeric](38, 4) NULL
) ON [BI_DM_Fact_NonPartition]
WITH
(
DATA_COMPRESSION = PAGE
)
GO
