USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_VD_APL3_CRM](
	[APL1] [nvarchar](1) NULL,
	[APL1_TXT] [nvarchar](40) NULL,
	[APL2] [nvarchar](2) NULL,
	[APL2_TXT] [nvarchar](40) NULL,
	[APL3] [nvarchar](3) NULL,
	[APL3_TXT] [nvarchar](40) NULL,
	[AFFECT_GST] [nvarchar](300) NULL,
	[GST_1] [nvarchar](300) NULL,
	[GST_2] [nvarchar](300) NULL
) ON [BI_DM_Dimension]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_M_VD_APL3_CRM_1] ON [dbo].[M_VD_APL3_CRM]
(
	[APL1] ASC,
	[APL2] ASC,
	[APL3] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
GO
