USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VPRC_FT_OPPORTUNITY_DIN_TBLR] AS
WITH CUR_RATE AS 
     (SELECT * FROM [DM_MST].[dbo].[VPRC_FSDM_OSC_CUR_RATE]),
OPPORTUNITY AS (
SELECT [SCM_CUSTOMER_CD]
      ,[B_WIN_SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,[CURRENCY_EXCH]
      ,[DATATYPE]
      ,SUM([S1_AMT]) AS [S1_AMT]
      ,SUM([S1_STD]) AS [S1_STD]
      ,SUM([S2_AMT]) AS [S2_AMT]
      ,SUM([S2_STD]) AS [S2_STD]
      ,SUM([S3_AMT]) AS [S3_AMT]
      ,SUM([S3_STD]) AS [S3_STD]
      ,SUM([S4_AMT]) AS [S4_AMT]
      ,SUM([S4_STD]) AS [S4_STD]
FROM [BI_DM].[dbo].[F_SAL_OPPORTUNITY_DIN]
GROUP BY [SCM_CUSTOMER_CD]
      ,[B_WIN_SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,[CURRENCY_EXCH]
      ,[DATATYPE]
),
OPPORTUNITY_BM AS (
SELECT [SCM_CUSTOMER_CD]
      ,[B_WIN_SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,CUR_RATE.[CURR_CD_TO]          AS [CURRENCY_EXCH]
      ,[DATATYPE]
      ,[S1_AMT] * CUR_RATE.B_RATE     AS [S1_AMT_B]
      ,[S1_AMT] * CUR_RATE.M_RATE     AS [S1_AMT_M]
      ,[S1_STD] * CUR_RATE.B_RATE     AS [S1_STD_B]
      ,[S1_STD] * CUR_RATE.M_RATE     AS [S1_STD_M]
      ,[S2_AMT] * CUR_RATE.B_RATE     AS [S2_AMT_B]
      ,[S2_AMT] * CUR_RATE.M_RATE     AS [S2_AMT_M]
      ,[S2_STD] * CUR_RATE.B_RATE     AS [S2_STD_B]
      ,[S2_STD] * CUR_RATE.M_RATE     AS [S2_STD_M]
      ,[S3_AMT] * CUR_RATE.B_RATE     AS [S3_AMT_B]
      ,[S3_AMT] * CUR_RATE.M_RATE     AS [S3_AMT_M]
      ,[S3_STD] * CUR_RATE.B_RATE     AS [S3_STD_B]
      ,[S3_STD] * CUR_RATE.M_RATE     AS [S3_STD_M]
      ,[S4_AMT] * CUR_RATE.B_RATE     AS [S4_AMT_B]
      ,[S4_AMT] * CUR_RATE.M_RATE     AS [S4_AMT_M]
      ,[S4_STD] * CUR_RATE.B_RATE     AS [S4_STD_B]
      ,[S4_STD] * CUR_RATE.M_RATE     AS [S4_STD_M]
FROM OPPORTUNITY
LEFT OUTER JOIN CUR_RATE
  ON OPPORTUNITY.[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
 AND OPPORTUNITY.[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
WHERE [CURRENCY] = 'JPY'
AND [CURRENCY_EXCH]='JPY'
AND [DATATYPE]='0'
UNION ALL
SELECT [SCM_CUSTOMER_CD]
      ,[B_WIN_SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,CUR_RATE.[CURR_CD_TO]          AS [CURRENCY_EXCH]
      ,[DATATYPE]
      ,[S1_AMT] * CUR_RATE.B_RATE     AS [S1_AMT_B]
      ,[S1_AMT] * CUR_RATE.M_RATE     AS [S1_AMT_M]
      ,[S1_STD] * CUR_RATE.B_RATE     AS [S1_STD_B]
      ,[S1_STD] * CUR_RATE.M_RATE     AS [S1_STD_M]
      ,[S2_AMT] * CUR_RATE.B_RATE     AS [S2_AMT_B]
      ,[S2_AMT] * CUR_RATE.M_RATE     AS [S2_AMT_M]
      ,[S2_STD] * CUR_RATE.B_RATE     AS [S2_STD_B]
      ,[S2_STD] * CUR_RATE.M_RATE     AS [S2_STD_M]
      ,[S3_AMT] * CUR_RATE.B_RATE     AS [S3_AMT_B]
      ,[S3_AMT] * CUR_RATE.M_RATE     AS [S3_AMT_M]
      ,[S3_STD] * CUR_RATE.B_RATE     AS [S3_STD_B]
      ,[S3_STD] * CUR_RATE.M_RATE     AS [S3_STD_M]
      ,[S4_AMT] * CUR_RATE.B_RATE     AS [S4_AMT_B]
      ,[S4_AMT] * CUR_RATE.M_RATE     AS [S4_AMT_M]
      ,[S4_STD] * CUR_RATE.B_RATE     AS [S4_STD_B]
      ,[S4_STD] * CUR_RATE.M_RATE     AS [S4_STD_M]
FROM OPPORTUNITY
LEFT OUTER JOIN CUR_RATE
  ON OPPORTUNITY.[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
 AND OPPORTUNITY.[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
WHERE [CURRENCY] = 'USD'
AND [CURRENCY_EXCH]='USD'
AND [DATATYPE]='0'
UNION ALL
SELECT [SCM_CUSTOMER_CD]
      ,[B_WIN_SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,CUR_RATE.[CURR_CD_TO]          AS [CURRENCY_EXCH]
      ,[DATATYPE]
      ,[S1_AMT] * CUR_RATE.B_RATE     AS [S1_AMT_B]
      ,[S1_AMT] * CUR_RATE.M_RATE     AS [S1_AMT_M]
      ,[S1_STD] * CUR_RATE.B_RATE     AS [S1_STD_B]
      ,[S1_STD] * CUR_RATE.M_RATE     AS [S1_STD_M]
      ,[S2_AMT] * CUR_RATE.B_RATE     AS [S2_AMT_B]
      ,[S2_AMT] * CUR_RATE.M_RATE     AS [S2_AMT_M]
      ,[S2_STD] * CUR_RATE.B_RATE     AS [S2_STD_B]
      ,[S2_STD] * CUR_RATE.M_RATE     AS [S2_STD_M]
      ,[S3_AMT] * CUR_RATE.B_RATE     AS [S3_AMT_B]
      ,[S3_AMT] * CUR_RATE.M_RATE     AS [S3_AMT_M]
      ,[S3_STD] * CUR_RATE.B_RATE     AS [S3_STD_B]
      ,[S3_STD] * CUR_RATE.M_RATE     AS [S3_STD_M]
      ,[S4_AMT] * CUR_RATE.B_RATE     AS [S4_AMT_B]
      ,[S4_AMT] * CUR_RATE.M_RATE     AS [S4_AMT_M]
      ,[S4_STD] * CUR_RATE.B_RATE     AS [S4_STD_B]
      ,[S4_STD] * CUR_RATE.M_RATE     AS [S4_STD_M]
FROM OPPORTUNITY
LEFT OUTER JOIN CUR_RATE
  ON OPPORTUNITY.[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
 AND OPPORTUNITY.[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
WHERE [CURRENCY] = 'EUR'
AND [CURRENCY_EXCH]='EUR'
AND [DATATYPE]='0'
UNION ALL
SELECT [SCM_CUSTOMER_CD]
      ,[B_WIN_SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,CUR_RATE.[CURR_CD_TO]          AS [CURRENCY_EXCH]
      ,[DATATYPE]
      ,[S1_AMT] * CUR_RATE.B_RATE     AS [S1_AMT_B]
      ,[S1_AMT] * CUR_RATE.M_RATE     AS [S1_AMT_M]
      ,[S1_STD] * CUR_RATE.B_RATE     AS [S1_STD_B]
      ,[S1_STD] * CUR_RATE.M_RATE     AS [S1_STD_M]
      ,[S2_AMT] * CUR_RATE.B_RATE     AS [S2_AMT_B]
      ,[S2_AMT] * CUR_RATE.M_RATE     AS [S2_AMT_M]
      ,[S2_STD] * CUR_RATE.B_RATE     AS [S2_STD_B]
      ,[S2_STD] * CUR_RATE.M_RATE     AS [S2_STD_M]
      ,[S3_AMT] * CUR_RATE.B_RATE     AS [S3_AMT_B]
      ,[S3_AMT] * CUR_RATE.M_RATE     AS [S3_AMT_M]
      ,[S3_STD] * CUR_RATE.B_RATE     AS [S3_STD_B]
      ,[S3_STD] * CUR_RATE.M_RATE     AS [S3_STD_M]
      ,[S4_AMT] * CUR_RATE.B_RATE     AS [S4_AMT_B]
      ,[S4_AMT] * CUR_RATE.M_RATE     AS [S4_AMT_M]
      ,[S4_STD] * CUR_RATE.B_RATE     AS [S4_STD_B]
      ,[S4_STD] * CUR_RATE.M_RATE     AS [S4_STD_M]
FROM OPPORTUNITY
LEFT OUTER JOIN CUR_RATE
  ON CUR_RATE.[CURR_CD_FROM] = 'JPY'
 AND OPPORTUNITY.[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
WHERE [CURRENCY_EXCH]='JPY'
AND [DATATYPE]='1'

)
SELECT OPPORTUNITY.[SCM_CUSTOMER_CD]
      ,OPPORTUNITY.[B_WIN_SCM_CUSTOMER_CD]
      ,OPPORTUNITY.[ORDER_PART_NO_CD]
      ,OPPORTUNITY.[SEG_CD]
      ,OPPORTUNITY.[CALENDAR_YM]
      ,OPPORTUNITY.[CURRENCY]
      ,OPPORTUNITY.[CURRENCY_EXCH]
      ,OPPORTUNITY.[DATATYPE]
      ,OPPORTUNITY.[S1_AMT] AS [S1_AMT_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S1_AMT_B])  AS [S1_AMT_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S1_AMT_M])  AS [S1_AMT_M]
      ,OPPORTUNITY.[S1_STD] AS [S1_STD_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S1_STD_B])  AS [S1_STD_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S1_STD_M])  AS [S1_STD_M]
      ,OPPORTUNITY.[S2_AMT] AS [S2_AMT_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S2_AMT_B])  AS [S2_AMT_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S2_AMT_M])  AS [S2_AMT_M]
      ,OPPORTUNITY.[S2_STD] AS [S2_STD_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S2_STD_B])  AS [S2_STD_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S2_STD_M])  AS [S2_STD_M]
      ,OPPORTUNITY.[S3_AMT] AS [S3_AMT_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S3_AMT_B])  AS [S3_AMT_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S3_AMT_M])  AS [S3_AMT_M]
      ,OPPORTUNITY.[S3_STD] AS [S3_STD_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S3_STD_B])  AS [S3_STD_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S3_STD_M])  AS [S3_STD_M]
      ,OPPORTUNITY.[S4_AMT] AS [S4_AMT_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S4_AMT_B])  AS [S4_AMT_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S4_AMT_M])  AS [S4_AMT_M]
      ,OPPORTUNITY.[S4_STD] AS [S4_STD_Q]
      ,CONVERT(money,OPPORTUNITY_BM.[S4_STD_B])  AS [S4_STD_B]
      ,CONVERT(money,OPPORTUNITY_BM.[S4_STD_M])  AS [S4_STD_M]
FROM OPPORTUNITY
LEFT JOIN OPPORTUNITY_BM
 ON ISNULL(OPPORTUNITY.[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(OPPORTUNITY_BM.[SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL(OPPORTUNITY.[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(OPPORTUNITY_BM.[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL(OPPORTUNITY.[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(OPPORTUNITY_BM.[ORDER_PART_NO_CD],'$$NULL$$')
AND ISNULL(OPPORTUNITY.[SEG_CD],'$$NULL$$') = ISNULL(OPPORTUNITY_BM.[SEG_CD],'$$NULL$$')
AND ISNULL(CONVERT(nvarchar,OPPORTUNITY.[CALENDAR_YM],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,OPPORTUNITY_BM.[CALENDAR_YM],112),'$$NULL$$')
AND ISNULL(OPPORTUNITY.[CURRENCY],'$$NULL$$') = ISNULL(OPPORTUNITY_BM.[CURRENCY],'$$NULL$$')
AND ISNULL(OPPORTUNITY.[CURRENCY_EXCH],'$$NULL$$') = ISNULL(OPPORTUNITY_BM.[CURRENCY_EXCH],'$$NULL$$')
AND ISNULL(OPPORTUNITY.[DATATYPE],'$$NULL$$') = ISNULL(OPPORTUNITY_BM.[DATATYPE],'$$NULL$$')


GO
