USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_CMN_RATE_PATTERN](
	[PATTERN_CODE] [nvarchar](2) NOT NULL,
	[PATTERN_NAME] [nvarchar](50) NULL,
	[COST_RATE_USD_CAL] [decimal](9, 5) NULL,
	[BILL_RATE_USD_CAL] [decimal](9, 5) NULL,
	[BILL_RATE_EUR_CAL] [decimal](9, 5) NULL,
	[COST_RATE_USD_DISP] [nvarchar](20) NULL,
	[BILL_RATE_USD_DISP] [nvarchar](20) NULL,
	[BILL_RATE_EUR_DISP] [nvarchar](20) NULL,
	[PROCESS_FLAG] [nvarchar](2) NULL,
	[ABNORMAL_FLAG] [nvarchar](2) NULL,
	[REG_DATETIME] [smalldatetime] NULL,
	[UPD_DATETIME] [smalldatetime] NULL,
 CONSTRAINT [PK_M_CMN_RATE_PATTERN] PRIMARY KEY CLUSTERED 
(
	[PATTERN_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
) ON [BI_DM_Dimension]

GO
