USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_VD_SFM_BCCV_PRODUCT_HISTORY_H_CRM](
	[PRODUCT_HISTORY_NO] [nvarchar](13) NOT NULL,
	[OPPORTUNITY_SEQ] [nvarchar](13) NULL,
	[ACTUAL_TYPE] [nvarchar](2) NULL,
	[EVENT_TYPE] [nvarchar](2) NULL,
	[STAGE_TYPE] [nvarchar](2) NULL,
	[UPDATE_DATE] [date] NULL
) ON [BI_DM_Dimension]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [I_M_VD_SFM_BCCV_PRODUCT_HISTORY_H_CRM_1] ON [dbo].[M_VD_SFM_BCCV_PRODUCT_HISTORY_H_CRM]
(
	[PRODUCT_HISTORY_NO] ASC,
	[OPPORTUNITY_SEQ] ASC,
	[UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Fact_NonPartition]
GO
