USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VU_TR_RAINBOWDATA_HISTORY_PU]
AS
SELECT
--20170201 明細データ開示対応 START
-- [RAINBOWDATA].[CURRENCY_EXCH]                   AS [CURRENCY_EXCH]
--,[RAINBOWDATA].[UPDATE_DATE]                     AS [UPDATE_DATE]
 [RAINBOWDATA].[UPDATE_DATE]                     AS [UPDATE_DATE]
--20170201 明細データ開示対応 E N D
,[RAINBOWDATA].[CALENDAR_YM]                     AS [CALENDAR_YM]
,[RAINBOWDATA].[SCM_CUSTOMER_CD]                 AS [SCM_Customer]
,[SCM_MST].[SCM_CUSTOMER_TXT_S]                  AS [SCM_Customer_txt_S]
,[SCM_MST].[INTERNALFLG_TXT]                     AS [InternalFLG_txt]
,[SCM_MST].[SALES_RT1_TXT]                       AS [Sales_Rt1_txt]
,[SCM_MST].[SALES_RT2_TXT]                       AS [Sales_Rt2_txt]
,[SCM_MST].[RECEIPT_RENESASGROUP_TXT]            AS [Receipt_RenesasGroup_txt]
,[SCM_MST].[RECEIPT_UNIT_TXT]                    AS [Receipt_Unit_txt]
,[SCM_MST].[RECEIPT_DIVISION_TXT]                AS [Receipt_Division_txt]
,[SCM_MST].[RECEIPT_DEPT_TXT]                    AS [Receipt_Dept_txt]
,[SCM_MST].[RECEIPT_SECTION_TXT]                 AS [Receipt_Section_txt]
,[SCM_MST].[RECEIPT_AGENT_TXT]                   AS [Receipt_Agent_txt]
,[SCM_MST].[REL_SALES_SITE]                      AS [REL_Sales_Site]
,[SCM_MST].[REL_SALES_UNIT_TXT]                  AS [REL_Sales_Unit_txt]
,[SCM_MST].[REL_SALES_DIVISION_TXT]              AS [REL_Sales_Division_txt]
,[SCM_MST].[REL_SALES_DEPARTMENT_TXT]            AS [REL_Sales_Department_txt]
,[SCM_MST].[REL_SALES_SECTION_TXT]               AS [REL_Sales_Section_txt]
,[SCM_MST].[PRICE_CODE]                          AS [Price_Code]
,[SCM_MST].[AGENT_LOCATION]                      AS [Agent_Location]
,[SCM_MST].[SCM_CUSTOMER_COUNTRY]                AS [SCM_Customer_Country]
,[SCM_MST].[BF_CHANNEL]                          AS [BF_Channel]
,[SCM_MST].[CUSTOMER_GRP1]                       AS [Customer_Grp1]
,[SCM_MST].[CUSTOMER_GRP2]                       AS [Customer_Grp2]
,[SCM_MST].[CUSTOMER_GRPCOUNTRY]                 AS [Customer_GrpCountry]
,[SCM_MST].[NIKKEI_WW_FLG]                       AS [NIKKEI_WW_FLG]
,[SCM_MST].[SALES_PLANNING_GRP]                  AS [Sales_Planning_Grp]
,[RAINBOWDATA].[ORDER_PART_NO_CD]                AS [Booking_PN_CD]
,[BOOK_MST].[SO_PT_NO_K_A4_W]                    AS [Booking_PN_White40]
,[BOOK_MST].[BOOKING_PN]                         AS [Booking_PN]
,[BOOK_MST].[RENESAS_PRODUCT_FLAG_TXT]           AS [Renesas_Product_Flag_txt]
,[BOOK_MST].[DESIGN_GROUP_UNIT_TXT]              AS [Design_Group_Unit_txt]
,[BOOK_MST].[DESIGN_GROUP_DIVISION_TXT]          AS [Design_Group_Division_txt]
,[BOOK_MST].[DESIGN_GROUP_DEPARTMENT_TXT]        AS [Design_Group_Department_txt]
,[BOOK_MST].[DESIGN_GROUP_SECTION_TXT]           AS [Design_Group_Section_txt]
,[BOOK_MST].[CAT1]                               AS [CAT1]
,[BOOK_MST].[CAT1_TXT]                           AS [CAT1_txt]
,[BOOK_MST].[CAT2]                               AS [CAT2]
,[BOOK_MST].[CAT2_TXT]                           AS [CAT2_txt]
,[BOOK_MST].[CAT3]                               AS [CAT3]
,[BOOK_MST].[CAT3_TXT]                           AS [CAT3_txt]
,[BOOK_MST].[CAT4]                               AS [CAT4]
,[BOOK_MST].[CAT4_TXT]                           AS [CAT4_txt]
,[BOOK_MST].[CAT5]                               AS [CAT5]
,[BOOK_MST].[CAT5_TXT]                           AS [CAT5_txt]
,[BOOK_MST].[RENESAS_PN]                         AS [Renesas_PN]
,[BOOK_MST].[ORDER_PRODUCT_STATUS_TXT]           AS [Order_Product_Status_txt]
,[BOOK_MST].[MOQ]                                AS [MOQ]
,[BOOK_MST].[SPQ]                                AS [SPQ]
,[BOOK_MST].[TS_FLAG_TXT]                        AS [TS_Flag_txt]
,[BOOK_MST].[WAREHOUSE_TYPE_TXT]                 AS [Warehouse_Type_txt]
,[BOOK_MST].[ROM_TYPE_TXT]                       AS [ROM_Type_txt]
,[BOOK_MST].[PACKAGE_CODE]                       AS [Package_Code]
,[BOOK_MST].[CATALOG_PN]                         AS [Catalog_PN]
,[BOOK_MST].[FRAME_2_4_DIV]                      AS [Frame_2_4_Div]
,[BOOK_MST].[EISUI_UNIT_TXT]                     AS [Eisui_Unit_txt]
,[BOOK_MST].[EISUI_DIVITION_TXT]                 AS [Eisui_Divition_txt]
,[BOOK_MST].[EISUI_DEPARTMENT_TXT]               AS [Eisui_Department_txt]
,[BOOK_MST].[EISUI_SECTION_TXT]                  AS [Eisui_Section_txt]
,[BOOK_MST].[MP_DATE]                            AS [MP_Date]
,[BOOK_MST].[1ST_SHIP_DATE]                      AS [1st_Ship_Date]
,[BOOK_MST].[SCM_FLAG_TXT]                       AS [SCM_Flag_txt]
,[BOOK_MST].[PART_NO_FROM_DIV_TXT]               AS [Original_PN_Type_txt]
,[BOOK_MST].[EOL_AFFECT_POLICY]                  AS [EOL_AFFECT_POLICY]
,[BOOK_MST].[EOL_CURRENT_WP_WT]                  AS [EOL_CURRENT_WP_WT]
,[BOOK_MST].[EOL_POLICY]                         AS [EOL_POLICY]
,[BOOK_MST].[EOL_POLICY_TYPE]                    AS [EOL_POLICY_TYPE]
,[BOOK_MST].[EOL_SITECHANGE_ASSY]                AS [EOL_SITECHANGE_ASSY]
,[BOOK_MST].[EOL_WPWT_DETAIL]                    AS [EOL_WPWT_DETAIL]
,[BOOK_MST].[EOL_WPWT_FUTURE]                    AS [EOL_WPWT_FUTURE]
,[BOOK_MST].[EOL_X1FREE_ITEM]                    AS [EOL_x1FREE_ITEM]
,[BOOK_MST].[EOL_X2FREE_ITEM]                    AS [EOL_x2FREE_ITEM]
,[BOOK_MST].[EOL_X3FREE_ITEM]                    AS [EOL_x3FREE_ITEM]
--20181205 Liang 標準原価マスタIF停止に伴うAM残存資源の改修 START
--,[STD_PRC].[STANDARD_PRICE]                      AS [StdCst]
--,[STD_PRC].[StdCst_Flg]                          AS [StdCst_Flg]
,[BOOK_PN].[COST]                                AS [StdCst]
,[BOOK_PN].[STDCST_FLG]                          AS [StdCst_Flg]
--20181205 Liang 標準原価マスタIF停止に伴うAM残存資源の改修 END
,[BOOK_MST].[MCU_SOC_AP_KBN]                     AS [MCU_SOC_AP_KBN]
,[BOOK_MST].[COST_CENTER_CD]                     AS [Cost_Center_CD]
,[BOOK_MST].[COST_CENTER_TXT]                    AS [Cost_Center_txt]
,[BOOK_MST].[DEVELOPMENT_YEAR_HARF]              AS [Development_Year_Harf]
,[RAINBOWDATA].[SEG_CD]                          AS [SEG_CD]
,[APL_MST].[APL1_TXT]                            AS [APL1_txt]
,[APL_MST].[APL2_TXT]                            AS [APL2_txt]
,[APL_MST].[APL3_TXT]                            AS [APL3_txt]
,[APL_MST].[AFFECT_GST]                          AS [GST_1_AFFECT]
,[APL_MST].[GST_1]                               AS [GST_2]
,[APL_MST].[GST_2]                               AS [GST_3]
,[RAINBOWDATA].[CURRENCY]                        AS [Cur]
,[RAINBOWDATA].[BUSINESS_SITE]                   AS [Business_Site]
,[APL_MST].[RR_BU_UNIT_TXT]                      AS [Revenue_Recognition_BU_Unit_txt]
,[APL_MST].[RR_BU_DIVISION_TXT]                  AS [Revenue_Recognition_BU_Division_txt]
,[APL_MST].[RR_BU_DEPARTMENT_TXT]                AS [Revenue_Recognition_BU_Department_txt]
,[APL_MST].[RR_BU_SECTION_TXT]                   AS [Revenue_Recognition_BU_Section_txt]
,[APL_MST].[SEGMENT_BU]                          AS [Segment_BU]
,[APL_MST].[FREE_ITEM_01]                        AS [Free_Item_01]
,[APL_MST].[FREE_ITEM_02]                        AS [Free_Item_02]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[TODemand_Amt]                    AS [TO_Demand_Amt]
,[RAINBOWDATA].[TODemand_Amt_JPY]                AS [TO_Demand_Amt_JPY]
,[RAINBOWDATA].[TODemand_Amt_USD]                AS [TO_Demand_Amt_USD]
,[RAINBOWDATA].[TODemand_Amt_EUR]                AS [TO_Demand_Amt_EUR]
--20170201 明細データ開示対応 E N D
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
,[RAINBOWDATA].[TODemand_Std_JPY]                AS [TO_Demand_StdCst_Amt_JPY]
,[RAINBOWDATA].[TODemand_Std_USD]                AS [TO_Demand_StdCst_Amt_USD]
,[RAINBOWDATA].[TODemand_Std_EUR]                AS [TO_Demand_StdCst_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
,[RAINBOWDATA].[TODemand_Qty]                    AS [TO_Demand_Qty]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[TOReply_Amt]                     AS [TO_Reply_Amt]
,[RAINBOWDATA].[TOReply_Amt_JPY]                 AS [TO_Reply_Amt_JPY]
,[RAINBOWDATA].[TOReply_Amt_USD]                 AS [TO_Reply_Amt_USD]
,[RAINBOWDATA].[TOReply_Amt_EUR]                 AS [TO_Reply_Amt_EUR]
--20170201 明細データ開示対応 E N D
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
,[RAINBOWDATA].[TOReply_Std_JPY]                 AS [TO_Reply_StdCst_Amt_JPY]
,[RAINBOWDATA].[TOReply_Std_USD]                 AS [TO_Reply_StdCst_Amt_USD]
,[RAINBOWDATA].[TOReply_Std_EUR]                 AS [TO_Reply_StdCst_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
,[RAINBOWDATA].[TOReply_Qty]                     AS [TO_Reply_Qty]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[GODemand_Amt]                    AS [GO_Demand_Amt]
--,[RAINBOWDATA].[GODemand_V0_Amt]                 AS [GO_Demand_V0_Amt]
--,[RAINBOWDATA].[GODemand_V1_Amt]                 AS [GO_Demand_V1_Amt]
--,[RAINBOWDATA].[GODemand_Std]                    AS [GO_Demand_StdCst_Amt]
--,[RAINBOWDATA].[GODemand_V0_Std]                 AS [GO_Demand_V0_StdCst_Amt]
--,[RAINBOWDATA].[GODemand_V1_Std]                 AS [GO_Demand_V1_StdCst_Amt]
,[RAINBOWDATA].[GODemand_Amt_JPY]                AS [GO_Demand_Amt_JPY]
,[RAINBOWDATA].[GODemand_Amt_USD]                AS [GO_Demand_Amt_USD]
,[RAINBOWDATA].[GODemand_Amt_EUR]                AS [GO_Demand_Amt_EUR]
,[RAINBOWDATA].[GODemand_V0_Amt_JPY]             AS [GO_Demand_V0_Amt_JPY]
,[RAINBOWDATA].[GODemand_V0_Amt_USD]             AS [GO_Demand_V0_Amt_USD]
,[RAINBOWDATA].[GODemand_V0_Amt_EUR]             AS [GO_Demand_V0_Amt_EUR]
,[RAINBOWDATA].[GODemand_V1_Amt_JPY]             AS [GO_Demand_V1_Amt_JPY]
,[RAINBOWDATA].[GODemand_V1_Amt_USD]             AS [GO_Demand_V1_Amt_USD]
,[RAINBOWDATA].[GODemand_V1_Amt_EUR]             AS [GO_Demand_V1_Amt_EUR]
,[RAINBOWDATA].[GODemand_Std_JPY]                AS [GO_Demand_StdCst_Amt_JPY]
,[RAINBOWDATA].[GODemand_Std_USD]                AS [GO_Demand_StdCst_Amt_USD]
,[RAINBOWDATA].[GODemand_Std_EUR]                AS [GO_Demand_StdCst_Amt_EUR]
,[RAINBOWDATA].[GODemand_V0_Std_JPY]             AS [GO_Demand_V0_StdCst_Amt_JPY]
,[RAINBOWDATA].[GODemand_V0_Std_USD]             AS [GO_Demand_V0_StdCst_Amt_USD]
,[RAINBOWDATA].[GODemand_V0_Std_EUR]             AS [GO_Demand_V0_StdCst_Amt_EUR]
,[RAINBOWDATA].[GODemand_V1_Std_JPY]             AS [GO_Demand_V1_StdCst_Amt_JPY]
,[RAINBOWDATA].[GODemand_V1_Std_USD]             AS [GO_Demand_V1_StdCst_Amt_USD]
,[RAINBOWDATA].[GODemand_V1_Std_EUR]             AS [GO_Demand_V1_StdCst_Amt_EUR]
--20170201 明細データ開示対応 E N D
,[RAINBOWDATA].[GODemand_Qty]                    AS [GO_Demand_Qty]
,[RAINBOWDATA].[GODemand_V0_Qty]                 AS [GO_Demand_V0_Qty]
,[RAINBOWDATA].[GODemand_V1_Qty]                 AS [GO_Demand_V1_Qty]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[GOReply_Amt]                     AS [GO_Reply_Amt]
--,[RAINBOWDATA].[GOReply_Std]                     AS [GO_Reply_StdCst_Amt]
,[RAINBOWDATA].[GOReply_Amt_JPY]                 AS [GO_Reply_Amt_JPY]
,[RAINBOWDATA].[GOReply_Amt_USD]                 AS [GO_Reply_Amt_USD]
,[RAINBOWDATA].[GOReply_Amt_EUR]                 AS [GO_Reply_Amt_EUR]
,[RAINBOWDATA].[GOReply_Std_JPY]                 AS [GO_Reply_StdCst_Amt_JPY]
,[RAINBOWDATA].[GOReply_Std_USD]                 AS [GO_Reply_StdCst_Amt_USD]
,[RAINBOWDATA].[GOReply_Std_EUR]                 AS [GO_Reply_StdCst_Amt_EUR]
--20170201 明細データ開示対応 E N D
,[RAINBOWDATA].[GOReply_Qty]                     AS [GO_Reply_Qty]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[ShippableAATP_Amt]               AS [Shippable_AATP_Amt]
,[RAINBOWDATA].[ShippableAATP_Amt_JPY]           AS [Shippable_AATP_Amt_JPY]
,[RAINBOWDATA].[ShippableAATP_Amt_USD]           AS [Shippable_AATP_Amt_USD]
,[RAINBOWDATA].[ShippableAATP_Amt_EUR]           AS [Shippable_AATP_Amt_EUR]
--20170201 明細データ開示対応 E N D
,[RAINBOWDATA].[ShippableAATP_Qty]               AS [Shippable_AATP_Qty]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[AdjustedSFOut_Amt]               AS [Adjusted_SF_Out_Amt]
,[RAINBOWDATA].[AdjustedSFOut_Amt_JPY]           AS [Adjusted_SF_Out_Amt_JPY]
,[RAINBOWDATA].[AdjustedSFOut_Amt_USD]           AS [Adjusted_SF_Out_Amt_USD]
,[RAINBOWDATA].[AdjustedSFOut_Amt_EUR]           AS [Adjusted_SF_Out_Amt_EUR]
--20170201 明細データ開示対応 E N D
,[RAINBOWDATA].[AdjustedSFOut_Qty]               AS [Adjusted_SF_Out_Qty]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[JSF_Amt]                         AS [JSF_Amt]
--,[RAINBOWDATA].[JSF_V0_Amt]                      AS [JSF_V0_Amt]
--,[RAINBOWDATA].[JSF_V1_Amt]                      AS [JSF_V1_Amt]
,[RAINBOWDATA].[JSF_Amt_JPY]                     AS [JSF_Amt_JPY]
,[RAINBOWDATA].[JSF_Amt_USD]                     AS [JSF_Amt_USD]
,[RAINBOWDATA].[JSF_Amt_EUR]                     AS [JSF_Amt_EUR]
,[RAINBOWDATA].[JSF_V0_Amt_JPY]                  AS [JSF_V0_Amt_JPY]
,[RAINBOWDATA].[JSF_V0_Amt_USD]                  AS [JSF_V0_Amt_USD]
,[RAINBOWDATA].[JSF_V0_Amt_EUR]                  AS [JSF_V0_Amt_EUR]
,[RAINBOWDATA].[JSF_V1_Amt_JPY]                  AS [JSF_V1_Amt_JPY]
,[RAINBOWDATA].[JSF_V1_Amt_USD]                  AS [JSF_V1_Amt_USD]
,[RAINBOWDATA].[JSF_V1_Amt_EUR]                  AS [JSF_V1_Amt_EUR]
--20170201 明細データ開示対応 E N D
,[RAINBOWDATA].[JSF_Qty]                         AS [JSF_Qty]
,[RAINBOWDATA].[JSF_V0_Qty]                      AS [JSF_V0_Qty]
,[RAINBOWDATA].[JSF_V1_Qty]                      AS [JSF_V1_Qty]
--20170201 明細データ開示対応 START
--,[RAINBOWDATA].[ProductionPlanning_Amt]          AS [Production_pln_Amt]
--20190220_mod_yushuang.yin_データカバレッジ対応_START
,[RAINBOWDATA].[ProductionPlanning_Amt_JPY]      AS [Production_Plan_Reply_Amt_JPY]
,[RAINBOWDATA].[ProductionPlanning_Amt_USD]      AS [Production_Plan_Reply_Amt_USD]
,[RAINBOWDATA].[ProductionPlanning_Amt_EUR]      AS [Production_Plan_Reply_Amt_EUR]
--20170201 明細データ開示対応 E N D
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
,[RAINBOWDATA].[ProductionPlanning_Std_JPY]      AS [Production_Plan_Reply_StdCst_Amt_JPY]
,[RAINBOWDATA].[ProductionPlanning_Std_USD]      AS [Production_Plan_Reply_StdCst_Amt_USD]
,[RAINBOWDATA].[ProductionPlanning_Std_EUR]      AS [Production_Plan_Reply_StdCst_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
,[RAINBOWDATA].[ProductionPlanning_Qty]          AS [Production_Plan_Reply_Qty]
--20190220_mod_yushuang.yin_データカバレッジ対応_END
,[RAINBOWDATA].[OSC_MoveAve_Cst]                 AS [GO_Reply_MoveAve_Amt]
,[RAINBOWDATA].[OSC_MoveAve_GP_Amt]              AS [GO_Reply_Margin_Amt]
--20170201 明細データ開示対応 START
--FROM [BI_DM].[dbo].[VF_SAL_RAINBOWDATA] [RAINBOWDATA]
FROM
(
   SELECT
   [SCM_CUSTOMER_CD]
  ,[ORDER_PART_NO_CD]
  ,[SEG_CD]
  ,[BUSINESS_SITE]
  ,[CALENDAR_YM]
  ,[UPDATE_DATE]
  ,[CURRENCY]
  ,0 AS [TODemand_Amt_JPY]
  ,0 AS [TODemand_Amt_USD]
  ,0 AS [TODemand_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,0 AS [TODemand_Std_JPY]
  ,0 AS [TODemand_Std_USD]
  ,0 AS [TODemand_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END  
  ,0 AS [TODemand_Qty]
  ,0 AS [TOReply_Amt_JPY]
  ,0 AS [TOReply_Amt_USD]
  ,0 AS [TOReply_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,0 AS [TOReply_Std_JPY]
  ,0 AS [TOReply_Std_USD]
  ,0 AS [TOReply_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,0 AS [TOReply_Qty]
  ,0 AS [GODemand_Amt_JPY]
  ,0 AS [GODemand_Amt_USD]
  ,0 AS [GODemand_Amt_EUR]
  ,0 AS [GODemand_V0_Amt_JPY]
  ,0 AS [GODemand_V0_Amt_USD]
  ,0 AS [GODemand_V0_Amt_EUR]
  ,0 AS [GODemand_V1_Amt_JPY]
  ,0 AS [GODemand_V1_Amt_USD]
  ,0 AS [GODemand_V1_Amt_EUR]
  ,0 AS [GODemand_Std_JPY]
  ,0 AS [GODemand_Std_USD]
  ,0 AS [GODemand_Std_EUR]
  ,0 AS [GODemand_V0_Std_JPY]
  ,0 AS [GODemand_V0_Std_USD]
  ,0 AS [GODemand_V0_Std_EUR]
  ,0 AS [GODemand_V1_Std_JPY]
  ,0 AS [GODemand_V1_Std_USD]
  ,0 AS [GODemand_V1_Std_EUR]
  ,0 AS [GODemand_Qty]
  ,0 AS [GODemand_V0_Qty]
  ,0 AS [GODemand_V1_Qty]
  ,0 AS [GOReply_Amt_JPY]
  ,0 AS [GOReply_Amt_USD]
  ,0 AS [GOReply_Amt_EUR]
  ,0 AS [GOReply_Std_JPY]
  ,0 AS [GOReply_Std_USD]
  ,0 AS [GOReply_Std_EUR]
  ,0 AS [GOReply_Qty]
  ,[ShippableAATP_Amt_JPY]
  ,[ShippableAATP_Amt_USD]
  ,[ShippableAATP_Amt_EUR]
  ,[ShippableAATP_Qty]
  ,[AdjustedSFOut_Amt_JPY]
  ,[AdjustedSFOut_Amt_USD]
  ,[AdjustedSFOut_Amt_EUR]
  ,[AdjustedSFOut_Qty]
  ,0 AS [JSF_Amt_JPY]
  ,0 AS [JSF_Amt_USD]
  ,0 AS [JSF_Amt_EUR]
  ,0 AS [JSF_V0_Amt_JPY]
  ,0 AS [JSF_V0_Amt_USD]
  ,0 AS [JSF_V0_Amt_EUR]
  ,0 AS [JSF_V1_Amt_JPY]
  ,0 AS [JSF_V1_Amt_USD]
  ,0 AS [JSF_V1_Amt_EUR]
  ,0 AS [JSF_Qty]
  ,0 AS [JSF_V0_Qty]
  ,0 AS [JSF_V1_Qty]
  ,0 AS [ProductionPlanning_Amt_JPY]
  ,0 AS [ProductionPlanning_Amt_USD]
  ,0 AS [ProductionPlanning_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,0 AS [ProductionPlanning_Std_JPY]
  ,0 AS [ProductionPlanning_Std_USD]
  ,0 AS [ProductionPlanning_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,0 AS [ProductionPlanning_Qty]
  ,0 AS [OSC_MoveAve_Cst]
  ,0 AS [OSC_MoveAve_GP_Amt]
  FROM [DM_SALES].[dbo].[TPRC_T_FORECASTHISTORY]
  WHERE [RESULTDIV] <> N'1'

  UNION ALL

   SELECT
   [SCM_CUSTOMER_CD]
  ,[ORDER_PART_NO_CD]
  ,[SEG_CD]
  ,[BUSINESS_SITE]
  ,[CALENDAR_YM]
  ,[UPDATE_DATE]
  ,[CURRENCY]
  ,[TODemand_Amt_JPY]                                                      AS [TODemand_Amt_JPY]
  ,[TODemand_Amt_USD]                                                      AS [TODemand_Amt_USD]
  ,[TODemand_Amt_EUR]                                                      AS [TODemand_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,[TODemand_Std_JPY]                                                      AS [TODemand_Std_JPY]
  ,[TODemand_Std_USD]                                                      AS [TODemand_Std_USD]
  ,[TODemand_Std_EUR]                                                      AS [TODemand_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,[TODemand_Qty]                                                          AS [TODemand_Qty]
  ,[TOReply_Amt_JPY]                                                       AS [TOReply_Amt_JPY]
  ,[TOReply_Amt_USD]                                                       AS [TOReply_Amt_USD]
  ,[TOReply_Amt_EUR]                                                       AS [TOReply_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,[TOReply_Std_JPY]                                                       AS [TOReply_Std_JPY]
  ,[TOReply_Std_USD]                                                       AS [TOReply_Std_USD]
  ,[TOReply_Std_EUR]                                                       AS [TOReply_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,[TOReply_Qty]                                                           AS [TOReply_Qty]
  ,(isnull([GODemand_V0_Amt_JPY],(0)) + isnull([GODemand_V1_Amt_JPY],(0))) AS [GODemand_Amt_JPY]
  ,(isnull([GODemand_V0_Amt_USD],(0)) + isnull([GODemand_V1_Amt_USD],(0))) AS [GODemand_Amt_USD]
  ,(isnull([GODemand_V0_Amt_EUR],(0)) + isnull([GODemand_V1_Amt_EUR],(0))) AS [GODemand_Amt_EUR]
  ,[GODemand_V0_Amt_JPY]                                                   AS [GODemand_V0_Amt_JPY]
  ,[GODemand_V0_Amt_USD]                                                   AS [GODemand_V0_Amt_USD]
  ,[GODemand_V0_Amt_EUR]                                                   AS [GODemand_V0_Amt_EUR]
  ,[GODemand_V1_Amt_JPY]                                                   AS [GODemand_V1_Amt_JPY]
  ,[GODemand_V1_Amt_USD]                                                   AS [GODemand_V1_Amt_USD]
  ,[GODemand_V1_Amt_EUR]                                                   AS [GODemand_V1_Amt_EUR]
  ,(isnull([GODemand_V0_Std_JPY],(0)) + isnull([GODemand_V1_Std_JPY],(0))) AS [GODemand_Std_JPY]
  ,(isnull([GODemand_V0_Std_USD],(0)) + isnull([GODemand_V1_Std_USD],(0))) AS [GODemand_Std_USD]
  ,(isnull([GODemand_V0_Std_EUR],(0)) + isnull([GODemand_V1_Std_EUR],(0))) AS [GODemand_Std_EUR]
  ,[GODemand_V0_Std_JPY]                                                   AS [GODemand_V0_Std_JPY]
  ,[GODemand_V0_Std_USD]                                                   AS [GODemand_V0_Std_USD]
  ,[GODemand_V0_Std_EUR]                                                   AS [GODemand_V0_Std_EUR]
  ,[GODemand_V1_Std_JPY]                                                   AS [GODemand_V1_Std_JPY]
  ,[GODemand_V1_Std_USD]                                                   AS [GODemand_V1_Std_USD]
  ,[GODemand_V1_Std_EUR]                                                   AS [GODemand_V1_Std_EUR]
  ,(isnull([GODemand_V0_Qty],(0)) + isnull([GODemand_V1_Qty],(0)))         AS [GODemand_Qty]
  ,[GODemand_V0_Qty]                                                       AS [GODemand_V0_Qty]
  ,[GODemand_V1_Qty]                                                       AS [GODemand_V1_Qty]
  ,[GOReply_Amt_JPY]                                                       AS [GOReply_Amt_JPY]
  ,[GOReply_Amt_USD]                                                       AS [GOReply_Amt_USD]
  ,[GOReply_Amt_EUR]                                                       AS [GOReply_Amt_EUR]
  ,[GOReply_Std_JPY]                                                       AS [GOReply_Std_JPY]
  ,[GOReply_Std_USD]                                                       AS [GOReply_Std_USD]
  ,[GOReply_Std_EUR]                                                       AS [GOReply_Std_EUR]
  ,[GOReply_Qty]                                                           AS [GOReply_Qty]
  ,[ShippableAATP_Amt_JPY]                                                 AS [ShippableAATP_Amt_JPY]
  ,[ShippableAATP_Amt_USD]                                                 AS [ShippableAATP_Amt_USD]
  ,[ShippableAATP_Amt_EUR]                                                 AS [ShippableAATP_Amt_EUR]
  ,[ShippableAATP_Qty]                                                     AS [ShippableAATP_Qty]
  ,[AdjustedSFOut_Amt_JPY]                                                 AS [AdjustedSFOut_Amt_JPY]
  ,[AdjustedSFOut_Amt_USD]                                                 AS [AdjustedSFOut_Amt_USD]
  ,[AdjustedSFOut_Amt_EUR]                                                 AS [AdjustedSFOut_Amt_EUR]
  ,[AdjustedSFOut_Qty]                                                     AS [AdjustedSFOut_Qty]
  ,(isnull([JSF_V0_Amt_JPY],(0)) + isnull([JSF_V1_Amt_JPY],(0)))           AS [JSF_Amt_JPY]
  ,(isnull([JSF_V0_Amt_USD],(0)) + isnull([JSF_V1_Amt_USD],(0)))           AS [JSF_Amt_USD]
  ,(isnull([JSF_V0_Amt_EUR],(0)) + isnull([JSF_V1_Amt_EUR],(0)))           AS [JSF_Amt_EUR]
  ,[JSF_V0_Amt_JPY]                                                        AS [JSF_V0_Amt_JPY]
  ,[JSF_V0_Amt_USD]                                                        AS [JSF_V0_Amt_USD]
  ,[JSF_V0_Amt_EUR]                                                        AS [JSF_V0_Amt_EUR]
  ,[JSF_V1_Amt_JPY]                                                        AS [JSF_V1_Amt_JPY]
  ,[JSF_V1_Amt_USD]                                                        AS [JSF_V1_Amt_USD]
  ,[JSF_V1_Amt_EUR]                                                        AS [JSF_V1_Amt_EUR]
  ,(isnull([JSF_V0_Qty],(0)) + isnull([JSF_V1_Qty],(0)))                   AS [JSF_Qty]
  ,[JSF_V0_Qty]                                                            AS [JSF_V0_Qty]
  ,[JSF_V1_Qty]                                                            AS [JSF_V1_Qty]
  ,[ProductionPlanning_Amt_JPY]                                            AS [ProductionPlanning_Amt_JPY]
  ,[ProductionPlanning_Amt_USD]                                            AS [ProductionPlanning_Amt_USD]
  ,[ProductionPlanning_Amt_EUR]                                            AS [ProductionPlanning_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,[ProductionPlanning_Std_JPY]                                            AS [ProductionPlanning_Std_JPY]
  ,[ProductionPlanning_Std_USD]                                            AS [ProductionPlanning_Std_USD]
  ,[ProductionPlanning_Std_EUR]                                            AS [ProductionPlanning_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,[ProductionPlanning_Qty]                                                AS [ProductionPlanning_Qty]
  ,[OSC_MoveAve_Cst]                                                       AS [OSC_MoveAve_Cst]
  ,[OSC_MoveAve_GP_Amt]                                                    AS [OSC_MoveAve_GP_Amt]
  FROM
  (
       SELECT
       [SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[BUSINESS_SITE]
      ,[CALENDAR_YM]
      ,[UPDATE_DATE]
      ,[RESULTDIV]
      ,[CURRENCY]
      ,0 AS [TODemand_Amt_JPY]
      ,0 AS [TODemand_Amt_USD]
      ,0 AS [TODemand_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
      ,0 AS [TODemand_Std_JPY]
      ,0 AS [TODemand_Std_USD]
      ,0 AS [TODemand_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
      ,0 AS [TODemand_Qty]
      ,0 AS [TOReply_Amt_JPY]
      ,0 AS [TOReply_Amt_USD]
      ,0 AS [TOReply_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
      ,0 AS [TOReply_Std_JPY]
      ,0 AS [TOReply_Std_USD]
      ,0 AS [TOReply_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
      ,0 AS [TOReply_Qty]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Amt_JPY] ELSE 0 END AS [GODemand_V0_Amt_JPY]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Amt_USD] ELSE 0 END AS [GODemand_V0_Amt_USD]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Amt_EUR] ELSE 0 END AS [GODemand_V0_Amt_EUR]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
      THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
      THEN 0
      ELSE [GODemand_Amt_JPY]
      END
      ELSE 0 END                                         AS [GODemand_V1_Amt_JPY]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
      THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
      THEN 0
      ELSE [GODemand_Amt_USD]
      END
      ELSE 0 END                                         AS [GODemand_V1_Amt_USD]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
      THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
      THEN 0
      ELSE [GODemand_Amt_EUR]
      END
      ELSE 0 END                                         AS [GODemand_V1_Amt_EUR]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Std_JPY] ELSE 0 END AS [GODemand_V0_Std_JPY]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Std_USD] ELSE 0 END AS [GODemand_V0_Std_USD]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Std_EUR] ELSE 0 END AS [GODemand_V0_Std_EUR]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
      THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
      THEN 0
      ELSE [GODemand_Std_JPY]
      END
      ELSE 0 END                                         AS [GODemand_V1_Std_JPY]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
      THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
      THEN 0
      ELSE [GODemand_Std_USD]
      END
      ELSE 0 END                                         AS [GODemand_V1_Std_USD]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
      THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
      THEN 0
      ELSE [GODemand_Std_EUR]
      END
      ELSE 0 END                                         AS [GODemand_V1_Std_EUR]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')             THEN [GODemand_Qty] ELSE 0 END AS [GODemand_V0_Qty]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')
      THEN CASE WHEN [CALENDAR_YM] between DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE) and DATEADD(MONTH,5,DATEADD(DAY,1-DATEPART(DAY,UPDATE_DATE),UPDATE_DATE))
      THEN 0
      ELSE [GODemand_Qty]
      END
      ELSE 0 END                                         AS [GODemand_V1_Qty]
      ,0 AS [GOReply_Amt_JPY]
      ,0 AS [GOReply_Amt_USD]
      ,0 AS [GOReply_Amt_EUR]
      ,0 AS [GOReply_Std_JPY]
      ,0 AS [GOReply_Std_USD]
      ,0 AS [GOReply_Std_EUR]
      ,0 AS [GOReply_Qty]
      ,0 AS [ShippableAATP_Amt_JPY]
      ,0 AS [ShippableAATP_Amt_USD]
      ,0 AS [ShippableAATP_Amt_EUR]
      ,0 AS [ShippableAATP_Qty]
      ,0 AS [AdjustedSFOut_Amt_JPY]
      ,0 AS [AdjustedSFOut_Amt_USD]
      ,0 AS [AdjustedSFOut_Amt_EUR]
      ,0 AS [AdjustedSFOut_Qty]
      ,CASE WHEN [V0V1DIV] IN (N'V0',N'S0')             THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_V0_Amt_JPY]
      ,CASE WHEN [V0V1DIV] IN (N'V0',N'S0')             THEN [JSF_Amt_USD] ELSE 0 END AS [JSF_V0_Amt_USD]
      ,CASE WHEN [V0V1DIV] IN (N'V0',N'S0')             THEN [JSF_Amt_EUR] ELSE 0 END AS [JSF_V0_Amt_EUR]
      ,CASE WHEN [V0V1DIV] IN (N'V1',N'S1')             THEN [JSF_Amt_JPY] ELSE 0 END AS [JSF_V1_Amt_JPY]
      ,CASE WHEN [V0V1DIV] IN (N'V1',N'S1')             THEN [JSF_Amt_USD] ELSE 0 END AS [JSF_V1_Amt_USD]
      ,CASE WHEN [V0V1DIV] IN (N'V1',N'S1')             THEN [JSF_Amt_EUR] ELSE 0 END AS [JSF_V1_Amt_EUR]
      ,CASE WHEN [V0V1DIV] IN (N'V0', N'S0')            THEN [JSF_Qty] ELSE 0 END AS [JSF_V0_Qty]
      ,CASE WHEN [V0V1DIV] IN (N'V1', N'S1')            THEN [JSF_Qty] ELSE 0 END AS [JSF_V1_Qty]
      ,0 AS [ProductionPlanning_Amt_JPY]
      ,0 AS [ProductionPlanning_Amt_USD]
      ,0 AS [ProductionPlanning_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
      ,0 AS [ProductionPlanning_Std_JPY]
      ,0 AS [ProductionPlanning_Std_USD]
      ,0 AS [ProductionPlanning_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
      ,0 AS [ProductionPlanning_Qty]
      ,0 AS [OSC_MoveAve_Cst]
      ,0 AS [OSC_MoveAve_GP_Amt]
      FROM [DM_SALES].[dbo].[TPRC_T_V1JSF]
  ) AST

  UNION ALL

   SELECT
   [SCM_CUSTOMER_CD]
  ,[ORDER_PART_NO_CD]
  ,[SEG_CD]
  ,[BUSINESS_SITE]
  ,[CALENDAR_YM]
  ,[UPDATE_DATE]
  ,[CURRENCY]
  ,[TODemand_Amt_JPY] AS [TODemand_Amt_JPY]
  ,[TODemand_Amt_USD] AS [TODemand_Amt_USD]
  ,[TODemand_Amt_EUR] AS [TODemand_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,[TODemand_Std_JPY] AS [TODemand_Std_JPY]
  ,[TODemand_Std_USD] AS [TODemand_Std_USD]
  ,[TODemand_Std_EUR] AS [TODemand_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,[TODemand_Qty]
  ,[TOReply_Amt_JPY]  AS [TOReply_Amt_JPY]
  ,[TOReply_Amt_USD]  AS [TOReply_Amt_USD]
  ,[TOReply_Amt_EUR]  AS [TOReply_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,[TOReply_Std_JPY]  AS [TOReply_Std_JPY]
  ,[TOReply_Std_USD]  AS [TOReply_Std_USD]
  ,[TOReply_Std_EUR]  AS [TOReply_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,[TOReply_Qty]
  ,0 AS [GODemand_Amt_JPY]
  ,0 AS [GODemand_Amt_USD]
  ,0 AS [GODemand_Amt_EUR]
  ,0 AS [GODemand_V0_Amt_JPY]
  ,0 AS [GODemand_V0_Amt_USD]
  ,0 AS [GODemand_V0_Amt_EUR]
  ,0 AS [GODemand_V1_Amt_JPY]
  ,0 AS [GODemand_V1_Amt_USD]
  ,0 AS [GODemand_V1_Amt_EUR]
  ,0 AS [GODemand_Std_JPY]
  ,0 AS [GODemand_Std_USD]
  ,0 AS [GODemand_Std_EUR]
  ,0 AS [GODemand_V0_Std_JPY]
  ,0 AS [GODemand_V0_Std_USD]
  ,0 AS [GODemand_V0_Std_EUR]
  ,0 AS [GODemand_V1_Std_JPY]
  ,0 AS [GODemand_V1_Std_USD]
  ,0 AS [GODemand_V1_Std_EUR]
  ,0 AS [GODemand_Qty]
  ,0 AS [GODemand_V0_Qty]
  ,0 AS [GODemand_V1_Qty]
  ,[GOReply_Amt_JPY] AS [GOReply_Amt_JPY]
  ,[GOReply_Amt_USD] AS [GOReply_Amt_USD]
  ,[GOReply_Amt_EUR] AS [GOReply_Amt_EUR]
  ,[GOReply_Std_JPY] AS [GOReply_Std_JPY]
  ,[GOReply_Std_USD] AS [GOReply_Std_USD]
  ,[GOReply_Std_EUR] AS [GOReply_Std_EUR]
  ,[GOReply_Qty]
  ,0 AS [ShippableAATP_Amt_JPY]
  ,0 AS [ShippableAATP_Amt_USD]
  ,0 AS [ShippableAATP_Amt_EUR]
  ,0 AS [ShippableAATP_Qty]
  ,0 AS [AdjustedSFOut_Amt_JPY]
  ,0 AS [AdjustedSFOut_Amt_USD]
  ,0 AS [AdjustedSFOut_Amt_EUR]
  ,0 AS [AdjustedSFOut_Qty]
  ,0 AS [JSF_Amt_JPY]
  ,0 AS [JSF_Amt_USD]
  ,0 AS [JSF_Amt_EUR]
  ,0 AS [JSF_V0_Amt_JPY]
  ,0 AS [JSF_V0_Amt_USD]
  ,0 AS [JSF_V0_Amt_EUR]
  ,0 AS [JSF_V1_Amt_JPY]
  ,0 AS [JSF_V1_Amt_USD]
  ,0 AS [JSF_V1_Amt_EUR]
  ,0 AS [JSF_Qty]
  ,0 AS [JSF_V0_Qty]
  ,0 AS [JSF_V1_Qty]
  ,0 AS [ProductionPlanning_Amt_JPY]
  ,0 AS [ProductionPlanning_Amt_USD]
  ,0 AS [ProductionPlanning_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,0 AS [ProductionPlanning_Std_JPY]
  ,0 AS [ProductionPlanning_Std_USD]
  ,0 AS [ProductionPlanning_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,0 AS [ProductionPlanning_Qty]
  ,[OSC_MoveAve_Cst]    AS [OSC_MoveAve_Cst]
  ,[OSC_MoveAve_GP_Amt] AS [OSC_MoveAve_GP_Amt]
  FROM [DM_SALES].[dbo].[TPRC_T_TOGOINV]

  UNION ALL
  
   SELECT
   [SCM_CUSTOMER_CD]
  ,[ORDER_PART_NO_CD]
  ,[SEG_CD]
  ,[BUSINESS_SITE]
  ,[CALENDAR_YM]
  ,[UPDATE_DATE]
  ,[CURRENCY]
  ,0 AS [TODemand_Amt_JPY]
  ,0 AS [TODemand_Amt_USD]
  ,0 AS [TODemand_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,0 AS [TODemand_Std_JPY]
  ,0 AS [TODemand_Std_USD]
  ,0 AS [TODemand_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,0 AS [TODemand_Qty]
  ,0 AS [TOReply_Amt_JPY]
  ,0 AS [TOReply_Amt_USD]
  ,0 AS [TOReply_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,0 AS [TOReply_Std_JPY]
  ,0 AS [TOReply_Std_USD]
  ,0 AS [TOReply_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,0 AS [TOReply_Qty]
  ,0 AS [GODemand_Amt_JPY]
  ,0 AS [GODemand_Amt_USD]
  ,0 AS [GODemand_Amt_EUR]
  ,0 AS [GODemand_V0_Amt_JPY]
  ,0 AS [GODemand_V0_Amt_USD]
  ,0 AS [GODemand_V0_Amt_EUR]
  ,0 AS [GODemand_V1_Amt_JPY]
  ,0 AS [GODemand_V1_Amt_USD]
  ,0 AS [GODemand_V1_Amt_EUR]
  ,0 AS [GODemand_Std_JPY]
  ,0 AS [GODemand_Std_USD]
  ,0 AS [GODemand_Std_EUR]
  ,0 AS [GODemand_V0_Std_JPY]
  ,0 AS [GODemand_V0_Std_USD]
  ,0 AS [GODemand_V0_Std_EUR]
  ,0 AS [GODemand_V1_Std_JPY]
  ,0 AS [GODemand_V1_Std_USD]
  ,0 AS [GODemand_V1_Std_EUR]
  ,0 AS [GODemand_Qty]
  ,0 AS [GODemand_V0_Qty]
  ,0 AS [GODemand_V1_Qty]
  ,0 AS [GOReply_Amt_JPY]
  ,0 AS [GOReply_Amt_USD]
  ,0 AS [GOReply_Amt_EUR]
  ,0 AS [GOReply_Std_JPY]
  ,0 AS [GOReply_Std_USD]
  ,0 AS [GOReply_Std_EUR]
  ,0 AS [GOReply_Qty]
  ,0 AS [ShippableAATP_Amt_JPY]
  ,0 AS [ShippableAATP_Amt_USD]
  ,0 AS [ShippableAATP_Amt_EUR]
  ,0 AS [ShippableAATP_Qty]
  ,0 AS [AdjustedSFOut_Amt_JPY]
  ,0 AS [AdjustedSFOut_Amt_USD]
  ,0 AS [AdjustedSFOut_Amt_EUR]
  ,0 AS [AdjustedSFOut_Qty]
  ,0 AS [JSF_Amt_JPY]
  ,0 AS [JSF_Amt_USD]
  ,0 AS [JSF_Amt_EUR]
  ,0 AS [JSF_V0_Amt_JPY]
  ,0 AS [JSF_V0_Amt_USD]
  ,0 AS [JSF_V0_Amt_EUR]
  ,0 AS [JSF_V1_Amt_JPY]
  ,0 AS [JSF_V1_Amt_USD]
  ,0 AS [JSF_V1_Amt_EUR]
  ,0 AS [JSF_Qty]
  ,0 AS [JSF_V0_Qty]
  ,0 AS [JSF_V1_Qty]
  ,[ProductionPlanning_Amt]     AS [ProductionPlanning_Amt_JPY]
  ,[ProductionPlanning_Amt_USD] AS [ProductionPlanning_Amt_USD]
  ,[ProductionPlanning_Amt_EUR] AS [ProductionPlanning_Amt_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_START
  ,[ProductionPlanning_Std]     AS [ProductionPlanning_Std_JPY]
  ,[ProductionPlanning_Std_USD] AS [ProductionPlanning_Std_USD]
  ,[ProductionPlanning_Std_EUR] AS [ProductionPlanning_Std_EUR]
--20190201_add_c.ma_標準原価ディメンションの非表示対応により派生した対応_END
  ,[ProductionPlanning_Qty]     AS [ProductionPlanning_Qty]
  ,0 AS [OSC_MoveAve_Cst]
  ,0 AS [OSC_MoveAve_GP_Amt]
  FROM [DM_SALES].[dbo].[TPRC_T_PRODUCTION_PLAN_REPLY]
) RAINBOWDATA
--20170201 明細データ開示対応 E N D
  LEFT OUTER JOIN [BI_DM].[dbo].[M_SCM_CUST] [SCM_MST]
    ON [SCM_MST].[SCM_CUSTOMER] = [RAINBOWDATA].[SCM_CUSTOMER_CD]

  LEFT OUTER JOIN [BI_DM].[dbo].[M_PNO_BOOK_PN] [BOOK_MST]
    ON [BOOK_MST].[BOOKING_PN_CD] = [RAINBOWDATA].[ORDER_PART_NO_CD]

  LEFT OUTER JOIN [BI_DM].[dbo].[M_APL_CUST_BOOK_PN] [APL_MST]
    ON [APL_MST].[SCM_CUSTOMER] = [RAINBOWDATA].[SCM_CUSTOMER_CD]
    AND [APL_MST].[BOOKING_PN_CD] = [RAINBOWDATA].[ORDER_PART_NO_CD]

--20181205 Liang 標準原価マスタIF停止に伴うAM残存資源の改修 START
  --LEFT OUTER JOIN [BI_DM].[dbo].[M_PNO_STANDARD_PRICE] [STD_PRC]
  --  ON [STD_PRC].[ORDER_PART_NO_CD] = [BOOK_MST].[ANCESTRAL_PART_NO_CD]
  LEFT OUTER JOIN [DM_MST].[dbo].[V_MST_BOOK_PN] [BOOK_PN]
    ON [BOOK_PN].[BOOKING_PN_CD] = [RAINBOWDATA].[ORDER_PART_NO_CD]
--20181205 Liang 標準原価マスタIF停止に伴うAM残存資源の改修 END

 WHERE [UPDATE_DATE] IN (SELECT [UPDATE_DATE]
--20170201 明細データ開示対応 START
                       --FROM [BI_DM].[dbo].[VD_SAL_RAINBOW_UPDATE]
                       FROM [DM_MST].[dbo].[VPRC_SDM_RAINBOW_UPDATE]
--20170201 明細データ開示対応 E N D
                       WHERE [LATEST_DATE_TYPE] IS NULL)

GO
