USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VT_SFM_BCCV_UNIQUE_OPPORTUNITY_SEQ_COUNT_L] AS
SELECT distinct 
   DISP_UPDATE_DATE
  ,CURRENCY_TYPE
  ,TARGET_NOMINATION_DATE
  ,TARGET_AWARD_DATE
  ,TARGET_NOMINATION_DATE_D
  ,TARGET_AWARD_DATE_D
  ,APPROVED_DATE
  ,SALES_ORDER_PN_FOR_MTF
  ,D_IN_SCM_CUST_CODE_FOR_MTF
  ,OPP_APPLICATION1_CODE
  ,OPP_APPLICATION2_CODE
  ,OPP_APPLICATION3_CODE
  ,OPPORTUNITY_NO
  ,OPPORTUNITY_SEQ AS UNIQUE_OPPORTUNITY_SEQ
  ,MP_START_DATE
  ,CURRENCY
  ,CALENDAR_YM
  ,CALENDAR_YEAR_MONTH_DATE
  ,CRM_APPROVALDATE
  ,CRM_APPROVELREQUESTDATE
  ,CRM_AWARDAPPROVEDDATE
  ,CREATEDDATE
  ,CRM_STATUSUPDATEDATE
  ,CRM_DINACTUALDATE
  ,CRM_DINACTUALNEWDATE
  ,CRM_DINAPPROVEDDATE
  ,CRM_DINDATE
  ,CRM_DINREQUESTDATE
  ,CRM_DINTARGETDATE
  ,CRM_DRAPPROVEDDATE
  ,CRM_DREXPIRATIONDATE
  ,CRM_EXCLUDEDISTI_COMMENTDATE
  ,LASTMODIFIEDDATE
  ,CRM_LASTSTAGEMODIFIEDDATE
  ,CRM_LATEST_COMMENTDATE
  ,CRM_MPEND
  ,CRM_NOMINATIONAPPROVEDDATE
  ,CRM_NOMINATIONREQUESTDATE
  ,CRM_S0ACTUALDATE
  ,CRM_S1ACTUALDATE
  ,CRM_S2ACTUALDATE
  ,CRM_S3ACTUALDATE
  ,CRM_S4ACTUALDATE
  ,CRM_USERLASTMODIFIEDDATE
from [BI_DM].[dbo].[F_SFM_OPP_PRD_DEMAND_AGGREGATE_L]
WHERE OPPORTUNITY_SEQ IS NOT NULL
GO