USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VT_SFM_BCCV_OPPORTUNITY_SEQ_COUNT_H] AS
SELECT distinct 
   DISP_UPDATE_DATE
  ,CURRENCY_TYPE
  ,CASE WHEN TARGET_NOMINATION_DATE IS NULL THEN TARGET_NOMINATION_DATE
   ELSE CAST((TARGET_NOMINATION_DATE + '/01') AS DATE)
   END AS TARGET_NOMINATION_DATE
  ,CASE WHEN TARGET_AWARD_DATE IS NULL THEN TARGET_AWARD_DATE
   ELSE CAST((TARGET_AWARD_DATE + '/01') AS DATE)
   END AS TARGET_AWARD_DATE
  ,TARGET_NOMINATION_DATE_D
  ,TARGET_AWARD_DATE_D
  ,APPROVED_DATE
  ,SALES_ORDER_PN_FOR_MTF
  ,D_IN_SCM_CUST_CODE_FOR_MTF
  ,OPP_APPLICATION1_CODE
  ,OPP_APPLICATION2_CODE
  ,OPP_APPLICATION3_CODE
  ,OPPORTUNITY_NO
  ,OPPORTUNITY_SEQ
  ,MP_START_DATE
  ,CURRENCY
  ,CALENDAR_YM
  ,UPDATE_DATE
from [BI_DM].[dbo].[F_SFM_OPP_PRD_DEMAND_H]
GO