USE [BI_DM]
GO

/****** Object:  View [dbo].[VPRC_FT_BUDGET_FIXED_TBLR]    Script Date: 2018/01/15 21:15:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VPRC_FT_BUDGET_FIXED_TBLR]
AS
WITH FIXED_BM AS (
SELECT [SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[BUSINESS_SITE]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,[VERSION_RESULT]
      ,[VERSION_OPEN]
      ,CUR_RATE.[CURR_CD_TO]          AS [CURRENCY_EXCH]
      ,[TO_AMT] * CUR_RATE.B_RATE     AS [TO_AMT_B]
      ,[TO_AMT] * CUR_RATE.M_RATE     AS [TO_AMT_M]
      ,[TO_STD] * CUR_RATE_STD.B_RATE AS [TO_STD_B]
      ,[TO_STD] * CUR_RATE_STD.M_RATE AS [TO_STD_M]
      ,[GO_AMT] * CUR_RATE.B_RATE     AS [GO_AMT_B]
      ,[GO_AMT] * CUR_RATE.M_RATE     AS [GO_AMT_M]
      ,[GO_STD] * CUR_RATE_STD.B_RATE AS [GO_STD_B]
      ,[GO_STD] * CUR_RATE_STD.M_RATE AS [GO_STD_M]
      ,[SO_AMT] * CUR_RATE.B_RATE     AS [SO_AMT_B]
      ,[SO_AMT] * CUR_RATE.M_RATE     AS [SO_AMT_M]
      ,[SO_STD] * CUR_RATE_STD.B_RATE AS [SO_STD_B]
      ,[SO_STD] * CUR_RATE_STD.M_RATE AS [SO_STD_M]
FROM [BI_DM].[dbo].[F_SAL_BUDGET_FIXED] FIXED
LEFT OUTER JOIN [DM_MST].[dbo].[VPRC_FSDM_OSC_CUR_RATE] CUR_RATE
  ON FIXED.[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
 AND FIXED.[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
LEFT OUTER JOIN [DM_MST].[dbo].[VPRC_FSDM_OSC_CUR_RATE] CUR_RATE_STD
  ON CUR_RATE_STD.[CURR_CD_FROM] = 'JPY'
 AND CUR_RATE.[CURR_CD_TO] = CUR_RATE_STD.[CURR_CD_TO]
 AND FIXED.[CALENDAR_YM] = CUR_RATE_STD.[VALID_FROM_YMD]
WHERE [CURRENCY_EXCH]='Input Currency'
),
FIXED_BM_INXS AS (
SELECT [SCM_CUSTOMER_CD]
      ,[ORDER_PART_NO_CD]
      ,[SEG_CD]
      ,[BUSINESS_SITE]
      ,[CALENDAR_YM]
      ,[CURRENCY]
      ,[VERSION_RESULT]
      ,[VERSION_OPEN]
      ,CUR_RATE.[CURR_CD_TO]          AS [CURRENCY_EXCH]
      ,[TO_AMT] * CUR_RATE.B_RATE     AS [TO_AMT_B]
      ,[TO_AMT] * CUR_RATE.M_RATE     AS [TO_AMT_M]
      ,[TO_STD] * CUR_RATE_STD.B_RATE AS [TO_STD_B]
      ,[TO_STD] * CUR_RATE_STD.M_RATE AS [TO_STD_M]
      ,[GO_AMT] * CUR_RATE.B_RATE     AS [GO_AMT_B]
      ,[GO_AMT] * CUR_RATE.M_RATE     AS [GO_AMT_M]
      ,[GO_STD] * CUR_RATE_STD.B_RATE AS [GO_STD_B]
      ,[GO_STD] * CUR_RATE_STD.M_RATE AS [GO_STD_M]
      ,[SO_AMT] * CUR_RATE.B_RATE     AS [SO_AMT_B]
      ,[SO_AMT] * CUR_RATE.M_RATE     AS [SO_AMT_M]
      ,[SO_STD] * CUR_RATE_STD.B_RATE AS [SO_STD_B]
      ,[SO_STD] * CUR_RATE_STD.M_RATE AS [SO_STD_M]
FROM [DM_SALES].[dbo].[TPRC_T_NREL_BUDGET] FIXED_INXS
LEFT OUTER JOIN [DM_MST].[dbo].[VPRC_FSDM_OSC_CUR_RATE] CUR_RATE
  ON FIXED_INXS.[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
 AND FIXED_INXS.[CALENDAR_YM] = CUR_RATE.[VALID_FROM_YMD]
LEFT OUTER JOIN [DM_MST].[dbo].[VPRC_FSDM_OSC_CUR_RATE] CUR_RATE_STD
  ON CUR_RATE_STD.[CURR_CD_FROM] = 'USD'
 AND CUR_RATE.[CURR_CD_TO] = CUR_RATE_STD.[CURR_CD_TO]
 AND FIXED_INXS.[CALENDAR_YM] = CUR_RATE_STD.[VALID_FROM_YMD]
WHERE [CURRENCY_EXCH]='Input Currency'
)

SELECT F_SAL_BUDGET_FIXED.[SCM_CUSTOMER_CD]
      ,F_SAL_BUDGET_FIXED.[ORDER_PART_NO_CD]
      ,F_SAL_BUDGET_FIXED.[SEG_CD]
      ,F_SAL_BUDGET_FIXED.[BUSINESS_SITE]
      ,F_SAL_BUDGET_FIXED.[CALENDAR_YM]
      ,F_SAL_BUDGET_FIXED.[CURRENCY]
      ,F_SAL_BUDGET_FIXED.[VERSION_RESULT]
      ,F_SAL_BUDGET_FIXED.[CURRENCY_EXCH]
      ,F_SAL_BUDGET_FIXED.[TO_AMT]   AS [TO_AMT_Q]
      ,CONVERT(money,FIXED_BM.[TO_AMT_B])           AS [TO_AMT_B]
      ,CONVERT(money,FIXED_BM.[TO_AMT_M])           AS [TO_AMT_M]
      ,F_SAL_BUDGET_FIXED.[TO_AMT_JPY]
      ,F_SAL_BUDGET_FIXED.[TO_STD]   AS [TO_STD_Q]
      ,CONVERT(money,FIXED_BM.[TO_STD_B])           AS [TO_STD_B]
      ,CONVERT(money,FIXED_BM.[TO_STD_M])           AS [TO_STD_M]
      ,F_SAL_BUDGET_FIXED.[TO_QTY]
      ,F_SAL_BUDGET_FIXED.[GO_AMT]   AS [GO_AMT_Q]
      ,CONVERT(money,FIXED_BM.[GO_AMT_B])           AS [GO_AMT_B]
      ,CONVERT(money,FIXED_BM.[GO_AMT_M])           AS [GO_AMT_M]
      ,F_SAL_BUDGET_FIXED.[GO_AMT_JPY]
      ,F_SAL_BUDGET_FIXED.[GO_STD]   AS [GO_STD_Q]
      ,CONVERT(money,FIXED_BM.[GO_STD_B])           AS [GO_STD_B]
      ,CONVERT(money,FIXED_BM.[GO_STD_M])           AS [GO_STD_M]
      ,F_SAL_BUDGET_FIXED.[GO_QTY]
      ,F_SAL_BUDGET_FIXED.[SO_AMT]   AS [SO_AMT_Q]
      ,CONVERT(money,FIXED_BM.[SO_AMT_B])           AS [SO_AMT_B]
      ,CONVERT(money,FIXED_BM.[SO_AMT_M])           AS [SO_AMT_M]
      ,F_SAL_BUDGET_FIXED.[SO_AMT_JPY]
      ,F_SAL_BUDGET_FIXED.[SO_STD]   AS [SO_STD_Q]
      ,CONVERT(money,FIXED_BM.[SO_STD_B])           AS [SO_STD_B]
      ,CONVERT(money,FIXED_BM.[SO_STD_M])           AS [SO_STD_M]
      ,F_SAL_BUDGET_FIXED.[SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_BUDGET_FIXED]
LEFT JOIN FIXED_BM
ON  ISNULL(F_SAL_BUDGET_FIXED.[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(FIXED_BM.[SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(FIXED_BM.[ORDER_PART_NO_CD],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[SEG_CD],'$$NULL$$') = ISNULL(FIXED_BM.[SEG_CD],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[BUSINESS_SITE],'$$NULL$$') = ISNULL(FIXED_BM.[BUSINESS_SITE],'$$NULL$$')
AND ISNULL(CONVERT(nvarchar,F_SAL_BUDGET_FIXED.[CALENDAR_YM],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,FIXED_BM.[CALENDAR_YM],112),'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[CURRENCY],'$$NULL$$') = ISNULL(FIXED_BM.[CURRENCY],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[VERSION_RESULT],'$$NULL$$') = ISNULL(FIXED_BM.[VERSION_RESULT],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[VERSION_OPEN],'$$NULL$$') = ISNULL(FIXED_BM.[VERSION_OPEN],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[CURRENCY_EXCH],'$$NULL$$') = ISNULL(FIXED_BM.[CURRENCY_EXCH],'$$NULL$$')
WHERE (F_SAL_BUDGET_FIXED.[VERSION_RESULT] IN (N'0', N'H'))

UNION ALL

SELECT F_SAL_BUDGET_FIXED.[SCM_CUSTOMER_CD]
      ,F_SAL_BUDGET_FIXED.[ORDER_PART_NO_CD]
      ,F_SAL_BUDGET_FIXED.[SEG_CD]
      ,F_SAL_BUDGET_FIXED.[BUSINESS_SITE]
      ,F_SAL_BUDGET_FIXED.[CALENDAR_YM]
      ,F_SAL_BUDGET_FIXED.[CURRENCY]
      ,F_SAL_BUDGET_FIXED.[VERSION_RESULT]
      ,F_SAL_BUDGET_FIXED.[CURRENCY_EXCH]
      ,F_SAL_BUDGET_FIXED.[TO_AMT]   AS [TO_AMT_Q]
      ,CONVERT(money,FIXED_BM.[TO_AMT_B])           AS [TO_AMT_B]
      ,CONVERT(money,FIXED_BM.[TO_AMT_M])           AS [TO_AMT_M]
      ,F_SAL_BUDGET_FIXED.[TO_AMT_JPY]
      ,F_SAL_BUDGET_FIXED.[TO_STD]   AS [TO_STD_Q]
      ,CONVERT(money,FIXED_BM.[TO_STD_B])           AS [TO_STD_B]
      ,CONVERT(money,FIXED_BM.[TO_STD_M])           AS [TO_STD_M]
      ,F_SAL_BUDGET_FIXED.[TO_QTY]
      ,F_SAL_BUDGET_FIXED.[GO_AMT]   AS [GO_AMT_Q]
      ,CONVERT(money,FIXED_BM.[GO_AMT_B])           AS [GO_AMT_B]
      ,CONVERT(money,FIXED_BM.[GO_AMT_M])           AS [GO_AMT_M]
      ,F_SAL_BUDGET_FIXED.[GO_AMT_JPY]
      ,F_SAL_BUDGET_FIXED.[GO_STD]   AS [GO_STD_Q]
      ,CONVERT(money,FIXED_BM.[GO_STD_B])           AS [GO_STD_B]
      ,CONVERT(money,FIXED_BM.[GO_STD_M])           AS [GO_STD_M]
      ,F_SAL_BUDGET_FIXED.[GO_QTY]
      ,F_SAL_BUDGET_FIXED.[SO_AMT]   AS [SO_AMT_Q]
      ,CONVERT(money,FIXED_BM.[SO_AMT_B])           AS [SO_AMT_B]
      ,CONVERT(money,FIXED_BM.[SO_AMT_M])           AS [SO_AMT_M]
      ,F_SAL_BUDGET_FIXED.[SO_AMT_JPY]
      ,F_SAL_BUDGET_FIXED.[SO_STD]   AS [SO_STD_Q]
      ,CONVERT(money,FIXED_BM.[SO_STD_B])           AS [SO_STD_B]
      ,CONVERT(money,FIXED_BM.[SO_STD_M])           AS [SO_STD_M]
      ,F_SAL_BUDGET_FIXED.[SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_BUDGET_FIXED]
LEFT JOIN FIXED_BM
ON  ISNULL(F_SAL_BUDGET_FIXED.[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(FIXED_BM.[SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(FIXED_BM.[ORDER_PART_NO_CD],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[SEG_CD],'$$NULL$$') = ISNULL(FIXED_BM.[SEG_CD],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[BUSINESS_SITE],'$$NULL$$') = ISNULL(FIXED_BM.[BUSINESS_SITE],'$$NULL$$')
AND ISNULL(CONVERT(nvarchar,F_SAL_BUDGET_FIXED.[CALENDAR_YM],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,FIXED_BM.[CALENDAR_YM],112),'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[CURRENCY],'$$NULL$$') = ISNULL(FIXED_BM.[CURRENCY],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[VERSION_RESULT],'$$NULL$$') = ISNULL(FIXED_BM.[VERSION_RESULT],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[VERSION_OPEN],'$$NULL$$') = ISNULL(FIXED_BM.[VERSION_OPEN],'$$NULL$$')
AND ISNULL(F_SAL_BUDGET_FIXED.[CURRENCY_EXCH],'$$NULL$$') = ISNULL(FIXED_BM.[CURRENCY_EXCH],'$$NULL$$')

WHERE (F_SAL_BUDGET_FIXED.[VERSION_RESULT] IN
(
SELECT MAX([VERSION_RESULT])
  FROM [BI_DM].[dbo].[F_SAL_BUDGET_FIXED]
 WHERE ([VERSION_RESULT] NOT IN (N'0', N'H', N'O')) ---N'1', N'2', N'3'
)
       )

--INXS‘Î‰ž
UNION ALL

SELECT
 TPRC_T_NREL_BUDGET.[SCM_CUSTOMER_CD]
,TPRC_T_NREL_BUDGET.[ORDER_PART_NO_CD]
,TPRC_T_NREL_BUDGET.[SEG_CD]
,TPRC_T_NREL_BUDGET.[BUSINESS_SITE]
,TPRC_T_NREL_BUDGET.[CALENDAR_YM]
,TPRC_T_NREL_BUDGET.[CURRENCY]
,TPRC_T_NREL_BUDGET.[VERSION_RESULT]
,TPRC_T_NREL_BUDGET.[CURRENCY_EXCH]
,TPRC_T_NREL_BUDGET.[TO_AMT]   AS [TO_AMT_Q]
,CONVERT(money,FIXED_BM_INXS.[TO_AMT_B])   AS [TO_AMT_B]
,CONVERT(money,FIXED_BM_INXS.[TO_AMT_M])   AS [TO_AMT_M]
,TPRC_T_NREL_BUDGET.[TO_AMT_JPY]
,TPRC_T_NREL_BUDGET.[TO_STD]   AS [TO_STD_Q]
,CONVERT(money,FIXED_BM_INXS.[TO_STD_B])   AS [TO_STD_B]
,CONVERT(money,FIXED_BM_INXS.[TO_STD_M])   AS [TO_STD_M]
,TPRC_T_NREL_BUDGET.[TO_QTY]
,TPRC_T_NREL_BUDGET.[GO_AMT]   AS [GO_AMT_Q]
,CONVERT(money,FIXED_BM_INXS.[GO_AMT_B])   AS [GO_AMT_B]
,CONVERT(money,FIXED_BM_INXS.[GO_AMT_M])   AS [GO_AMT_M]
,TPRC_T_NREL_BUDGET.[GO_AMT_JPY]
,TPRC_T_NREL_BUDGET.[GO_STD]   AS [GO_STD_Q]
,CONVERT(money,FIXED_BM_INXS.[GO_STD_B])   AS [GO_STD_B]
,CONVERT(money,FIXED_BM_INXS.[GO_STD_M])   AS [GO_STD_M]
,TPRC_T_NREL_BUDGET.[GO_QTY]
,TPRC_T_NREL_BUDGET.[SO_AMT]   AS [SO_AMT_Q]
,CONVERT(money,FIXED_BM_INXS.[SO_AMT_B])   AS [SO_AMT_B]
,CONVERT(money,FIXED_BM_INXS.[SO_AMT_M])   AS [SO_AMT_M]
,TPRC_T_NREL_BUDGET.[SO_AMT_JPY]
,TPRC_T_NREL_BUDGET.[SO_STD]   AS [SO_STD_Q]
,CONVERT(money,FIXED_BM_INXS.[SO_STD_B])   AS [SO_STD_B]
,CONVERT(money,FIXED_BM_INXS.[SO_STD_M])   AS [SO_STD_M]
,TPRC_T_NREL_BUDGET.[SO_QTY]
FROM [DM_SALES].[dbo].[TPRC_T_NREL_BUDGET]
LEFT JOIN FIXED_BM_INXS
ON  ISNULL(TPRC_T_NREL_BUDGET.[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[SCM_CUSTOMER_CD],'$$NULL$$')
AND ISNULL(TPRC_T_NREL_BUDGET.[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[ORDER_PART_NO_CD],'$$NULL$$')
AND ISNULL(TPRC_T_NREL_BUDGET.[SEG_CD],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[SEG_CD],'$$NULL$$')
AND ISNULL(TPRC_T_NREL_BUDGET.[BUSINESS_SITE],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[BUSINESS_SITE],'$$NULL$$')
AND ISNULL(CONVERT(nvarchar,TPRC_T_NREL_BUDGET.[CALENDAR_YM],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,FIXED_BM_INXS.[CALENDAR_YM],112),'$$NULL$$')
AND ISNULL(TPRC_T_NREL_BUDGET.[CURRENCY],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[CURRENCY],'$$NULL$$')
AND ISNULL(TPRC_T_NREL_BUDGET.[VERSION_RESULT],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[VERSION_RESULT],'$$NULL$$')
AND ISNULL(TPRC_T_NREL_BUDGET.[VERSION_OPEN],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[VERSION_OPEN],'$$NULL$$')
AND ISNULL(TPRC_T_NREL_BUDGET.[CURRENCY_EXCH],'$$NULL$$') = ISNULL(FIXED_BM_INXS.[CURRENCY_EXCH],'$$NULL$$')
;



GO


