USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[M_C_CURRENCY_FACT](
	[CURR_CD_FROM] [nvarchar](5) NOT NULL,
	[CURR_CD_TO] [nvarchar](5) NOT NULL,
	[VALID_FROM_YMD] [nvarchar](8) NOT NULL,
	[CURR_FACT_FROM] [decimal](18, 0) NULL,
	[CURR_FACT_TO] [decimal](18, 0) NULL,
 CONSTRAINT [PK_M_C_CURRENCY_FACT] PRIMARY KEY CLUSTERED 
(
	[CURR_CD_FROM] ASC,
	[CURR_CD_TO] ASC,
	[VALID_FROM_YMD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Dimension]
) ON [BI_DM_Dimension]

GO
