USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VF_SAL_ORDER] AS
SELECT
 [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, CASE
  WHEN DATEDIFF(mm, [RECORD_DATE], [RDLV_DATE])  <= -1 THEN -1
  WHEN DATEDIFF(mm, [RECORD_DATE], [RDLV_DATE])  >= 24 THEN 24
  ELSE DATEDIFF(mm, [RECORD_DATE], [RDLV_DATE])
  END AS [RDLV_DIFF]
, [CURRENCY_EXCH]
, SUM([TO_AMT_JPY]) AS [TO_AMT_JPY]
, SUM([TO_AMT_TTM]) AS [TO_AMT_TTM]
, SUM([TO_AMT_NET_EXCH]) AS [TO_AMT]
, SUM([TO_AMT_STD_EXCH]) AS [TO_AMT_STD]
, SUM([TO_QTY]) AS [TO_QTY]
, SUM([GO_AMT_JPY]) AS [GO_AMT_JPY]
, SUM([GO_AMT_TTM]) AS [GO_AMT_TTM]
, SUM([GO_AMT_NET_EXCH]) AS [GO_AMT]
, SUM([GO_AMT_STD_EXCH]) AS [GO_AMT_STD]
, SUM([GO_QTY]) AS [GO_QTY]
, SUM([SO_AMT_JPY]) AS [SO_AMT_JPY]
, SUM([SO_AMT_TTM]) AS [SO_AMT_TTM]
, SUM([SO_AMT_NET_EXCH]) AS [SO_AMT]
, SUM([SO_AMT_STD_EXCH]) AS [SO_AMT_STD]
, SUM([SO_QTY]) AS [SO_QTY]
FROM (

 SELECT
 [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, 'Input Currency' AS [CURRENCY_EXCH]
, [TO_AMT_JPY]
, 0 AS [TO_AMT_TTM]
, [TO_AMT_NET] AS [TO_AMT_NET_EXCH]
, [TO_AMT_STD] AS [TO_AMT_STD_EXCH]
, [TO_QTY]
, 0 AS [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, 0 AS [GO_AMT_NET_EXCH]
, 0 AS [GO_AMT_STD_EXCH]
, 0 AS [GO_QTY]
, 0 AS [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, 0 AS [SO_AMT_NET_EXCH]
, 0 AS [SO_AMT_STD_EXCH]
, 0 AS [SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_ORDER_TO]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, 'Input Currency' AS [CURRENCY_EXCH]
, 0 AS [TO_AMT_JPY]
, 0 AS [TO_AMT_TTM]
, 0 AS [TO_AMT_NET_EXCH]
, 0 AS [TO_AMT_STD_EXCH]
, 0 AS [TO_QTY]
, [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, [GO_AMT_NET] AS[GO_AMT_NET_EXCH]
, [GO_AMT_STD] AS [GO_AMT_STD_EXCH]
, [GO_QTY]
, 0 AS [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, 0 AS [SO_AMT_NET_EXCH]
, 0 AS [SO_AMT_STD_EXCH]
, 0 AS [SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_ORDER_GO]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, 'Input Currency' AS [CURRENCY_EXCH]
, 0 AS [TO_AMT_JPY]
, 0 AS [TO_AMT_TTM]
, 0 AS [TO_AMT_NET_EXCH]
, 0 AS [TO_AMT_STD_EXCH]
, 0 AS [TO_QTY]
, 0 AS [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, 0 AS [GO_AMT_NET_EXCH]
, 0 AS [GO_AMT_STD_EXCH]
, 0 AS [GO_QTY]
, [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, [SO_AMT_NET] AS [SO_AMT_NET_EXCH]
, [SO_AMT_STD] AS [SO_AMT_STD_EXCH]
, [SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_ORDER_SO]

UNION ALL

 SELECT
  [F_SAL_ORDER_TO_EXCH].[SCM_CUSTOMER_CD]
, [F_SAL_ORDER_TO_EXCH].[ORDER_PART_NO_CD]
, [F_SAL_ORDER_TO_EXCH].[SEG_CD]
, [F_SAL_ORDER_TO_EXCH].[CURRENCY]
, [F_SAL_ORDER_TO_EXCH].[RECORD_DATE]
, [F_SAL_ORDER_TO_EXCH].[ORDER_DATE]
, [F_SAL_ORDER_TO_EXCH].[RDLV_DATE]
, [F_SAL_ORDER_TO_EXCH].[CURRENCY_EXCH]
, 0 AS [TO_AMT_JPY]
, ( CASE WHEN [F_SAL_ORDER_TO_EXCH].[CURRENCY_EXCH] = 'JPY' 
         THEN [F_SAL_ORDER_TO].[TO_AMT_TTM]
	     ELSE 0
    END) AS [TO_AMT_TTM]
, [F_SAL_ORDER_TO_EXCH].[TO_AMT_NET_EXCH]
, [F_SAL_ORDER_TO_EXCH].[TO_AMT_STD_EXCH]
, [F_SAL_ORDER_TO_EXCH].[TO_QTY]
, 0 AS [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, 0 AS [GO_AMT_NET_EXCH]
, 0 AS [GO_AMT_STD_EXCH]
, 0 AS [GO_QTY]
, 0 AS [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, 0 AS [SO_AMT_NET_EXCH]
, 0 AS [SO_AMT_STD_EXCH]
, 0 AS [SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_ORDER_TO_EXCH]
LEFT OUTER JOIN [BI_DM].[dbo].[F_SAL_ORDER_TO]
  ON ISNULL([F_SAL_ORDER_TO_EXCH].[SCM_CUSTOMER_CD], ' ')  = ISNULL([F_SAL_ORDER_TO].[SCM_CUSTOMER_CD], ' ')
 AND ISNULL([F_SAL_ORDER_TO_EXCH].[ORDER_PART_NO_CD], ' ') = ISNULL([F_SAL_ORDER_TO].[ORDER_PART_NO_CD], ' ')
 AND ISNULL([F_SAL_ORDER_TO_EXCH].[SEG_CD], ' ')           = ISNULL([F_SAL_ORDER_TO].[SEG_CD], ' ')
 AND ISNULL([F_SAL_ORDER_TO_EXCH].[CURRENCY], ' ')         = ISNULL([F_SAL_ORDER_TO].[CURRENCY], ' ')
 AND ISNULL([F_SAL_ORDER_TO_EXCH].[RECORD_DATE], ' ')      = ISNULL([F_SAL_ORDER_TO].[RECORD_DATE], ' ')
 AND ISNULL([F_SAL_ORDER_TO_EXCH].[ORDER_DATE], ' ')       = ISNULL([F_SAL_ORDER_TO].[ORDER_DATE], ' ')
 AND ISNULL([F_SAL_ORDER_TO_EXCH].[RDLV_DATE], ' ')        = ISNULL([F_SAL_ORDER_TO].[RDLV_DATE], ' ')

UNION ALL

SELECT
  [F_SAL_ORDER_GO_EXCH].[SCM_CUSTOMER_CD]
, [F_SAL_ORDER_GO_EXCH].[ORDER_PART_NO_CD]
, [F_SAL_ORDER_GO_EXCH].[SEG_CD]
, [F_SAL_ORDER_GO_EXCH].[CURRENCY]
, [F_SAL_ORDER_GO_EXCH].[RECORD_DATE]
, [F_SAL_ORDER_GO_EXCH].[ORDER_DATE]
, [F_SAL_ORDER_GO_EXCH].[RDLV_DATE]
, [F_SAL_ORDER_GO_EXCH].[CURRENCY_EXCH]
, 0 AS [TO_AMT_JPY]
, 0 AS [TO_AMT_TTM]
, 0 AS [TO_AMT_NET_EXCH]
, 0 AS [TO_AMT_STD_EXCH]
, 0 AS [TO_QTY]
, 0 AS [GO_AMT_JPY]
, ( CASE WHEN [F_SAL_ORDER_GO_EXCH].[CURRENCY_EXCH] = 'JPY' 
         THEN [F_SAL_ORDER_GO].[GO_AMT_TTM]
	     ELSE 0
    END) AS [GO_AMT_TTM]
, [F_SAL_ORDER_GO_EXCH].[GO_AMT_NET_EXCH]
, [F_SAL_ORDER_GO_EXCH].[GO_AMT_STD_EXCH]
, [F_SAL_ORDER_GO_EXCH].[GO_QTY]
, 0 AS [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, 0 AS [SO_AMT_NET_EXCH]
, 0 AS [SO_AMT_STD_EXCH]
, 0 AS [SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_ORDER_GO_EXCH]
LEFT OUTER JOIN [BI_DM].[dbo].[F_SAL_ORDER_GO]
  ON ISNULL([F_SAL_ORDER_GO_EXCH].[SCM_CUSTOMER_CD], ' ')  = ISNULL([F_SAL_ORDER_GO].[SCM_CUSTOMER_CD], ' ')
 AND ISNULL([F_SAL_ORDER_GO_EXCH].[ORDER_PART_NO_CD], ' ') = ISNULL([F_SAL_ORDER_GO].[ORDER_PART_NO_CD], ' ')
 AND ISNULL([F_SAL_ORDER_GO_EXCH].[SEG_CD], ' ')           = ISNULL([F_SAL_ORDER_GO].[SEG_CD], ' ')
 AND ISNULL([F_SAL_ORDER_GO_EXCH].[CURRENCY], ' ')         = ISNULL([F_SAL_ORDER_GO].[CURRENCY], ' ')
 AND ISNULL([F_SAL_ORDER_GO_EXCH].[RECORD_DATE], ' ')      = ISNULL([F_SAL_ORDER_GO].[RECORD_DATE], ' ')
 AND ISNULL([F_SAL_ORDER_GO_EXCH].[ORDER_DATE], ' ')       = ISNULL([F_SAL_ORDER_GO].[ORDER_DATE], ' ')
 AND ISNULL([F_SAL_ORDER_GO_EXCH].[RDLV_DATE], ' ')        = ISNULL([F_SAL_ORDER_GO].[RDLV_DATE], ' ')

UNION ALL

SELECT
  [F_SAL_ORDER_SO_EXCH].[SCM_CUSTOMER_CD]
, [F_SAL_ORDER_SO_EXCH].[ORDER_PART_NO_CD]
, [F_SAL_ORDER_SO_EXCH].[SEG_CD]
, [F_SAL_ORDER_SO_EXCH].[CURRENCY]
, [F_SAL_ORDER_SO_EXCH].[RECORD_DATE]
, [F_SAL_ORDER_SO_EXCH].[ORDER_DATE]
, [F_SAL_ORDER_SO_EXCH].[RDLV_DATE]
, [F_SAL_ORDER_SO_EXCH].[CURRENCY_EXCH]
, 0 AS [TO_AMT_JPY]
, 0 AS [TO_AMT_TTM]
, 0 AS [TO_AMT_NET_EXCH]
, 0 AS [TO_AMT_STD_EXCH]
, 0 AS [TO_QTY]
, 0 AS [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, 0 AS [GO_AMT_NET_EXCH]
, 0 AS [GO_AMT_STD_EXCH]
, 0 AS [GO_QTY]
, 0 AS [SO_AMT_JPY]
, ( CASE WHEN [F_SAL_ORDER_SO_EXCH].[CURRENCY_EXCH] = 'JPY' 
         THEN [F_SAL_ORDER_SO].[SO_AMT_TTM]
	     ELSE 0
    END) AS [SO_AMT_TTM]
, [F_SAL_ORDER_SO_EXCH].[SO_AMT_NET_EXCH]
, [F_SAL_ORDER_SO_EXCH].[SO_AMT_STD_EXCH]
, [F_SAL_ORDER_SO_EXCH].[SO_QTY]
FROM [BI_DM].[dbo].[F_SAL_ORDER_SO_EXCH]
LEFT OUTER JOIN [BI_DM].[dbo].[F_SAL_ORDER_SO]
  ON ISNULL([F_SAL_ORDER_SO_EXCH].[SCM_CUSTOMER_CD], ' ')  = ISNULL([F_SAL_ORDER_SO].[SCM_CUSTOMER_CD], ' ')
 AND ISNULL([F_SAL_ORDER_SO_EXCH].[ORDER_PART_NO_CD], ' ') = ISNULL([F_SAL_ORDER_SO].[ORDER_PART_NO_CD], ' ')
 AND ISNULL([F_SAL_ORDER_SO_EXCH].[SEG_CD], ' ')           = ISNULL([F_SAL_ORDER_SO].[SEG_CD], ' ')
 AND ISNULL([F_SAL_ORDER_SO_EXCH].[CURRENCY], ' ')         = ISNULL([F_SAL_ORDER_SO].[CURRENCY], ' ')
 AND ISNULL([F_SAL_ORDER_SO_EXCH].[RECORD_DATE], ' ')      = ISNULL([F_SAL_ORDER_SO].[RECORD_DATE], ' ')
 AND ISNULL([F_SAL_ORDER_SO_EXCH].[ORDER_DATE], ' ')       = ISNULL([F_SAL_ORDER_SO].[ORDER_DATE], ' ')
 AND ISNULL([F_SAL_ORDER_SO_EXCH].[RDLV_DATE], ' ')        = ISNULL([F_SAL_ORDER_SO].[RDLV_DATE], ' ')

) BASE

GROUP BY [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [CURRENCY_EXCH]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]


GO
