USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VT_SFM_BCCV_AGGREGATE_L] AS

SELECT
--20180824 Latest CUBE仕様改修 関 Update start
-- DISP_UPDATE_DATE
--,UPDATE_DATE
--,CURRENCY_TYPE
 CRM_DISP_UPDATE_DATE AS DISP_UPDATE_DATE
,CRM_UPDATE_DATE AS UPDATE_DATE
,CRM_CURRENCY_TYPE AS CURRENCY_TYPE
--20180824 Latest CUBE仕様改修 関 Update end
,CRM_TARGETNOMINATIONDATE
,CRM_TARGETAWARDDATE
,CRM_APPROVALDATE
,CRM_MPSTART
--20180824 Latest CUBE仕様改修 関 Update start
--,CALENDAR_YM
--,OPPORTUNITY_NO
,CRM_CALENDAR_YM AS CALENDAR_YM
,CRM_OPPORTUNITY_NO AS OPPORTUNITY_NO
--20180824 Latest CUBE仕様改修 関 Update end
,CRM_UNIQUEOPPORTUNITY_SEQ
,CRM_FULFILLSCMCUSTOMERCODE
--20180824 Latest CUBE仕様改修 関 Update start
--,SALES_ORDER_PN_FOR_MTF
,CRM_SALES_ORDER_PN_FOR_MTF AS SALES_ORDER_PN_FOR_MTF
--20180824 Latest CUBE仕様改修 関 Update end
,CURRENCYISOCODE
,CRM_RFYCURRENTCOST
,CRM_RFYCURRENTGOGP
,CRM_RFYCURRENTGP
,CRM_RFYDINCOST
,CRM_RFYDINGOGP
,CRM_RFYDINGP
,CRM_RFYAPPROVEDAMOUNT
,CRM_RFYAPPROVEDQUANTITY
,CRM_RFYC
,CRM_RFYCURRENTAMOUNT
,CRM_RFYCURRENTGOAMOUNT
,CRM_RFYCURRENTQUANTITY
,CRM_RFYDINGOAMOUNT
--20180627 【CRM Aggregate対応】CUBE & 明細ビュー 王雅楠 start
,CRM_APPROVELREQUESTDATE
,CRM_AWARDAPPROVEDDATE
,CREATEDDATE
,CRM_STATUSUPDATEDATE
,CRM_DINACTUALDATE
,CRM_DINACTUALNEWDATE
,CRM_DINAPPROVEDDATE
,CRM_DINDATE
,CRM_DINREQUESTDATE
,CRM_DINTARGETDATE
,CRM_DRAPPROVEDDATE
,CRM_DREXPIRATIONDATE
,CRM_EXCLUDEDISTI_COMMENTDATE
,LASTMODIFIEDDATE
,CRM_LASTSTAGEMODIFIEDDATE
,CRM_LATEST_COMMENTDATE
,CRM_MPEND
,CRM_NOMINATIONAPPROVEDDATE
,CRM_NOMINATIONREQUESTDATE
,CRM_S0ACTUALDATE
,CRM_S1ACTUALDATE
,CRM_S2ACTUALDATE
,CRM_S3ACTUALDATE
,CRM_S4ACTUALDATE
,CRM_USERLASTMODIFIEDDATE
--20180627 【CRM Aggregate対応】CUBE & 明細ビュー 王雅楠 end
--20180824 Latest CUBE仕様改修 関 Update start
--FROM [BI_DM].[dbo].[F_SFM_AGGREGATE_L]
FROM [BI_DM].[dbo].[F_SFM_OPP_PRD_DEMAND_AGGREGATE_L]
WHERE CRM_UNIQUEOPPORTUNITY_SEQ IS NOT NULL
--20180824 Latest CUBE仕様改修 関 Update end
GO
