USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VF_SAL_BILL_SEG] AS
SELECT
  [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, [SHIPTO_DATE]
, [CURRENCY_EXCH]
, SUM([GO_AMT_JPY]) AS [GO_AMT_JPY]
, SUM([GO_AMT_TTM]) AS [GO_AMT_TTM]
, SUM([GO_AMT_NET_EXCH]) AS [GO_AMT]
, SUM([GO_AMT_STD_EXCH]) AS [GO_AMT_STD]
, SUM([GO_AMT_NET_EXCH_MLR]) AS [GO_AMT_MLR]
, SUM([GO_AMT_STD_EXCH_MLR]) AS [GO_AMT_STD_MLR]
, SUM([GO_QTY]) AS [GO_QTY]
, SUM([GO_AMT_TP1]) AS [GO_AMT_TP1]
, SUM([GO_AMT_TP2]) AS [GO_AMT_TP2]
, SUM([GO_AMT_STD_USER_EXCH]) AS [GO_AMT_STD_USER]
, SUM([GO_AMT_STD_USER_EXCH_MLR]) AS [GO_AMT_STD_USER_MLR]
, SUM([GO_AMT_SRP]) AS [GO_AMT_SRP]
, SUM([SO_AMT_JPY]) AS [SO_AMT_JPY]
, SUM([SO_AMT_TTM]) AS [SO_AMT_TTM]
, SUM([SO_AMT_NET_EXCH]) AS [SO_AMT]
, SUM([SO_AMT_STD_EXCH]) AS [SO_AMT_STD]
, SUM([SO_AMT_NET_EXCH_MLR]) AS [SO_AMT_MLR]
, SUM([SO_AMT_STD_EXCH_MLR]) AS [SO_AMT_STD_MLR]
, SUM([SO_QTY]) AS [SO_QTY]
, SUM([SO_AMT_TP1]) AS [SO_AMT_TP1]
, SUM([SO_AMT_TP2]) AS [SO_AMT_TP2]
, SUM([SO_AMT_STD_USER_EXCH]) AS [SO_AMT_STD_USER]
, SUM([SO_AMT_STD_USER_EXCH_MLR]) AS [SO_AMT_STD_USER_MLR]
, SUM([SO_AMT_SRP]) AS [SO_AMT_SRP]
, SUM([OSC_MoveAve_Cst]) AS [OSC_MoveAve_Cst]
, SUM([OSC_MoveAve_GP_Amt]) AS [OSC_MoveAve_GP_Amt]
, '0000000-00' AS OPPSEQ
, '0.non' AS PROBABILITY
, 0 AS LTVACCURACY
, 0 AS MTFRATE
, 'B0' AS STAGEDIV
, CAST('9999-12-31' AS DATE) AS DINPLANDATE
FROM (
SELECT
 [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, [SHIPTO_DATE]
, 'Input Currency' AS [CURRENCY_EXCH]
, [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, [GO_AMT_NET] AS [GO_AMT_NET_EXCH]
, [GO_AMT_STD] AS [GO_AMT_STD_EXCH]
, [GO_AMT_NET] AS [GO_AMT_NET_EXCH_MLR]
, [GO_AMT_STD] AS [GO_AMT_STD_EXCH_MLR]
, [GO_QTY]
, 0 AS [GO_AMT_TP1]
, 0 AS [GO_AMT_TP2]
, [GO_AMT_STD_USER] AS [GO_AMT_STD_USER_EXCH]
, [GO_AMT_STD_USER] AS [GO_AMT_STD_USER_EXCH_MLR]
, 0 AS [GO_AMT_SRP]
, 0 AS [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, 0 AS [SO_AMT_NET_EXCH]
, 0 AS [SO_AMT_STD_EXCH]
, 0 AS [SO_AMT_NET_EXCH_MLR]
, 0 AS [SO_AMT_STD_EXCH_MLR]
, 0 AS [SO_QTY]
, 0 AS [SO_AMT_TP1]
, 0 AS [SO_AMT_TP2]
, 0 AS [SO_AMT_STD_USER_EXCH]
, 0 AS [SO_AMT_STD_USER_EXCH_MLR]
, 0 AS [SO_AMT_SRP]
, 0 AS [OSC_MoveAve_Cst]
, 0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_BILL_GO]

UNION ALL

SELECT
 [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, [SHIPTO_DATE]
, 'Input Currency' AS [CURRENCY_EXCH]
, 0 AS [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, 0 AS [GO_AMT_NET_EXCH]
, 0 AS [GO_AMT_STD_EXCH]
, 0 AS [GO_AMT_NET_EXCH_MLR]
, 0 AS [GO_AMT_STD_EXCH_MLR]
, 0 AS [GO_QTY]
, 0 AS [GO_AMT_TP1]
, 0 AS [GO_AMT_TP2]
, 0 AS [GO_AMT_STD_USER_EXCH]
, 0 AS [GO_AMT_STD_USER_EXCH_MLR]
, 0 AS [GO_AMT_SRP]
, [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, [SO_AMT_NET] AS [SO_AMT_NET_EXCH]
, [SO_AMT_STD] AS [SO_AMT_STD_EXCH]
, [SO_AMT_NET] AS [SO_AMT_NET_EXCH_MLR]
, [SO_AMT_STD] AS [SO_AMT_STD_EXCH_MLR]
, [SO_QTY]
, 0 AS [SO_AMT_TP1]
, 0 AS [SO_AMT_TP2]
, [SO_AMT_STD_USER] AS [SO_AMT_STD_USER_EXCH]
, [SO_AMT_STD_USER] AS [SO_AMT_STD_USER_EXCH_MLR]
, 0 AS [SO_AMT_SRP]
, 0 AS [OSC_MoveAve_Cst]
, 0 AS [OSC_MoveAve_GP_Amt]
FROM [BI_DM].[dbo].[F_SAL_BILL_SO]

UNION ALL

SELECT 
  [F_SAL_BILL_GO_EXCH_MLR].[SCM_CUSTOMER_CD]
, [F_SAL_BILL_GO_EXCH_MLR].[ORDER_PART_NO_CD]
, [F_SAL_BILL_GO_EXCH_MLR].[SEG_CD]
, [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY]
, [F_SAL_BILL_GO_EXCH_MLR].[RECORD_DATE]
, [F_SAL_BILL_GO_EXCH_MLR].[ORDER_DATE]
, [F_SAL_BILL_GO_EXCH_MLR].[RDLV_DATE]
, [F_SAL_BILL_GO_EXCH_MLR].[SHIPTO_DATE]
, [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY_EXCH]
, 0 AS [GO_AMT_JPY]
, (CASE WHEN [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_GO].[GO_AMT_TTM] 
        ELSE 0 
   END) AS [GO_AMT_TTM]
, [F_SAL_BILL_GO_EXCH_MLR].[GO_AMT_NET_EXCH]
, [F_SAL_BILL_GO_EXCH_MLR].[GO_AMT_STD_EXCH]
, [F_SAL_BILL_GO_EXCH_MLR].[GO_AMT_NET_EXCH_MLR]
, [F_SAL_BILL_GO_EXCH_MLR].[GO_AMT_STD_EXCH_MLR]
, [F_SAL_BILL_GO_EXCH_MLR].[GO_QTY]
, (CASE WHEN [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_GO].[GO_AMT_TP1] 
        ELSE 0 
   END) AS [GO_AMT_TP1]
, (CASE WHEN [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_GO].[GO_AMT_TP2] 
         ELSE 0 
   END) AS [GO_AMT_TP2]
, [F_SAL_BILL_GO_EXCH_MLR].[GO_AMT_STD_USER_EXCH]
, [F_SAL_BILL_GO_EXCH_MLR].[GO_AMT_STD_USER_EXCH_MLR]
, (CASE WHEN [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_GO].[GO_AMT_SRP] 
        ELSE 0 
   END) AS [GO_AMT_SRP]
, 0 AS [SO_AMT_JPY]
, 0 AS [SO_AMT_TTM]
, 0 AS [SO_AMT_NET_EXCH]
, 0 AS [SO_AMT_STD_EXCH]
, 0 AS [SO_AMT_NET_EXCH_MLR]
, 0 AS [SO_AMT_STD_EXCH_MLR]
, 0 AS [SO_QTY]
, 0 AS [SO_AMT_TP1]
, 0 AS [SO_AMT_TP2]
, 0 AS [SO_AMT_STD_USER_EXCH]
, 0 AS [SO_AMT_STD_USER_EXCH_MLR]
, 0 AS [SO_AMT_SRP]
, (CASE WHEN [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_GO].[OSC_MoveAve_Cst] 
        ELSE 0 
   END) AS [OSC_MoveAve_Cst]
, (CASE WHEN [F_SAL_BILL_GO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_GO].[OSC_MoveAve_GP_Amt] 
        ELSE 0 
   END) AS [OSC_MoveAve_GP_Amt]
  FROM [BI_DM].[dbo].[F_SAL_BILL_GO_EXCH_MLR]
LEFT OUTER JOIN [BI_DM].[dbo].[F_SAL_BILL_GO]
 ON ISNULL([F_SAL_BILL_GO_EXCH_MLR].[SCM_CUSTOMER_CD], ' ')  = ISNULL([F_SAL_BILL_GO].[SCM_CUSTOMER_CD], ' ')
AND ISNULL([F_SAL_BILL_GO_EXCH_MLR].[ORDER_PART_NO_CD], ' ') = ISNULL([F_SAL_BILL_GO].[ORDER_PART_NO_CD], ' ')
AND ISNULL([F_SAL_BILL_GO_EXCH_MLR].[SEG_CD], ' ')           = ISNULL([F_SAL_BILL_GO].[SEG_CD], ' ')
AND ISNULL([F_SAL_BILL_GO_EXCH_MLR].[CURRENCY], ' ')         = ISNULL([F_SAL_BILL_GO].[CURRENCY], ' ')
AND ISNULL([F_SAL_BILL_GO_EXCH_MLR].[RECORD_DATE], ' ')      = ISNULL([F_SAL_BILL_GO].[RECORD_DATE], ' ')
AND ISNULL([F_SAL_BILL_GO_EXCH_MLR].[ORDER_DATE], ' ')       = ISNULL([F_SAL_BILL_GO].[ORDER_DATE], ' ')
AND ISNULL([F_SAL_BILL_GO_EXCH_MLR].[RDLV_DATE], ' ')        = ISNULL([F_SAL_BILL_GO].[RDLV_DATE], ' ')
AND ISNULL([F_SAL_BILL_GO_EXCH_MLR].[SHIPTO_DATE], ' ')      = ISNULL([F_SAL_BILL_GO].[SHIPTO_DATE], ' ')

UNION ALL

SELECT 
  [F_SAL_BILL_SO_EXCH_MLR].[SCM_CUSTOMER_CD]
, [F_SAL_BILL_SO_EXCH_MLR].[ORDER_PART_NO_CD]
, [F_SAL_BILL_SO_EXCH_MLR].[SEG_CD]
, [F_SAL_BILL_SO_EXCH_MLR].[CURRENCY]
, [F_SAL_BILL_SO_EXCH_MLR].[RECORD_DATE]
, [F_SAL_BILL_SO_EXCH_MLR].[ORDER_DATE]
, [F_SAL_BILL_SO_EXCH_MLR].[RDLV_DATE]
, [F_SAL_BILL_SO_EXCH_MLR].[SHIPTO_DATE]
, [F_SAL_BILL_SO_EXCH_MLR].[CURRENCY_EXCH]
, 0 AS [GO_AMT_JPY]
, 0 AS [GO_AMT_TTM]
, 0 AS [GO_AMT_NET_EXCH]
, 0 AS [GO_AMT_STD_EXCH]
, 0 AS [GO_AMT_NET_EXCH_MLR]
, 0 AS [GO_AMT_STD_EXCH_MLR]
, 0 AS [GO_QTY]
, 0 AS [GO_AMT_TP1]
, 0 AS [GO_AMT_TP2]
, 0 AS [GO_AMT_STD_USER_EXCH]
, 0 AS [GO_AMT_STD_USER_EXCH_MLR]
, 0 AS [GO_AMT_SRP]
, 0 AS [SO_AMT_JPY]
, (CASE WHEN [F_SAL_BILL_SO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_SO].[SO_AMT_TTM] 
        ELSE 0 
   END) AS [SO_AMT_TTM]
, [F_SAL_BILL_SO_EXCH_MLR].[SO_AMT_NET_EXCH]
, [F_SAL_BILL_SO_EXCH_MLR].[SO_AMT_STD_EXCH]
, [F_SAL_BILL_SO_EXCH_MLR].[SO_AMT_NET_EXCH_MLR]
, [F_SAL_BILL_SO_EXCH_MLR].[SO_AMT_STD_EXCH_MLR]
, [F_SAL_BILL_SO_EXCH_MLR].[SO_QTY]
, (CASE WHEN [F_SAL_BILL_SO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_SO].[SO_AMT_TP1] 
        ELSE 0 
   END) AS [SO_AMT_TP1]
, (CASE WHEN [F_SAL_BILL_SO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_SO].[SO_AMT_TP2] 
        ELSE 0 
   END) AS [SO_AMT_TP2]
, [F_SAL_BILL_SO_EXCH_MLR].[SO_AMT_STD_USER_EXCH]
, [F_SAL_BILL_SO_EXCH_MLR].[SO_AMT_STD_USER_EXCH_MLR]
, (CASE WHEN [F_SAL_BILL_SO_EXCH_MLR].[CURRENCY_EXCH] = 'JPY'
        THEN [F_SAL_BILL_SO].[SO_AMT_SRP] 
        ELSE 0 
   END) AS [SO_AMT_SRP]
, 0 AS [OSC_MoveAve_Cst]
, 0 AS [OSC_MoveAve_GP_Amt]
  FROM [BI_DM].[dbo].[F_SAL_BILL_SO_EXCH_MLR]
LEFT OUTER JOIN [BI_DM].[dbo].[F_SAL_BILL_SO]
 ON ISNULL([F_SAL_BILL_SO_EXCH_MLR].[SCM_CUSTOMER_CD], ' ')  = ISNULL([F_SAL_BILL_SO].[SCM_CUSTOMER_CD], ' ')
AND ISNULL([F_SAL_BILL_SO_EXCH_MLR].[ORDER_PART_NO_CD], ' ') = ISNULL([F_SAL_BILL_SO].[ORDER_PART_NO_CD], ' ')
AND ISNULL([F_SAL_BILL_SO_EXCH_MLR].[SEG_CD], ' ')           = ISNULL([F_SAL_BILL_SO].[SEG_CD], ' ')
AND ISNULL([F_SAL_BILL_SO_EXCH_MLR].[CURRENCY], ' ')         = ISNULL([F_SAL_BILL_SO].[CURRENCY], ' ')
AND ISNULL([F_SAL_BILL_SO_EXCH_MLR].[RECORD_DATE], ' ')      = ISNULL([F_SAL_BILL_SO].[RECORD_DATE], ' ')
AND ISNULL([F_SAL_BILL_SO_EXCH_MLR].[ORDER_DATE], ' ')       = ISNULL([F_SAL_BILL_SO].[ORDER_DATE], ' ')
AND ISNULL([F_SAL_BILL_SO_EXCH_MLR].[RDLV_DATE], ' ')        = ISNULL([F_SAL_BILL_SO].[RDLV_DATE], ' ')
AND ISNULL([F_SAL_BILL_SO_EXCH_MLR].[SHIPTO_DATE], ' ')      = ISNULL([F_SAL_BILL_SO].[SHIPTO_DATE], ' ')

) BASE

GROUP BY [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, [SHIPTO_DATE]
, [CURRENCY_EXCH]


GO
