USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VD_SFM_BCCV_D_IN_TARGET_PRD_H] AS
SELECT
   OPPORTUNITY_SEQ
  ,SCM_CUSTOMER_CODE
  ,D_IN_TARGET_YEAR
  ,D_IN_INPUT_YEAR
  ,D_IN_TARGET_PROBABILITY
  ,APPLICATION1_CODE
  ,APPLICATION2_CODE
  ,APPLICATION3_CODE
  ,PART_NO
  ,CURRENCY_ISO_CODE
  ,UPDATE_DATE
FROM
  [BI_DM].[dbo].[F_SFM_D_IN_TARGET_H]
--CDC CRM明細ビューAggregate対応 2018/06/20 START 
WHERE CURRENCY_TYPE = 'Input Currency'
--CDC CRM明細ビューAggregate対応 2018/06/20 END
GO


