USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VT_SFM_BCCV_AGGREGATE_SUMMARY_L] AS

SELECT
 DISP_UPDATE_DATE
,UPDATE_DATE
,CURRENCY_TYPE
,CRM_TARGETNOMINATIONDATE
,CRM_TARGETAWARDDATE
,CRM_APPROVALDATE
,CRM_MPSTART
,OPPORTUNITY_NO
,CRM_UNIQUEOPPORTUNITY_SEQ
,CRM_FULFILLSCMCUSTOMERCODE
,SALES_ORDER_PN_FOR_MTF 
,CURRENCYISOCODE
,CRM_RFYTOTALAWARDAPPROVEDAMT
,CRM_RFYTOTALCURRENTAMOUNT
,CRM_RFYTOTALCURRENTGOAMOUNT
,CRM_RFYTOTALCURRENTQUANTITY
,CRM_RFYTOTALCURRENTCOST
,CRM_RFYTOTALCURRENTGOGP
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲 start
--CRM_RFYTOTALCURRENTGOGPPERCENT 
,CRM_RFYTOTALCURRENTGOGPPERCENT*0.01 AS CRM_RFYTOTALCURRENTGOGPPERCENT
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲　end　
,CRM_RFYTOTALCURRENTGOGPOFREM
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲 start
--CRM_RFYTOTALGOGPPERCENTOFREM
,CRM_RFYTOTALGOGPPERCENTOFREM*0.01 AS CRM_RFYTOTALGOGPPERCENTOFREM
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲 end　　
,CRM_RFYTOTALCURRENTGP
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲 start
--CRM_RFYTOTALCURRNETGPPERCENT
,CRM_RFYTOTALCURRNETGPPERCENT*0.01 AS CRM_RFYTOTALCURRNETGPPERCENT
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲 end　　
,CRM_RFYTOTALDINAMOUNT 
,CRM_RFYTOTALDINGOAMOUNT
,CRM_RFYTOTALDINQUANTITY
,CRM_RFYTOTALDINCOST
,CRM_RFYTOTALDINGOGP
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲 start
--CRM_RFYTOTALDINGOGPPERCENT
,CRM_RFYTOTALDINGOGPPERCENT*0.01 AS CRM_RFYTOTALDINGOGPPERCENT
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲　end　
,CRM_RFYTOTALDINGP
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲 start
--CRM_RFYTOTALDINGPPERCENT
,CRM_RFYTOTALDINGPPERCENT*0.01 AS CRM_RFYTOTALDINGPPERCENT 
--20190301  CRM Cube パーセント表示メジャー項目ー王　金玲　end
,CRM_DAYSTOMP
,CRM_DELTAAMOUNTCURRENTANDDIN
,CRM_MOSTLATESTLTQ
,CRM_CURRENTLTQ
,CRM_MOSTLATESTLTV
,CRM_CURRENTLTV
,CRM_QTYUNIT
--20180627 【CRM Aggregate対応】CUBE & 明細ビュー 王雅楠 start
,CRM_APPROVELREQUESTDATE
,CRM_AWARDAPPROVEDDATE
,CREATEDDATE
,CRM_STATUSUPDATEDATE
,CRM_DINACTUALDATE
,CRM_DINACTUALNEWDATE
,CRM_DINAPPROVEDDATE
,CRM_DINDATE
,CRM_DINREQUESTDATE
,CRM_DINTARGETDATE
,CRM_DRAPPROVEDDATE
,CRM_DREXPIRATIONDATE
,CRM_EXCLUDEDISTI_COMMENTDATE
,LASTMODIFIEDDATE
,CRM_LASTSTAGEMODIFIEDDATE
,CRM_LATEST_COMMENTDATE
,CRM_MPEND
,CRM_NOMINATIONAPPROVEDDATE
,CRM_NOMINATIONREQUESTDATE
,CRM_S0ACTUALDATE
,CRM_S1ACTUALDATE
,CRM_S2ACTUALDATE
,CRM_S3ACTUALDATE
,CRM_S4ACTUALDATE
,CRM_USERLASTMODIFIEDDATE
--20180627 【CRM Aggregate対応】CUBE & 明細ビュー 王雅楠 end
FROM [BI_DM].[dbo].[F_SFM_AGGREGATE_SUMMARY_L]

GO