USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_SAL_OPPORTUNITY](
	[SCM_CUSTOMER_CD] [nvarchar](10) NULL,
	[ORDER_PART_NO_CD] [nvarchar](18) NULL,
	[SEG_CD] [nvarchar](28) NULL,
	[CALENDAR_YM] [date] NOT NULL,
	[CURRENCY] [nvarchar](5) NULL,
	[CURRENCY_EXCH] [nvarchar](14) NULL,
	[DATATYPE] [nvarchar](1) NOT NULL,
	[S1_AMT] [money] NULL,
	[S1_STD] [money] NULL,
	[S1_QTY] [decimal](20, 4) NULL,
	[S2_AMT] [money] NULL,
	[S2_STD] [money] NULL,
	[S2_QTY] [decimal](20, 4) NULL,
	[S3_AMT] [money] NULL,
	[S3_STD] [money] NULL,
	[S3_QTY] [decimal](20, 4) NULL,
	[S4_AMT] [money] NULL,
	[S4_STD] [money] NULL,
	[S4_QTY] [decimal](20, 4) NULL,
	[InsertDatetime] [datetime] NULL,
	[UpdateDatetime] [datetime] NULL
) ON [PS_PartitionByMonth_DM]([CALENDAR_YM])
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [I_F_SAL_OPPORTUNITY_1] ON [dbo].[F_SAL_OPPORTUNITY]
(
	[SCM_CUSTOMER_CD] ASC,
	[ORDER_PART_NO_CD] ASC,
	[SEG_CD] ASC,
	[CALENDAR_YM] ASC,
	[CURRENCY] ASC,
	[CURRENCY_EXCH] ASC,
	[DATATYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [PS_PartitionByMonth_DM]([CALENDAR_YM])
GO
