USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_WA_R_DAT_EXECTIVE_MEETING]
AS
SELECT 
		CONVERT(date,DAT_002) AS MEETING_DT
		,CONVERT(date,DAT_003) AS INPUT_DEADLINE
		,CONVERT(date,DAT_004) AS PUBLISH_DT
		,DAT_005 AS NENKI
		,CONCAT(LEFT(DAT_001,4),'/',RIGHT(DAT_001,2)) AS YEAR_MONTH
FROM OPENQUERY([WA]
	, 'SELECT * FROM UWA00001.R_DAT') D
WHERE D.DAT_ID = 'DAT0000003'


GO
