USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[F_VT_SFM_BCCV_PRODUCT_HISTORY_H_CRM](
	[PRODUCT_HISTORY_NO] [nvarchar](13) NOT NULL,
	[OPPORTUNITY_SEQ] [nvarchar](13) NULL,
	[OPPORTUNITY_NO] [nvarchar](7) NULL,
	[D_IN_DATE] [date] NULL,
	[CURRENCY_ISO_CODE] [nvarchar](3) NULL,
	[CURRENCY_TYPE] [nvarchar](14) NULL,
	[D_IN_SCM_CUST_CODE_FOR_MTF] [nvarchar](10) NULL,
	[SALES_ORDER_PN_FOR_MTF] [nvarchar](18) NULL,
	[APPLICATION1_CODE] [nvarchar](1) NULL,
	[APPLICATION2_CODE] [nvarchar](2) NULL,
	[APPLICATION3_CODE] [nvarchar](3) NULL,
	[UPDATE_DATE] [date] NULL,
	[DISP_UPDATE_DATE] [varchar](8) NULL,
	[AMOUNT_DIFFERENCE] [numeric](38, 4) NULL,
	[AMOUNT] [numeric](38, 4) NULL,
	[QUANTITY_DIFFERENCE] [numeric](18, 0) NULL,
	[QUANTITY] [numeric](18, 0) NULL
) ON [BI_DM_Fact_NonPartition]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [I_F_VT_SFM_BCCV_PRODUCT_HISTORY_H_CRM_1] ON [dbo].[F_VT_SFM_BCCV_PRODUCT_HISTORY_H_CRM]
(
	[PRODUCT_HISTORY_NO] ASC,
	[OPPORTUNITY_SEQ] ASC,
	[UPDATE_DATE] ASC,
	[DISP_UPDATE_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE) ON [BI_DM_Fact_NonPartition]
GO
