USE [BI_DM]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VT_SFM_BCCV_PRODUCT_HISTORY_H] AS
SELECT
   PRO_HIS_H.PRODUCT_HISTORY_NO
  ,PRO_HIS_H.OPPORTUNITY_SEQ
  ,PRO_HIS_H.OPPORTUNITY_NO
  ,PRO_HIS_H.D_IN_DATE
  ,PRO_HIS_H.CURRENCY_ISO_CODE
  ,PRO_HIS_H.CURRENCY_TYPE
  ,PRO_HIS_H.D_IN_SCM_CUST_CODE_FOR_MTF
  ,PRO_HIS_H.SALES_ORDER_PN_FOR_MTF
  ,PRO_HIS_H.APPLICATION1_CODE
  ,PRO_HIS_H.APPLICATION2_CODE
  ,PRO_HIS_H.APPLICATION3_CODE
  ,PRO_HIS_H.UPDATE_DATE
  ,REPLACE(CAST(PRO_HIS_H.UPDATE_DATE AS CHAR(10)) ,'-', '') AS DISP_UPDATE_DATE
  ,PRO_HIS_H.AMOUNT_DIFFERENCE
  ,PRO_HIS_H.AMOUNT
  ,PRO_HIS_H.QUANTITY_DIFFERENCE
  ,PRO_HIS_H.QUANTITY
FROM
  [BI_DM].[dbo].[F_SFM_PRODUCT_HISTORY_H] PRO_HIS_H

GO