USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VF_SAL_BACKLOG] AS
SELECT
 [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, CASE
  WHEN DATEDIFF(mm, [RECORD_DATE], [RDLV_DATE])  <= -1 THEN -1
  WHEN DATEDIFF(mm, [RECORD_DATE], [RDLV_DATE])  >= 24 THEN 24
  ELSE DATEDIFF(mm, [RECORD_DATE], [RDLV_DATE])
  END AS [RDLV_DIFF]
, [CURRENCY_EXCH]
, SUM([TO_AMT_JPY]) AS [TO_AMT_JPY]
, SUM([TO_AMT_NET_EXCH]) AS [TO_AMT]
, SUM([TO_AMT_STD_EXCH]) AS [TO_AMT_STD]
, SUM([TO_QTY]) AS [TO_QTY]
, SUM([GO_AMT_JPY]) AS [GO_AMT_JPY]
, SUM([GO_AMT_NET_EXCH]) AS [GO_AMT]
, SUM([GO_AMT_STD_EXCH]) AS [GO_AMT_STD]
, SUM([GO_QTY]) AS [GO_QTY]
, SUM([SO_AMT_JPY]) AS [SO_AMT_JPY]
, SUM([SO_AMT_NET_EXCH]) AS [SO_AMT]
, SUM([SO_AMT_STD_EXCH]) AS [SO_AMT_STD]
, SUM([SO_QTY]) AS [SO_QTY]
FROM (
	SELECT
	  [SCM_CUSTOMER_CD]
	, [ORDER_PART_NO_CD]
	, [SEG_CD]
	, [CURRENCY]
	, [RECORD_DATE]
	, [ORDER_DATE]
	, [RDLV_DATE]
    , 'Input Currency' AS [CURRENCY_EXCH]
	, [TO_AMT_JPY]
	, [TO_AMT_NET] AS [TO_AMT_NET_EXCH]
	, [TO_AMT_STD] AS [TO_AMT_STD_EXCH]
	, [TO_QTY]
	, 0 AS [GO_AMT_JPY]
	, 0 AS [GO_AMT_NET_EXCH]
	, 0 AS [GO_AMT_STD_EXCH]
	, 0 AS [GO_QTY]
	, 0 AS [SO_AMT_JPY]
	, 0 AS [SO_AMT_NET_EXCH]
	, 0 AS [SO_AMT_STD_EXCH]
	, 0 AS [SO_QTY]
	FROM [BI_DM].[dbo].[F_SAL_BACKLOG_TO]

	UNION ALL

	SELECT
	 [SCM_CUSTOMER_CD]
	, [ORDER_PART_NO_CD]
	, [SEG_CD]
	, [CURRENCY]
	, [RECORD_DATE]
	, [ORDER_DATE]
	, [RDLV_DATE]
    , 'Input Currency' AS [CURRENCY_EXCH]
	, 0 AS [TO_AMT_JPY]
	, 0 AS [TO_AMT_NET_EXCH]
	, 0 AS [TO_AMT_STD_EXCH]
	, 0 AS [TO_QTY]
	, [GO_AMT_JPY]
	, [GO_AMT_NET] AS [GO_AMT_NET_EXCH]
	, [GO_AMT_STD] AS [GO_AMT_STD_EXCH]
	, [GO_QTY]
	, 0 AS [SO_AMT_JPY]
	, 0 AS [SO_AMT_NET_EXCH]
	, 0 AS [SO_AMT_STD_EXCH]
	, 0 AS [SO_QTY]
	FROM [BI_DM].[dbo].[F_SAL_BACKLOG_GO]

	UNION ALL

	SELECT
	 [SCM_CUSTOMER_CD]
	, [ORDER_PART_NO_CD]
	, [SEG_CD]
	, [CURRENCY]
	, [RECORD_DATE]
	, [ORDER_DATE]
	, [RDLV_DATE]
    , 'Input Currency' AS [CURRENCY_EXCH]
	, 0 AS [TO_AMT_JPY]
	, 0 AS [TO_AMT_NET_EXCH]
	, 0 AS [TO_AMT_STD_EXCH]
	, 0 AS [TO_QTY]
	, 0 AS [GO_AMT_JPY]
	, 0 AS [GO_AMT_NET_EXCH]
	, 0 AS [GO_AMT_STD_EXCH]
	, 0 AS [GO_QTY]
	, [SO_AMT_JPY]
	, [SO_AMT_NET] AS [SO_AMT_NET_EXCH]
	, [SO_AMT_STD] AS [SO_AMT_STD_EXCH]
	, [SO_QTY]
	FROM [BI_DM].[dbo].[F_SAL_BACKLOG_SO]

UNION ALL	

    SELECT
	  [SCM_CUSTOMER_CD]
    , [ORDER_PART_NO_CD]
    , [SEG_CD]
    , [CURRENCY]
    , [RECORD_DATE]
    , [ORDER_DATE]
    , [RDLV_DATE]
    , [CURRENCY_EXCH]
	, 0 AS [TO_AMT_JPY]
    , [TO_AMT_NET_EXCH]
    , [TO_AMT_STD_EXCH]
    , [TO_QTY]
	, 0 AS [GO_AMT_JPY]
	, 0 AS [GO_AMT_NET_EXCH]
	, 0 AS [GO_AMT_STD_EXCH]
	, 0 AS [GO_QTY]
	, 0 AS [SO_AMT_JPY]
	, 0 AS [SO_AMT_NET_EXCH]
	, 0 AS [SO_AMT_STD_EXCH]
	, 0 AS [SO_QTY]
  FROM [BI_DM].[dbo].[F_SAL_BACKLOG_TO_EXCH]

UNION ALL

    SELECT
	  [SCM_CUSTOMER_CD]
    , [ORDER_PART_NO_CD]
    , [SEG_CD]
    , [CURRENCY]
    , [RECORD_DATE]
    , [ORDER_DATE]
    , [RDLV_DATE]
    , [CURRENCY_EXCH]
	, 0 AS [TO_AMT_JPY]
    , 0 AS [TO_AMT_NET_EXCH]
    , 0 AS [TO_AMT_STD_EXCH]
    , 0 AS [TO_QTY]
	, 0 AS [GO_AMT_JPY]
	, [GO_AMT_NET_EXCH]
	, [GO_AMT_STD_EXCH]
	, [GO_QTY]
	, 0 AS [SO_AMT_JPY]
	, 0 AS [SO_AMT_NET_EXCH]
	, 0 AS [SO_AMT_STD_EXCH]
	, 0 AS [SO_QTY]
  FROM [BI_DM].[dbo].[F_SAL_BACKLOG_GO_EXCH]

UNION ALL

    SELECT
	  [SCM_CUSTOMER_CD]
    , [ORDER_PART_NO_CD]
    , [SEG_CD]
    , [CURRENCY]
    , [RECORD_DATE]
    , [ORDER_DATE]
    , [RDLV_DATE]
    , [CURRENCY_EXCH]
	, 0 AS [TO_AMT_JPY]
    , 0 AS [TO_AMT_NET_EXCH]
    , 0 AS [TO_AMT_STD_EXCH]
    , 0 AS [TO_QTY]
	, 0 AS [GO_AMT_JPY]
	, 0 AS [GO_AMT_NET_EXCH]
	, 0 AS [GO_AMT_STD_EXCH]
	, 0 AS [GO_QTY]
	, 0 AS [SO_AMT_JPY]
	, [SO_AMT_NET_EXCH]
	, [SO_AMT_STD_EXCH]
	, [SO_QTY]
  FROM [BI_DM].[dbo].[F_SAL_BACKLOG_SO_EXCH]

) BASE

GROUP BY [SCM_CUSTOMER_CD]
, [ORDER_PART_NO_CD]
, [SEG_CD]
, [CURRENCY]
, [RECORD_DATE]
, [ORDER_DATE]
, [RDLV_DATE]
, [CURRENCY_EXCH]


GO
