USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VPRC_FT_BACKLOG_DIN_TBLR] AS

WITH   CUR_RATE
AS     (SELECT * FROM [DM_MST].[dbo].[VPRC_FSDM_OSC_CUR_RATE]),

BACKLOG_DIN_BM AS (
SELECT [SCM_CUSTOMER_CD]
  ,[B_WIN_SCM_CUSTOMER_CD]
  ,[ORDER_PART_NO_CD]
  ,[SEG_CD]
  ,[CURRENCY]
  ,[RECORD_DATE]
  ,[ORDER_DATE]
  ,[RDLV_DATE]
  ,CUR_RATE.[CURR_CD_TO] AS  [CURRENCY_EXCH]
  ,CONVERT(money,[TO_AMT] * CUR_RATE.B_RATE) AS [TO_AMT_B]
  ,CONVERT(money,[TO_AMT] * CUR_RATE.M_RATE) AS [TO_AMT_M]
  ,CONVERT(money,[TO_AMT_STD] * CUR_RATE_STD.B_RATE)  AS [TO_AMT_STD_B]
  ,CONVERT(money,[TO_AMT_STD] * CUR_RATE_STD.M_RATE)  AS [TO_AMT_STD_M]
  ,CONVERT(money,[GO_AMT] * CUR_RATE.B_RATE) AS [GO_AMT_B]
  ,CONVERT(money,[GO_AMT] * CUR_RATE.M_RATE) AS [GO_AMT_M]
  ,CONVERT(money,[GO_AMT_STD] * CUR_RATE_STD.B_RATE)  AS [GO_AMT_STD_B]
  ,CONVERT(money,[GO_AMT_STD] * CUR_RATE_STD.M_RATE)  AS [GO_AMT_STD_M]
  ,CONVERT(money,[SO_AMT] * CUR_RATE.B_RATE) AS [SO_AMT_B]
  ,CONVERT(money,[SO_AMT] * CUR_RATE.M_RATE) AS [SO_AMT_M]
  ,CONVERT(money,[SO_AMT_STD] * CUR_RATE_STD.B_RATE)  AS [SO_AMT_STD_B]
  ,CONVERT(money,[SO_AMT_STD] * CUR_RATE_STD.M_RATE)  AS [SO_AMT_STD_M]
FROM [BI_DM].[dbo].[T_SAL_BACKLOG_DIN]
LEFT OUTER JOIN CUR_RATE
          ON [T_SAL_BACKLOG_DIN].[CURRENCY] = CUR_RATE.[CURR_CD_FROM]
         AND [T_SAL_BACKLOG_DIN].[RECORD_DATE] = CUR_RATE.[VALID_FROM_YMD]
LEFT OUTER JOIN CUR_RATE CUR_RATE_STD
  ON CUR_RATE_STD.[CURR_CD_FROM] = 'JPY'
 AND CUR_RATE.[CURR_CD_TO]= CUR_RATE_STD.[CURR_CD_TO]
 AND [T_SAL_BACKLOG_DIN].[RECORD_DATE] = CUR_RATE_STD.[VALID_FROM_YMD]
WHERE [CURRENCY_EXCH] = 'Input Currency'
)

SELECT
   [T_SAL_BACKLOG_DIN].[SCM_CUSTOMER_CD]
  ,[T_SAL_BACKLOG_DIN].[B_WIN_SCM_CUSTOMER_CD]
  ,[T_SAL_BACKLOG_DIN].[ORDER_PART_NO_CD]
  ,[T_SAL_BACKLOG_DIN].[SEG_CD]
  ,[T_SAL_BACKLOG_DIN].[CURRENCY]
  ,[T_SAL_BACKLOG_DIN].[RECORD_DATE]
  ,[T_SAL_BACKLOG_DIN].[ORDER_DATE]
  ,[T_SAL_BACKLOG_DIN].[RDLV_DATE]
  ,[T_SAL_BACKLOG_DIN].[CURRENCY_EXCH]
  ,[TO_AMT] AS [TO_AMT_Q]
  ,[TO_AMT_B]
  ,[TO_AMT_M]
  ,[TO_AMT_STD] AS [TO_AMT_STD_Q]
  ,[TO_AMT_STD_B]
  ,[TO_AMT_STD_M]
  ,[GO_AMT] AS [GO_AMT_Q]
  ,[GO_AMT_B]
  ,[GO_AMT_M]
  ,[GO_AMT_STD] AS [GO_AMT_STD_Q]
  ,[GO_AMT_STD_B]
  ,[GO_AMT_STD_M]
  ,[SO_AMT] AS [SO_AMT_Q]
  ,[SO_AMT_B]
  ,[SO_AMT_M]
  ,[SO_AMT_STD] AS [SO_AMT_STD_Q]
  ,[SO_AMT_STD_B]
  ,[SO_AMT_STD_M]
--20180410  D-in CUBEÇ…QtyçÄñ⁄ÇÃí«â¡ëŒâû CDC  Start
  ,[GO_QTY]
  ,[TO_QTY]
  ,[SO_QTY]
--20180410  D-in CUBEÇ…QtyçÄñ⁄ÇÃí«â¡ëŒâû CDC  End
  FROM [BI_DM].[dbo].[T_SAL_BACKLOG_DIN]
  LEFT JOIN BACKLOG_DIN_BM
  ON  ISNULL([T_SAL_BACKLOG_DIN].[SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BACKLOG_DIN_BM.[SCM_CUSTOMER_CD],'$$NULL$$')
  AND ISNULL([T_SAL_BACKLOG_DIN].[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$') = ISNULL(BACKLOG_DIN_BM.[B_WIN_SCM_CUSTOMER_CD],'$$NULL$$')
  AND ISNULL([T_SAL_BACKLOG_DIN].[ORDER_PART_NO_CD],'$$NULL$$') = ISNULL(BACKLOG_DIN_BM.[ORDER_PART_NO_CD],'$$NULL$$')
  AND ISNULL([T_SAL_BACKLOG_DIN].[SEG_CD],'$$NULL$$') = ISNULL(BACKLOG_DIN_BM.[SEG_CD],'$$NULL$$')
  AND ISNULL([T_SAL_BACKLOG_DIN].[CURRENCY],'$$NULL$$') = ISNULL(BACKLOG_DIN_BM.[CURRENCY],'$$NULL$$')
  AND ISNULL(CONVERT(nvarchar,[T_SAL_BACKLOG_DIN].[RECORD_DATE],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,BACKLOG_DIN_BM.[RECORD_DATE],112),'$$NULL$$')
  AND ISNULL(CONVERT(nvarchar,[T_SAL_BACKLOG_DIN].[ORDER_DATE],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,BACKLOG_DIN_BM.[ORDER_DATE],112),'$$NULL$$')
  AND ISNULL(CONVERT(nvarchar,[T_SAL_BACKLOG_DIN].[RDLV_DATE],112),'$$NULL$$') = ISNULL(CONVERT(nvarchar,BACKLOG_DIN_BM.[RDLV_DATE],112),'$$NULL$$')
  AND ISNULL([T_SAL_BACKLOG_DIN].[CURRENCY_EXCH],'$$NULL$$') = ISNULL(BACKLOG_DIN_BM.[CURRENCY_EXCH],'$$NULL$$')



GO
