USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




CREATE view [DCP].[VF_KPI_DCP]
AS
SELECT
	[WBS]
	,[DELIBERATION_CD]
	,[CALENDAR_YM]
	,[ORDER_PART_NO_CD]
	,[SCM_CUSTOMER_CD]
	,[REVISION_ID]
	,[HORIZON_ID]
	,[VOLUME]
	,[REVENUE]
	,[PRICE]
	,[DEV_EXPENSE]
	,[PROFIT]
	,[PTI]
	,[ROI]
	,[GP_AMT]
	,[SC_AMT]
	,[WAFER]
	,[TTP]
	,[GP_AMT_HURDLE]
	,[PROFIT_AMT_HURDLE]
	,[ROI_HURDLE]
	,[DEV_EXPENSE_HURDLE]
	,[PRELIMINARY1] AS [DCP_LABEL]
	,[PRELIMINARY2]
	,[PRELIMINARY3]
	,[PRELIMINARY4]
	,[PRELIMINARY5]
	,[PRELIMINARY6]
	,[PRELIMINARY7]
	,[PRELIMINARY8]
	,[PRELIMINARY9]
	,[PRELIMINARY10]
	,[BUDvsACT_DCP_PLAN]
	,[BUDvsACT_DCP_DEV]
	,[BUDvsACT_DCP_PLAN_VOL]
	,[BUDvsACT_DCP_DEV_VOL]
	,[BUBBLE_DCP_PROFIT]
	,[BUBBLE_DCP_DEV]
	,[BUBBLE_DCP_REVENUE]
	,[RESOURCE_DCP_REVENUE]
	,[RESOURCE_DCP_PROFIT]
	,NEWID() as ALTKEY
	,CASE [HORIZON_ID]
		WHEN 0 THEN 'Under planning'
		WHEN 1 THEN 'Under development'
		WHEN 2 THEN 'Under Mass-production'
	END as HORIZON_TXT
	,CASE [REVISION_ID]
		WHEN 1 THEN 'Current QVW'
		WHEN 2 THEN 'Last QVW'
		WHEN 3 THEN 'QVW before last'
		WHEN 4 THEN 'Current DCP'
		WHEN 5 THEN 'Sales plan as of design completion DCP'
		WHEN 6 THEN 'Sales plan as of plan DCP'
		WHEN 0 THEN ''
		ELSE [PRELIMINARY1]
	END as REVISION_TXT
FROM (
	SELECT
	 WBS
	, DELIBERATION_CD
	, CALENDAR_YM
	, CAST('$DCP$' AS NVARCHAR(18)) AS ORDER_PART_NO_CD
	, CAST('$DCP$' AS NVARCHAR(10)) AS SCM_CUSTOMER_CD
	, REVISION_ID
	, HORIZON_ID

	--既存メジャー
	, VOLUME
	, REVENUE
	, PRICE
	, DEV_EXPENSE
	, PROFIT
	, PTI
	, ROI
	, GP_AMT
	, SC_AMT
	, WAFER
	, TTP
	, GP_AMT_HURDLE
	, PROFIT_AMT_HURDLE
	, ROI_HURDLE
	, DEV_EXPENSE_HURDLE
	, PRELIMINARY1
	, PRELIMINARY2
	, PRELIMINARY3
	, PRELIMINARY4
	, PRELIMINARY5
	, PRELIMINARY6
	, PRELIMINARY7
	, PRELIMINARY8
	, PRELIMINARY9
	, PRELIMINARY10

	--レポート用メジャー 3-1
	, CASE WHEN REVISION_ID = '6' THEN REVENUE ELSE 0 END AS BUDvsACT_DCP_PLAN --計画DCP
	, CASE WHEN REVISION_ID = '5' THEN REVENUE ELSE 0 END AS BUDvsACT_DCP_DEV --設計完了DCP
	, CASE WHEN REVISION_ID = '6' THEN VOLUME ELSE 0 END AS BUDvsACT_DCP_PLAN_VOL --計画DCP
	, CASE WHEN REVISION_ID = '5' THEN VOLUME ELSE 0 END AS BUDvsACT_DCP_DEV_VOL --設計完了DCP

	--レポート用メジャー 2-2
	, CASE WHEN REVISION_ID = '4' THEN PROFIT ELSE 0 END AS BUBBLE_DCP_PROFIT --最新DCP
	, CASE WHEN REVISION_ID = '4' THEN DEV_EXPENSE ELSE 0 END AS BUBBLE_DCP_DEV --最新DCP
	, CASE WHEN REVISION_ID = '4' THEN REVENUE ELSE 0 END AS BUBBLE_DCP_REVENUE --最新DCP

	--レポート用メジャー 3-2
	, CASE 
		WHEN REVISION_ID = '4' THEN REVENUE
		WHEN REVISION_ID = '0' THEN REVENUE
		-- 設計完了DCP（REV=5）のときは、同じWBS/審議コードで最新DCP（REV=4）がないときに数値を計上する。（重複回避） 
		WHEN REVISION_ID = '5' 
			AND NOT EXISTS 
				(SELECT DELIBERATION_CD FROM F_DCP_KPI_DCP D2 
				WHERE D1.WBS = D2.WBS AND D1.DELIBERATION_CD = D2.DELIBERATION_CD 
				AND D2.REVISION_ID =4) THEN REVENUE
		-- 計画DCP（REV=6）のときは、同じWBS/審議コードで最新DCP（REV=4）がないときに数値を計上する。（重複回避） 
		WHEN REVISION_ID = '6' 
			AND NOT EXISTS 
				(SELECT DELIBERATION_CD FROM F_DCP_KPI_DCP D2 
				WHERE D1.WBS = D2.WBS AND D1.DELIBERATION_CD = D2.DELIBERATION_CD 
				AND D2.REVISION_ID =4) THEN REVENUE
		ELSE 0 END AS RESOURCE_DCP_REVENUE --最新DCP
	, CASE 
		WHEN REVISION_ID = '4' THEN PROFIT
		WHEN REVISION_ID = '0' THEN PROFIT 
		-- 設計完了DCP（REV=5）のときは、同じWBS/審議コードで最新DCP（REV=4）がないときに数値を計上する。（重複回避） 
		WHEN REVISION_ID = '5' 
			AND NOT EXISTS 
				(SELECT DELIBERATION_CD FROM F_DCP_KPI_DCP D2 
				WHERE D1.WBS = D2.WBS AND D1.DELIBERATION_CD = D2.DELIBERATION_CD 
				AND D2.REVISION_ID =4) THEN PROFIT
		-- 計画DCP（REV=6）のときは、同じWBS/審議コードで最新DCP（REV=4）がないときに数値を計上する。（重複回避） 
		WHEN REVISION_ID = '6' 
			AND NOT EXISTS 
				(SELECT DELIBERATION_CD FROM F_DCP_KPI_DCP D2 
				WHERE D1.WBS = D2.WBS AND D1.DELIBERATION_CD = D2.DELIBERATION_CD 
				AND D2.REVISION_ID =4) THEN PROFIT
		ELSE 0 END AS RESOURCE_DCP_PROFIT --最新DCP

	FROM F_DCP_KPI_DCP D1
) T



GO
