USE [BI_DM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [DCP].[VF_RESOURCE]
AS
SELECT
 WBS
, DELIBERATION_CD
, CALENDAR_YM
, DELIBERATION_FLAG
, DESIGN_CD

--既存メジャー
, DEV_RESOURCE_ACT
, DEV_RESOURCE_BUD

--レポート用メジャー 3-2
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = 'FE' THEN DEV_RESOURCE_ACT ELSE 0 END AS DEV_RESOURCE_ACT_FE
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = 'BE' THEN DEV_RESOURCE_ACT ELSE 0 END AS DEV_RESOURCE_ACT_BE
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = 'L試' THEN DEV_RESOURCE_ACT ELSE 0 END AS DEV_RESOURCE_ACT_L
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = '量産立上' THEN DEV_RESOURCE_ACT ELSE 0 END AS DEV_RESOURCE_ACT_FT
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = 'FE' THEN DEV_RESOURCE_BUD ELSE 0 END AS DEV_RESOURCE_BUD_FE
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = 'BE' THEN DEV_RESOURCE_BUD ELSE 0 END AS DEV_RESOURCE_BUD_BE
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = 'L試' THEN DEV_RESOURCE_BUD ELSE 0 END AS DEV_RESOURCE_BUD_L
, CASE WHEN DELIBERATION_FLAG = '2' AND DESIGN_CD = '量産立上' THEN DEV_RESOURCE_BUD ELSE 0 END AS DEV_RESOURCE_BUD_FT

FROM F_DCP_RESOURCE


GO
